### ISSUE TITLE
Module Request: DEXON DIMAX-Pro

### ISSUE THREAD

**Issue by drewtaylor11** [bitfocus/companion-module-requests#1]
Module request for DEXON USA DIMAX-Pro and DIVIP-Pro modular scaling matrix and video processor system. 

We put together a consolidated TCP control protocol document features only the important basic commands needed. Please see PDF.

Please contact me with any questions. We are the US distributor for DEXON. I attached another PDF use case for our new 4K@60 product highlighting media serer matrix switching with built in multi-viewer to give a better idea of how our customer would like to use companion with our products. Thanks for your help!

[DEXON USA DIMAX-Pro and DIVIP-Pro Control Commands_v2.pdf](https://github.com/bitfocus/companion/files/3510678/DEXON.USA.DIMAX-Pro.and.DIVIP-Pro.Control.Commands_v2.pdf)

[DEXON USA - Media Server Management diagram draft1.pdf](https://github.com/bitfocus/companion/files/3502632/DEXON.USA.-.Media.Server.Management.diagram.draft1.pdf)

**Comment by McHauge** [comment]
Let's try again, I think I got all the "" right this time, ups.

 [https://1drv.ms/u/s!AtUYbExJseNtlK56u-n71V_UcLDe7g?e=1ItNEl](url)

**Comment by drewtaylor11** [comment]
@McHauge thanks. I will try this out with wireshark. I shipped out my demo unit but should be back with it and able to test on Tuesday. I will report back as soon as I can.

**Comment by McHauge** [comment]
@drewtaylor11 Hey, did you get a new demo unit in for testing again?

**Comment by drewtaylor11** [comment]
@McHauge all commands are working now and tested. Thank you for your help!

**Comment by McHauge** [comment]
Nice, I'll let them know that it's up and running so they can add it to the core.

**Comment by McHauge** [comment]
@drewtaylor11 I just checked the nightly builds of companion and can confirm that it's now included in the core version.

**Comment by McHauge** [comment]
@drewtaylor11 I was just looking through the list of module requests and found this one: Dexonsystem 8x4 4K HDBaseT Seamless Matrix Switcher #43. I would like to ask since you are a distributor of DEXON products, and therefore maybe also this one. 

Two things, first do you know if they are directly compatible in their API?
And second, would it be possible for you if you got this device to try and run the module on it, just to see if it works.

**Comment by drewtaylor11** [comment]
@mchauge I do have one of these units in the office. I'll look in to it and let you know.

**Comment by drewtaylor11** [comment]
@McHauge verified the same modules work with the 8x4. The only thing funky about the 8x4 is the password needs to be converted to a hash string. a site like this will do the conversion for you. Thenyou enter the hash string in the password field in companion.  https://www.md5hashgenerator.com/

do you know of a way in companion to verify companion is logged in? or send the login command on every new TCP connection. In the event the connection is lost companion would have to send the login command on a TCP reconnect. one method to work around this would be to put the login command first on every button then whatever other command you want second.

**Comment by McHauge** [comment]
Thanks, for testing it and comming through with the insight. I'll try and make the loggin hashed for that unit and see if I can make it auto-login/semi-auto-login. 

Another thing, are their other units in the Dexon Dimax or Dexon Divip family that has these kinds of quirks that I should try and implement in the future?

**Comment by drewtaylor11** [comment]
@McHauge all Dexon products require the login sequence on all new TCP connections. as far as the hash string for the password I believe it is only the 8x4 and maybe the 4x4. Thanks.

**Comment by McHauge** [comment]
@drewtaylor11 did you get time to test it? and how did it go?

**Comment by McHauge** [comment]
@drewtaylor11 Hey again, I just finished the module for the Dexon Matrix 8x4 and 4x4 with MD5 hashing included in the module. it's included in the V2.0.0 build and is ready for testing if you got time to test it that would be awesome.

**Comment by drewtaylor11** [comment]
That’s awesome. Thank you. I will follow up when I have a chance to test the updates.

**Comment by McHauge** [comment]
also, there are a few changes in the other to as well, mainly there is now presets for all functions and the config page is identical between all 3 modules.

If it completes your testing then I will get them added to the queue for inclusion in the next release build (all 3, but you have already kinda done the 2 of them)

-Andreas (McHauge)

**Comment by drewtaylor11** [comment]
@McHauge I finally got a chance to test with the 8x4 and the DIMAX-Pro and DIVIP-Pro. Everything seems tot be working fine. i will admit I did not test all the new commands yet like presets but all the main commands I requested are working great. Auto login is working with no issues. Also the MD5 hash converter is working for the 8x4 login. Thanks for all of your help.

**Comment by McHauge** [comment]
That's awesome, I'll mark them as done, if something comes up, we can take it from there.

-Andreas
