### ISSUE TITLE
16x16 UHD 4K@60Hz HDR HDMI Matrix Switcher w/ Down Scaler SPDIF Audio Extractor

### ISSUE THREAD

**Issue by Shattercone** [bitfocus/companion-module-requests#1000]
This product does have a web interface, but we'd like to see if you are able to add it so we don't have to use that.
We would like to be able to route any input to any output, as well as have the presets available(multiple ins to multiple outs with one button click)  this link takes you to the website for this unit.  If you click on the 'downloads and datasheets', it has the manual, hex files and control driver links you can download.
Thank you!!

https://www.a-neuvideo.com/shop/product_info.php?products_id=178

**Comment by jrviz** [comment]
This is very, very similar to another matrix module I have written. PM me on the email in my profile to connect. I would need you to connect via telnet and run some tests. You should try the orei matrix module although that currently supports only 4 or 8 channels at the moment and supports 4 presets. The commands are the same although the orei also supports video over Cat5/6 so the status query for that may generate an error. You could try.

**Comment by Shattercone** [comment]
Thanks.  emailed

**Comment by jrviz** [comment]
Hello. Are you able to try the orei module? The commands are the same  but it (currently)only supports up to 8 inputs/outputs and 4 presets (a trivial change) and the orei also supports video of Cat5/6 to receivers. The modules queries these cat settings as well so I'm not sure if that would upset your matrix. If not, I can just make this a configurable option that switches the query off and expand the channels/presets.

Another matrix switch I am working on has a UI setup like this where the first two rows Select an input and you can then set the outputs to take that input. Red shows the active selected input and the green lights up to show outputs it maps to. The text also shows where the bidirectional mapping is. These are just Companion presets and the text is stored in variables and it's all optional for the button labels. The switch presets save and load is already supported and the power control as well. Plus a simple in to out or in to all action. I could  also add an in to multi action. Hdmi output enable/disable already supported.

My view is that the Orei module should be updated with the expanded scope and the help text can refer tot the Neuvideo being supported as well.

When I build modules I tend to send a link of a test build to the requester to allow it to be tested. This would allow you to test in advance of the module going into the next release and when you are happy I would push the code to the release stream

***@***.***

**Comment by Shattercone** [comment]
I can try it once the unit is set up which will be around Dec. 29-30.  I'll get back to you then. Thanks!

**Comment by Shattercone** [comment]
Hi James,
The Orei module works with this unit.  So adding in the additional 8 ins and outs, along with the units presets(it has 8 built in presets we can save) would be super helpful!
Thanks!

**Comment by jrviz** [comment]
Please PM me from your own email (not Github) so I can send you a link for a build to test.

**Comment by josephdadams** [comment]
Closing this as it looks like the Orei module takes care of the request with some minor modifications.

**Comment by Shattercone** [comment]
Hi james. Sorry for delays on this. Ill be at the warehouse on Tuesday and
will make a point of seeing how it works.

**Comment by dragon788** [comment]
@jrviz just curious if you ever published your changes? I've got one of these and at first blush the Orei module doesn't seem to be working even though I have the right IP.

**Comment by dragon788** [comment]
Got the Orei working for the first 8 ports after a restart of the device, will have to poke at getting more going and see if I can do it without using telnet (I think I read it can do similar socket based stuff via a web port, default is 8000).
