### ISSUE TITLE
Module Request: Sain Smart TCP/IP 8-Channel Relay

### ISSUE THREAD

**Issue by hallandrewjohn** [bitfocus/companion-module-requests#101]
Hello,

I have a TCP/IP 8-Channel Relay Box from Sain Smart. One of the comments on the product does a good job of explaining how the modules works, but basically there is a web URL that turns relays on and off.

If I browse to the webpage "http://192.168.1.4/30000/**01**" relay 1 will turn off & if I go to "http://192.168.1.4/30000/**01**" relay 1 will turn on.

The default IP is 192.168.1.4, but it can be changed. The port defaults to 30000, but can also be changed.

I did some quick test with the basic HTTP modules using GET and POST and was not able to get either for those to work.

192.168.1.4/30000/[X]   where [X] =
00 - relay 0 OFF
01 - relay 0 ON
02 - relay 1 OFF
03 - relay 1 ON
04 - relay 2 OFF
05 - relay 2 ON

Product Link:
https://www.sainsmart.com/collections/internet-of-things/products/rj45-tcp-ip-remote-control-board-with-integrated-8-ch-relay

**Comment by McHauge** [comment]
@hallandrewjohn Hey just got done with the initial part of the module, and I think I got it up and running.

It would be awesome if you had time to test the module, there is a Windows build of companion 2.0 with the module, attached in the download link below.

[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by hallandrewjohn** [comment]
@McHauge You're a champ! I only had a quick minute to test it out while at work today, but it seemed to work great. I'll run it through a stress test this evening to see if I can break it. 

I'm new to this community and the process here, should I anticipate this to be in the next release of Companion or is there a way I can get this to merge with the version I'm running on my mac?

**Comment by McHauge** [comment]
That's great after you have done some testing I will mark it as ready and then it will show up in the next release, and in the daily v2.0 builds, where there should be both Windows, LInux and Mac builds:
[https://builds.bitfocus.io/companion/](url)

**Comment by hallandrewjohn** [comment]
Thanks! I did some further testing and it worked great! Thanks again.

**Comment by McHauge** [comment]
@hallandrewjohn Great gonna mark this as done and set it up for the next release.
