### ISSUE TITLE
Companion to Companion Module

### ISSUE THREAD

**Issue by echalupka** [bitfocus/companion-module-requests#1010]
We have a scenario in which companion satellite is not feasible; instead two instances of companion on two separate computers must be running.  Mac 1 (running companion) has access to 3 different networks; dante, LX, and building network. Mac 2 (also running companion) only has building network.  I want to share buttons from mac 1, including the current label, with mac 2 so mac 2 can trigger things on the network that mac 1 has access to. 

I was able to get TCP strings from mac 2 to press the button on mac 1, but mac 1 has variables inserting on buttons that I want to be able to see on mac 2 in real-time as they are updated by the LX network and dante networks.

**Comment by josephdadams** [comment]
#304

**Comment by echalupka** [comment]
Hi @josephdadams ,
I see you closed this, but I looked at the ticket you linked and don’t see anyway to get variables sent from companion to another companion instance without using satellite (which doesn’t work here). Can you provide a little more info?
Eric

**Comment by josephdadams** [comment]
I closed it because the concept is a duplicate of the linked issue. You want a module in companion that can send and receive data to another companion instance
