### ISSUE TITLE
RLM w12 - generic http request

### ISSUE THREAD

**Issue by tljunggren** [bitfocus/companion-module-requests#1033]
Hi . I have a good old Barco RLM-W12.
and would like to control power+shutter from companion.

I found the #2 and also info in the #187 , but still fairly stuck.

The command: http://projectorip/tgi/remote.tgi?onky and offky work fine from a browser, but I'm getting nowhere from within companion.
I'm supposed to connect it with generic http request? using POST-command? txt-plain? Tried them all to no effect so far.
Any help appreciated here..

Would you also know the commands for picture mute?
the command I used previously via serial is op picture.mute = 1 , is there another syntax for http?

thanks.

**Comment by josephdadams** [comment]
It should be GET not POST

**Comment by tljunggren** [comment]
Thank you. Works with GET.
For more info #187
