### ISSUE TITLE
Microsoft Teams websocket API

### ISSUE THREAD

**Issue by clarkezone** [bitfocus/companion-module-requests#1041]
There is a new streamdeck extension for Microsoft Teams that enables mute, reactions etc without the need for the teams window to have focus:

[Teams native streamdeck integration](https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/using-the-native-elgato-streamdeck-integration-with-microsoft/ba-p/3732044)

The underlying API has been documented here:
https://lostdomain.notion.site/Microsoft-Teams-WebSocket-API-5c042838bc3e4731bdfe679e864ab52a

Would be awesome to get a companion module with the same support.

**Comment by QuinnMatthews** [comment]
Microsoft has pulled the WebSocket api and the ability to generate a key while they are working on security issues... (knowing Microsoft, it could be back tomorrow, or we could never see this feature again. I'll let you flip the coin.)

**Comment by clarkezone** [comment]
FWIW The plug-in was released last Friday

**Comment by dnmeid** [comment]
@clarkezone Can you verify if the link to the documentation is still valid, it doesn't work for me.

**Comment by jobridts** [comment]
The link (and commands) work for me (tested using Postman), so the API seems to work

**Comment by leonreucher** [comment]
I developed a module for the API. It is already included in the latest Companion beta versions - just give it a try :)

**Comment by peternewman** [comment]
For anyone playing along at home, that's https://github.com/bitfocus/companion-module-microsoft-teams
