### ISSUE TITLE
Analog Way Zenith 200

### ISSUE THREAD

**Issue by s21deg** [bitfocus/companion-module-requests#1044]
I would like to control multiple Zenith 200 switchers

Cheers

**Comment by JeffreyDavidsz** [comment]
Did you try the livepremiere module?

**Comment by s21deg** [comment]
Hi JeffreyDavidsz thanks for your reply,
I updated companion today and there was an Analog way Alta4k newly added, this works perfectly
All sorted

**Comment by JeffreyDavidsz** [comment]
Great!
