### ISSUE TITLE
NCH Software

### ISSUE THREAD

**Issue by Mar10nDVC** [bitfocus/companion-module-requests#1049]
I need Companion ADD for NCH Software WavePad Sound Editor and VideoPad Video Editor also fra NCH.
Can you fix it?
Best regards fra Martin Vinther Rasmussen, Denmark

**Comment by josephdadams** [comment]
@Mar10nDVC please resubmit this as separate requests for each product/module you wish to have, along with links to the control protocol and documentation that would allow Companion to control it over the network.
