### ISSUE TITLE
Module Request: Slack

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-requests#105]
**Describe the feature**
Ability to send out preset messages via Slack.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
https://api.slack.com/rtm ; sending messages portion

**Usecases**
We use Slack in our studio complex, and it would be helpful if a TD could ping the engineer, report an issue, or notify that recording has wrapped without having to type while switching. Since they all already have Streamdecks with Companion, my idea would be a Slack module where you could select a channel and have a custom message for each button.

**Comment by josephdadams** [comment]
Sure thing, I'd like this too. I'll get started soon.

**Comment by josephdadams** [comment]
@bryce-seifert I'm waiting on the module repo to be set up so I can push the code to it, then we can get it in a dev build for you to try out. Or, if you have your own dev environment set up, you can just download the code and run it yourself.

**Comment by bryce-seifert** [comment]
Nice! Thanks for working on this. I don't have a dev environment, but am excited to try this one out.

**Comment by josephdadams** [comment]
You're welcome! It supports 3 actions:

1. Send a predefined message (you can define up to 5 messages in the instance settings)
1. Send a custom message (textbox)
1. Send a Block Kit message in JSON format. Slack supports very dynamic message styles, so if you know how to do that, you can send it!

**Comment by josephdadams** [comment]
@bryce-seifert go download the latest bleeding edge build of 2.0 from http://builds.bitfocus.io and test this out please. Report back any issues. Thanks!

**Comment by bryce-seifert** [comment]
Got this installed this morning and took it for a test run, it’s looking great! I’ll keep testing and provide feedback here.

**Comment by bryce-seifert** [comment]
Did some more testing, and everything seems to be working well with booth predefined and custom messages. I haven't tested Block Kit. One question, though it may prove unwieldy: would it be possible to echo the message in the instance dropdown for predefined messages instead of just "1...2...etc." Not sure if that makes sense, but I found myself having to go back to remember which message is which.

**Comment by josephdadams** [comment]
Sure. Done. Updated the repo, just need it pushed to the core and binary built if you're not running a dev environment.

**Comment by josephdadams** [comment]
Closing since this has been made!
