### ISSUE TITLE
Could LiveToAir be added into Companion?

### ISSUE THREAD

**Issue by DmxDesigner** [bitfocus/companion-module-requests#1054]
There is another very useful video production software that several folks use with vMix, OBS and other video streaming. It's called: LiveToAir. By http://www.gnuralnet.com  It would be fantastic if "companion" could connect to this program as well. Thanks! Bill

**Comment by josephdadams** [comment]
There’s a module for this in the “companion” v3 betas.

**Comment by DmxDesigner** [comment]
Hi Joe, I was mistaken when I posted the above question. I meant to ask for Control Central which is use mostly. Thanks.
