### ISSUE TITLE
Stagetimer.io

### ISSUE THREAD

**Issue by SteveHoffmannCarl** [bitfocus/companion-module-requests#1062]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
the Timer Software from stagetimer.io

What you would like to be able to make it do from Companion:
set timing, start, stop, send messages (maybe send with a string) and focus and flash, adjust timer (min+ and min-) 

Direct links or attachments to the ethernet control protocol or API:
https://stagetimer.io/docs/
https://stagetimer.io/docs/api/

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-hermann-stagetimerio

This already exists. I suggest checking next time before making a request.

**Comment by SteveHoffmannCarl** [comment]
Sorry, apparently i searched at the wrong place. Won't happen again :)

**Comment by josephdadams** [comment]
No problem. I was in a bad mood when I commented that, sorry. I know this is a large project with lots of places to find things.
