### ISSUE TITLE
Request for support of Roland VR-50HD MKII video switcher

### ISSUE THREAD

**Issue by mko1989** [bitfocus/companion-module-requests#107]
Basically the same control standard as V60-HD with a couple different commands.

Here is a link to the reference manual with all the commands:
https://proav.roland.com/global/support/by_product/vr-50hd_mk_ii/owners_manuals/df616773-c6e6-42e7-8f86-c89f61885d55/

**Comment by McHauge** [comment]
I'll take a look at it, but I guess some of the V-60HD modules also works with this unit but will make a new module, will probably have a test build ready next week.

**Comment by josephdadams** [comment]
@McHauge i’m happy to take a look, since I’ve created all the other Roland modules.

**Comment by McHauge** [comment]
If you want to you can then just swap the assigned to, back to you

**Comment by josephdadams** [comment]
@mko1989 just waiting on the repo to be set up. The module is ready.

**Comment by josephdadams** [comment]
@mko1989 code is uploaded. https://github.com/bitfocus/companion-module-roland-vr50hd-mk2
Do you have a development environment set up where you could test this? Or do you need a binary built?

**Comment by josephdadams** [comment]
@mko1989 go download the latest bleeding edge build of 2.0 from http://builds.bitfocus.io and test this out please. Report back any issues. Thanks!

**Comment by josephdadams** [comment]
@mko1989 how did testing go?

**Comment by mko1989** [comment]
Sorry about that. I went ahead of time with that module request. My company
is getting few units of that Roland but in a few weeks. As soon as we get
them I will test it but it will take some time.
Sorry for that.



sob., 2 lis 2019, 11:49 użytkownik Joseph Adams <notifications@github.com>
napisał:

**Comment by josephdadams** [comment]
@mko1989 let me know how testing goes. Thanks!

**Comment by josephdadams** [comment]
@mko1989 did you get your units yet?

**Comment by mko1989** [comment]
Finally got them yesterday. Had a little time for testing but in that time everything seemed to work fine. The only thing i noticed was that in option "Select source video for video input" there is "Still" in the Input number drop down which doesn't work nor it should. There is another option "Select still image of the STILL button" which does that and works as expected.
I will do more testing soon  when I have the time but for now it seems very good.
Thanks Guys

**Comment by josephdadams** [comment]
Thanks! I thought that was strange too, but it was listed in the official reference manual from Roland, so I put it in there. Now we know that was not correct. I’ll remove it and update the repository.

**Comment by josephdadams** [comment]
@mko1989 I've fixed this in the code. @JeffreyDavidsz will update the core and when the build server is working correctly again you can download an updated version of Companion from builds.bitfocus.io.

**Comment by mko1989** [comment]
Had a little time with the vr-50 today and found another bug, in the select video for AUX bus there is a still source in the drop down which is not available in the actual unit. Please remove this option from the drop down. Thanks a lot for the module :)

**Comment by josephdadams** [comment]
@mko1989 fixed in the code. The manual lists it but actually lists them like this:
0 (INPUT 1)
1 (INPUT 2)
2 (INPUT 3)
3 (INPUT 4)
4 (STILL)
4 (PinP)
5 (PinP/KEY)
6 (PGM)

As you can see, id 4 is duplicated. I had simply incremented them in the code assuming the id numbers were typos, but now we can see that it's the entire STILL entry is the typo. :) Please test PinP, PinP/Key, and PGM.

@JeffreyDavidsz can you update this in the core and set off a build?

**Comment by JeffreyDavidsz** [comment]
check
