### ISSUE TITLE
Ross Dashboard

### ISSUE THREAD

**Issue by MandyDroid** [bitfocus/companion-module-requests#1073]
I am looking to use the dial buttons for some of the volume controls. We currently use a keyboard, but we are looking for a better method. 

https://www.rossvideo.com/products-services/management-systems/automated-production-control/dashboard/

**Comment by josephdadams** [comment]
Can you be more specific? Is this a custom panel? If it is, you can send Rosstalk or even just generic tcp from companion to your panel and modify your panel to receive it and operate the controls.

**Comment by MandyDroid** [comment]
Greatest apologies - I spoke with my person here and they said we need to be able to assign to PTZ camera to adjust color and stuff using dial buttons. I am going to spend the next few days looking into if there is a way to connect using RossTalk or direct TCP comms from companion. Thank you for the additional direction.

**Comment by josephdadams** [comment]
Which PTZ is it? Perhaps it is already supported in companion

**Comment by johnnymets17** [comment]
Canon and Panasonic PTZs

was hoping to use it for delicate painting and fine adjustments instead of a mouse.

**Comment by josephdadams** [comment]
Both supported in companion

**Comment by MandyDroid** [comment]
I am currently trying to use the companion-module-canon-ptz but I am not able to connect using https at 443 with a user and password. I have moved to https://github.com/bitfocus/companion-module-canon-ptz
