### ISSUE TITLE
Youtube Studio

### ISSUE THREAD

**Issue by IanPurpose** [bitfocus/companion-module-requests#1077]
- [ ] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Youtube Studio

What you would like to be able to make it do from Companion:
Looking mainly to be able to start and stop livestreams in YT Studio from a companion button. I am sure there are plenty more functions and applications available, but for now that is the main function I am searching for.

Direct links or attachments to the ethernet control protocol or API:
https://developers.google.com/youtube/v3
https://github.com/adasq/youtube-studio
https://pypi.org/project/ytstudio/

**Comment by josephdadams** [comment]
Did you try looking to see if this is already supported?

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-youtube-live
