### ISSUE TITLE
Local Keyboard

### ISSUE THREAD

**Issue by fahhem** [bitfocus/companion-module-requests#1082]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Local keyboard

What you would like to be able to make it do from Companion:
Keyboard shortcuts without running xdotool or equivalent

Direct links or attachments to the ethernet control protocol or API:
This is already implemented by Enerccio: https://github.com/Enerccio/companion-modules-os-keyboard

Is there a reason not to just add this?

**Comment by josephdadams** [comment]
We don't have a record of this developer saying this module is ready for release. In addition, it is not compatible with the new module API and will need to be updated. So there is your reason to not just add this.
