### ISSUE TITLE
Add Connections Shure MXCWAPT

### ISSUE THREAD

**Issue by Soundguy17** [bitfocus/companion-module-requests#1085]
Looking for Shure MXCWAPT Access Point Transceiver control
Looking for Mute all microphones and or mute speakers.
Volume up and down control

Send question to joe@bluechipsound.com

Thanks
Joe

**Comment by josephdadams** [comment]
bitfocus/companion-module-shure-mxcw#1

**Comment by krocheck** [comment]
Module is in betaa

**Comment by jamesmthetech** [comment]
Shure MXCW Command string can be found here: https://pubs.shure.com/command-strings/MXCW/en-US

Missing Command for mic on and off. < SET 1 MIC_STATUS OFF > < SET 1 MIC_STATUS ON >
