### ISSUE TITLE
Support for Epson EB-L-Series Projectors

### ISSUE THREAD

**Issue by tiefschallwerk** [bitfocus/companion-module-requests#109]
There is a windows application to control Epson EB-L Projectors in your local Network. You can also reach the Devices in your Browser over their IP-address.

Is there a way to implement at least basic Controls like turning it on/off or triggering the shutter on these Projectors?

We use EPSON EB-L1755U 3LCD PROJECTORS and really miss this feature!

**Comment by McHauge** [comment]
Hey, @tiefschallwerk would it be possible for you to look up some documentation on how it communicates? this would make for a faster implementation.

**Comment by josephdadams** [comment]
Duplicates #4.
