### ISSUE TITLE
Please Add a Module for Tuya/Smart Life IoT Devices like bulbs, switches, plugs, maybe sensors.

### ISSUE THREAD

**Issue by MathiasGIZ** [bitfocus/companion-module-requests#1094]
The usecases of that are many:

- lighting in decorations (studio and theatre),
- switching devices remotly
- powercycle hung up equipment remotly
- smart switches may trigger actions in companion, like PTZ presets (different switches on table)
- alerting if a sensor measures high temp in a rack or a room, maybe triggering a plug with a fan or something like that.

**Comment by josephdadams** [comment]
#496
