### ISSUE TITLE
H2R Support

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion-module-requests#110]
Module Support for a H2R that does cut and fill and Chroma key messages and lower thrids

https://heretorecord.com/graphics#download
https://heretorecord.com/graphics/docs#osc-control

Just adding OSC support in a module

**Comment by josephdadams** [comment]
Just waiting on the repo to be made so I can push this. @hadphild will you test it when it's there?

**Comment by josephdadams** [comment]
@hadphild https://github.com/bitfocus/companion-module-h2r-graphics

**Comment by josephdadams** [comment]
@hadphild tested?

**Comment by josephdadams** [comment]
@hadphild did you test this yet?

**Comment by josephdadams** [comment]
@hadphild pinging you again to see if you've tested this module you requested.

**Comment by josephdadams** [comment]
@JeffreyDavidsz can we push this to the core and just track bugs as it gets used? I can’t get @hadphild to respond.

**Comment by JeffreyDavidsz** [comment]
done

**Comment by iamjohnbarker** [comment]
Huge thanks for getting the ball rolling on this @josephdadams - Mail me if there is anything I can do to make the integration smoother 😄

**Comment by josephdadams** [comment]
I built it based on the OSC spec. The original requester @hadphild ghosted us so I don’t know if it’s been tested. @iamjohnbarker if you could confirm it does what it’s supposed to, that’d be great! Or, feel free to rewrite or make a tighter integration!

**Comment by houtacheng** [comment]
H2R installed in WIN/MAC cannot be triggered by Companion in other computers.
However, H2R installed in the MAC can be triggered by the local (127.0.0.1) companion.
