### ISSUE TITLE
Feature request: speed test

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-requests#1108]
I've had two occasions that I know of, oddly almost exactly a year apart, where I suspect my internet connection quality was lacking. While this was easily resolved with a hardware reset of some networking equipment, it wasn't apparent to anyone in "production" that there was even a problem. 

"Production" in our case consists of the guy who switches cameras and me, who watches the stream on my phone in case anything goes wrong, and there's almost no camera motion to really push the bandwidth until it's already too late.

It would be immensely helpful to be able to press a Companion button, or have a trigger execute 20 minutes before showtime, to run a speed test using someone's free API. Don't need real time or graphical results, just to stick the final results in two variables that I can then use comparison operators to change a button color.

**Comment by bryce-seifert** [comment]
Seems like it should be simple enough. I can take a look at this.

**Comment by bryce-seifert** [comment]
@mark-epstein This will be available in the upcoming Companion v3

**Comment by dnmeid** [comment]
Completed by addition of https://github.com/bitfocus/companion-module-generic-speedtest
Thanks to @bryce-seifert
