### ISSUE TITLE
Request for Ecamm Live Support on Companion

### ISSUE THREAD

**Issue by Chasemcw** [bitfocus/companion-module-requests#1118]
Dear developers,

I'm a frequent user of Ecamm Live, and I think it's an amazing live streaming tool. However, I've been facing issues when trying to use it with certain platforms that don't provide direct integration with the software.

I would like to kindly request that you consider adding support for Ecamm Live in your platform. This would enable users like me to fully leverage the capabilities of your platform while using our preferred live streaming tool.

I believe this would be a valuable addition to your software, as Ecamm Live is gaining popularity among content creators and businesses alike. With its rich set of features and user-friendly interface, it has become an essential tool for many of us.

Thank you for your consideration, and I'm looking forward to seeing this feature implemented soon.

Best regards,

**Comment by JeffreyDavidsz** [comment]
Ecamm live is supported also in V3
