### ISSUE TITLE
Ross Mira/Tria

### ISSUE THREAD

**Issue by wtapper89** [bitfocus/companion-module-requests#112]
I'd love to see a module to be able to cue and play a clip using a Ross Tria using the API documented here: https://usermanual.wiki/Document/AbekasMiraEthernetAPI.2237119839/html

**Comment by cjluck** [comment]
I would also like see this. We have a Tria Express at my workplace, and it would be nice to trigger it with companion.

**Comment by josephdadams** [comment]
There's a module for this in the betas now! :)
