### ISSUE TITLE
Add Request

### ISSUE THREAD

**Issue by felizax** [bitfocus/companion-module-requests#1120]
I wonder for Steinberg Dorico

**Comment by jonarnoldmusic** [comment]
Why was this closed? I went looking for a Dorico module in the software because this ticket says it was completed (couldn't find a list online, so I had to install it), but I don't see it. I installed 3.4.0.

**Comment by josephdadams** [comment]
Because it’s an awful request for a module? Literally no info provided.

**Comment by jonarnoldmusic** [comment]
Ah I thought it would be closed with a different reason tag then. I will open another issue if I can commit to testing for a Dorico module.
