### ISSUE TITLE
Google Chrome Browser

### ISSUE THREAD

**Issue by desertdognl** [bitfocus/companion-module-requests#1130]
Often in a live event situation, you want to show a full-screen browser window that is on a secondary monitor. Being on a secondary monitor (external display, not mirrored) makes it not very easy to control. Often I have multiple tabs open, for example: one with a countdown timer, one with current time, one with a live update agenda. To show the different tabs you now need to go to the external browser window and use ctrl/command + tab, or go to the specific tab with Ctrl/command + 1/2/3.

It would be really great if there was a companion module that can do this, so you could just change to the right tab from the streamdeck.

Google Chrome API: https://developer.chrome.com/docs/extensions/reference/

**Comment by JeffreyDavidsz** [comment]
You can use VICREO-listener for that, download and install it and run. Free version can do this

**Comment by josephdadams** [comment]
I think to do this without Vicreo-listener, a Chrome extension would have to be developed, be running on that browser, and allow for network access. Using VICRO Listener and the VICREO hotkey module would be a much easier approach.
