### ISSUE TITLE
Generic SMTP - send emails

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion-module-requests#1134]
Use SMTP to send emails.  Ideally we could just enter in the SMTP host, port, username and password. A bonus would be to specify a reply-to email.

Action would be
-send email
-send email with CC/BCC

In the send email action we'd need to be able to fill in a subject and body of the email. Supporting variables in the subject and body would be ideal.

Plenty of SMTP integrations available, such as Nodemailer: https://github.com/nodemailer/nodemailer/

**Comment by hartmann-jonas** [comment]
I am working on a module for this and the basic functionality is working, but it needs some more testing. 

If you are available for testing you can reach me at git.jonashartmann@proton.me so I can send you the packaged module.

**Comment by BenJamesAndo** [comment]
Great, thank you! Email sent.
