### ISSUE TITLE
Request: Add support to RME Totalmix via OSC

### ISSUE THREAD

**Issue by dcocharro** [bitfocus/companion-module-requests#1136]
[fface_ucx_e.pdf](https://github.com/bitfocus/companion-module-requests/files/11343240/fface_ucx_e.pdf)
[OscTableTotalMix_230112.xls](https://github.com/bitfocus/companion-module-requests/files/11343241/OscTableTotalMix_230112.xls)

https://www.forum.rme-audio.de/viewtopic.php?id=18177

https://forum.rme-audio.de/viewtopic.php?id=32715

https://www.rme-audio.de/totalmix-fx.html

Thank you

**Comment by josephdadams** [comment]
#42

**Comment by thepoison606** [comment]
Module v1.0.0 was just released: [https://bitfocus.io/connections/rme-totalmix](https://bitfocus.io/connections/rme-totalmix)

Use totalmix fx 2.1 for the best experience: [https://forum.rme-audio.de/viewtopic.php?id=43075](https://forum.rme-audio.de/viewtopic.php?id=43075)
