### ISSUE TITLE
Tascam DA-6400

### ISSUE THREAD

**Issue by tlblankenship** [bitfocus/companion-module-requests#1147]
Hello,

I would like to control transport and marks on the Tascam DA-6400. The communication for the Tascam SS-R250N works with the Password protocol and most Transport functions work. 

I'm using the unit for Theatrical playback, where 18 tracks are part of the same "song" utilizing marks to navigate to different parts of the show. They are a single "song" because SMPTE is a track apart of the "song". A needed function would be to Stop, Arm at Postion/Mark, and Hold/Play. 

I tried using TCP plugin and built-in Telnet function in windows to see if I could make scripts that could be triggerable. 

Here is the [Telnet Protocol](https://tascam.com/downloads/products/tascam/da-6400/TELNET_Protocol_DA6400dp_V100_en.pdf).

**Comment by josephdadams** [comment]
#418
