### ISSUE TITLE
Support for Dahua / Amcrest PTZ cams (developed by me)

### ISSUE THREAD

**Issue by bastiaanrodenburg** [bitfocus/companion-module-requests#116]
**PLEASE USE THIS PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE**

https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
I'm developing a module to control Dahua PTZ cams. They use the Amcrest protocol over HTTP. Are you interested in the source?  

**Is this platform dependent (windows, mac, ..)?**
No
[Amcrest+HTTP+API+3.2017.pdf](https://github.com/bitfocus/companion/files/3828908/Amcrest%2BHTTP%2BAPI%2B3.2017.pdf)

**If documentation is required to implement, do you know where to find it?**
Included

**Usecases**
Productions and situations with less budget can use security cams for live streaming.

**Comment by josephdadams** [comment]
@bastiaanrodenburg how is your module coming?

**Comment by bastiaanrodenburg** [comment]
Thank you for coming back to me. I'ts working here. I'm not very good in
working with Git (this is my first project!). But if you could make a repo
I can upload it. Maybe somebody else should check it out before it becomes
part of the build.
I've also create another module voor Foscam PTZ camera's.

Op zo 24 nov. 2019 om 02:24 schreef Joseph Adams <notifications@github.com>:

**Comment by JeffreyDavidsz** [comment]
Hi Bastiaan, the repo's have been created for you and you have access (please check mail).

**Comment by bastiaanrodenburg** [comment]
Thank you. I've added to files to the repos. Not sure about the further
proces of incorporating this in the core build. I guess you have to make a
link in lib/module to the new repos. I've not tested the foscam module
because I don't have the camera at home :-) Will do it this week.

Bastiaan

Op zo 24 nov. 2019 om 14:11 schreef Jeffrey Davidsz <
notifications@github.com>:

**Comment by josephdadams** [comment]
@JeffreyDavidsz can pull them to the core and generate a build when you're ready. Ping back here when the foscam is tested. Thanks!

**Comment by josephdadams** [comment]
@bastiaanrodenburg all tested and ready to close this?

**Comment by bastiaanrodenburg** [comment]
Module is tested and ready for a first release if necessary.

**Comment by JeffreyDavidsz** [comment]
@bastiaanrodenburg of not done already please put a message in slack #moduledevelopment so we don't miss it
