### ISSUE TITLE
Please make additional modules for the TP_Link Tapo series.

### ISSUE THREAD

**Issue by bniel77** [bitfocus/companion-module-requests#1164]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

There are several modules in the TP_Link Kasa series,
but there is only one Plug in the Tapo series.  
Please make various modules like Kasa.
![image](https://github.com/bitfocus/companion/assets/20009066/b700cffd-4fab-454b-8ed2-f4612b9ad0df)

**Comment by josephdadams** [comment]
@bniel77 please resubmit this as a specific request(s) for the Tapo device(s) you are wanting to control (bulb, dimmer, etc.)
