### ISSUE TITLE
AWS Elemental Live API

### ISSUE THREAD

**Issue by toddpthayer** [bitfocus/companion-module-requests#1165]
Good Morning,
I did some digging and I don't see the Elemental Live Server in the list of supported / requested devices.

The name of the device, hardware, or software you would like to control:
AWS Elemental Live Streaming Encoder

What you would like to be able to make it do from Companion:
Current project would benefit from  start / stop / reset events.  Additional desired functionality would include modifying static and motion graphic overlay parameters... (there's a complete API (attached) the whole thing would be a serious...)

Direct links or attachments to the ethernet control protocol or API:
[AWS Elemental live_api.pdf](https://github.com/bitfocus/companion-module-requests/files/11557923/AWS.Elemental.live_api.pdf)

**Comment by bryce-seifert** [comment]
@toddpthayer Just to clarify, this is a request for the Elemental Live hardware encoder?
Or AWS Elemental MediaLive, the server component?

The linked documentation is for the hardware encoder, just want to make sure that's accurate

**Comment by toddpthayer** [comment]
Bryce, the hardware encoders... there are several functions the GUI can't control directly.  Sending POST commands works, but is clunky.
Thanks
Todd

**Comment by bryce-seifert** [comment]
@toddpthayer Got it. I can likely take a look at this, but I don't have the hardware to test with so I would have to delegate that to you unless you have a unit I could access remotely for testing.

**Comment by toddpthayer** [comment]
I can do the bulk of any testing (depending on workload / system availability).  We can also open up a tunnel in if needed...
Cheers,
Todd

**Comment by bryce-seifert** [comment]
@toddpthayer Are you on the Bitfocus [Slack](https://bitfocus.io/api/slackinvite)? If we want to continue the conversation there, I can get you some test builds to try. Email also works if that's easier.

**Comment by bryce-seifert** [comment]
Module is now available in Companion.
https://github.com/bitfocus/companion-module-aws-elementallive/releases/tag/v1.0.0
