### ISSUE TITLE
Serial 2 Decisive Tactics Stream Deck Plugin

### ISSUE THREAD

**Issue by Eye-Jessup** [bitfocus/companion-module-requests#1167]
Hi,
I am requesting a plugin for Companion to control Serial 2 by Decisive Tactics, a MacOS program that sends serial commands to devices via USB to DB9 wire. https://www.decisivetactics.com/products/serial/
It would be helpful to be able to send Serial commands (RS232) directly from the Stream Deck. I have tried to use a Global Cache IP2SL as an alternative, without success.
Thank you for your assistance

**Comment by istnv** [comment]
The `generic-tcp-serial` module does that.
It creates an internal TCP server to send and receive data through an RS232 port.

**Comment by Eye-Jessup** [comment]
Thanks very much John. Generic-tcp-serial works perfectly and solves the problem.
Really appreciate your help.
