### ISSUE TITLE
Integration Zeevee Management Platform to CompanionPi

### ISSUE THREAD

**Issue by Lulu2409** [bitfocus/companion-module-requests#1171]
dear community,
When I was looking for the integration of the Elgato Stream Deck to control various applications in the network, I came across your "CompanionPi" software, which immediately impressed me.
I am surprised by the large number of devices that have already been entered.
In our company, we use a ZyPer management platform (https://www.zeevee.com/documentation/) to control our video technology, which can be triggered via REST API commands.
Unfortunately, I did not find the possibility to send commands from CompanionPi to this management platform in the devices.
Is there a way to control the server via an Elgato Stream Deck in combination with CompanionPi?
Kind regards and many thanks in advance
Lulu2409

**Comment by josephdadams** [comment]
Generic HTTP module can send REST API commands

**Comment by josephdadams** [comment]
#1020

**Comment by Lulu2409** [comment]
I have to log in to the platform in order to be able to send API commands. also via telnet. is there a way to store this login data for the Telnet or SSH connection?
Best regards
