### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by SirDesh** [bitfocus/companion-module-requests#1188]
Hey, I am attempting to use Bitfocus Companion's streamdeck plugin to press an existing button action on my streamdeck once Streamer.bot tells Companion that a Twitch Channel Point Reward has been redeemed.

The existing action is from Dixper's streamdeck Plugin.
Otherwise, Streamer.bot and Twitch channel point rewards.

Ultimately trying to run Dixper skills via channel points.

**Comment by haakonnessjoen** [comment]
I am sorry to tell you that the plugin framework of the Elgato Stream Deck application does not let plugins interact with other buttons or plugins within the stream deck application.

If your other button could also be implemented in Companion, it would be easier, and then run everything without the elgato application.
