### ISSUE TITLE
Dante Domain Manager API

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-requests#1189]
- [ ] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
[Audinate Dante Domain Manager](https://www.audinate.com/products/software/dante-domain-manager)

What you would like to be able to make it do from Companion:
Check domain & device  status.
Check, set & clear device subscriptions.

Direct links or attachments to the ethernet control protocol or API:

[AUD-MAN_Managed_API_v1.3.pdf](https://github.com/bitfocus/companion-module-requests/files/11810775/AUD-MAN_Managed_API_v1.3.pdf)

**Comment by josephdadams** [comment]
This module exists
