### ISSUE TITLE
X-key XK-12 USB switch interface

### ISSUE THREAD

**Issue by alias2alias** [bitfocus/companion-module-requests#1194]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:

What you would like to be able to make it do from Companion:

Direct links or attachments to the ethernet control protocol or API:

**Comment by dnmeid** [comment]
Can you please specify which XK-12 you are refering to. According to the X-Keys website, there are four different models.

**Comment by alias2alias** [comment]
Yes, it's the USB Switch Interface.

https://www.x-keys-uk.com/products/x-keys-xk-12-usb-switch-interface

**Comment by dnmeid** [comment]
This model is supported by the library we are using for interfacing to the X-Key products. I think it should work without any adjustments. Did you already try using the XK-12 switch without success?

**Comment by alias2alias** [comment]
Yes.  Couldn't get it to work.  Got it working in Central Control (after Joe modified his code for it) and using that to trigger companion buttons but not the best solution.  Would prefer to run it natively.

**Comment by dnmeid** [comment]
Did you only try with Linux or Raspi? You need to adjust some UDEV rules on this OSs for USB.

**Comment by alias2alias** [comment]
Got it working yesterday.  It seems one of our engineers had put a custom firmware in the XK-12 to get it working in Central Control.  I did a factory reset and replaced the firmware and it was recognised by companion.  Thanks.
