### ISSUE TITLE
SONOS

### ISSUE THREAD

**Issue by parrot2602** [bitfocus/companion-module-requests#121]
I would like to user streamdeck for sonos volume up/down and 
previous/next song in the playlist.
...maybe choose a playlist but that isn´t much important.

**Comment by josephdadams** [comment]
A quick google search for Sonos API, I found this. Pasting it here for anyone who is interested: https://github.com/jishi/node-sonos-http-api

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion-module-sonos
