### ISSUE TITLE
Farrago Rogue Amoeba

### ISSUE THREAD

**Issue by 300333** [bitfocus/companion-module-requests#1210]
Hello all, my first request is about Farrago of Rogue Amoeba. I´m a Soundguy, using qlab very often in combination with companion/streamdeck, Farrago I´ve bought last week and wanna get it to my Companion-sound-envirement. Thanks a lot and greetings from berlin. Lexa

**Comment by daniep01** [comment]
This should be possible by using the OSC controls

**Comment by bryce-seifert** [comment]
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/227
