### ISSUE TITLE
Sony VPL-FHZ85 Projector

### ISSUE THREAD

**Issue by shaunmiller615** [bitfocus/companion-module-requests#1211]
Hoping to get our Sony Projectors controlled by Companion. Ideally just Power ON and OFF is all I need it to do. 

https://helpguide.sony.net/vpl/fhz85/v1/en/contents/TP1000435425.html

**Comment by istnv** [comment]
For power and shutter on/of, Sony projectors should have a PJLink option.

**Comment by bryce-seifert** [comment]
@shaunmiller615 Can you trying using the "Generic PJ Link" module and seeing if that works for your needs? I don't see any specific API at a glance in the link provided.

**Comment by shaunmiller615** [comment]
Thanks, Guys! I feel stupid, haha. Had no idea there was a generic PJ link module. Sorry about that!

**Comment by bryce-seifert** [comment]
No worries! I'm going to close this, and but if you need any help let us know.

**Comment by tacvideo** [comment]
I have updated to the latest version (4.2.3), but I see NO "generic PJ link module" or "generic: pj link" specifically.

When I search for "generic PJ link", I get 2 results 
1. Toggl: Trackl
2. ToolsonAir: just:in Capture Solutions

Neither have anything to do with PJ Link. What am I missing?

**Comment by bryce-seifert** [comment]
Try searching for "JBMIA". Also make sure you have "Available" selected in the filters 

<img width="582" height="187" alt="Image" src="https://github.com/user-attachments/assets/d45b08fe-cef5-4317-8fb4-73a3bb0f525e" />

**Comment by tacvideo** [comment]
I tried that one, it does not connect and there's no way to set/verify Port

**Comment by tacvideo** [comment]
Ok, changed the "PJ Talk service" on the projector to 4352 and enabled "Start PJ Link Service", and now appears to be working.

Thanks @bryce-seifert

**Comment by tacvideo** [comment]
The above broke "PJ Talk" and the Sony IP Remote iOS App, but I figured out the "PJ Link" service is what Companion needs

<img width="1112" height="516" alt="Image" src="https://github.com/user-attachments/assets/4ceff21f-f6ba-4f9a-b93c-b083847821d7" />

The problem I have now is, with "Requires Authentication" set on projector and password in Companion, the buttons do nothing but button Feedback will reflect the correct status (eventually). But if I remove "Requires Authentication" and the password I can turn the projectors On or Off, but it takes 30 seconds for button "Feedbacks" to reflect status updates, any idea why? Changing the Poll time from 10 seconds to 1 second in the Connection makes no difference.

Why does Authentication break functionality and why the 30s delay in Feedback?

Thanks.

**Comment by bryce-seifert** [comment]
I would suggest raising new issues here regarding these: https://github.com/bitfocus/companion-module-generic-pjlink/issues
