### ISSUE TITLE
NovaStar MX40 PRO to be added into Companion

### ISSUE THREAD

**Issue by NovaStarDavid** [bitfocus/companion-module-requests#1213]
It would be great if someone could help to add MX40 PRO into Companion.
API attached.

Thanks!
[COEX Series Interface API User Manual.pdf](https://github.com/bitfocus/companion-module-requests/files/12038459/COEX.Series.Interface.API.User.Manual.pdf)

**Comment by bryce-seifert** [comment]
Looks like this module is in progress 
https://github.com/bitfocus/companion-module-novastar-controller/issues/27

**Comment by krisdahl** [comment]
> It would be great if someone could help to add MX40 PRO into Companion. API attached.
> 
> Thanks! [COEX Series Interface API User Manual.pdf](https://github.com/bitfocus/companion-module-requests/files/12038459/COEX.Series.Interface.API.User.Manual.pdf)

We did get this implemented.

https://github.com/bitfocus/companion-module-novastar-coex
