### ISSUE TITLE
Luminex Products Gigacore and Luminode

### ISSUE THREAD

**Issue by Mike-Ghosty** [bitfocus/companion-module-requests#1222]
Hi,

Would like to build a plug in that reads data from a node and allows you to set values.

https://support.luminex.be/portal/en/kb/articles/luminode-api-documentation

also for the gigacore range
https://support.luminex.be/portal/en/kb/articles/gigacore-http-commands

**Comment by leonreucher** [comment]
Possible to build - but this would need some time and I don't have a Luminode device right now to test.

**Comment by bryce-seifert** [comment]
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/586 and https://github.com/bitfocus/companion-module-requests/issues/813
