### ISSUE TITLE
Rodecaster Pro 2

### ISSUE THREAD

**Issue by florianbeaufreton** [bitfocus/companion-module-requests#1235]
- [ ] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control: Rode Rodecaster Pro 2

What you would like to be able to make it do from Companion:
- Mute or Unmute audio sources
- Control MIDI Pads
- Record/Stop Record
- ...

Direct links or attachments to the ethernet control protocol or API: https://rode.com/en/user-guides/rodecaster-pro-ii

**Comment by josephdadams** [comment]
#885
