### ISSUE TITLE
Connection for TESmart 8x1 HDMI Switch

### ISSUE THREAD

**Issue by chawkins117** [bitfocus/companion-module-requests#1238]
Looking to do Network control of TESmart 8x1 HDMI Switch. There is a connection on Companion for the Matrix Switch but that didn't work.

Below is link to the Switch Controller also I did Wireshark filtering the 5000 port. Connecting through the Controller App, selecting input 1, then Input 2.

[Wireshark Port 5000](https://www.dropbox.com/scl/fi/0vha42rako6xsalee3tl4/Port-5000-filter-Packets.pcapng?rlkey=nsi0tgt9w471ag1txir5cllh9&dl=0)

[TESmart 8x1 HDMI Switch controller.rar](https://www.dropbox.com/scl/fi/xh14e18sgoz5mfbogep47/8x1-HDMI-Switch-Controler.rar?rlkey=ns3wsyn6dpwrn4el1ta8c0ov8&dl=0)

[Extracted Folder](https://www.dropbox.com/sh/l75ajgjzbmcwsty/AAAktBFIW2DcIQ9YtPinFW30a?dl=0)

**Comment by leonreucher** [comment]
Try this module, works for me: https://github.com/bitfocus/companion-module-tesla-smart

**Comment by chawkins117** [comment]
that works, thanks!
