### ISSUE TITLE
Blackmagic Hyperdeck Extreme 4K HDR

### ISSUE THREAD

**Issue by n3rdz** [bitfocus/companion-module-requests#1242]
Please add the new "Blackmagic Hyperdeck Extreme 4K HDR" to the list of Blackmagic Devices

**Comment by peternewman** [comment]
I think you'd be better off asking on the existing module:
https://github.com/bitfocus/companion-module-bmd-hyperdeck/issues

There's already this:
https://github.com/bitfocus/companion-module-bmd-hyperdeck/issues/88
