### ISSUE TITLE
Kiloview N Series

### ISSUE THREAD

**Issue by benwithbanana** [bitfocus/companion-module-requests#1243]
Hey guys.. there is a N40 module which not working anymore.. Im using the new N6 NDI Encoder/Decoder and tested the available API with GET Method.. it works!

Would be nice, if someone would repair or write a new module for N3/30/4/40/5/50/6/60....

I attached the available API reference Document....

Thanks and greetings

David

[NDI-Device-HTTP-API-for-N3N4N30N40-Version-1.0.pdf](https://github.com/bitfocus/companion-module-requests/files/12358023/NDI-Device-HTTP-API-for-N3N4N30N40-Version-1.0.pdf)

**Comment by peternewman** [comment]
You're probably better off asking/reporting in the existing module:
https://github.com/bitfocus/companion-module-kiloview-ndi

What do you mean by "not working anymore", does it work fine in Companion but just doesn't control the device?
