### ISSUE TITLE
Lightshark LS CORE/LS 1 Sync/dynamic/feedback from Lightshark to companion

### ISSUE THREAD

**Issue by guitarmac1** [bitfocus/companion-module-requests#1266]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

Lightshark LS Core/LS 1, LightShark Software: Sync/dynamic/feedback from Lightshark to companion

Has anyone had any luck with getting Sync Executors feedback on the Lightshark instance? I have control over the Executors which is amazing but not the feedback. I can only see port 8000 for incoming within companion but not the outgoing port 9000.

<img width="1400" alt="Screenshot 2023-09-16 at 2 25 26 pm" src="https://github.com/bitfocus/companion-module-requests/assets/65983295/a9adcb8b-ea0d-4e6d-b089-20deaeebcfa3">
<img width="1401" alt="Screenshot 2023-09-16 at 2 25 56 pm" src="https://github.com/bitfocus/companion-module-requests/assets/65983295/44aafc40-f84e-4672-a00c-84332a51fb99">
[Lightshark OSC.pdf](https://github.com/bitfocus/companion-module-requests/files/12641583/Lightshark.OSC.pdf)

**Comment by leonreucher** [comment]
I had a quick look at the module in GitHub and it does not look like there are any feedbacks implemented in the module.
Regarding to the documentation a sync command can be used to poll the device - currently the LS does not send updates when values on the console have changed.
But using polling it should be possible to provide feedbacks.

**Comment by leonreucher** [comment]
As I don't have the console here right now, could you do me a favor?
If you could send the following OSC commands to the LS1 and capture the response, this would be perfect.

/LS/Sync
/LS/Sync/Playbacks
/LS/Sync/Executors

Then I could see, what the console returns to these messages.

**Comment by guitarmac1** [comment]
Hi @leonreucher thank you for your reply. If I can set up a lightshark with a computer that can be remoted into for testing, would you be able to test it that way? I really appreciate your time on this it means a lot.

**Comment by leonreucher** [comment]
Yeah that would be perfect!

**Comment by leonreucher** [comment]
Probably you can join the Companion Slack (https://bitfocus.io/api/slackinvite), then we can communicate there :)

**Comment by guitarmac1** [comment]
Great thank you @leonreucher. I should be able to get a lightshark today and set up the environment for testing for you. Perfect I'll jump on slack.

**Comment by leonreucher** [comment]
Perfect - I am located in Germany, therefore my day will end soon. But I should find some time tomorrow, to make the required tests/changes.

**Comment by ziginfo** [comment]
Hello
the request "/LS/Sync/Executors” with the argument Float(0)  works as expected !! when sending it to the LightShark, than the LighShark will send back the state of every single Executor-Button (independant if the Button is patched with a CUE or not....
as for example => INT32(1) means ON and INT32(0) means OFF
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/1/1) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/1/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/1/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/1/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/1/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/1/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/2/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/2/2) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/2/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/2/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/2/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/2/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/3/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/3/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/3/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/3/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/3/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/3/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/4/1) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/4/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/4/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/4/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/4/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/4/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/5/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/5/2) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/5/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/5/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/5/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/5/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/6/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/6/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/6/3) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/6/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/6/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/6/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/7/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/7/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/7/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/7/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/7/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/7/6) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/8/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/8/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/8/3) INT32(1)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/8/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/8/5) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/1/8/6) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/2/1/1) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/2/1/2) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/2/1/3) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/2/1/4) INT32(0)
RECEIVE    | ENDPOINT([::ffff:192.168.42.1]:57933) ADDRESS(/LS/Executor/2/1/5) INT32(0)
etc etc etc etc ......

---------------------------

![protocol-lightshark](https://github.com/bitfocus/companion-module-requests/assets/34913387/7cbed995-7d7f-433f-b1cb-ea5b6d272f4b)

**Comment by leonreucher** [comment]
Sorry guys - I'm on vacation till Sunday. I can build the executor state etc. into companion feedbacks. The module is ready so far, just needs a few code adjustments :)

**Comment by ziginfo** [comment]
Hello [leonreucher](https://github.com/leonreucher)
the thing that is wrong in the LightShark-Companion-plugins JS-File is that for nearly all OSC commands the argument is missing !!
and "LightShark" needs the argument FLOAT(0) to  validate !!
that means that Companion must be recompiled with the right JS-File... otherwise pretty none of those OSC-Commands will work !

so for example
Companion sends out the command "/LS/Sync" which is ignored by LightShark if there is no argument...
otherwiese the command "/LS/Sync f(0)" is correctly received by LightShark and a Feedback concerning the state of all faders and Executor-Buttons is than send back to the configured Send-Port in LightShark

**Comment by leonreucher** [comment]
I developed a whole new module for the Lightshark. I am aware of the steps needed to get the new module into the next companion version :)

**Comment by ziginfo** [comment]
nice !! thanks already !!
where can we get this module-plugin ? is it already integrated in the Companion-App ?
or is ther something special to do, to integrate the plug-in into the App ?

if you need any further help or infos don't hesitate to ask... :)

thanks greatly !! and friendly greetings...

**Comment by leonreucher** [comment]
It's not integrated into the app yet - as I stated I'm on vacation - will do this next week :)

**Comment by ziginfo** [comment]
there is no rush and no fire...
thanks anyway for your great help... and have fun for your Sunday-holiday....
cheers Ziggy

**Comment by guitarmac1** [comment]
Thank you Leon. I hope you are relaxing nicely on your vacation

**Comment by guitarmac1** [comment]
Hi @ziginfo do we need to apply the same for our playbacks and GM?

**Comment by leonreucher** [comment]
As I found out during our AnyDesk sessions, the /LS/Sync sends information about executors and playbacks 👍🏻

**Comment by ziginfo** [comment]
Hello
there are three different OSC-Command concerning the State-Feedback : 
"/LS/Sync f(0)" sends back all available feedback
"/LS/Sync/Playbacks f(0)" sends back only feedback concerning the Faderposition of the Playbacks
"/LS/Sync/Executors f(0)" sends back only feedback about the state ON-OFF of the Executor-Buttons

**Comment by ziginfo** [comment]
Hello
just in reminder...
here are a few new OSC-Commands present in the latest Softwares for LightShark (since 1.4.47... the actual latest version is 1.5.13); they do not figure yet in the LS-Manual ! some very interesting features are there, as the Tap-functions and Go-to-CUE etc... might be worth to add some of them to the Companion-Config-File...

![osc-commandes-new](https://github.com/bitfocus/companion-module-requests/assets/34913387/869d9ce1-989c-44d4-8515-63a568f17bbf)
------------------------------------
and these are the standard OSC-Commands, figuring also in the official LS-Manual....
[LightShark_OSC1.pdf](https://github.com/bitfocus/companion-module-requests/files/12711271/LightShark_OSC1.pdf)

**Comment by guitarmac1** [comment]
It would be good to have the GM if the OSC-Command is available

**Comment by dnmeid** [comment]
Please proceed with requests or disqussion about the existing Lightshark module at its repo.
