### ISSUE TITLE
QLC+

### ISSUE THREAD

**Issue by marcusleonas** [bitfocus/companion-module-requests#1268]
QLC+ is a free and open-source lighting console for Linux, Windows and macOS.

Website: [www.qlcplus.org/](https://www.qlcplus.org/)
Web Interface docs: [docs.qlcplus.org/v4/advanced/web-interface)](https://docs.qlcplus.org/v4/advanced/web-interface)

**Comment by Julusian** [comment]
Duplicate of #612
