### ISSUE TITLE
Ross Video: NK Router for Companion v3

### ISSUE THREAD

**Issue by bbkwtx** [bitfocus/companion-module-requests#1269]
There is already a connection  for this device, however it does not work with v3.  A rquest was made on the github page for the code, but nothing has been done on the code for at least 2 years.

I'm not a devloper, but just trying to get someone's attention so that this code can be made to work with v3.

It appears that one of the parameters needed is not being displayed in the gui.  In the code type is 'multiselect'.  Perhaps this had been deprecated and all that need to be done is to change this to the new type?

If someone could please try to make this functional with v3

**Comment by daniep01** [comment]
Could you post a link to repo you would like to be updated to v3

**Comment by bbkwtx** [comment]
https://github.com/bitfocus/companion-module-rossvideo-nkrouter

Thanks

**Comment by hartmann-jonas** [comment]
I don't have access to the device, but if you are down for testing I can upgrade the module for Companion v3.

**Comment by bbkwtx** [comment]
I can test it
Here is the error I throws the first time you press a button.
error: (node:10864) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

I do not get the error on subsequent button presses.

**Comment by hartmann-jonas** [comment]
I took a look at the code and started updating.
There is still a lot of old code in there that won't work properly in v3. I'll try and get it done over the weekend, also it would be great if you can give me an email address to which I can send the reworked module.

**Comment by hartmann-jonas** [comment]
I've got a first beta version ready for you to test.
Just hit me up at [git.jonashartmann@proton.me](mailto:git.jonashartmann@proton.me).

**Comment by dnmeid** [comment]
Well as it seems you  got someone's attention and the upgrade is in the making, I'm going to close the issue here and kindly ask you to proceed with upgrade requests at the module repo.
