### ISSUE TITLE
Vitec (formerly Exterity) IPTV Receiver Control

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-requests#1271]
- [ ] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:

Vitec / Exterity IPTV Endpoints
[https://www.vitec.com/exterity/media-players](https://www.vitec.com/exterity/media-players)

What you would like to be able to make it do from Companion:

Check & Change mode, Check & Change channel, Check & Change Volume

Other functions nice to have.

Direct links or attachments to the ethernet control protocol or API:

See attached doc from page 78 for HTTP GET and POST commands.

[Receiver_Development_Kit_6_7.3.pdf](https://github.com/bitfocus/companion-module-requests/files/12694140/Receiver_Development_Kit_6_7.3.pdf)

**Comment by leonreucher** [comment]
Should be possible - please join the Bitfocus Slack and contact me there, so we can talk about the implementation.

**Comment by phillipivan** [comment]
@leonreucher Done.

**Comment by phillipivan** [comment]
Have written module, will submit once repo is created.
