### ISSUE TITLE
Softron On The Air Video

### ISSUE THREAD

**Issue by stephanemex** [bitfocus/companion-module-requests#1274]
I Already use Companion with On The Air Video, but, it not allow to have remote controle on two players. It's because the connection preset not take in charge the port. It's only basic ip as 127.0.0.1. 
To get arroud it, I use Generic HTTP connection the my second player, but I have to set manually Rest API commands.

Is it possible to have a connection preset with Softron OTA taking in charge ip with listening port like 127.0.0.1:8081 ? 

Thank you in advance,

**Comment by bryce-seifert** [comment]
@stephanemex Which version of Companion are you using?
It looks like the latest versions f Companion (3.0) should support multiple players and port configuration https://github.com/bitfocus/companion-module-softron-ontheairvideo/pull/2

**Comment by bryce-seifert** [comment]
Please open an issue in the [On The Air module repository](https://github.com/bitfocus/companion-module-softron-ontheairvideo/issues) if you continue to have issues.
