### ISSUE TITLE
Musco Lighting

### ISSUE THREAD

**Issue by thav3735** [bitfocus/companion-module-requests#1284]
I am trying to do commands to Musco lighting through a Stream Deck, using UDP commands that I have.  What is the best way to go about this?

**Comment by bryce-seifert** [comment]
Do you have a document with the UDP commands you could attach here? Or any API documentation?

**Comment by thav3735** [comment]
We actually got it going using the Companion software from Bitfocus.  Part of the issue was the proper punctuation that is required.  The commands that Musco gave us, had to many capitalized letters.   Once fixed that, we got instant feedback.

**Comment by bryce-seifert** [comment]
So do you have what you need working? Or do you still need a module created?

**Comment by thav3735** [comment]
I have what I need.  Thanks.

**Comment by peternewman** [comment]
Hi @thav3735 ,

It doesn't impact me personally, but the next person finding this might appreciate anything you can add, e.g. the documentation of UDP commands and/or a working command with the right punctuation.

**Comment by RobarePruyn** [comment]
FYI - I'm working on the same integration as we speak.  I'll provide comments regarding how I resolved the issue so others can reference once I have it fully working.

**Comment by RobarePruyn** [comment]
So let me run through how I have this working today in Companion without a dedicated module:

Generic TCP/UDP Module
Musco provides a Sonicwall appliance between their internally managed equipment and their controller.
Control messages are sent as UDP to the Sonicwall appliance IP at port 6000
Messages are sent raw ASCII with no end Command End character.

Musco provides the list of preset commands (although they have a history of providing them with caps errors)

In the implementation I just worked through, the message was in the following format:
Cue 0001 Go

Case sensitivity was the biggest problem - the command string was provided to the end customer with CUE in all caps which was not correct.  (In the working example above, what Musco provided was actually CUE 0001 Go)

Happy to share or help troubleshoot with anyone still struggling.

**Comment by RobarePruyn** [comment]
Side note - to the extent Musco provides "API Documentation", it's essentially just "Send an ASCII string from Ross to your Sonicwall appliance on port 6000".  It's the least detailed control documentation I've ever seen.
