### ISSUE TITLE
Module Request: Colorlight Sender

### ISSUE THREAD

**Issue by chukie-clt** [bitfocus/companion-module-requests#1286]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Colorlight Sender

What you would like to be able to make it do from Companion:
Please help me create a new Companion Module, then I can complete it, like this:
https://github.com/bitfocus/companion-module-colorlight-processor

Direct links or attachments to the ethernet control protocol or API:
I hava protocols to control the device.

**Comment by bryce-seifert** [comment]
If you are a developer and need a repository created, please request this in #module-development channel on the Bitfocus slack channel. https://bitfocus.io/api/slackinvite
