### ISSUE TITLE
Module Request - Avolites Ai mediaserver.

### ISSUE THREAD

**Issue by bikeatefoucault** [bitfocus/companion-module-requests#129]
support for Avolites Ai mediaserver.

https://www.avolites.com/ai-features

**Comment by bikeatefoucault** [comment]
https://www.avolites.com/Portals/0/downloads/Software/Ai/Ai%20v12%20User%20Manual.pdf?ver=2019-10-14-120228-527

it works with Artnet, midi, and keyboard shortcuts.

**Comment by yyy898** [comment]
give me a few days, i started creating this module, are there specific features you realy want to be able to control ?

I am implementing:
play
stop
intensity
red value
green value
blue value
hue adjust
saturation adjust
contrast adjust
strobe value
selecting a clip
playspeed
audio volume

**Comment by bikeatefoucault** [comment]
hell yeah!

most Ai/mediaserver users have lighting consoles with knobs to control things like rgb/hue/sat.

playback: play & stop (on specific layers)/layer selection/file selection (play file), scene triggers, intensity choke groups (one layer goes full intensity others go to zero) are the useful kinds of things to have on a stream deck.

think switcher functionality.

I'll try again to get some Ai people over here to chime in.

**Comment by yyy898** [comment]
i dont think scene triggers are possible over artnet.
the rest of the functions are implemented, just some more testing on my side to make sure everything runs smooth and i think il have it up and running by tomorrow

**Comment by yyy898** [comment]
@josephdadams this module is ready, you can close this issue # #
