### ISSUE TITLE
ROLAND VR-120HD

### ISSUE THREAD

**Issue by Mattymc001** [bitfocus/companion-module-requests#1294]
I would like to request the ROLAND VR-120HD to be added to the companion app device list.
Many thanks.
Matt

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-roland-vr120hd

**Comment by Mattymc001** [comment]
hi and thanks for sharing this module.
I can't seem to get it working with my VR120HD. If you have a config
tutorial or step by step that would be amazing.

Regards,
Matt

*+61 423568501*

*QLD | **AUSTRALIA*

**Comment by josephdadams** [comment]
Are you getting an error?

**Comment by Mattymc001** [comment]
Hi, no error, connected OK, but none of the commands are working. What
firmware version were you testing with on the VR120?


Regards,
Matt

*+61 423568501*

*QLD | **AUSTRALIA*

**Comment by josephdadams** [comment]
I don't remember. I wrote it for a client and we tested remotely. File an issue on that repo and maybe we can track it down at some point

**Comment by Mattymc001** [comment]
Ok thank you. Will do. I have been waiting for the day someone added Roland
to the list. Well done!


Regards,
Matt

*+61 423568501*

*QLD | **AUSTRALIA*
