### ISSUE TITLE
akai apc mk2

### ISSUE THREAD

**Issue by danny-housley** [bitfocus/companion-module-requests#1308]
Are there any thoughts to adding the akai apc mini mk2 to the list of profiles in companion?   Its becoming more and more used

**Comment by dnmeid** [comment]
Did you read this?

**Please include with your request:**
* The name of the device, hardware, or software you would like to control.
* What you would like to be able to make it do from Companion.
* Direct links or attachments to the ethernet control protocol or API. Without this, it can be very difficult, *and in some cases, impossible* to fulfill your request.
* Module requests that do not come with enough information may be deleted. This will not happen without some form of response, so please be thorough in your request.

**Guidelines:**
* Commit to being a tester for the module you requested. Make sure you are subscribed to notifications to your request with a method you will check up on.
* If a developer asks a question about your request, provide feedback promptly. Be thorough in your responses.
* Remember, everyone working on this project is donating their time. Please be courteous and respectful.
* If your request has a tight timeline, consider offering a financial reward to speed up development of your module request.
* Consider other ways you can serve the community and project here, like verifying and submitting thorough bug reports, creating documentation, and helping others along the way.


Anyway: at this point there are no considerations for including any MIDI controllers. There is a roadmap which will lead us to surface modules which can be of any type and with a wide variety of controls. At this point which I guess is in ca. two years we can think about which Midi controllers would be nice to be included.
