### ISSUE TITLE
MultiPlay Audio Cue Playback software

### ISSUE THREAD

**Issue by paulxharris** [bitfocus/companion-module-requests#131]
MultiPlay is some great free software for playing back sounds cues in a theater environment and it would be great if Companion could control it.

MultiPlay has a Telnet interface with some simple commands to drive it.

In the manual attached there is a list of the telnet commands on page 21
ius it possible to get companion to drive it ?

website for multiplay
https://www.da-share.com/software/multiplay/
[MultiPlay.pdf](https://github.com/bitfocus/companion-module-requests/files/3952464/MultiPlay.pdf)

**Comment by josephdadams** [comment]
@paulxharris a model module request submission. Thank you! I imagine this will get made pretty quickly because of that.

**Comment by JeffreyDavidsz** [comment]
Traveling today, might be able to create it. Always like a new windows program ;-)

**Comment by JeffreyDavidsz** [comment]
@paulxharris the module is ready for you, tested it with GO and stop all. Could you download a new build and test the other stuff? I'll close this. When there is something please create an issue under the repo (companion-module-da-share-multiplay)

**Comment by paulxharris** [comment]
Hi,
All Functions tested and working correctly.
only thing I see unusual is that on the connections screen, it always says connecting and doesn't go OK
But looks great thanks

Paul

**Comment by JeffreyDavidsz** [comment]
That's strange I have to check that. There is no info coming back so standard would be OK

**Comment by JamboPE** [comment]
I can't seem to get this module working in the latest releases of both multiplay and companion. Is it just an error at my end?

**Comment by paulxharris** [comment]
Hi The new version of Multiplay dos'nt use the same communication process.
you can now use OSC to control it.
________________________________
From: Jamie Parker-East ***@***.***>
Sent: 17 December 2022 23:02
To: bitfocus/companion-module-requests ***@***.***>
Cc: Harris, Paul ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [bitfocus/companion-module-requests] MultiPlay Audio Cue Playback software (#131)


I can't seem to get this module working in the latest releases of both multiplay and companion. Is it just an error at my end?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbitfocus%2Fcompanion-module-requests%2Fissues%2F131%23issuecomment-1356494304&data=05%7C01%7Cpaul.x.harris%40marks-and-spencer.com%7Cc5e64463bf4f4b40c0ab08dae082cbde%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C638069149623310482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xninAyESz2l4nZsegBZxaxi8aYEbTVx5fmnsEsAm%2FQ4%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALW7YP5VPBPHPPXJJYAITPDWNZBA5ANCNFSM4JZU22FA&data=05%7C01%7Cpaul.x.harris%40marks-and-spencer.com%7Cc5e64463bf4f4b40c0ab08dae082cbde%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C638069149623310482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e%2B8Wp3cmIpxWIMEDp2Rrhls%2FHJ9aC1GMojoEKj%2FVJcE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


Marks and Spencer
________________________________
Unless otherwise stated:
Marks and Spencer plc
Registered Office:
Waterside House
35 North Wharf Road
London
W2 1NW

Registered No. 214436 in England and Wales.

www.marksandspencer.com

Please note that electronic mail may be monitored.

This e-mail is confidential. If you received it by mistake, please let us know and then delete it from your system; you should not copy, disclose, or distribute its contents to anyone nor act in reliance on it, as this is prohibited and may be unlawful.

Facebook<https://www.Facebook.com/marksandspencer/>     Twitter<https://www.Twitter.com/marksandspencer/>       Linkedin<https://www.linkedin.com/company/marks-and-spencer>    Pinterest<https://www.Pinterest.com/marksandspencer/>   Youtube<https://www.youtube.com/user/marksandspencertv?sub_confirmation=1>      Instagram<https://www.instagram.com/marksandspencer/>

**Comment by NijsJonas** [comment]
> Hi The new version of Multiplay dos'nt use the same communication process. you can now use OSC to control it.
> […](#)
> ________________________________ From: Jamie Parker-East ***@***.***> Sent: 17 December 2022 23:02 To: bitfocus/companion-module-requests ***@***.***> Cc: Harris, Paul ***@***.***>; Mention ***@***.***> Subject: [EXTERNAL] Re: [bitfocus/companion-module-requests] MultiPlay Audio Cue Playback software (#131) I can't seem to get this module working in the latest releases of both multiplay and companion. Is it just an error at my end? — Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbitfocus%2Fcompanion-module-requests%2Fissues%2F131%23issuecomment-1356494304&data=05%7C01%7Cpaul.x.harris%40marks-and-spencer.com%7Cc5e64463bf4f4b40c0ab08dae082cbde%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C638069149623310482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xninAyESz2l4nZsegBZxaxi8aYEbTVx5fmnsEsAm%2FQ4%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALW7YP5VPBPHPPXJJYAITPDWNZBA5ANCNFSM4JZU22FA&data=05%7C01%7Cpaul.x.harris%40marks-and-spencer.com%7Cc5e64463bf4f4b40c0ab08dae082cbde%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C638069149623310482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e%2B8Wp3cmIpxWIMEDp2Rrhls%2FHJ9aC1GMojoEKj%2FVJcE%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***> Marks and Spencer
> ________________________________ Unless otherwise stated: Marks and Spencer plc Registered Office: Waterside House 35 North Wharf Road London W2 1NW Registered No. 214436 in England and Wales. [www.marksandspencer.com](http://www.marksandspencer.com) Please note that electronic mail may be monitored. This e-mail is confidential. If you received it by mistake, please let us know and then delete it from your system; you should not copy, disclose, or distribute its contents to anyone nor act in reliance on it, as this is prohibited and may be unlawful. Facebook<https://www.Facebook.com/marksandspencer/> Twitter<https://www.Twitter.com/marksandspencer/> Linkedin<https://www.linkedin.com/company/marks-and-spencer> Pinterest<https://www.Pinterest.com/marksandspencer/> Youtube<https://www.youtube.com/user/marksandspencertv?sub_confirmation=1> Instagram<https://www.instagram.com/marksandspencer/>

do you know the osc commands ? i can get the go working with osc but not the stop or stop all

**Comment by JamboPE** [comment]
Unfortunately Multiplay has stopped working on my laptop all together, I have contacted the developer but the thread has gone cold so unfortunately I can't be much more help, will let you know if I ever manage to get it working again however
