### ISSUE TITLE
Streamdeck brightness / screen timeout

### ISSUE THREAD

**Issue by BestBackwards** [bitfocus/companion-module-requests#1327]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
Streamdeck (already supported)

What you would like to be able to make it do from Companion:
1. Set a screen timeout; if button is not pressed in X seconds / minutes, timeout and sleep the display.

Direct links or attachments to the ethernet control protocol or API:
N/A

Edit: Pressed enter before ready.

**Comment by bryce-seifert** [comment]
I think this is more of a Companion core feature than a module, and I think this request is covered in this open issue
https://github.com/bitfocus/companion-module-requests/issues/1327

**Comment by BestBackwards** [comment]
Sorry, I'm confused, you linked this very same issue

**Comment by bryce-seifert** [comment]
Apologies, that’s my mistake.

Here’s the actual issue:
https://github.com/bitfocus/companion/issues/1660
And possibly this as well:
https://github.com/bitfocus/companion/issues/428
