### ISSUE TITLE
Kramer VP-734

### ISSUE THREAD

**Issue by dgsauer** [bitfocus/companion-module-requests#133]
I'm either looking for a module or just an explanation of how to use the generic http module to switch inputs on this device.  

I'm told by Kramer that the RS-232 commands also work via http, but I don't know the syntax.

Here is a link to the manual with all the control codes:
https://cdn.kramerav.com/web/downloads/manuals/in-out_resolutions.pdf

Any help greatly appreciated.  THANKS.

**Comment by JeffreyDavidsz** [comment]
Did you look in that file?

**Comment by josephdadams** [comment]
@dgsauer the file you linked to is not the protocol information. Can you track that down?

**Comment by dgsauer** [comment]
Sorry about that.  The RS-232 protocol and syntax is near the end, and I was told by Kramer that that is what was needed for the tcp control.  I will try to contact them and see if there is some other documentation.

**Comment by dgsauer** [comment]
OK, so I spoke to tech support.  They said that the TCP control codes are the same as the RS-232 codes which start on page 63 of the manual.  
The syntax is as follows:   #Y [space] Control_Type [space] Function [space] Parameter [space] [carriage return]
So, according to him, the syntax to switch to Input 1 would be:
#y 0 30 0 [carriage return]

I'm not positive how to designate the carriage return (CR), though the manual gives the ASCII code which is 0x0D.

Does that help?  Again, if it is too big a deal to build a module, just give me an explanation of how to send this code using the generic http module.
Thanks!

**Comment by JeffreyDavidsz** [comment]
I think you have uploaded the wrong file, as said there is no protocol information there. Generic http cannot be used for what you want, but if the protocol is clear, we can make a module for it

**Comment by dgsauer** [comment]
Oh yeah, the link I posted was the wrong one.  Apologies! Here is the link to the manual:
https://cdn.kramerav.com/web/downloads/manuals/kramer-vp-734-um-5.pdf

After looking at the discussions in the generic http module, I realized that it won't do what I wanted.  A new module would be greatly appreciated.  Or, is there any other way to simply text send strings to an IP address?

**Comment by JeffreyDavidsz** [comment]
@dgsauer looking at that file, it seems that the commands are only supported via RS-232. Unless you have a LAN->RS-232 box, it will probably not work. Might want to check if its possible via the lan port first (ask for portnumber too). The ethernetport seems to connect to a build in webserver to control the machine

**Comment by EventReplay** [comment]
@dgsauer please look @ this module:
 https://github.com/bitfocus/companion-module-kramer-vp727/tree/6fc463a3b32f60e002019b26456b4af0d55ebcf4
This is a good starting point. 5000 port is correct commands look same format and should just need tweaking IMHO.

**Comment by EventReplay** [comment]
@JeffreyDavidsz section 10.1 in the manual stating ethernet connection could be misleading as I've seen 2 different manuals one says port 80 and one says port 5000(This I believe to be correct and is the latest to my knowledge).
PLEASE NOTE: it does say in both manuals only 1 TCP connection! So you might run in to issues if you have web interface and a companion instance at the same time.

**Comment by JeffreyDavidsz** [comment]
I will copy the old module with the new commands, needs to be tested I guess. What kind of os are you running?

**Comment by JeffreyDavidsz** [comment]
Ok new module added. Please test it. The commands in the old module where without the `#` so I did the same here. Also a custom option to test for yourself. Please let me know in the new repo if there are any things that need to be changed; https://github.com/bitfocus/companion-module-kramer-vp734/issues

**Comment by dgsauer** [comment]
@JeffreyDavidsz and @EventReplay,  THANK YOU!  You all are amazing. Unbelievably helpful and incredible response time.  I have not had access to the equipment yet because of the holiday schedule, but as soon as I am able I will test.  Thank you again!

**Comment by JeffreyDavidsz** [comment]
No problem, please let us know if it works as @EventReplay mentioned we second guess the end of the sended command.

**Comment by dgsauer** [comment]
I started to test, but I'm having trouble figuring out how to install the module.  Can you point me to the module install instructions?

**Comment by JeffreyDavidsz** [comment]
You need to download the latest build from the website. Unless you have a develop environment running you cannot just install a module yet
