### ISSUE TITLE
Device Request: Vidblaster X

### ISSUE THREAD

**Issue by Vuurmannetje** [bitfocus/companion-module-requests#1344]
Simple request.

Great piece of software with a publically available API.
Vidblaster X is a Software based production Mixer with reliable high bandwith NDI processing.

However theres no quick and easy way to add controllers, so Companion integration would be insane.

**Comment by Vuurmannetje** [comment]
Official Website: https://www.vidblasterx.com/

Official help that contains API info: https://vidblaster.com/help/x6/

**Comment by mikeversteeg** [comment]
I'm the developer of VidBlaster and available in case there are any questions. Thanks!

**Comment by lundbergjohan** [comment]
A great flexible software. Been using it it on various projects for many years, including control through raw TCP/IP connection from Companion to it's API.
Also been working tightly with Mike (the developer) throughout the years, pushing it forward and fit for some larger NDI-based productions we have done.

A module for this would för sure be great and make integration alot easier!

Let me know if you need any help in discussions or testing of this.

Thanks!

**Comment by Splashaudio** [comment]
Yea Please! The lack of a Companion is the only thing stopping me from changing to VBX

**Comment by JeLuF** [comment]
Work in progress: https://github.com/bitfocus/companion-module-combitech-vidblasterx

**Comment by JeLuF** [comment]
Support for VidblasterX is available in Companion v3.3.0

**Comment by mikeversteeg** [comment]
Super, thanks!
