### ISSUE TITLE
Open webpage on specific computer

### ISSUE THREAD

**Issue by themathsim** [bitfocus/companion-module-requests#1353]
Hi everyone,

Sorry if the question had already asked, but how (if it is possible) to open a http link on a specific computer.

In fact, I have a magic mirror on my server (virtual computer); I use the companion as controler for Home Assistant, and I would like to open a link on this computer for another dashboard.

Thanks

**Comment by bryce-seifert** [comment]
I would look into  [VICREO Listener](http://www.vicreo-listener.com), which already has a module, for something like this.
