### ISSUE TITLE
Build module to control "ProjectorManager" 

### ISSUE THREAD

**Issue by echalupka** [bitfocus/companion-module-requests#1355]
https://www.sigmasix.ch/projectormanager/

**Comment by echalupka** [comment]
(Controllable via AppleScript or JavaScript) - should be able to select projector number, mute AV, unmute AV, power on and power off the projector, and select input.  Taking variables from the application would also be a nice plus, if possible.

**Comment by istnv** [comment]
Have you tried the PJLink module already available in Companion?

**Comment by echalupka** [comment]
Whoops! Disregard the request... PJLink module works for our needs. Thank you!
