### ISSUE TITLE
farrago bitfocus companion

### ISSUE THREAD

**Issue by IceCubeNinJah** [bitfocus/companion-module-requests#1376]
Hello
Is there a Module for Farrago and bitfocus companion?
Thanks!

**Comment by bryce-seifert** [comment]
Yes, available in v3.2 (beta) version.

**Comment by IceCubeNinJah** [comment]
thanks ill check it out

Bobby

**Comment by IceCubeNinJah** [comment]
thanks, but do you know any way to get it to actually play a sound?
I can connect and get the app to stop and fade

thanks

**Comment by bryce-seifert** [comment]
I would take a look at the “Presets” section for help getting started.

The two ways to play are to play a specific tile, or use the “Play Selected” title action.
