### ISSUE TITLE
Add tplink-taposmartplug TP-Link module for 3.2.0 version

### ISSUE THREAD

**Issue by Wostam** [bitfocus/companion-module-requests#1382]
it is possible to redo a module to control the tapo p110 since the new stable version 3.2.0, because in the old version it was giving me failures and did not let me connect.
Or if anyone knows any solution to the connection problem, I would be very grateful.

**Comment by Doogiechap** [comment]
Hi Wostam,
I'm having the same issues as you and have started a [Gofundme](https://www.gofundme.com/f/bitfocus-companion-tp-link-tapo-smartplug-module?utm_campaign=m_pd%20share-sheet&utm_medium=copy_link_all&utm_source=customer&fbclid=IwAR2ZPzGVKXj4eqIhoox7MUjgFnIj8F9AZjkwYh5IJRNaMsxYYHZjJNx_4Qs) for the module to be upgraded. Fingers crossed it gets enough backing to get up and running :-) 
**Edit** Funding target reached - things will start moving once funds are released and able to be forwarded onto the developer :-)
