### ISSUE TITLE
Generic app control by keyboard shortcuts (macOS)

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-requests#1398]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control: **any Mac app that has keyboard shortcuts.**

What you would like to be able to make it do from Companion: **run arbitrary app commands by giving app name and keyboard shortcut.**

(I can't quite believe this isn't possible, but I can't see it as a built-in module, or a module request, or in Slack FAQ etc.)

Direct links or attachments to the ethernet control protocol or API: ?

**Comment by bryce-seifert** [comment]
You can accomplish this with [VICREO Listener](https://www.vicreo-listener.com), which has a Companion module

**Comment by jgclark** [comment]
I have since discovered that, but only from rather more googling around.
There's no way that people who aren't already aware of VICREO will understand from its module title that its anything to do with sending commands or keystrokes.
I appreciate you might not want to change its title, but at least add to a FAQ about this.

**Comment by bryce-seifert** [comment]
Modules are developed independent of Companion itself, and the determined by the developer of specific module.
