### ISSUE TITLE
Generic OSC Listener - Outside of Companion Service

### ISSUE THREAD

**Issue by drjeffries** [bitfocus/companion-module-requests#1409]
I would love the ability to get feedback from devices that don't necessarily have current support via OSC; or to get OSC messages back for Dev purposes. 

As it stands right now, the generic OSC module only allows for sending OSC commands. 

**The name of the device, hardware, or software you would like to control.**

- Companion custom variables

**What you would like to be able to make it do from Companion.**

- Generate or update an internal variable, so other modules can reference the custom var.
- It would be great if it could parse either the last /xyx of the message or the whole sring.
- Bundles are interesting but not critical

**Direct links or attachments to the ethernet control protocol or API. Without this, it can be very difficult, and in some cases, impossible to fulfill your request.**

- It would seem that the current service could be repurposed for a module like this:
- companion/lib/Service/OscListener.js
- https://github.com/CNMAT/OpenSoundControl.org/tree/master

**Comment by thedist** [comment]
Is there a reason you want this as a separate module, rather than as a feature request for the Generic OSC to be updated to allow for this sort of functionality?

**Comment by drjeffries** [comment]
Honestly, no. I was just focused on what that looks like.

It probably makes the most sense to extend the generic OSC module.

**Comment by dnmeid** [comment]
Your usecase "updating custom variables" from OSC is already possible using Companion's OSC API.
Even if it was not possible, it would be better to extend the existing OSC module than to request a new one.
So as this is possible, I'm closing this issue.

**Comment by drjeffries** [comment]
As reference in the built-in (I didn't see it previously) 

`/custom-variable/<name>/value <value>
Change custom variable value`
