### ISSUE TITLE
MagicSoft Recorder

### ISSUE THREAD

**Issue by borderlander19** [bitfocus/companion-module-requests#141]
Hello,

Please would it be possible to have a module to control MagicSoft recorder? 

http://magicsoft.tv/recorder.html 

Only the basic functions would be required - start/stop recording per channel, ideally as a toggle in companion with status reported back from MagicSoft.

Unfortunately their documentation appears to be sparse, however they do have web-remote functionality, so perhaps that could be used for the companion controls? There is a full-featured trial version of the software available.

Many Thanks!

**Comment by josephdadams** [comment]
@borderlander19 as a user of this software, can you reach out to them about documentation?

**Comment by josephdadams** [comment]
@borderlander19 did you reach out to them?

**Comment by borderlander19** [comment]
@josephdadams Apologies for the delay, I did and they have supplied details of their REST interface 
[REST protocol description for Recording .pdf](https://github.com/bitfocus/companion-module-requests/files/4241837/REST.protocol.description.for.Recording.pdf)

**Comment by josephdadams** [comment]
Yes. I glanced through the protocol and it is fairly simple. @McHauge you want to pick this one up?

**Comment by McHauge** [comment]
i'll give it a go

**Comment by McHauge** [comment]
@borderlander19 Hi, I think I got a simple demo/test version setup for testing.

If you click the link below you will find a compiled version of Companion V2.0 (inside .ZIP) with my demo module if you could test if all actions work, and if possibly get the response from the "PGM Status" and "Rec Status" that would be awesome and if not that's fine too. if you open companion via a terminal like CMD it should post the response in there for now.

[Download from OneDrive](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)

-McHauge/Andreas

**Comment by josephdadams** [comment]
@McHauge I set up a repo for you, push when you're ready

**Comment by borderlander19** [comment]
@McHauge Thanks for getting this moving so quickly!
I have done some (basic) testing (I only have my laptop with me currently so no licensed machine) and unfortunately it does not appear to work... 
Should it work with the loopback IP (127.0.0.1)? I will try to test with a physical network adapter tomorrow. 
I'm using the default ports, and have tested with channel 1 set to both 'free' and 'remote controlled' in MagicSoft. The built-in web remote functions as expected. 
One other thing I note is the 'record status' etc options show up under key up/down in companion, and not under 'instance feedback' so I was unable to test the feedback functions.
Thanks!
David 
![Capture](https://user-images.githubusercontent.com/57448192/75807341-1bfbbf80-5d7d-11ea-87f5-cd7769cce786.PNG)

**Comment by McHauge** [comment]
Makes sense with the no feedbacks since I haven't added anny yet, also if you're not on a licensed unit most of the commands will be disassembled on their side. Also it looks like from your foto that you will need to use the IP: 2.3.1.250 and not 127.0.0.1

**Comment by McHauge** [comment]
@borderlander19  Ups... My bad I miss read the documentation and phrased the commands as Jason parameters, and not as URI parameters. this is now fixed and from what I can test here it seems to work at least to what the non-licenced version can do.

Also updated the module and added a new test build on the same download link as before. if you could try again that would be awesome.

-McHauge

**Comment by josephdadams** [comment]
This is in the core now, closing this issue.
