### ISSUE TITLE
PTZOptics Superjoy - HTTP-CGI Commands API

### ISSUE THREAD

**Issue by Wareitar** [bitfocus/companion-module-requests#1418]
Would like to be able to control the new HTTP-CGI API on the PTZ Optics Superjoy through Companion.
Read more about the PTZ Joystick here: https://ptzoptics.com/superjoy/

Would be nice to access all of it, but I believe the following functions would be most used:

1. Direct Preset Recall (it's mainly this I am after).
2. Current Preset Recall
3. Custom Buttons

The API is attached to this post and for most of you making these additions to Companions, I believe this would be very easy to create. I have this implemented in ROSS DashBoard allready, but would be nice to have a Companion work with it as well.
Will happily test for you.

[SuperJoy HTTP-CGI Commands.pdf](https://github.com/bitfocus/companion-module-requests/files/14462440/SuperJoy.HTTP-CGI.Commands.pdf)

**Comment by jswalden** [comment]
@bryce-seifert  is already working on a module for this (or at least created/committed it on someone else's behalf).  It might not be in whatever version of Companion you're running, tho.

https://github.com/bitfocus/companion-module-ptzoptics-superjoy

**Comment by bryce-seifert** [comment]
Yes, It should be in the latest beta builds of Companion, so version 3.3.0. If you have any further needs, please post in that repository linked above
