### ISSUE TITLE
Denon DN-700R

### ISSUE THREAD

**Issue by dewiweb** [bitfocus/companion-module-requests#142]
I saw the recent implementation of  Denon DN-500BD-MKII,
I'm not a specialist but it seems to have some similarity with the serial protocol used by DN-700R model (Yes, it's an audio recorder and not a BD player but...)
[DN-700R - Serial Command Protocol Guide - v1.1.pdf](https://github.com/bitfocus/companion-module-requests/files/4032468/DN-700R.-.Serial.Command.Protocol.Guide.-.v1.1.pdf)

**Comment by josephdadams** [comment]
@McHauge?

**Comment by McHauge** [comment]
I'll give it a look

**Comment by josephdadams** [comment]
@McHauge hows this coming along?

**Comment by McHauge** [comment]
ran out of time, about half way, with normal commands

**Comment by McHauge** [comment]
@dewiweb surry ran out of time due to the size of the command list. Do you have a list of commands/options that you would like to see included? Then I will just take it from there.

-McHauge

**Comment by dewiweb** [comment]
@McHauge, 
Basic ones:
Play, Pause,Stop and initiate recording could be a good start.

**Comment by JordanResLife** [comment]
Would love to see this as a module as well! Thanks!

**Comment by istnv** [comment]
The new `denon-recorder` module supports this device.
