### ISSUE TITLE
ViewSonic P748 4k Control

### ISSUE THREAD

**Issue by grantdraper** [bitfocus/companion-module-requests#1423]
Hi would like to be able to control Viewsonic P748 4k. I have succesfully tested this with hercules and tried to use a generic tcp connection with no luck.  Controll Specifications can be found here https://manuals.viewsonic.com/IFP50-3_RS-232_Protocols. For my puroposes i would just like on and off control.

**Comment by istnv** [comment]
This projector should work with the PJLink module.
You may be required to set the admin password on the web setup page.

**Comment by grantdraper** [comment]
OOO BEAUTIFUL!!! Works like a charm!!! Should have tried that i had assumed PJlink was more specific to manfactures!

**Comment by istnv** [comment]
PJLink is a standard protocol developed by the Japan Business Machine and Information Association. Nearly all projectors produced in Japan provide support.

**Comment by grantdraper** [comment]
THE MOOOOORE YOU KNOW! Thanks everyone!
