### ISSUE TITLE
Module Request: FreeShow

### ISSUE THREAD

**Issue by vassbo** [bitfocus/companion-module-requests#1426]
FreeShow is a free and powerful open-source presenter tool, and people have requested support for Bitfocus Companion.

I have created a working module here: https://github.com/vassbo/churchapps-freeshow
(Currently it only connects to the dev version of the program (https://github.com/ChurchApps/FreeShow/tree/dev), when the setting for Companion is turned on.)

This module allows users to trigger these actions at the moment:
- Go to next/previous slide
- Go to next/previous item in the project
- Go to a specific slide by index
- Clear the output

**Comment by bryce-seifert** [comment]
@vassbo Since you have working module, next steps would be following the [Releasing your module guide](https://github.com/bitfocus/companion-module-base/wiki/Releasing-your-module). One note: you'll want to bump the version number to 1.0.0 or higher if it's ready for release!

**Comment by vassbo** [comment]
Thanks. I joined the "Bitfocus Community" Slack page, but could not find any channel with the name `#module-development`. As stated in step 4.

**Comment by bryce-seifert** [comment]
Did you join using this link? https://bitfocus.io/api/slackinvite

If so, what is your username on Slack there

**Comment by vassbo** [comment]
I found that Slack page, but could not join because you have to use a **@bitfocus.io** or **@soniccity.no** email domain.

**Comment by istnv** [comment]
Try this one:
https://join.slack.com/t/bitfocusio/shared_invite/zt-1v8877kva-XnhKMI3maDyJ2vruqrp2Dw

**Comment by vassbo** [comment]
Thanks! Will try later today.
