### ISSUE TITLE
Overview over Supported Surfaces

### ISSUE THREAD

**Issue by fluffviech** [bitfocus/companion-module-requests#1437]
Hey there,

After my Streamdeck XL died, i am looking for a new surface. while doing so, i serached for a list of all suppoerted surfaces - and found none. neither here, nor on the homepage.  there is a list of plugins for Hardware controlled by companion, but none for hardware to _CONTROL_ companion? maybe add this as a wiki-page?
thanks!

**Comment by Julusian** [comment]
The supported types is documented in the help pages of companion

**Comment by fluffviech** [comment]
hey,

thanks for the Info. digged through the documantation again, and...well...yeah. its all there! ;) *gets new glasses and a blind-cone* 
Thanks for the help! issue can be closed and/or Deleted!
