### ISSUE TITLE
Request to add program support - Holyrics (Presentation of slides and verses)

### ISSUE THREAD

**Issue by Nahon-od** [bitfocus/companion-module-requests#1442]
Good day everyone.
I recently started using Companion to remotely control our ATEM using a MIDI controller.
This works well! Thanks to the creators.

I would like to expand the control capabilities of our MIDI controller so that it can control some of the Holyrics functions. This would be very convenient for us.
But unfortunately I understand absolutely nothing about programming.

Is it possible to add a module to manage Holyrics?

At least with the simplest functions
- Next slide
- Previous slide
- Disable slide show
- Show LOGO

[API](https://github.com/holyrics/API-Server)

**Comment by JeLuF** [comment]
I'm currently working on this module, c.f. https://github.com/bitfocus/companion-module-limagiran-holyrics
 I'm in contact with the Holyrics developer at https://github.com/holyrics/API-Server/issues/3

**Comment by Nahon-od** [comment]
> I'm currently working on this module, c.f. https://github.com/bitfocus/companion-module-limagiran-holyrics I'm in contact with the Holyrics developer at [holyrics/API-Server#3](https://github.com/holyrics/API-Server/issues/3)

Good day.  
Can I get this module to try/test it?  If this is possible, how to do it?  
(sorry, I don’t understand anything at all about programming).

**Comment by JeLuF** [comment]
I've asked the Bitfocus team to add the [module](https://github.com/bitfocus/companion-module-limagiran-holyrics/releases/tag/v1.0.1) to the next release.

Once it is accepted, it will show up in the next _beta_ version.

**Comment by JeLuF** [comment]
The Holyrics module has been added to the beta version, starting with version number `3.3.0+6909-main-04c4b0c1`

@Nahon-od - If you want to test the module, you can use the beta version. You need to follow the steps documented in the help page https://github.com/bitfocus/companion-module-limagiran-holyrics/blob/v1.0.1/companion/HELP.md to enable the remote control option in holyrics and to obtain the authentication token.

I'm not an active user of Holyrics, so if there's anything missing or something that's inconvenient to use, please provide feedback and I'll see what I can do to fix it.

**Comment by Nahon-od** [comment]
Thank you very much, I will try today to check everything I need to manage Holyrics

**Comment by JeLuF** [comment]
Support for Holyrics is available in Companion v3.3.0
