### ISSUE TITLE
PPT/VIDEO - OSC 

### ISSUE THREAD

**Issue by MonteiroVideo** [bitfocus/companion-module-requests#1454]
I would like to create modules and variables for my software project.

My project is currently receiving generic osc commands, but I want to create my own buttons

**Comment by dnmeid** [comment]
Please contact the core development team at slack with the enquiry for a repo for your module.

**Comment by MonteiroVideo** [comment]
Where can I make this request? Do you have the email or how to request this?

Em sex., 5 de abr. de 2024, 12:29, Dorian Meid ***@***.***>
escreveu:
