### ISSUE TITLE
QUERO CRIAR MODULO DO MEU SOFTWARE

### ISSUE THREAD

**Issue by MonteiroVideo** [bitfocus/companion-module-requests#1455]
I HAVE SOFTWARE THAT RECEIVES THE COMMAND FROM THE OSC GENERIC, BUT I WANT TO CREATE A MODULE WHERE I ALREADY HAVE THE PRESET OF MY COMMANDS. I WOULD LIKE HELP

**Comment by JeLuF** [comment]
You can find a developer guide at https://github.com/bitfocus/companion-module-base/wiki

**Comment by MonteiroVideo** [comment]
I used this link and made a project based on another, but I couldn't add it to the companion

https://github.com/MonteiroVideo/ppt-video-osc.git

esse é meu git

**Comment by JeLuF** [comment]
Your copy of the existing module is incomplete. You need to have a `companion/manifest.json` file in your module.
https://github.com/bitfocus/companion-module-base/wiki/manifest.json

**Comment by MonteiroVideo** [comment]
https://github.com/MonteiroVideo/ppt-video-osc.git

This is my test code. But I still have to know how to create the button
ready for preset

Em ter., 9 de abr. de 2024, 04:10, JeLuF ***@***.***>
escreveu:

**Comment by JeLuF** [comment]
How to define presets is documented in the wiki as well. https://github.com/bitfocus/companion-module-base/wiki/Presets

**Comment by MonteiroVideo** [comment]
The problem is that I can't place my project within the companion. So I
wanted to start testing the command

Em ter., 9 de abr. de 2024, 07:57, JeLuF ***@***.***>
escreveu:

**Comment by dnmeid** [comment]
This repo is for module-requests, not for general discussion. If you like you can continue your discussion in this topic, but I'm closing the issue as there is no request.
Best place to get help with module development is the slack group, you find the link in the sidebar of Companion.

**Comment by JeLuF** [comment]
> The problem is that I can't place my project within the companion. So I wanted to start testing the command

If the github repo is the latest version, then it's still missing the `manifest.json` file. Every module must have this file.

**Comment by MonteiroVideo** [comment]
The problem is that I don't have access to slack, so it's difficult to try
to help there without permission

Em ter., 9 de abr. de 2024 às 16:41, Dorian Meid ***@***.***>
escreveu:

**Comment by MonteiroVideo** [comment]
I tried to access Slack, but I can't access it because you didn't allow me

***@***.***

Em ter., 9 de abr. de 2024 às 16:41, Dorian Meid ***@***.***>
escreveu:
