### ISSUE TITLE
ppt-video-osc

### ISSUE THREAD

**Issue by MonteiroVideo** [bitfocus/companion-module-requests#1458]
I'm trying to insert the application into the companion, but I can't.

I'm trying to join slack and I can't either.

my app git

https://github.com/MonteiroVideo/ppt-video-osc

I need help implementing the preset buttons within the companion.

my email monteiro.audiovisual@gmail.com

**Comment by JeLuF** [comment]
Why can't you join slack? What did you try, what happened?

**Comment by MonteiroVideo** [comment]
I enter my email ***@***.***, it gives me an error to
enter the bitfocus as community, but I already have a registration within
slack. But I just can't join your community

Em sex., 12 de abr. de 2024, 13:33, JeLuF ***@***.***>
escreveu:

**Comment by JeLuF** [comment]
The field to enter an email is only for people having a `@bitfocus.io` email address.

If you already have a slack account, use the "sign in instead" button.
![image](https://github.com/bitfocus/companion-module-requests/assets/5852422/f6a3f398-2534-44ba-aaf9-570fb0236a41)

Or use the 'Continue with Google' button to log in using your gmail account.

**Comment by MonteiroVideo** [comment]
When I do this procedure using your link, I get an error, using the login
method, I can log into my account. but I can't see your community

Em sex., 12 de abr. de 2024, 14:52, JeLuF ***@***.***>
escreveu:

**Comment by MonteiroVideo** [comment]
[image: image.png]

 this is the error

Em sex., 12 de abr. de 2024 às 14:52, JeLuF ***@***.***>
escreveu:

**Comment by JeLuF** [comment]
There is no image in your message.

**Comment by MonteiroVideo** [comment]
I have a standard Slack account, but I can't access it with your link.
When I access the link via companion, I cannot access slack. This error
appears immediately in the attached image.
I even managed to find my program on the system, but it doesn't find
@module_base. And I wish I could.
I would like help creating the preset buttons for those who use it, having
already made them, instead of me using the adaptation that I have to make
for it to work.


Em ter., 16 de abr. de 2024, 08:24, JeLuF ***@***.***>
escreveu:

**Comment by JeLuF** [comment]
There still isn't any attached image. If you can't send images via mail, you can paste them directly on github.com instead.

**Comment by JeLuF** [comment]
> it doesn't find @module_base

Did you run yarn in the module's directory?

**Comment by MonteiroVideo** [comment]
I was unable to do this Yarn system as stated in the text. It made an error.

Em ter., 16 de abr. de 2024, 09:59, JeLuF ***@***.***>
escreveu:

**Comment by JeLuF** [comment]
If it made an error, you didn't do it properly. To tell you why it made an error, you'd need to share exactly what you did and the error message that you got. Without an error message, it's hard to tell what you did wrong.

**Comment by MonteiroVideo** [comment]
this is the error

Em ter., 16 de abr. de 2024 às 11:22, JeLuF ***@***.***>
escreveu:

**Comment by JeLuF** [comment]
I guess you tried again to attach an image. Which didn't work. Again. If you can't send images via mail, you can paste them directly on github.com instead. Use the "view in github" link at the end of the mail to go to the github page.

**Comment by MonteiroVideo** [comment]
![Screenshot_1](https://github.com/bitfocus/companion-module-requests/assets/166059439/1c5c3852-b4b4-43ae-a9ed-f424ff8adf3c)

**Comment by MonteiroVideo** [comment]
I didn't understand how to put yarn inside the folder.
but I opened powershell and put yarn and it gave this error in the photo

**Comment by thedist** [comment]
That would indicate you don't even have yarn installed then. Have you read the basic guide on how to develop Companion modules? https://github.com/bitfocus/companion-module-base/wiki

**Comment by MonteiroVideo** [comment]
The problem I tried to solve using fnm and it didn't work, so I tried to do something through github.
but apparently I need to fix this fnm, but on my pc it is giving an error reading about fnm

**Comment by JeLuF** [comment]
I don't use PS, but `cmd`, and there I use:
```
set PATH=c:\Program Files\Companion\resources\node-runtime\node_modules\corepack\shims;c:\Program Files\Companion\resources\node-runtime;%PATH%

yarn.cmd
```
Where `c:\program files\companion\` needs to be changed if you have installed Companion to a different directory.

This uses the node installation that is part of Companion, so it doesn't need `fnm`

**Comment by MonteiroVideo** [comment]
> Eu não uso PS, mas `cmd`, e aí eu uso:
> 
> ```
> set PATH=c:\Program Files\Companion\resources\node-runtime\node_modules\corepack\shims;c:\Program Files\Companion\resources\node-runtime;%PATH%
> 
> yarn.cmd
> ```
> 
> Onde `c:\program files\companion\`precisa ser alterado se você instalou o Companion em um diretório diferente.
> 
> Isso usa a instalação do nó que faz parte do Companion, portanto não precisa`fnm`

I did the process you mentioned. Can I just get the yarn file that is in the companion folder and paste it into my project?

**Comment by MonteiroVideo** [comment]
> Eu não uso PS, mas `cmd`, e aí eu uso:
> 
> ```
> set PATH=c:\Program Files\Companion\resources\node-runtime\node_modules\corepack\shims;c:\Program Files\Companion\resources\node-runtime;%PATH%
> 
> yarn.cmd
> ```
> 
> Onde `c:\program files\companion\`precisa ser alterado se você instalou o Companion em um diretório diferente.
> 
> Isso usa a instalação do nó que faz parte do Companion, portanto não precisa`fnm`



I did the process you mentioned. Can I just get the yarn file that is in the companion folder and paste it into my project?

**Comment by MonteiroVideo** [comment]
Thanks for your help guys, I was able to read my file.
in my project I used communication via osc-generic
However, I would like to know how to create a preset button, using a command that is in the generic project

send_int: {
name: 'Send integer',
options: [
{
type: 'textinput',
label: 'OSC Path',
id: 'path',
default: '/osc/path',
useVariables: true,
},
{
type: 'textinput',
label: 'Value',
id: 'int',
default: 1,
regex: Regex.SIGNED_NUMBER,
useVariables: true,
},
],
callback: async (event) => {
const path = await this.parseVariablesInString(event.options.path)
const int = await this.parseVariablesInString(event.options.int)

sendOscMessage(path, [
{
type: 'i',
value: parseInt(int),
},
])
},
},

How could I get this command to become a preset button?

**Comment by thedist** [comment]
Creating a preset is documented in the wiki https://github.com/bitfocus/companion-module-base/wiki/Presets

**Comment by JeLuF** [comment]
> I did the process you mentioned. Can I just get the yarn file that is in the companion folder and paste it into my project?

I think this wouldn't work. The yarn file has a bunch of dependencies to other files in the companion folders. The copied version of `yarn.cmd` would probably not find these dependencies any more.

**Comment by MonteiroVideo** [comment]
> > I did the process you mentioned. Can I just get the yarn file that is in the companion folder and paste it into my project?
> 
> I think this wouldn't work. The yarn file has a bunch of dependencies to other files in the companion folders. The copied version of `yarn.cmd` would probably not find these dependencies any more.



master, I managed to create the project within the companion, but I didn't understand how I would generate a preset button, starting from a command like this:

send_int: {
name: 'Send integer',
options: [
{
type: 'textinput',
label: 'OSC Path',
id: 'path',
default: '/osc/path',
useVariables: true,
},
{
type: 'textinput',
label: 'Value',
id: 'int',
default: 1,
regex: Regex.SIGNED_NUMBER,
useVariables: true,
},
],
callback: async (event) => {
const path = await this.parseVariablesInString(event.options.path)
const int = await this.parseVariablesInString(event.options.int)

sendOscMessage(path, [
{
type: 'i',
value: parseInt(int),
},
])
},
},

I would like to understand how to create this preset button using this method. because I would leave the buttons ready for anyone who wanted to use them. but when reading the document about preset, I didn't understand how I would call this function within the la command

**Comment by JeLuF** [comment]
Did you read the article that [thedist mentioned](https://github.com/bitfocus/companion-module-requests/issues/1458#issuecomment-2059854977) and that [I mentioned last week](https://github.com/bitfocus/companion-module-requests/issues/1455#issuecomment-2044712191)?

**Comment by MonteiroVideo** [comment]
I read the document, but I couldn't understand this document. I tried to read the finished project, but I also couldn't understand it because each code is different and my language is C#. That's why I have these doubts

**Comment by JeLuF** [comment]
Can you commit that command to your repo? I'd then make a PR with a preset.

**Comment by MonteiroVideo** [comment]
send_int: {
				name: 'Send integer',
				options: [
					{
						type: 'textinput',
						label: 'OSC Path',
						id: 'path',
						default: '/osc/path',
						useVariables: true,
					},
					{
						type: 'textinput',
						label: 'Value',
						id: 'int',
						default: 1,
						regex: Regex.SIGNED_NUMBER,
						useVariables: true,
					},
				],
				callback: async (event) => {
					const path = await this.parseVariablesInString(event.options.path)
					const int = await this.parseVariablesInString(event.options.int)

					sendOscMessage(path, [
						{
							type: 'i',
							value: parseInt(int),
						},
					])
				},
			},
			
			
This is the command that I need to implement as a preset for a button, and from there I will know how to create the rest.

**Comment by JeLuF** [comment]
> This is the command that I need to implement as a preset for a button, and from there I will know how to create the rest.

Yes, you said that already. Can you make the current version of the module available in your github repo? Then I can implement the preset based on your code and create a pull request.

**Comment by MonteiroVideo** [comment]
This is the base companion project inside my git.

https://github.com/MonteiroVideo/ppt-video-osc.git

**Comment by JeLuF** [comment]
Yes. But it is not up to date. It doesn't have `send_int`. Please make a working version that has a working `send_int` action, push it to github, and then I can take your code and add a preset.

**Comment by MonteiroVideo** [comment]
It's updated now, I left two functions. to differentiate.

Starting from them, I would like to have the buttons created in the preset.

**Comment by MonteiroVideo** [comment]
I tried to make various types of changes to my code, but I couldn't access it. I get an error right away when I try to play the preset.

**Comment by JeLuF** [comment]
Have a look at https://github.com/MonteiroVideo/ppt-video-osc/pull/1 for an example how to define a preset.

**Comment by MonteiroVideo** [comment]
> Have a look at [MonteiroVideo/ppt-video-osc#1](https://github.com/MonteiroVideo/ppt-video-osc/pull/1) for an example how to define a preset.

It worked, master... Thank you very much for your help. When I finished making my buttons. Do I need to do something so that other people can see inside the companion?

But your code worked beautifully. Thank you very much

**Comment by MonteiroVideo** [comment]
@JeLuF 
Could you look at my two codes in git and tell me what I need to improve so that the companion accepts it?

I have 2 free softwares that receive the communication from these two projects.

https://github.com/MonteiroVideo/companion-module-monteiro-pptvideoosc.git

https://github.com/MonteiroVideo/cronosDown.git

and here is the link to download the softwares

https://monteiroaudiovisua.wixsite.com/ppt-video

**Comment by JeLuF** [comment]
That won't help you much, since I'm not one of the people deciding whether your modules get added or not.
