### ISSUE TITLE
release my code

### ISSUE THREAD

**Issue by MonteiroVideo** [bitfocus/companion-module-requests#1468]
I would like to generate my code within the companion.
Follow my git so you can see the code and release it within the companion

https://github.com/MonteiroVideo/ppt-video-osc.git

**Comment by thedist** [comment]
I recommend reading the Module Development guide, [https://github.com/bitfocus/companion-module-base/wiki/Module-development-101](https://github.com/bitfocus/companion-module-base/wiki/Module-development-101), as this is not the appropriate place to request repos be created or for developers to request their modules be added to Companion, for that you will need to use the Bitfocus Slack server.

Additionally, it appears your module has lots of example things that should not be present in a module for public usage, so you may want to go through the wiki and work through making your module suitable for inclusion in Companion.
