### ISSUE TITLE
Barco PDS 902 3G-SDI

### ISSUE THREAD

**Issue by wasserfall7** [bitfocus/companion-module-requests#147]
Hi, please ad the Barco PDS 902 3G-SDI to Instances.
the difference to the existing PDS Instances are: 4 DVI Inputs instead of 2 , 1 SDI Input
because DVI and SDI is much better than the VGA Inputs the "upgrade" would be very useful
Thank you very much

simon

**Comment by EventReplay** [comment]
This has been noted as a bug and has been resolved in v2.
https://github.com/bitfocus/companion-module-pds/issues/9

**Comment by MarcHagen** [comment]
Hi there!
The fix has been pushed to the 2.0 release.

**Comment by josephdadams** [comment]
Closed because it’s fixed in 2.0.
