### ISSUE TITLE
Riedel RRCS

### ISSUE THREAD

**Issue by Tonts95** [bitfocus/companion-module-requests#1481]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control: Riedel RRCS

What you would like to be able to make it do from Companion: RRCS is a module that allows external devices to control a Riedel Artist intercoms Matrix. The RRCS's documentation gives all the function that can be controlled externally.

Direct links or attachments to the ethernet control protocol or API: the documentation of RRCS can be found there : 
[RRCS Interface Specification_8_5_1_Rev1.pdf](https://github.com/bitfocus/companion-module-requests/files/15249513/RRCS.Interface.Specification_8_5_1_Rev1.pdf)

**Comment by dnmeid** [comment]
Can you please give a direct link to the documentation or attach it.

**Comment by Tonts95** [comment]
Yes of course, sorry about that. It is now attached in the post.

**Comment by phillipivan** [comment]
I am working on this. What functionality were you after?

**Comment by Tonts95** [comment]
Hi Phillip,

Thank you!

The first function I would need on my side is the "Set output function" (page 33, 8.5, "Set the output gain for the given port" si I can control the Artist with the rotaries of a Stream Deck +. Having the feed back on the screen of the output level would be nice as well. And than the remote key function (page 122, 8.10.4.18).

Let me know if you need anything.

**Comment by phillipivan** [comment]
The documentation for the remote key function reads like it's only for creating or deleting remote keys functions, not activating them. Is this indeed what you are after?

I expect some of the more complex config change methods to come later on, probably on a bit of an as-needs-be basis. Since there are so many of them.

I hope to have input and output gain control going this week.

I probably don't need to much, but it would be great if you can help test.

**Comment by phillipivan** [comment]
I'm going to submit a version for inclusion in the beta builds soon. You can see the functionality that will be available here:

https://github.com/phillipivan/companion-module-riedel-rrcs/blob/main/companion/HELP.md

**Comment by Tonts95** [comment]
That's amazing, thank you!

No indeed, the remote key function is not what I had in mind. It's more the "Key - Press" function that I had in mind.

Unfortunately, I'm currently away from the OB Van in which I work. I won't have a chance to help before October I think. I'm really sorry.

Are your tests conclusive?

Thank you again for your work and your time in this project, I hope that it will benefit a lot of intercoms guys.

**Comment by phillipivan** [comment]
Hey,


So far I have all the actions and feedbacks in the help.md working. So setting cross points, pressing keys etc seem ok, and the relevant ports can either be selected by long name from a drop down or specified by address with variables.

I may add one or two more actions (IFB Volume), but that’s basically the scope of the 1.0 release.

What probably does need some more attention is the handling of connection failures and reconnections.

Phillip.

**Comment by phillipivan** [comment]
This is in betas now.

**Comment by phillipivan** [comment]
Hey @Tonts95 when you get to using this please create an issue in the module repo for any bugs/feature requests/feedback you have.

**Comment by Tonts95** [comment]
Hi @phillipivan,

I FINALLY had the chance to come back to the OB Van where the module was necesary. So I'm just discovering it, and it's pretty cool and usefull. Thank you very much for your time and work. I have a question though, so I will ask it on module repo.

Thanks.
