### ISSUE TITLE
JVC KY-PZ100 cameras

### ISSUE THREAD

**Issue by ryanjohnclark** [bitfocus/companion-module-requests#149]
Hi there. Could control for JVC KY-PZ100 cameras or the JVC RM-LP100 camera controller be added to the Companion?  Even simple program switching would be huge.  Pan and zoom would be a plus.  Thanks for considering!

Link to JVC API reference:
http://pro.jvc.com/pro/attributes/ip/manual/JvcCamcorderApiReferenceV111_public.pdf?fbclid=IwAR370LAVBjJsB642cAXbi9a0Vdy66dbzrbBRtEet0XZT0FD-0RukT8i8RMI

**Comment by ryanjohnclark** [comment]
I think the settings are in section 3.4 of the API reference.  Ideally, I would like to be able to:
Set the pan speed
Set the zoom speed
Pan Up, Up&Rt, Rt, Rt&Dn, Dn, Dn&Lt, Lt, Lt&Up
Zoom in, Zoom out
set the Iris
set the Gain
Recall Presets
[JvcCamcorderApiReferenceV107_public.pdf](https://github.com/bitfocus/companion-module-requests/files/4101458/JvcCamcorderApiReferenceV107_public.pdf)

**Comment by ryanjohnclark** [comment]
I have the cameras and could answer questions and test if someone was interested in taking this on. I'm sure some compensation could be worked out for the time/skill but I have no idea what something like this would run. I would love to get a quote to see if it's something our outfit could accommodate. I suppose it would also depend on how well it functioned.

**Comment by ryanjohnclark** [comment]
This said I closed it but I didn't do it knowingly.

**Comment by ryanjohnclark** [comment]
Hi guys. Just following up to see if anyone might be interested in taking this on.

**Comment by JeffreyDavidsz** [comment]
How badly do you need it? You could set a bounty on it to speed things up?

**Comment by JeffreyDavidsz** [comment]
Just read your upper request, I would say it takes 1,5 hours without testing to create the module with the desired actions in it. Looking at the API this should not be hard. Send me an email on jeffrey.davidsz@vicreo.eu if you want me to create it today/tomorrow

**Comment by ryanjohnclark** [comment]
I've heard the mention of Bounty a couple times but when I go look at the
existing module requests I couldn't find any examples to reference. I'm not
familiar with how the open source community works so I wasn't sure what to
offer.  It's for our church and will help us with a shortage of volunteer
servers if I can assign values that will move the cameras to predetermined
positions (not just "zoom in/out" or "pan left/right", but also "zoom to
here" and "pan to here") so  if I can afford to do it I'm happy to pay for
it.

**Comment by ryanjohnclark** [comment]
Should we dialog on Slack or is this preferred?

**Comment by JeffreyDavidsz** [comment]
Slack is fine! Send me a PM

Met vriendelijke groet,

Jeffrey Davidsz

Verzonden met Outlook voor mobiel

________________________________

**Comment by josephdadams** [comment]
@JeffreyDavidsz is this module done?

**Comment by JeffreyDavidsz** [comment]
Yes it's in the builds!

**Comment by kimaernoudt** [comment]
any updates ?

**Comment by josephdadams** [comment]
What type of update are you lookin for, @kimaernoudt ?
