### ISSUE TITLE
Kramer VS-311H HDMI Switcher 

### ISSUE THREAD

**Issue by dmxking512** [bitfocus/companion-module-requests#150]
**Describe the feature**
Support for Kramer VS-311H HDMI Switcher

**Is this platform dependent (windows, mac, ..)?**
Yes this appears to be PC spesific and doesnt work on a mac ( would be helpful if it did though) 

**If documentation is required to implement, do you know where to find it?**
Uses the same Protocol-2000 as other Kramer matrix switchers. i belive the commands issued vary from devices. I have access to the windows based diagnostics tool which generates the bytes sent to the unit. happy to provide this

**Usecases**
Production Switching.
<img width="815" alt="Screenshot 2020-01-20 at 22 00 04" src="https://user-images.githubusercontent.com/14097214/72760311-3b28fe00-3bd0-11ea-9e78-017d39e231d0.png">

**Comment by dmxking512** [comment]
So further digging reveals that this only seems to work on PC and not on MAC. 

Ive run a capture using the Kramer Protocol-2000 tool and this is the capture in wireshark, showing a packet of 4 bytes 01818181 from my understadning:

Byte1 : 01 sends the type of action in this case Switch Video
Byte2 : 81 input number one, 82 input 2 83 input 3 
Byte3 : 81 output 1 switcher only has 1 output
Byte4 : 81 Machine number so if you have more than one switcher 

![Kramer tool](https://user-images.githubusercontent.com/14097214/72929590-0ba1ff00-3d52-11ea-85ac-b4ca0f4835e5.JPG)


the Kramer Matrix module in companion sends a packet of 5 bytes with a different value:

018181810a

![Companion Matrix](https://user-images.githubusercontent.com/14097214/72929617-18265780-3d52-11ea-98b5-3803610ad701.JPG)

**Comment by EventReplay** [comment]
0a is a Line Feed.
Can you ping the units IP Address? Should be able from both PC & Mac. If not then Check firewall & K-LAN Configuator settings, maybe reset to default settings for testing.
Doc's & Software (This is filed as a discontinued model)
https://k.kramerav.com/support/product_downloads.asp?pt=5&pid=569
when you can ping the unit try testing commands with telnet, if they work then I think companion should work.

Hope that's helpful.

**Comment by dmxking512** [comment]
I am able to ping from both mac and PC. 

Do i telnet to the port 5000 ? how do i then send the commands via telnet , do i just type 01 81 81 81 ect ? 


Appreciate your help :)

**Comment by dmxking512** [comment]
I am able to connect via putty on port 5000 but anything i type doesnt change the switcher. 
Wireshark shows a different type of communication when using telnet so i dont think this is right.

**Comment by EventReplay** [comment]
If your using putty your not sending Hex.
https://www.hw-group.com/software/hercules-setup-utility (TCP Client Tab)
or
https://packetsender.com/

**Comment by dmxking512** [comment]
Okay so i've had a play with packet sender and the following works:
![image](https://user-images.githubusercontent.com/14097214/73071353-6babb900-3eaa-11ea-9ca0-f9d30462cdc6.png)

But once again the plugin in companion doesnt. it seems to be sending a different packet as shown in my wireshark captures above

**Comment by dmxking512** [comment]
i can also see through wireshark that its constantly sending a single 00 byte as a keep alive.... wondering if this isnt helping?

**Comment by dmxking512** [comment]
Everything else is correct its just that extra bite 0a that the Companion module is sending.....

**Comment by EventReplay** [comment]
I've had a look through code and I think I can see a possible issue in this line of code:
0x0a  // End with a \r to separate multiple commands
\r carriage return is 0x0d \n line feed is 0x0a.
You may require \r\n
I'll Post an issue here:
https://github.com/bitfocus/companion-module-kramer-matrix/tree/master

**Comment by dmxking512** [comment]
Much appreciated! :D

**Comment by dmxking512** [comment]
My only concern though is by actually terminating it adds an extra byte. making it 5 bytes 

i tried appending the hex sent in packet sender and the swithcer doesnt like it. 

the Protocol-2000 calculator tool from Kramer only lets you sepcify the 4 bytes.

it may be less of a case of it being \r or \n and just a case of it simply shouldn't be there. 

I've also double checked that the switcher is running the most recent firmware.

**Comment by EventReplay** [comment]
I have a VS-42HDMI Matrix it uses P2000 and works fine with the module.
Using Packetsender I can send 01 82 81 81 or 01 82 81 81 0A or 01 82 81 81 0D, they all work fine executing the same command.
Dosn't make sense it's not working if it's sending the right command.

**Comment by EventReplay** [comment]
This model is now working with the Kramer Matrix Module in the current v2.0 build .

**Comment by EventReplay** [comment]
@dmxking512 Could this be closed?

**Comment by dmxking512** [comment]
Yes . All solved on this one too
