### ISSUE TITLE
DiGiCo

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-requests#151]
via OCS, fetching API at the moment

**Comment by josephdadams** [comment]
Is this one done or still in progress?

**Comment by JeffreyDavidsz** [comment]
In progress, waiting for connection confirmation

**Comment by Fader-Monkey** [comment]
Any testing needed on this still? I’ve got an sd9 and 2 sd10s if it needs to be tested with hardware.

**Comment by JeffreyDavidsz** [comment]
Actually not, module is ready and works. Thanks for the reminder
