### ISSUE TITLE
Social Stream - Multi Channel Chat Message Overlay Management

### ISSUE THREAD

**Issue by chrisspiegl** [bitfocus/companion-module-requests#1510]
**The name of the device, hardware, or software you would like to control:**

Social Stream by @steveseguin
https://socialstream.ninja
https://github.com/steveseguin/social_stream

**What you would like to be able to make it do from Companion:**

- Bring up the next message in queue
- Clear the Current Featured Message
- Enable / Disable TTS
- Enable / Disable Auto Feature Chat Messages
- etc.

**Direct links or attachments to the control protocol or API:**

Based on this page, there is an HTTP and Web Socket API:

https://socialstream.ninja

**Comment by rjmunro** [comment]
Is there any progress on this?

I'd like to do the opposite - add some companion buttons to the bottom of the Social Stream Ninja dashboard, so that you can control anything from a mobile while presenting a live stream.

**Comment by steveseguin** [comment]
For general reference, I have some documentation and sandbox tools for testing the Social Stream Ninja API linked below:

https://socialstream.ninja/sampleapi.html (sandbox)
https://socialstream.ninja/api (documentation)
https://socialstream.ninja/landing#hotkey-midi--streamlabs-support (some additional API options and details, like MIDI control, here)

It's all on Github and I am on Discord if you need support with any development efforts on this front.

> Is there any progress on this?
> 
> I'd like to do the opposite - add some companion buttons to the bottom of the Social Stream Ninja dashboard, so that you can control anything from a mobile while presenting a live stream.

Social Stream Ninja can control some basic OBS options currently, like [start/start/record](https://socialstream.ninja/landing#obs-remote-scene-support) and change scene, but not much else.  I'd be happy to support any initiative to add Companion control to SocialStream.Ninja in some way. The existing API (io.socialstream.ninja) should be two-way messaging compatible when connected via websockets.

**Comment by bryce-seifert** [comment]
@rjmunro There is a [module for Social Stream](https://github.com/bitfocus/companion-module-socialstream-ninja) available in Companion v3.4. I think it has everything listed in this original request except TTS.

I've been meaning to expand the module with the new additions made to the API, but have not gotten to that quite yet. But if you have a specific request related to the Companion module, you can add that as an [issue](https://github.com/bitfocus/companion-module-socialstream-ninja/issues).

Regarding the companion buttons to the bottom of the Social Stream Ninja dashboard, that's not exactly related to the module itself, but is an interesting idea. But not something I myself will likely be able to tackle soon.

**Comment by chrisspiegl** [comment]
I like the addition of the buttons natively with the module.

The one thing I find 'missing' right now would be the “feedback” to see if a message is currently on stream (so that the “clear” button can have a variable background).

Should I open a new issue for that?

**Comment by bryce-seifert** [comment]
@chrisspiegl Yes please, if you can open it in the social stream module  repository that would help me keep track and get to it!
