### ISSUE TITLE
CRONOSDOWN

### ISSUE THREAD

**Issue by MonteiroVideo** [bitfocus/companion-module-requests#1516]
https://github.com/MonteiroVideo/cronosDown.git

CODE IS READY FOR ANALYSIS AND INCLUDED WITHIN THE COMPANION

**Comment by thedist** [comment]
As I had already explained to you on Slack, we do not include modules in repos outside of the Bitfocus org into official Companion builds. If you'd like for your module to be included you'd need to ask for a repo to be created for you that you can push to.

Additionally your module has a significant number of issues, some of which I have already pointed out on Slack.
