### ISSUE TITLE
Canon Eos 5 D Mark II

### ISSUE THREAD

**Issue by Elubotsira** [bitfocus/companion-module-requests#1528]
Hello,
For me, and i expect for other, it would be nice if i can command my caméra EOS 5 D Mark II.
If it's possible to remote the record, the focus, the zoom it would be super...
(Excuse my poor english)
Thanks

**Comment by bryce-seifert** [comment]
This camera does not have network connectivity that allows for control, so this will not be possible.

**Comment by Elubotsira** [comment]
Ok, Thanks a lot !

**Comment by Elubotsira** [comment]
Hello again,
If it's possible i suggest a fonction in Companion wich could allow to
change dashboard in Millumin with the streamdeck.
Thank you again

**Comment by bryce-seifert** [comment]
There is a Millumin module in Companion, you can learn about getting started at the following link

https://help.millumin.com/docs/tutorials/control-your-show-remotely/#touchosc

If you have a specific request for that module, you can post it in this repository below

https://github.com/bitfocus/companion-module-anomes-millumin

**Comment by Elubotsira** [comment]
Ok, thanks
