### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by FWSpelunker** [bitfocus/companion-module-requests#1537]
I want to be able to use an Arduino UNO R3 with an Ethernet shield and a Relay shield to control the up and down function of a Da-Lite roll-up screen via IP address.  What I want to do it press a button that changes projector input, trigger a video and start the screen down (via relay on the Arduino). I can supply you with the Arduino Sketch if you need it. It appears to not be a supported file type for attaching it here.

**Comment by dnmeid** [comment]
Ardunio is a highly programmable device. In your sketch you can use practically any existing ethernet protocol or invent your own protocol. Companion supports already a lot of the most common protocols as well as generic protocols. It would not really be economical to write a dedicated Companion module to supply convenient actions for your 2-3 commands you have to send to your Arduino, as they would only be working with exact that sketch.
Please look in the generic connections, e.g. `Generic: TCP and UDP Requests`. I assume you will easily find how to send the needed commands to the Arduino.

**Comment by FWSpelunker** [comment]
Thank you for the quick reply. As I am new to companion, I did not really know where to look for a generic connection. Although I did think there was probably something in there that could do that. This will at least get me started! Thank you.On Jun 28, 2024, at 8:10 PM, Dorian Meid ***@***.***> wrote:﻿
Ardunio is a highly programmable device. In your sketch you can use practically any existing ethernet protocol or invent your own protocol. Companion supports already a lot of the most common protocols as well as generic protocols. It would not really be economical to write a dedicated Companion module to supply convenient actions for your 2-3 commands you have to send to your Arduino, as they would only be working with exact that sketch.
Please look in the generic connections, e.g. Generic: TCP and UDP Requests. I assume you will easily find how to send the needed commands to the Arduino.
