### ISSUE TITLE
X-Keys XK-80 

### ISSUE THREAD

**Issue by DenBeerVanHoboken** [bitfocus/companion-module-requests#1544]
I would like to use my X-KeysXK-80 via companion to call up a website under a button or send other text lines, I cannot find a device in the list of devices (I did find a message that this button box is compatible ).

**Comment by Phil0** [comment]
In the Companion UI go to Settings > Surfaces > Enable connected X-keys
(Requires Companion restart)

Then you should be able to use X-Keys to control Companion.

**Comment by dnmeid** [comment]
it is already possible
