### ISSUE TITLE
RTP-Midi

### ISSUE THREAD

**Issue by samuraitheta** [bitfocus/companion-module-requests#155]
I would love a way to send note messages via RTP-midi. It would open up control over Ableton Live, Arkaos Media Master, and any other software that is midi controllable. 

Thanks!

**Comment by josephdadams** [comment]
If you want to use Companion to control MIDI devices like Ableton and Arkaos, look into the techministry-midirelay module in Companion. It works with a listener program that runs on your Ableton computer (for example) and can send MIDI voice and sysex messages to the listener which then relays it out via the specified MIDI port.

If you want to use programs like Ableton and Arkaos to control Companion, there are a few different ways to do this, basically just use a middleman program to hear the MIDI message and convert it to OSC, HTTP, etc.

Have you tried either of those approaches?

**Comment by samuraitheta** [comment]
Thank you Joseph. I will check it out!

**Comment by josephdadams** [comment]
@samuraitheta did you check out any of those options?

**Comment by josephdadams** [comment]
Duplicates #81
