### ISSUE TITLE
TR RACK YAMAHA

### ISSUE THREAD

**Issue by jeremy70250** [bitfocus/companion-module-requests#1558]
Bonjour,

Serait il possible d'avoir les fonctionnalités avec compagnon pour la table de mixage TF RACK de chez Yamaha?

Cordialement.

**Comment by dszoka** [comment]
Try the Yamaha RCP module 

<img width="551" alt="Screen Shot 2024-07-23 at 9 01 04 pm" src="https://github.com/user-attachments/assets/41de1cf4-adcb-4bf3-9fad-5fda133f174f">

**Comment by MeestorX** [comment]
@josephdadams You can probably close this issue.
