### ISSUE TITLE
Support for ZCAM Camera API via HTTP requests

### ISSUE THREAD

**Issue by luthere** [bitfocus/companion-module-requests#1559]
Have a ZCAM E2 and would like to help in some capcity to support its http GET requests. I currently have some buttons running with the Generic HTTP module to control record and playback states but would like a more polished module. 

I would be happy to help and assist in testing if approved.

Link below is to the list get requests supported by ZCAM.
https://github.com/imaginevision/Z-Camera-Doc/blob/master/E2/protocol/http.md

Link is to the Camera.
https://www.z-cam.com/e2/

EDIT: It looks like someone attempted this (#195) but never made it to the main repo...

**Comment by josephdadams** [comment]
So I’m gonna close this because it’s a duplicate, but go comment on that issue and see if anyone pipes in…
