### ISSUE TITLE
Baserow

### ISSUE THREAD

**Issue by xi-pen** [bitfocus/companion-module-requests#1561]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

_The name of the device, hardware, or software you would like to control:_
baserow - https://baserow.io/

_What you would like to be able to make it do from Companion:_
Use baserow, especially the self hosted version, as an alternative to google sheet

_Direct links or attachments to the ethernet control protocol or API:_
https://api.baserow.io/api/redoc/
https://baserow.io/api-docs
https://baserow.io/docs/apis/web-socket-api

**Comment by JeLuF** [comment]
companion-module-baserow-baserow has been added to the latest beta:

https://github.com/bitfocus/companion-bundled-modules/commit/8671ecfe98d960cd1f2eba9fc87d6c320482e98c

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion-module-baserow-baserow
