### ISSUE TITLE
LS Core LightShark

### ISSUE THREAD

**Issue by guitarmac1** [bitfocus/companion-module-requests#1571]
I am not sure how this can be submitted or implemented into Companion but I do have a module that no does have dynamic feedback. This was only given to me to test via a developer module path file. It works great. Can this file now be include in the next Companion release? 
[pkg(1).tgz](https://github.com/user-attachments/files/16465600/pkg.1.tgz)

**Comment by dnmeid** [comment]
There is an existing module for the Lightshark.
I don't know about the differences between the console and the LS core but I bet they are minimal. If you want some functionality to be added to the Lightshark module, please ask there.
Additionally it seems you are not the author of the module you did attach. We won't add some code not donated to the project by the author.
