### ISSUE TITLE
AVMATRIX PVS0403u

### ISSUE THREAD

**Issue by oleamundsen** [bitfocus/companion-module-requests#1572]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:

What you would like to be able to make it do from Companion:

Direct links or attachments to the ethernet control protocol or API:

**Comment by oleamundsen** [comment]
AVMATRIX PVS0403u

**Comment by dnmeid** [comment]
duplicate of #1478 #936 #1401 #1456
