### ISSUE TITLE
Shure - Microflex Wireless

### ISSUE THREAD

**Issue by Oldman-Winter** [bitfocus/companion-module-requests#1580]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**
There is a module for Shure Microflex Complete Wireless which connects but only 1 command works. The rest return errors.
This makes sense as Shure has two systems with similar names that are actually different things.

The name of the device, hardware, or software you would like to control:
Shure Microflex Wireless (not to be confused with Microflex Complete Wireless)

What you would like to be able to make it do from Companion:
The ability to mute and unmute mics
Control the status light of mics.
Get the battery charge levels.
Get gain setting and adjust gain setting.

Direct links or attachments to the ethernet control protocol or API:
Command strings are available here https://www.shure.com/en-US/docs/commandstrings/MXW

**Comment by switch180** [comment]
To be clear - I see a `Shure: Microflex (MXW)` connection option in v3.3.1 and you are saying this is different from Shure Microflex Wireless? It sounds like what you're asking for already exists, but whether it works or not I can't test. Are you saying the existing connection doesn't work?

It seems well featured, including the ability to set channel name, audio gain, and flash lights.

I also see the Microflex Complete Wireless (MXCW) module, but we both agree that is a different system than MXW.

**Comment by Oldman-Winter** [comment]
Oh I'm sorry. I was just about to update. This module isn't available in the v3.0.0 release.
That looks like what I need. I will update and test that out.
