### ISSUE TITLE
Yamaha M7CL

### ISSUE THREAD

**Issue by airbenich** [bitfocus/companion-module-requests#160]
A module for the Yamaha M7CL would be great. Is ist the same then QL series?

**Comment by josephdadams** [comment]
Given the wide date range of release between these two consoles, I would not expect the control protocol to be the same. The M7 is controllable via MIDI and the commands are laid out in the manual.

**Comment by MeestorX** [comment]
I've written a lot of stuff that works with the older consoles. Older Yamahas used only MIDI for communication. The newer consoles use both MIDI and SCP. The module here is using SCP as it's much easier to implement. Only the CL/QL and TF (and likely the PM7/10) use SCP. I've re-written the SCP module and after I have tested it a bit, it'll hopefully replace the existing module. The effort for me would be way greater than the reward to implement support the older consoles. Best to just use a generic MIDI module with companion if you want to do something with the older boards.

**Comment by josephdadams** [comment]
@airbenich you can use the techministry-midirelay module that is in Companion along with the midi-relay listener component that is connected to a midi hardware interface and send the MIDI out of the interface directly to the console's MIDI ports.

**Comment by MeestorX** [comment]
> @airbenich you can use the techministry-midirelay module that is in Companion along with the midi-relay listener component that is connected to a midi hardware interface and send the MIDI out of the interface directly to the console's MIDI ports.

Does companion support MIDI?

**Comment by josephdadams** [comment]
@MeestorX companion does not directly support MIDI in or out at this time, but with the midirelay module, you can send MIDI fairly easily.

**Comment by airbenich** [comment]
Thank you for your answers. The M7CL uses MIDI over TCP/IP. Would it be possible to send MIDI via TCP/IP from Companion? So no hardware interface would be needed.

**Comment by MeestorX** [comment]
Well, it's "sort of" MIDI over TCP/IP, but it's not rtpMIDI (the "standard" that MacOS uses). It uses a proprietary MIDI driver from Yamaha. If companion can spit out MIDI, it's simple enough to use LoopMIDI or another virtual MIDI driver to connect to the Yamaha driver. I've done this with my software and it works fine. Direct MIDI support by companion would be a welcome addition, but there are already workarounds as Joseph mentioned.

**Comment by airbenich** [comment]
Thank you @MeestorX and @josephdadams for your details about this!
