### ISSUE TITLE
Epson PowerLite L630U

### ISSUE THREAD

**Issue by steven-laws** [bitfocus/companion-module-requests#1609]
Please create a Companion feature to control Epson projectors with the model number PowerLite L630U

**Comment by joeltcaron** [comment]
I think you can use the Epson Business module or PJLINK. I have had success with PJLINK and multiple Epson projectors

**Comment by steven-laws** [comment]
Thank you!  That worked great. I appreciate your help. On Sep 15, 2024, at 9:19 PM, Joel Caron ***@***.***> wrote:﻿
I think you can use the Epson Business module or PJLINK. I have had success with PJLINK and multiple Epson projectors

**Comment by steven-laws** [comment]
Please close this request.

**Comment by brunodsg23** [comment]
HI, I have the same issue. I tried to do it with my l630u but i couldn't make it work. Could you please explain the steps?

Thanks

**Comment by steven-laws** [comment]
Hi, These are the basic steps, but if you have problems with one of them let me know.

1- Make sure the projector is on the same network as the computer running Bitfocus.
2. Check the network status in the projector’s setup menu to make sure it has an IP address, and can be accessed over the network.  There are passwords that may need to be used to connect Companion to the projector.
3.  Go into Companion, and search for the JBMIA PJLINK module.  It will look like this when added to companion.


￼

Add in the IP address of the projector into the Target IP field, and put in the projector’s password, if there is one set up in the Projector network settings.

Once the projector is connected to companion, the status should go from Initialing to a Green Checkmark.

Then, it is a matter of selecting the function you want to add to a Companion Button.  I use it for simple Power on and Power off.

You can also manage the Epson projector setting through a web browser.  Just type in the IP address, and you can control several functions over the network using a web interface.  

Good Luck.
