### ISSUE TITLE
Triggers Management color coded backgound

### ISSUE THREAD

**Issue by 7tech7** [bitfocus/companion-module-requests#1611]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control
**StreamDeck**

What you would like to be able to make it do from Companion
**I would like to see an integration of colored coded option for the triggers. 
A seach options would be great too. That would make it easier to find that already setup**

Direct links or attachments to the ethernet control protocol or API:

**Comment by dnmeid** [comment]
This is not a module request.
