### ISSUE TITLE
Allen & Heath CQ

### ISSUE THREAD

**Issue by cdc334** [bitfocus/companion-module-requests#1628]
- [*] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control: Allen & Heath CQ

What you would like to be able to make it do from Companion: Control the various functions of the mixer

Direct links or attachments to the ethernet control protocol or API: 
[CQ_MIDI_Protocol_V1_2_0_iss3.pdf](https://github.com/user-attachments/files/17174894/CQ_MIDI_Protocol_V1_2_0_iss3.pdf)

**Comment by tintinhamans** [comment]
Check out #1280

**Comment by josephdadams** [comment]
Duplicate request.
