### ISSUE TITLE
Unreal OSC

### ISSUE THREAD

**Issue by mmcvfineart1** [bitfocus/companion-module-requests#1633]
Hi there

It would be ace if you could add a connector to Unreal Engine's Remote Touch OSC.

https://dev.epicgames.com/documentation/en-us/unreal-engine/getting-started-with-remote-control-presets-in-unreal-engine

Warm regards,

mmcvfineart1

**Comment by thedist** [comment]
Duplicate of https://github.com/bitfocus/companion-module-requests/issues/1005
