### ISSUE TITLE
Pay for Writing a Simple Module

### ISSUE THREAD

**Issue by ukiews** [bitfocus/companion-module-requests#1639]
Are there programmers out there who would be willing to write a simple module for profit?
If anyone could point me in the right direction. Thank you!

**Comment by thedist** [comment]
If you want a module developed you should specify what hardware/service you wish the module to integrate with, what you want it to do, if there's any documentation available etc... as without know what you actually want, it's impossible for anyone to know if it's even possible as not everything support 3rd party integrations, some things require developers to be hands on with a piece of equipment to appropriately develop/test for it, and things like that.

**Comment by ukiews** [comment]
Specifically, I am referring to this request:
https://github.com/bitfocus/companion-module-requests/issues/1638

However, I am willing to pay something to get it expedited. 
Of course, it would be good to know in general if there are folks that develop Companion modules for pay.

**Comment by leonreucher** [comment]
Hey @ukiews,

would you be so kind to join the Bitfocus Slack, so we can talk about details?

https://bitfocus.io/api/slackinvite
