### ISSUE TITLE
Chroma-Q/Vista Lighting

### ISSUE THREAD

**Issue by chasemixon** [bitfocus/companion-module-requests#164]
So I just recently found this software and used it to control a lighting console, X32 soundboard, Propresenter, and ATEM deck... so I was super impressed with it... so I'm all excited to talk with my staff at church about it. but we use Chroma Q or vista software to control our lighting but I don't see support for it on here, any chance you guys are working on it already or is it something that might not happen? Again super impressed with it... Thank you!!! Amazing stuff you have here.

**Comment by josephdadams** [comment]
@chasemixon there is a Companion module called Tech Ministry MIDI Relay that I created specifically to allow you to send MIDI Note On/Off and MSC to control our Chroma Q Vista at my church. It can do much more, but I created it with that in mind. Here is my write up on it to show you how to get started: https://techministry.blog/2019/06/06/controlling-chroma-q-jands-vista-with-midi-show-control-and-a-stream-deck-using-node-js-and-the-web-midi-api/

**Comment by chasemixon** [comment]
Hey Josephdadams, thanks so much, I'll take a look at it! Great stuff!

**Comment by josephdadams** [comment]
@chasemixon did you get it working?
