### ISSUE TITLE
Native: REST API

### ISSUE THREAD

**Issue by MatzeP** [bitfocus/companion-module-requests#1647]
- [ ] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control:
with native REST Api you can control diffent devices

What you would like to be able to make it do from Companion:
To Control User specific REST Commands

Direct links or attachments to the ethernet control protocol or API:

**Comment by peternewman** [comment]
You can do most of this using the generic HTTP module already and just processing the results:
https://github.com/bitfocus/companion-module-generic-http

**Comment by MatzeP** [comment]
Hi,
thanks. I will test it.
