### ISSUE TITLE
 Panasonic projectors

### ISSUE THREAD

**Issue by airbenich** [bitfocus/companion-module-requests#165]
Dear community,

it would be great to steer Panasonic projectors via Companion as they are industry standard for events.
Especially it would be great to have the Panasonic PT-DZ110X DLP projector in the companion library. Maybe the API for all projectors are the same?

**Comment by JeffreyDavidsz** [comment]
Try the pjlink module for Panasonic

**Comment by airbenich** [comment]
I just tried it with the mentioned projector and the pjlink module. Unfortunately it’s not working as the authorization fails. The projector has not only a password. It has also a username wich I could find in the source code of this module.

**Comment by peschuster** [comment]
I am working on a module for the ntcontrol protocol for panasonic projectors. I still have a TODO on my list to improve responsiveness of feedback, but the rest should work.
https://github.com/peschuster/companion-module-panasonic-projector

**Comment by airbenich** [comment]
@peschuster What do I need to do, to integrate your module into Companion? Build the whole Companion project?

**Comment by peschuster** [comment]
@airbenich It was added to Companion 2.0 about a month ago (https://github.com/bitfocus/companion-module-panasonic-projector).
You can download version 2.0 from the website:
1. https://bitfocus.io/user/downloads
2. "2.0 BETA"
