### ISSUE TITLE
KVM

### ISSUE THREAD

**Issue by jgansen** [bitfocus/companion-module-requests#1657]
I have a Smart-AVI SM-HDN-8S KVM Switch connected through the RS 232 port to a StarTech  I13-SERIAL-ETHERNET device.  I used the tcp-udp connection to make it work.  However, now Companion is no longer connecting to it.  any tips?

**Comment by dnmeid** [comment]
This seems neither to be a request for a new module nor a bug report for an existing module, but a general discussion or seek for help. Please direct such questions to the slack group (link in companion sidebar), the discussions section of the companion repo or the facebook users group.
