### ISSUE TITLE
gostream plugin

### ISSUE THREAD

**Issue by advtelecom** [bitfocus/companion-module-requests#1664]
The Brand Osee Gostream, have create a sdi and hdmi switch, and in your support page is available the plugin for companion.
Ths is support page in order to download the plugin:
https://drive.google.com/file/d/1_QknvcrutMQW9b8CjSCvPfP4PctOq_uN/view?ref=ncsvzlil

Is possible to integrate this plugin in the next version of companion ?

best regards
Maurizio Bogino

**Comment by dnmeid** [comment]
It seems that this module is now finished, it has been marked v1.0.0 three weeks ago.
We will review and include it once the module developers think it is ready and ask for it. I'm sure this will be soon.
