### ISSUE TITLE
How to get latest release of a Connection

### ISSUE THREAD

**Issue by SDC-Tim** [bitfocus/companion-module-requests#1672]
Apologies if this is the wrong way to ask this, I'm a new be

One of the Connections I use is Mixing Technology's theatremix running on Companion 3.3.1
The version available is 2.0.0
The author has a new version that has some features I would like to use, how can I get to use version 2.1.0

Thank you

**Comment by thedist** [comment]
The latest stable release of Companion is v3.4.3, so perhaps try that to see if the module is included.

If it's not, it's recommend to just wait for the module developer to ask for their release to be included in Companion at which point it'll be checked, and then added to beta builds. As and when needed the beta builds are released as stable releases.

If you wish to use the module anyway regardless of if it's been tested or included natively in Companion, you could download the module, install the dependencies and build (if required), and put in your Module Development folder that's set for Companion and Companion will load the module from there.

**Comment by SDC-Tim** [comment]
Jeff
Thank you for responding
I am testing 3.4.2 on another machine at the moment, the theatremix app is still 2.0.0 but I might try the manual download
