### ISSUE TITLE
Add Digest Authentication for generic HTTP module

### ISSUE THREAD

**Issue by mandurphy** [bitfocus/companion-module-requests#1676]
Hi there, 

I would like to use Companion to control the Linkpi video encoders via the HTTP API calls the manufacture has made available, but it requires Digest Authentication to access them. I've tried to configure the HTTP generic module to perform the digest authentication, but it fails. 

I see many functions like start/stop streaming, start/stop recording, audio and video bussing, overlay on/off, etc to be a good fit with Companion and most of the users of these Encoders already use Companion in their workflows. 

I have attached the API documentation from the manufacturer (translated from Chinese) that should give more technical details to help develop a module. 

If you need more information, a better translation or would like remote access to one of these encoders to test with, please let me know.

[Island Encoder HTTP API Interface Description.pdf](https://github.com/user-attachments/files/17731900/Island.Encoder.HTTP.API.Interface.Description.pdf)

**Comment by peternewman** [comment]
This has already been requested in the module itself:
https://github.com/bitfocus/companion-module-generic-http/issues/32

**Comment by dnmeid** [comment]
Closing this as an duplicate
