### ISSUE TITLE
SoundPad integration

### ISSUE THREAD

**Issue by petefisher78** [bitfocus/companion-module-requests#1685]
Need to be able to play specific sounds with Soundpad.  It seems that stream deck already has integration
[
](https://steamcommunity.com/app/629520/discussions/0/1653297026034259393/)

**Comment by leonreucher** [comment]
Soundpad does not have an API to allow being controlled over a network connection - therefore it is (in general) not being supported by Companion. A workaround would be to use the "Run shell path" module to control Soundpad using the .exe
See more: https://www.leppsoft.com/soundpad/help/manual/tutorial/rc/#rc-command-line
