### ISSUE TITLE
TCP commands not supported by TCP/UDP app

### ISSUE THREAD

**Issue by BvBrienen** [bitfocus/companion-module-requests#1691]
Hi all,

I try to make a PDU working with TCP commands.
The commands working fine with Hercules but can't get any progress in companion with different commands.

Any support I can use right now ;-)

Some Commands I want to send;
$23|C001|TOUC|DELOFF|0|U|$0D$0A
$23|C001|TOUC|DELON|0|U|$0D$0A
1 state set 1$0A
3 state set 0$0A

Best regards,
Berry

**Comment by istnv** [comment]
Usually that text representation `$xx` refers to an ASCII Hex value. 
The `$0D$0A` at the end is `CR/LF` (carriage return + line feed) termination/end sequence.
The `$0A` is just a `LF` or linefeed.

In the first command, the `$23` is actually a `#` character so create a button with:
Command: `#|C001|TOUC|DELOFF|0|U|` and select `CR/LF` for the end character.

The shorter ones would be  `0` or `1` for Command, and `LF` for the end character.

**Comment by dnmeid** [comment]
This is not for discussions
