### ISSUE TITLE
Controlling a projector with IR

### ISSUE THREAD

**Issue by austgresh** [bitfocus/companion-module-requests#1698]
Hi,
Background:
I am setting up a system in a studio where multiple people will use it so I am trying to keep it very simple by using StreamDeck (attached to a RaspPi) to control most functions.  In this particular studio I have an Epson PowerLite 1288 projector mounted to the ceiling.  I would like to control it with the SD like I have done in other studios but this projector doesn't have a network port (like I have in other studios).  The only way to control it is either with the buttons on the projector (but it is too high for most to reach) or with the remote via IR signals.  I would like to set up an IR blaster in the room so I can create buttons on the SD for on/off and inputs so that I don't have to have another remote in the room that can get lost.  Because this is at a school, wifi devices are not an option.  This would have to be something plugged into the RaspPi to get it's commands and not like most home automation systems that connect via wifi.

Questions:
Is there a good device that has worked well for others?
Any other suggestions on how to best achieve turning the projector on/off and changing the input via streamdeck without wifi or network connected to the projector?

**Comment by PerRoine** [comment]
I have not tried the IR module but are using the serial for various purposes they have POE versions of the boxes and there are A module available for it 

https://www.globalcache.com/products.html#

**Comment by dnmeid** [comment]
There is a module for the globalcache IR sender available.
