### ISSUE TITLE
Add Canon remote camera controller RC-IP100

### ISSUE THREAD

**Issue by QRoland** [bitfocus/companion-module-requests#1699]
When using Canon PTZ CN500 and CN300 with the remote RC-IP100 and a stream deck, we do some actions through the stream deck and others through the remote. Globally, on the stream deck we call and save presets and we change the input of a 12x12 output cleanswitch to do the vision on a monitor. On the PTZ remote we pan/tilt/zoom the cameras. So if we want to change a preset we must select the correct camera to have it on the monitor, then we go to the remote to select also the correct camera and move it. Finally we save the new position into an existing preset with the stream deck.
Basic mistake is to forgot to also select the camera on the remote controller before moving the camera. So we move the wrong one, possibly the one on program... We would love to be able to use the stream deck to tell to the remote to select the camera.

**Comment by josephdadams** [comment]
#1502
