### ISSUE TITLE
Module Request: Multicam Suite 

### ISSUE THREAD

**Issue by berryv97** [bitfocus/companion-module-requests#17]
**Describe the feature**
integrated API of the mixer of multicam systems

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
[API Multicam 1.0(2).pdf](https://github.com/bitfocus/companion/files/3318369/API.Multicam.1.0.2.pdf)
http://www.multicam-systems.com
**Usecases**
control the software with companion to make macro

**Comment by berryv97** [comment]
Hello @josephdadams, can you create a repository for your module ? 
the module is done but I can't access Slack.
brand: Multicam Systems
product: multicam suite
thank you

**Comment by josephdadams** [comment]
@JeffreyDavidsz

**Comment by JeffreyDavidsz** [comment]
Done

**Comment by josephdadams** [comment]
@berryv97 I approved the PR. Is this tested and working?

**Comment by josephdadams** [comment]
Included in core; closing.
