### ISSUE TITLE
Rosstalk and XPression Modules to Support Custom Variables

### ISSUE THREAD

**Issue by jreynolds67** [bitfocus/companion-module-requests#1716]
I'd like to please request that the XPression and Rosstalk modules be updated to be able to support custom variables in their input fields. Thank you.

**Comment by thedist** [comment]
Module specific feature requests should be submitted to the specific modules, so in this case [https://github.com/bitfocus/companion-module-rossvideo-rosstalk](https://github.com/bitfocus/companion-module-rossvideo-rosstalk) and [https://github.com/bitfocus/companion-module-rossvideo-xpression](https://github.com/bitfocus/companion-module-rossvideo-xpression)

This repo is for requesting new modules that don't already exist.
