### ISSUE TITLE
请求添加MIG系列命令         名称MIG H8 & H9 (640/690 EC90可用)

### ISSUE THREAD

**Issue by jesse1013** [bitfocus/companion-module-requests#1721]
H6/H8/H9控台
通过UDP协议,在控台操作界面上连接外部设备,达到控制的目的.
UDP Server端口：18900
所有字符都是UTF-8格式

（1）连接时发送此命令明确是控制H6/H8/H9设备
<migConsole><connectDevice>1</connectDevice></migConsole>

（2）获取控台 presetInfo
<migConsole><presetInfo>1</presetInfo></migConsole>

Ack：返回所有预设中保存预设信息; result为指令执行结果，0为失败，1为成功;presetCount为有效预设个数.<preset>1</preset>// 1 代表presetid 

<migConsole>
    <presetCount>4</presetCount>
<preset>1</preset>   
<preset>2</preset>
    <preset>3</preset>
    <preset>4</preset>
</migConsole>

(2)LoadPreset 加载预设  示例 加载预设1
<migConsole><loadPreset>1</loadPreset></migConsole>
LoadPreset 加载预设  示例 加载预设30
<migConsole><loadPreset>30</loadPreset></migConsole>
LoadPreset 加载预设  示例 加载预设300
<migConsole><loadPreset>300</loadPreset></migConsole>

(3)Take 命令
<migConsole><take>1</take></migConsole>

(4)Cut命令
<migConsole><cut>1</cut></migConsole>

**Comment by willosof** [comment]
Please edit or refile in english.
