### ISSUE TITLE
Datavideo PTR-10

### ISSUE THREAD

**Issue by scottaroo02** [bitfocus/companion-module-requests#184]
I'd love to have a Datavideo PTR-10 module to control the PTR-10. This is a Robotic Pan Tilt Head that allows you to transform any camera into a PTZ camera. Datavideo allows control via DVIP protocol.  

DVIP Control Operation Guide: http://www.resource.datavideo.com/downloads/Datavideo_DVIP_Ethernet_Control_Operation_Guide.pdf

DVIP_Protocol:
http://www.resource.datavideo.com/downloads/Datavideo_PTC-150_DVIP_Protocol.pdf

Datavideo PRT-10 UserGuide:
https://resource.datavideo.com/Instruction_Manuals/PTR-10_E2_A4_EN.pdf

This may be easy to implement by using the Sony VISCA or PTZOptics as a template.

**Comment by josephdadams** [comment]
@bb21b how does this protocol line up with your module?

**Comment by BB21B** [comment]
@josephdadams I believe the Datavideo PTZ cameras encapsulate Visca over IP so it is probably more likely to be a derivative of that. I found this while Googling, which should shed some light on it.

https://github.com/jamesremuscat/avx/pull/78

**Comment by scottaroo02** [comment]
i saw that a Datavideo DVIP module was written, can that be used in creating this module to control the PTR-10 PTZ camera?

**Comment by BB21B** [comment]
@scottaroo02 Unfortunately DVIP isn't really a set standard and this is a completely different implementation. At a glance it is just Visca over IP with an extra header of 00 08 and all the commands I looked at appear to match the document below.

https://pro.sony/s3/cms-static-content/uploadfile/59/1237493025759.pdf

So it would probably be best if support is added to a copy of the Sony Visca module and then any differences that may exist can be addressed

**Comment by scottaroo02** [comment]
Is there any way to implement this in the current Sony VISCA protocol?

**Comment by BB21B** [comment]
> Is there any way to implement this in the current Sony VISCA protocol?

It would probably be best copied as its own module, I think there are a couple of visca flavours done in this way.

Without access to hardware though makes development a little tedious for whomever wants to pick this project up.

Some people will take on bounties though so that may be an option depending on how quickly you'd like to see this done.

**Comment by scottaroo02** [comment]
Happy to throw $150 towards someone to implement this for me.

**Comment by cjdenio** [comment]
Here's what I found: http://www.resource.datavideo.com/downloads/Datavideo_DVIP_Ethernet_Control_Operation_Guide.pdf

I think the PTR-10 implements the DVIP protocol, so it shouldn't be super difficult.

**Comment by BB21B** [comment]
@cjdenio From my understanding so far (Based on the vision mixers) I think these cameras just implement the device discovery and ethernet interface option setting part of DVIP and the camera control portion seems to follow the Visca format to a degree, it doesn't match with the standard DVIP command format I'm used too.

http://www.resource.datavideo.com/downloads/Datavideo_PTC-150_DVIP_Protocol.pdf

I've had another look at that document. The packet length in the first two bytes are right but too short it's normally a DWORD length. There is no command bytes (Normally DWORD). Then the the control/section bytes (Again shorter than normal DVIP) and the parameter layout is a bit weird too. That makes me think that part isn't what I'd call DVIP.

If you want to you can get a bit more info about DVIP from one of the vision mixer documents which I used for development.

https://github.com/BB21B/datavideo-dvip-docs/blob/master/SE1200MU/Datavideo%20SE-1200%20Ethernet%20Control%20Protocol_E1%2020190710.pdf

**Comment by scottaroo02** [comment]
Any way to bump this?  would love to have this implemented so I can control.

**Comment by josephdadams** [comment]
@scottaroo02 offering a financial incentive can help if you need something quickly.

**Comment by BB21B** [comment]
@josephdadams he has offered up $150 is there any way to tag that in the issue? 
@scottaroo02 I did mention it on the Slack chat when you posted originally.

**Comment by josephdadams** [comment]
Oh I missed that. Sorry!

**Comment by cjdenio** [comment]
I'd gladly build a module based on the protocol spec, but there's no promise it'll actually work on an _actual device_.

**Comment by BB21B** [comment]
@cjdenio the only thing I've not seen documented anywhere is the actual port the device uses for it's Visca style comms. Other than that it should be pretty standard.

**Comment by scottaroo02** [comment]
@cjdenio let me know what you want to do to get the ball rolling on this.

**Comment by scottaroo02** [comment]
would bumping the bounty to $200 help get this implemented?

**Comment by josephdadams** [comment]
@cjdenio are you working on this?

**Comment by cjdenio** [comment]
No, I was unable to find any decent protocol documentation. I'm also not sure about writing a module without an actual device to test.

**Comment by josephdadams** [comment]
@scottaroo02 can you provide a way to test against the device? Teamviewer access time a device on the same network?

**Comment by scottaroo02** [comment]
I can provide team viewer access to a computer on my network, the software that datavideo created on that computer to control the device, wireshark, a webcam of the device... whatever is needed.  Just let me know what I can do
To get this implemented.

**Comment by josephdadams** [comment]
@cjdenio does that change things for you?

**Comment by scottaroo02** [comment]
can I bump the bounty to $300 to implement this?  How can I make this happen?

**Comment by BB21B** [comment]
@scottaroo02 I could probably start taking a look at this within the next couple of weeks, I have been quite busy lately which is why I didn't take it up myself. Do you have an email I could contact you at?

**Comment by scottaroo02** [comment]
@BB21B  that would be awesome, thanks so much!  email is scottaroo@gmail.com.  I can have a dedicated computer with team viewer for when you have time to work on it.

**Comment by BB21B** [comment]
Implemented in:

https://github.com/bitfocus/companion-module-datavideo-visca
