### ISSUE TITLE
Avonic CM70-IP

### ISSUE THREAD

**Issue by magneriise** [bitfocus/companion-module-requests#185]
Hi. 
Want a module for Avonic CM7X IP. Theese are PTZ for use in installation and rental. 
With a growing demand for easy of use packages. 
Attached is the manual included the full control list. 
Hope to have control of:
PTZ, Focus, WB, Exposure, Position memory, tallylight. 
[Manual CM70-IP (2).pdf](https://github.com/bitfocus/companion-module-requests/files/4368423/Manual.CM70-IP.2.pdf)

**Comment by magneriise** [comment]
Have tested quickly with the Sony VISCA- ip and the basics work perfect. Havn't tested all functions, but I guess we're cloose with making a copy of the that file.

**Comment by josephdadams** [comment]
Do we need to make a copy of the module if it works the same?

**Comment by magneriise** [comment]
Sorry, reely noob of me. Was not aware that the VISCA a standard for more then Sony. 
It is testen and everything work just briliant.
