### ISSUE TITLE
Barco RLM-W12 Projector Control

### ISSUE THREAD

**Issue by ZachIsaiah** [bitfocus/companion-module-requests#187]
Hey guys, new to this so bear with me! I would love to control my Barco RLM-W12 Projectors (Lamp on, off, etc). Is there a simple way to go about creating the code for this? Any help would be appreciated!

**Comment by josephdadams** [comment]
I have the same projectors. If you send an HTTP request to /tgi/remote.tgi?onky, it will turn on.

http://projectorIP/tgi/remote.tgi?onky

offky will turn it off

I've been doing this for years and it works great every time

**Comment by ZachIsaiah** [comment]
Thank you so much! It worked!

**Comment by tljunggren** [comment]
Hi two + years later. I have the same projector. 
The command: http://projectorip/tgi/remote.tgi?onky and offky work fine from a browser, but I'm getting nowhere from within companion.
I'm supposed to connect it with generic http request? using POST? 
Any help appreciated here..

Would you also know the commands for picture mute?
the command I used via serial is op picture.mute = 1 , is there another syntax for http?

**Comment by ZachIsaiah** [comment]
Yo! I attached screenshots of our setup. Hope it helps.

Best,
__
ZACHARY I. MCCROREY
Sr. Creative Arts Director
Transformation Church
803.287.8018
MULTIETHNIC. MULTIGENERATIONAL. MISSION-SHAPED.


From: tljunggren ***@***.***>
Date: Wednesday, January 25, 2023 at 7:18 AM
To: bitfocus/companion-module-requests ***@***.***>
Cc: Zachary McCrorey ***@***.***>, State change ***@***.***>
Subject: Re: [bitfocus/companion-module-requests] Barco RLM-W12 Projector Control (#187)

Hi two + years later. I have the same projector.
The command: http://projectorip/tgi/remote.tgi?onky and offky work fine from a browser, but I'm getting nowhere from within companion.
I'm supposed to connect it with generic http request? using POST?
Any help appreciated here..

Would you also know the commands for picture mute?
the command I used via serial is op picture.mute = 1 , is there another syntax for http?

**Comment by josephdadams** [comment]
Replying to the github email does not always work with attachments.

**Comment by ZachIsaiah** [comment]
> 

Lets try it again
[Screenshot 2023-01-25 at 2 12 17 PM](https://user-images.githubusercontent.com/62719333/214682989-934d9a06-56e8-4aef-b39b-6df827876b8f.png)
![Screenshot 2023-01-25 at 2 11 40 PM](https://user-images.githubusercontent.com/62719333/214682991-57d38e68-c48b-4e06-9851-541d48cf6f89.png)

**Comment by ZachIsaiah** [comment]
![Screenshot 2023-01-25 at 2 12 17 PM](https://user-images.githubusercontent.com/62719333/214684069-c2ec4d80-9ee6-4617-bf96-f0bcde73766b.png)

**Comment by tljunggren** [comment]
Thank you guys! Now I GET it.. it works nicely. 
Apparently I didn't try that command yesterday.. 

For those interested the commands for shutter are:
http://192.168.2.201/tgi/general.tgi?pauseoff
http://ipadress/tgi/general.tgi?pauseon

For those even more interested, use Wireshark & the projector web-interface to find the command for the desired action.
Thanks again.

**Comment by josephdadams** [comment]
Thanks for POSTing a reply! :)
