### ISSUE TITLE
roland m5000

### ISSUE THREAD

**Issue by houtacheng** [bitfocus/companion-module-requests#188]
[M-5000_M-5000C_RS-232C_Telnet_e02_W.pdf](https://github.com/bitfocus/companion-module-requests/files/4395583/M-5000_M-5000C_RS-232C_Telnet_e02_W.pdf)

https://proav.roland.com/global/ohrca/

I have a roland m5000 device
I hope can use companion control
I found the telnet file, don't know if it helps?
thank you very much!

**Comment by josephdadams** [comment]
Follows Roland’s other protocols so is very straightforward to implement. If anyone is looking to pick this up, I recommend using the Roland V-60HD module as a template: https://github.com/bitfocus/companion-module-roland-v60hd

**Comment by josephdadams** [comment]
@houtacheng https://github.com/bitfocus/companion-module-roland-m5000

**Comment by houtacheng** [comment]
That's great.

**Comment by josephdadams** [comment]
Test it out and let me know how it goes!

**Comment by josephdadams** [comment]
@houtacheng did you test?

**Comment by houtacheng** [comment]
it's great!!!
![image](https://user-images.githubusercontent.com/25832189/89000094-d52ed900-d2cc-11ea-954c-3a3f22dace42.png)

**Comment by josephdadams** [comment]
Any changes needed?

**Comment by houtacheng** [comment]
I've only tested a few of the features I use and they all work. The others have not been tested yet.
