### ISSUE TITLE
Module Request: TV-One Corrio Master

### ISSUE THREAD

**Issue by PwllynBrwnt** [bitfocus/companion-module-requests#19]
**Describe the feature**
The TV-One corrio master is a excellent Video/Matrix scaler and video wall controller perfect for fixed installations..I would be interested in a Companion Instance that could simplyfy the external triggering of presets.

**Is this platform dependent (windows, mac, ..) currently the Corriographer network control software is only available on the windows platform but i believe a mac version is in deveopment. there is a smartphone app  available for basic control .

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along
[CORIOmaster App sheet insert.pdf](https://github.com/bitfocus/companion/files/3268687/CORIOmaster.App.sheet.insert.pdf)
[tvONE CORIOmaster Commands-v2.0.7.pdf](https://github.com/bitfocus/companion/files/3268688/tvONE.CORIOmaster.Commands-v2.0.7.pdf)
[PDF-C3-5x0-2.3-US.pdf](https://github.com/bitfocus/companion/files/3268689/PDF-C3-5x0-2.3-US.pdf)

**Usecases**
I have installed multiple of these units in Broardcast TV studios in the US and Europe they are perfect for feeding multiple screens in a broadcast enviroment.

**Comment by JeffreyDavidsz** [comment]
tvone basic module is in core now
