### ISSUE TITLE
Sony Bravia fwd-65x950g

### ISSUE THREAD

**Issue by ThatGuySittin** [bitfocus/companion-module-requests#197]
Hello all! I was wondering if someone could develop a module for the Sony Bravia TVs? They are IP controlled, and I would like to be able to use the companion infrastructure to do this! The controls I thought we could implement are simply a set Power Status ON and a set Power Status OFF. It may also need to allow for authentication, since the Bravia has an authentication setup. I will link below the detailed page provided by Sony on the IP Control information! Control is allowed over REST API, IRCC-IP, and simple IP. 

Simple information page:
https://pro.sony/ue_US/products/pro-displays/fwd-65x950g

IP Control Information:
(https://pro-bravia.sony.net/develop/integrate/ip-control/)

Thank you to all who investigate this!

**Comment by ThatGuySittin** [comment]
I have received confirmation I can in fact pay for this module. What would be a fair price for this? We need this to be functioning as soon as possible to test before next project.

**Comment by josephdadams** [comment]
Most modules take 2-3 hours minimum to create, even more to test/troubleshoot or apply special features. Do you have one of these TVs set up where it could be accessed remotely for module development? It makes testing go much faster.

**Comment by ThatGuySittin** [comment]
Hey Joseph, I do have one for remote access. What exactly would you need in this scenario? Connection through IP to a computer that also has companion on it? What program would you use for remote access?

**Comment by josephdadams** [comment]
Unattended teamviewer would be the easiest. I don’t have a lot of time during the day right now to develop but could possibly crank this out for you one night. I would need to be able to set up a dev environment of Companion on that remote computer in order to run custom code. Once it is proven to be working, we can set it up as a proper module and include it in 2.0 builds.

**Comment by ThatGuySittin** [comment]
Awesome. What is a reasonable hourly rate for you so I can make sure you get compensated for this?

**Comment by josephdadams** [comment]
Send me an email and let’s come up with a plan! My email is my GitHub username @ gmail. Thanks!
