### ISSUE TITLE
Elgato Key Light Module

### ISSUE THREAD

**Issue by billchurch** [bitfocus/companion-module-requests#198]
https://www.elgato.com/en/gaming/key-light

Didn't see an API posted anywhere that I can find, but looks simple enough from what I picked up from Wireshark...

Quick PostMan API here: https://www.getpostman.com/collections/f1c92ce7daec35ca2864

**Get list of lights (in case paired with others?)**
get http://<ip>:9123/elgato/lights
```
{
    "numberOfLights": 1,
    "lights": [
        {
            "on": 0,
            "brightness": 17,
            "temperature": 162
        }
    ]
}
```

**Get individual info for this light**
get http://<ip>:9123/elgato/accessory-info
```
{
    "productName": "Elgato Key Light",
    "hardwareBoardType": 53,
    "firmwareBuildNumber": 192,
    "firmwareVersion": "1.0.3",
    "serialNumber": "abc123",
    "displayName": "",
    "features": [
        "lights"
    ]
}
```

**Turn Light 1 on with settings:**
put http://<ip>:9123/elgato/lights
```
{
    "numberOfLights": 1,
    "lights": [
        {
            "on": 1,
            "brightness": 17,
            "temperature": 162
        }
    ]
}
```

**Turn Light 1 off:**
put http://<ip>:9123/elgato/lights
```
{
    "numberOfLights": 1,
    "lights": [
        {
            "on": 0,
            "brightness": 17,
            "temperature": 162
        }
    ]
}
```

**Comment by josephdadams** [comment]
This is in the latest beta builds now.
