### ISSUE TITLE
Button to Increment or decrement value

### ISSUE THREAD

**Issue by booguiseb** [bitfocus/companion-module-requests#201]
Hi,

I was thinking of button in COMPANION (like page up/down) that can increment values for exemples:
In a blackmagic hyperdeck instance, scroll up and down in the media player list, change the jog speed (may be an option to change the increment value( +1,+10,+100))

Thanks a lot

**Comment by josephdadams** [comment]
Thanks for your request. It sounds like there is an existing request falls in line with what you are asking for, so I will close this issue. Feel free to add your thoughts here: https://github.com/bitfocus/companion/issues/954
