### ISSUE TITLE
Sennheiser SSC and SMC Protocol (EM6000)

### ISSUE THREAD

**Issue by mpaulmitchell** [bitfocus/companion-module-requests#202]
Hello,

I would like to submit a request for development of the Sennheiser SSC and SMC Protocol. This protocol is used to communicate with a number of their products. I would specifically like communication with the Sennheiser EM6000 but I believe this can be expanded to the products listed in this document. https://assets.sennheiser.com/global-downloads/file/13001/AN_1260_v1.0_Media_Control_Systems_EN.pdf

I would like to be able to pull names and values from the devices as well as update those names and values over the network. This link is to the control of the EM6000. 
https://assets.sennheiser.com/global-downloads/file/8378/TI_1109_v2.2_Sennheiser_Sound_Control_Protocol_Digital_6000_EN.pdf

Here is the document for control of a secondary product over the SMC Protocol
https://assets.sennheiser.com/global-downloads/file/12379/ewG3_2000_MediaControlProtocolDescription_120122.pdf

**Comment by perrydegennaro** [comment]
I would also like this module to be created. I use the Sennheiser G3 IEM systems and this would be very helpful for me.

**Comment by mpaulmitchell** [comment]
Hi is this on anyone’s radar as a possibility?

**Comment by fccnorwalktech** [comment]
Bumping for interest.  We will be receiving several EW-DX receivers shortly.  Id be very interswetd in feedbacks as well as ability to mute, power and adjust transmitter gain.

**Comment by Jasper1980** [comment]
I am also interested. We are using the SpeechLine and would like to communicate with the Multi-Channel Receiver including feedback from the device.

This is the SSC protocol document:

https://assets.sennheiser.com/global-downloads/file/9541/TI_1093_v2.0_Sennheiser_Sound_Control_Protocol_ew_D1_EN.pdf

**Comment by DanielWilliamsMSC** [comment]
FYI i got this working with the tcp-udp generic module for now 

![image](https://github.com/bitfocus/companion-module-requests/assets/125619541/18dd7207-e418-4e4b-aa43-c2dc8df19808)

**Comment by phillipivan** [comment]
Perhaps this should be split as there requests for a few different products with different protocols?

For what its worth I could use and assist with testing of the EM6000's with SSCP.

**Comment by LukeSCC** [comment]
Bumping for interest as it would be awesome to have this work without having to rely on generic modules

**Comment by phillipivan** [comment]
Hi @LukeSCC  I have some WIP. Its presently subscribing to data from and creating variables for the EM6000 and L6000. Hopefully in the next week or so I will have some actions and feedbacks in place.
