### ISSUE TITLE
Panasonic UE4 control

### ISSUE THREAD

**Issue by magneriise** [bitfocus/companion-module-requests#203]
Want to control the new Panasonic E-PTZ camera from Companion. 
Hope to have as close to control on all parameters, but most important is:
- Zoom
- PTZ
- Focus
- Gain/iris
- WB
- Tally

Attached is documentation for control
[AW-UE4_InterfaceSpecification_V1.00E.pdf](https://github.com/bitfocus/companion-module-requests/files/4535018/AW-UE4_InterfaceSpecification_V1.00E.pdf)

**Comment by josephdadams** [comment]
@PerRoine should we try to incorporate this into the existing Panasonic PTZ module?

**Comment by McHauge** [comment]
@magneriise This is now implemented in the panasonic PTZ module, so I'm gonna close this for now
