### ISSUE TITLE
Magewell Pro Converter NDI Decoder

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-requests#205]
Device: Magewell Pro Convert for NDI to HDMI

Specific module feature requests:
- Switch between different pre-defined NDI sources (channels)
- Feedback to indicate whether an NDI source/channel is active

API Documentation: http://www.magewell.com/api-docs/pro-convert-decoder-api/

**Comment by cpuguru07** [comment]
I am successfully using the "internal: Run shell path" action to issue CURL commands to the Magewell NDI decoders. However, it requires issuing a Login command action for every button because the authentication times out after so long, so a pre-built module that automatically determines login state and re-authenticates if necessary would be ideal.
There is Node.js support in the API documentation, which I believe would be useful to building a Companion module. The Magewell API side of this seems relatively straightforward, but I haven't had time to figure out how to program Companion modules to be able to contribute to this module.

**Comment by josephdadams** [comment]
I wrote this on commission, it is here and will be available in a beta build soon: https://github.com/bitfocus/companion-module-magewell-proconvert-decoder
