### ISSUE TITLE
Request for Wysiwyg

### ISSUE THREAD

**Issue by julienferreiro** [bitfocus/companion-module-requests#213]
Hi to all
I'm using Wysiwyg from CAST software (https://cast-soft.com/), and I'd really like a companion profile to use with it.
The only way I found to control it is using keyboards shortcut, but there isn't some for every action.
I'm ready to answer your questions or try your ideas! :-)
Thanks

**Comment by josephdadams** [comment]
Please provide a link to the protocol documentation that would allow Companion to control it, along with what you’re hoping to specifically control.

**Comment by julienferreiro** [comment]
Hi Joseph
Thanks for answering! :-)
I asked to the developers from CAST software, but they told me that Wysiwyg doesn't have protocol that we can use to control it...
So it seems to be impossible?
Thanks anyway! :-)

**Comment by josephdadams** [comment]
No protocol, no native Companion module. Sorry!
