### ISSUE TITLE
Ross Carbonite feedback or Tally info

### ISSUE THREAD

**Issue by AlexHasker** [bitfocus/companion-module-requests#214]
Is there a way of getting feedback from Ross Carbonite vision mixers so buttons reflect the actual status of the mixers bus that is being controlled?

Ive been dabbling a bit with Wireshark and from what I can tell the Carbonite doesn't readily provide feedback unless a service is started within the mixer like TSL UMD,  I may be wrong as Im just fumbling here.

My ideal goal here is to use the feedback to trigger audio follow via Companion. Even getting the tally info (possibly by emulating a TSL listening device) would get the audio follow idea working.

**Comment by josephdadams** [comment]
I wrote this module awhile back: https://github.com/bitfocus/companion-module-techministry-umdlistener

Not sure if we ever got it tested by anyone other than me to get it included in the core. The goal was to have Companion trigger another action when a certain TSL value was met. So, Cam 1 comes into PGM, Companion could trigger an audio route on another device.

If you have a dev environment set up, clone this module into it and test it out for me.

**Comment by AlexHasker** [comment]
Thanks Joseph

I have no idea what the dev environment is but I’ll start looking into it

It may take me a while but it certainly sounds promising




Sincerely

Alex Hasker


Lex Audio Visual Pty Ltd
A.B.N. 57 638 179 317<tel:57%20638%20179%20317>
A.C.N.  095 213 193<tel:095%20213%20193>
Factory 3/123 Chesterville Rd,<x-apple-data-detectors://3/3>
Highett, Vic 3190<x-apple-data-detectors://3/3>
Melbourne, Australia
www.LexAudioVisual.com.au<http://www.lexaudiovisual.com.au/>
Email Alex@LexAudioVisual.com.au<mailto:Alex@LexAudioVisual.com.au>
Phone 03 9532 3006<tel:03%209532%203006>
Mobile 0418 307 485<tel:0418%20307%20485>

Accounts
For all account queries, please contact:
Lex Audio Visual accounts c/o The Outsourced Office
Attention Pauline May
Suite 4, 1414 Toorak Road<x-apple-data-detectors://4/1>
Camberwell,  VIC  3124<x-apple-data-detectors://4/1>
Email: LexAudioVisual@osoffice.com.au<mailto:LexAudioVisual@osoffice.com.au>
Phone 03 9889 1957<tel:03%209889%201957>

On 19 May 2020, at 12:29 pm, Joseph Adams <notifications@github.com> wrote:

﻿

I wrote this module awhile back: https://github.com/bitfocus/companion-module-techministry-umdlistener

Not sure if we ever got it tested by anyone other than me to get it included in the core. The goal was to have Companion trigger another action when a certain TSL value was met. So, Cam 1 comes into PGM, Companion could trigger an audio route on another device.

If you have a dev environment set up, clone this module into it and test it out for me.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion/wiki/Module-Development

**Comment by AlexHasker** [comment]
Sorry for the Nooby questions, Im trying to work out how I can run this module at my end so I can test it on a Carbonite. 

Preface -  I run Windows, have zero javascript knowledge and Im trying my best to learn all the lingo on GitHub.

For me to get this developer enviroment setup on Windows, from what I understand,  I  need to and have installed GitDesktop and I believe Ive "forked companion and your techminstry-umdlistner

I cant find any info on the next step,  running Compantion with this umdlister module - How do I go about this ? Any pointers?

Ive also installed Node.js but that just fires up a terminal window of some form, that I have no idea what to do with.

I followed the link you posted 
https://github.com/bitfocus/companion/wiki/Module-Development
and on the second paragraph I clicked the " _Developing on Windows 10_" link and that lead me to a "Create New Page" page ,  no helpful info there at all. Is there something missing there?

**Comment by AlexHasker** [comment]
Joseph, did you get any further with your UDM Listner beicoming part of the core of Companion  so Companion can receive tally info from Ross mixer or other TSL devices?

**Comment by josephdadams** [comment]
Nope I made tally arbiter instead 😃

**Comment by josephdadams** [comment]
Yes sir!

**Comment by AlexHasker** [comment]
Let em know what you think it will take

**Comment by AlexHasker** [comment]
Got it, reading now


Sincerely



Alex Hasker





Lex Audio Visual Pty Ltd

A.B.N. 57 638 179 317<tel:57%20638%20179%20317>

A.C.N.  095 213 193<tel:095%20213%20193>

Factory 3/123 Chesterville Rd,

Highett, Vic 3190

Melbourne, Australia

www.LexAudioVisual.com.au<http://www.lexaudiovisual.com.au/>

Email ***@***.******@***.***>

Phone 03 9532 3006<tel:03%209532%203006>

Mobile 0418 307 485<tel:0418%20307%20485>

________________________________

**Comment by Bazil313A** [comment]
> I wrote this module awhile back: https://github.com/bitfocus/companion-module-techministry-umdlistener
> 
> Not sure if we ever got it tested by anyone other than me to get it included in the core. The goal was to have Companion trigger another action when a certain TSL value was met. So, Cam 1 comes into PGM, Companion could trigger an audio route on another device.
> 
> If you have a dev environment set up, clone this module into it and test it out for me.

Hi. I am using this module to get tally info and labeling info into companion. Mainly I am using it to have 'roll-clip' functionality for vmix. I have a listener in companion that triggers when my playback source (tally 1) is on to program (tally1_PGM = true) at which point vmix is told to play. Works very well.

![Image](https://github.com/user-attachments/assets/a3cc137b-3aa2-4cdc-99d0-d6ee1fc92405)
