### ISSUE TITLE
PowerPoint OSC

### ISSUE THREAD

**Issue by mko1989** [bitfocus/companion-module-requests#221]
Hi, 
I'd like to request a module for PowerPoint remote control via OSC.
I know there is already module for Remote Show Control and i use it a lot, but the OSC remote can give feedback on which slide the presentation is which would be beneficial in these times as i use companion for remote remote for PPT.

Here is a link to PPT OSC:
https://github.com/benkuper/PowerPoint-OSC

Thanks for all the work, you guys are great!

**Comment by NoahCallaway** [comment]
#307 Seems to be a duplicate.
I should be able to take this on.

**Comment by josephdadams** [comment]
Closing this one as it’s a duplicate.
