### ISSUE TITLE
Elgato KeyLight support

### ISSUE THREAD

**Issue by alexeyzimarev** [bitfocus/companion-module-requests#223]
It would be nice to add control options for Elgato KeyLight as they did in the Elgato StreamDeck software.

There is no official KeyLight SDK but there are _a lot_ of repos on GitHub that either are SDKs for different languages or have some code insight that controls those lights. This one, form example, is for JS: https://github.com/NickParks/elgato-light-api

**Comment by josephdadams** [comment]
Duplicate of #198. Already requested.
