### ISSUE TITLE
Kramer VP-773A Scaler Switcher

### ISSUE THREAD

**Issue by dmxking512** [bitfocus/companion-module-requests#226]
Is it possible to add support for this unit?

**Comment by dmxking512** [comment]
Aparently the unit uses protocol 3000

**Comment by dmxking512** [comment]
I've spoken with Kramer technicians who have advised that this can be done by 

Telnet to device IP on port 5000 and issuing the commands:

`#Y 0,23,0`

followed by a carriage return or enter would switch the device to hdmi input 1. 

Replace 23 with the following numbers per function.

CH1_HDMI3 20
CH1_VGA1 21 
CH1_VGA2 22 
CH1_HDMI1 23 
CH1_HDMI2 24 
CH1_HDMI4 25 
CH1_DP 26 
MUTE 37
BLANK 16 
FREEZE 17 
LOCK 18

**Comment by EventReplay** [comment]
https://cdn.kramerav.com/web/downloads/manuals/vp-773a.pdf
It's a shame kramer aren't consistant with there protocol definitions!

I would suggest using vp-734 module as a base and use the definitions in above pdf

**Comment by dmxking512** [comment]
Yeah it's a pain they don't stick to one structure . 

JavaScript isn't my strong point but I've had a look at the file in that module and it looks like it could easily be adapted . 

I'm not sure who best to look at it as I've never developed using GitHub haha 😆

**Comment by EventReplay** [comment]
I hadn't used GitHub before being shown Companion! It's a good way to learn when your interested in the subject & you have a goal you want to achieve.

Do you have a dev enviroment for testing?

**Comment by dmxking512** [comment]
May have to look at a dev environment then.

Have tried with a custom command but no dice.

**Comment by dmxking512** [comment]
Ive managed to fork the repository to my git account and have cloned it to my machine but all the module folders are empty? 

Bit lost now :S

**Comment by dmxking512** [comment]
Right have been reading the very well put together developer.md file 

I am now at a point where i need the core developers to create a repository for my module.

**Comment by EventReplay** [comment]
This: https://github.com/bitfocus/companion/wiki/Module-Development gives a bit more detailed info than the Delevoper.md

Have you got your module working ok ?

**Comment by dmxking512** [comment]
I've had a read through bits and also joined the slack channel.

it was suggested that I amend the 734 module so that it offers different options based on the model.

I've started tweaking the code but as i said my javascript isn't great. 

I assume i can push the changes up to my own fork before they get merged into the master?

**Comment by dmxking512** [comment]
https://github.com/dmxking512/companion-module-kramer-vp734/commit/7ee8a828d7cacf33d51b0c43992f4c01055bdf58

**Comment by EventReplay** [comment]
Yes you can and should test locally with your fork before a merge.
I've posted an answer in the slack channel.

**Comment by dmxking512** [comment]
Ah yes have just seen your response. Thanks

**Comment by EventReplay** [comment]
Module created, this can be closed.

**Comment by dmxking512** [comment]
Agreed . Thankyou

**Comment by dmxking512** [comment]
Appreciate this is closed. has this made it into a release yet?

**Comment by EventReplay** [comment]
Sorry for delay in responding, there was some sort of issue when moving repo into builds which I flagged, this should have been rectified.

Should be available in the current beta builds.
