### ISSUE TITLE
Rogue Amoeba Farrago

### ISSUE THREAD

**Issue by retailgeek** [bitfocus/companion-module-requests#227]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

I wonder if anyone has thought about adding Rogue Amoeba Farrago support? It's a great soundboard for OSX.
https://weblog.rogueamoeba.com/2020/04/17/farrago-1-5-packs-a-powerful-list-mode-and-much-more/

**Comment by josephdadams** [comment]
@retailgeek the protocol documentation is missing. Please post that. Thank you!

**Comment by marvinogravel** [comment]
Yes please! I'd love Farrago support. Would it work on my Stream Deck alongside my Atem Mini macros?

**Comment by josephdadams** [comment]
@retailgeek @marvinogravel do either of you have links to the documentation or protocol sheet that would allow Companion to control this software?

**Comment by mhillmanz** [comment]
trying to ignite this thread again: link to documentation 
https://rogueamoeba.com/support/manuals/farrago/?page=osc

**Comment by bryce-seifert** [comment]
I can work on this module. I'll get started and post here when I have something to test.

**Comment by daniep01** [comment]
@bryce-seifert Are you still planning to write this module?

**Comment by bryce-seifert** [comment]
@daniep01 Yes! I actually have a fair bit done but got distracted before finished it. I’ll work on getting something releasable this week

**Comment by daniep01** [comment]
Thanks for the update, I'm not in urgent need of the module myself, but I could take on development, but looks like that's all in hand 👍

**Comment by bryce-seifert** [comment]
I've worked on this module, and it will be included in the Companion betas after tomorrow.
Please give it a try, and report any problems or requests to the [module issues](https://github.com/bitfocus/companion-module-rogueamoeba-farrago/issues)

**Comment by DBinNYC** [comment]
Good stuff! Thanks Bryce
