### ISSUE TITLE
LG Projector control HU85LA 4K

### ISSUE THREAD

**Issue by fccnorwalktech** [bitfocus/companion-module-requests#228]
Looking for a module to be created to control this projector. Specficially Shutter and power features are desired, but if more avaialble that works too!

https://www.lg.com/us/home-video/lg-HU85LA-4k-laser-projector?cmpid=2020HQProjector-SEM|US|Google|2020HQProjector-SEM-Brand-HU85LA-Exact|Generic-Generic|k0173&gclid=Cj0KCQjw_ez2BRCyARIsAJfg-ku8QEeLri_7R-7ODLWJuqSLJU2HFzDmg8UfVPx70d1rfbKd0KnMVzQaAukyEALw_wcB
[OM_ENG.pdf](https://github.com/bitfocus/companion-module-requests/files/4741221/OM_ENG.pdf)

**Comment by josephdadams** [comment]
Please include a link to the documentation and ethernet protocol spec. Thank you!
