### ISSUE TITLE
Chamsys QuickQ

### ISSUE THREAD

**Issue by cjmillet** [bitfocus/companion-module-requests#239]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
This is a lighting controller.  

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Chamsys.com

**Usecases**
Used to control lighting remotely for house of worship/theatre venues.  An IOS app exists for QuickQ, so being able to trigger scenes and advance scenes from Streamdeck would be great
[QuickQConsolesManualv1.8.pdf](https://github.com/bitfocus/companion/files/4816990/QuickQConsolesManualv1.8.pdf)

**Comment by josephdadams** [comment]
I’m guessing you’ve tried the magicq module and it didn’t work? I glanced at the documentation that you provided and it doesn’t seem to list specific ethernet protocol information, so I will have to mark this as missing documentation. Please provide the protocol spec if you would like for this request to be considered.

**Comment by mikethiessen21** [comment]
> 
> 
> I’m guessing you’ve tried the magicq module and it didn’t work? I glanced at the documentation that you provided and it doesn’t seem to list specific ethernet protocol information, so I will have to mark this as missing documentation. Please provide the protocol spec if you would like for this request to be considered.

Check this newer documentation (chapter 15 and 16):
https://secure.chamsys.co.uk/bugtracker/download_file.php?file_id=162&type=doc

**Comment by tijjuuu** [comment]
> > I’m guessing you’ve tried the magicq module and it didn’t work? I glanced at the documentation that you provided and it doesn’t seem to list specific ethernet protocol information, so I will have to mark this as missing documentation. Please provide the protocol spec if you would like for this request to be considered.
> 
> Check this newer documentation (chapter 15 and 16):
> https://secure.chamsys.co.uk/bugtracker/download_file.php?file_id=162&type=doc



I hope Companion intergrate QuickQ because osc is now supported and there is documentation. +1 from the Netherlands! :)

**Comment by mikethiessen21** [comment]
For the time being it is actually quite easy to use Companion's generic OSC module to control the QuickQ console.

**Comment by hallandrewjohn** [comment]
@mikethiessen21 or @tijjuuu Would you be able to post an example OSC message? I'm setting my QuickQ Rack set up this week and I'd love to use companion with it! If I could see an example message on one of your buttons I think I would be off and running!

**Comment by hallandrewjohn** [comment]
@josephdadams Also, renewed interest - I'd love a module for this. 
Manual with UDP and OSC commands:
file:///Users/livestream/Downloads/QuickQ_v6_Manual%20(2).pdf
![Screen Shot 2021-09-05 at 10 01 49 AM](https://user-images.githubusercontent.com/25835863/132131558-699afc79-15cd-42b7-b750-a61c71f84d3f.png)
![Screen Shot 2021-09-05 at 10 02 52 AM](https://user-images.githubusercontent.com/25835863/132131559-a9529d05-8392-4ce0-b50a-6e76b85b63a6.png)

**Comment by mikethiessen21** [comment]
@hallandrewjohn

This example jumps to cue 2 on playback 2. I think I had some issues when I tried using cues numbered with decimals (2.1, for example).

![QuickQ OSC](https://user-images.githubusercontent.com/9453221/132144763-c63dcb67-3620-4f30-9faa-8a9fd5e02855.png)

**Comment by tijjuuu** [comment]
I only used triggering executes. Because of a bug of the chamsys os I had to give all other executes a "0" argument. Otherwise multiple scenes will be active at the same time. 

<img width="946" alt="Schermafbeelding 2021-09-06 om 10 22 34" src="https://user-images.githubusercontent.com/79751943/132184915-c2deb968-533d-433e-9ac2-203de44c7001.png">

**Comment by lxdesigner** [comment]
I'm not able to find the module for QuickQ in V3.0?

**Comment by josephdadams** [comment]
No one said there was one

**Comment by lxdesigner** [comment]
Ok....are you able to create one or do we need to continue to use the generic?

**Comment by bryce-seifert** [comment]
For now you will need to continue using the generic module.

This is an open source community, so anyone can create a module.

I'd be happy to work on this, and can definitely expedite the process if one or two people were willing to sponsor the development

**Comment by lxdesigner** [comment]
Can you give me an estimate of total sponsorship expected?

**Comment by bryce-seifert** [comment]
@lxdesigner I don't have a specific amount in mind, but feel free to see some suggestions on [my sponsor page](https://github.com/sponsors/bryce-seifert). The protocol seems relatively simple to work with, so this will probably take around 3-5 hours to create and fully test. But really anything helps!

**Comment by lxdesigner** [comment]
Sonser in advance - or how does this work?

**Comment by bryce-seifert** [comment]
@lxdesigner If your comfortable doing that, it would certainly help encourage development! Regardless, I'll try and knock this out at some point and any support is appreciated.

**Comment by bryce-seifert** [comment]
@lxdesigner Are you on the Bitfocus [Slack](https://bitfocus.io/api/slackinvite)? If we want to continue the conversation there, I can get you an early alpha version of the module to try out soon. Email also works if that's easier!

**Comment by bryce-seifert** [comment]
@lxdesigner @cjmillet @mikethiessen21 @hallandrewjohn @tijjuuu  

The Chamsys QuickQ module should now be available for use in the [latest Companion beta builds](https://user.bitfocus.io/download/companion).

Feel free to give it a try, and report any issues you encounter in the [module repo.](https://github.com/bitfocus/companion-module-chamsys-quickq/issues)

And if you find the module useful, I'd appreciate if you consider [sponsoring me on GitHub](https://github.com/sponsors/bryce-seifert) for my time spent on it. Any amount is appreciated!

**Comment by Steffielight** [comment]
Hi @bryce-seifert ,

I have A problem with the lightingcontroller quick dmx and companion. I try a lot of hours but i cant get off the BPM signal from companion off. 

Some people talk about BPMcounter file and edit a line out to turn off BPM, but I have not a BPM counter file. I see only index.js.

Now companion send standard a BPM signal to the lightingcontroller software. I use BPM signal from other software. Now I would like to turn it off. How I can turn off from companion? It is a amazing software but I cant turn off the BPM. 

Please help! Will be nice!

![Schermafbeelding 2024-04-13 112732](https://github.com/bitfocus/companion-module-requests/assets/165475805/604f1ebf-5719-4119-bb29-d7a64627a253)
