### ISSUE TITLE
Faithlife Proclaim Software (similar in function to Renewed Vision ProPresenter)

### ISSUE THREAD

**Issue by vrelectronics** [bitfocus/companion-module-requests#240]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
@vrelectronics thanks for your request. For the future, please include more information when you make a request. Just the title is not enough. You can read more about what we are expecting here: https://github.com/bitfocus/companion-module-requests/blob/master/README.md

Now, specifically for your request about Proclaim: As far as we know, there is no external API available within Proclaim to allow Companion to control it. It does support MIDI control, so you could consider using any of the "midi middleman" type approaches available. A few options would be:
* qlab module with qlab sending MIDI
* midi-relay module with the midi-relay server sending MIDI
* generic OSC module with a receiving OSC to MIDI program (OSCulator, for example)

You can also try reaching out to Faithlife and see if they have other ideas or approaches for external control, possibly even making an API available.

I hope this helps! Until an API is available, a module specifically for Proclaim is not possible.

**Comment by vrelectronics** [comment]
Appreciate the quick response.
Just became a member a few minutes ago, but I will try to learn the system better.
I will check out the ‘Midi’ option.
Thanks again,

Doug

**Comment by josephdadams** [comment]
@vrelectronics let me know how I can help. I just helped another church get Proclaim working with midi relay and Companion.

**Comment by vrelectronics** [comment]
Interesting, thanks Joseph.
I am new to the Midi application, but I will tell you want I want to accomplish.

We have a 15 button Streamdeck and are using OBS with Proclaim.
I can change scenes (cameras) in OBS on the Streamdeck, and I was also hoping to be able to advance the Proclaim slides.

As an aside, one interesting thing I also setup on the Streamdeck is PTZ preset buttons for the HIK IP cameras.
And it works in the background so focus does not get taken away on the pc.
I tested it setup using Streamdeck hotkeys, but Proclaim needed to be in focus on the pc for that to work.
I’m hoping the slide advance can be done with Proclaim minimized.

Doug

**Comment by josephdadams** [comment]
Yes, you should be able to trigger Proclaim via MIDI with it minimized.

**Comment by josephdadams** [comment]
@vrelectronics https://techministry.blog/2020/06/25/walkthrough-using-a-streamdeck-and-midi-relay-to-control-faithlife-proclaim/

**Comment by josephdadams** [comment]
@vrelectronics did this help?

**Comment by vrelectronics** [comment]
Haven't tried yet but thanks for asking.
Hopefully by the weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vrelectronics** [comment]
I seem to be unable to create an account at Bitfocus to get Companion, not sure if they are checking their emails lately.
I was able to get it from Github but at a loss as to how to get it to run after downloading it.
Any ideas?

Doug

**Comment by haakonnessjoen** [comment]
@vrelectronics If you have signup issues, please use the contact form on the website to get help :)

**Comment by josephdadams** [comment]
@vrelectronics did you get your signup issue resolved?

**Comment by vrelectronics** [comment]
Yes, I was able to sign up successfully.
Unfortunately, the Midi software and the Companion software were both erratic on my machine.
I had to abandon the project and am researching other methods.

Doug

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by josephdadams** [comment]
Sorry to hear that. Best of luck.
