### ISSUE TITLE
[Module Request] aten Matrix Switch via serial interface

### ISSUE THREAD

**Issue by lighthousebulb** [bitfocus/companion-module-requests#241]
I would love to see support for [aten 4x4 4K HDMI Matrix Switch VM0404HA](https://www.aten.com/global/en/products/professional-audiovideo/video-matrix-switches/vm0404ha/)

Would be convenient to control the switch directly through companion.
The device can be controlled through a serial interface, with a few simple commands, have a look at the [product manual](https://assets.aten.com/product/manual/vm0404ha_um_w_2020-02-12.pdf).

**Comment by josephdadams** [comment]
@lighthousebulb since this device does not have an ethernet port, Companion can not directly control it. You would have to use a device in between like the GlobalCache iTach.

**Comment by lighthousebulb** [comment]
You could use a simple USB to RS232 Adapter, so that companion just needs to talk to a serial device.

**Comment by lighthousebulb** [comment]
btw. you added the Tag "Missing documentation"...
The [manual](https://assets.aten.com/product/manual/vm0404ha_um_w_2020-02-12.pdf), starting at Page 20, describes the simple serial interface communication.

**Comment by josephdadams** [comment]
@lighthousebulb Thanks for your feedback.

**Comment by NoahCallaway** [comment]
I'm starting development of a module for this but using the Telnet interface. Should work for a few of the ATEN Matrix devices.
[https://github.com/NoahCallaway/companion-module-aten-hdmi-matrix]
