### ISSUE TITLE
Magnimage MIG-680 4K Seamless Switcher.

### ISSUE THREAD

**Issue by MatthewKirby5** [bitfocus/companion-module-requests#243]
Looking for a module for the Magnimage MIG-680 4K Seamless Switcher. Or possibly any advice or tips on how to use UDP to send commands to the device.

I would like it to be able to Take cut and Take fade as well as load presets (as seen in image attached)

The protocol information can also be seen on the Image attached (UDP, Hexadecimal, Length 39 (0x27))

Product page: http://www.magnimage.com/article/detail/440
Manual Download: https://magnimage-hk-file.oss-cn-hongkong.aliyuncs.com/Upload/Upgrade/User%20Manual/MIG-680%20User%20Manual-V1.0.pdf

![IMG_20200701_092305](https://user-images.githubusercontent.com/67643380/86215905-7f57fb80-bb7d-11ea-892b-474054315845.jpg)

**Comment by EventReplay** [comment]
Please have a good look at the well written readme for requesting a module here: https://github.com/bitfocus/companion-module-requests/blob/master/README.md

The more info you provide will give you a better chance that a developer will take on your request.

https://packetsender.com/

**Comment by MatthewKirby5** [comment]
I have updated my original post. I hope this is all the information that is needed. If there is anything else please can you advise me. 

Thanks!

**Comment by EventReplay** [comment]
@MatthewKirby5 the info provided is a limited set of commands and you really need to know the command structure to fill in the blanks. The full command protocol info is what's needed to get you the functions I guess you want.
What functions do you want to control via companion?
Did you have a look at https://packetsender.com/ to try those commands?

**Comment by EventReplay** [comment]
You could also try the generic tcp-udp module in the short term to test those commands in comoanion.

**Comment by MatthewKirby5** [comment]
> You could also try the generic tcp-udp module in the short term to test those commands in companion.

what would I need to type into the command section and what would the "Command End Character" be. Sorry I am a bit new to all of this.

**Comment by MatthewKirby5** [comment]
> @MatthewKirby5 the info provided is a limited set of commands and you really need to know the command structure to fill in the blanks. The full command protocol info is what's needed to get you the functions I guess you want.
> What functions do you want to control via companion?
> Did you have a look at https://packetsender.com/ to try those commands?

Again, I am very new to all this so I am not sure what you would need from packet sender and what I would need to do in packet sender.

**Comment by EventReplay** [comment]
In generic tcp-udp Did you have a % before your 2 digits to define it as a hex value?
Try this for Take Fade:
%ED%CB%28%48%00%01%01%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2A
End Char "None" I think.
Let me know if that works.

**Comment by MatthewKirby5** [comment]
I did that and no success. And everything else is setup correctly. I also tried using "/" instead of % and that didn't work either as well as all the end char options. I am seeing activity when I press the button on the streamdeck on the network switch I use so companion is outputting. I also am on V2.

**Comment by EventReplay** [comment]
> 
> 
> I did that and no success. And everything else is setup correctly. I also tried using "/" instead of % and that didn't work either as well as all the end char options. I am seeing activity when I press the button on the streamdeck on the network switch I use so companion is outputting. I also am on V2.

I wish I could say I was surprised! I'm currently working with a Magnimage 780H and having a nightmare.

You will need to somehow confirm that you can get those commands working. You should be able to use either packetsender or https://www.hw-group.com/software/hercules-setup-utility which is what I generally use.

My suggestion would be first to use hercules TCP client tab and see if it will accept a connection to the unit and what if any the response is.

**Comment by MatthewKirby5** [comment]
In PacketSender I am not entirely sure what I am supposed to be looking for. I have tried a few things and no results yet.

**Comment by EventReplay** [comment]
By rights you should simply have to enter IP of unit, port 61215 change dropdown to UDP and hit send
Try this for Take Fade: (Put in HEX input box obviously)
ED CB 28 48 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A
If no Fade then try adding 0A (Line Feed) to the end so:
ED CB 28 48 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A 0A
The image above has [0x27] which maybe means it requires 40 bytes, so if with 0A no Fade try 0D or 04

Unfortunatly UDP is fire & forget so I wouldn't expect anything back.

Double check the units IP, try to change it and reboot.

Thats about all I can suggest, The 780H uses TCP and a different port!

**Comment by MatthewKirby5** [comment]
So I tried all those variations in Packet Sender and no luck. I also tried them all again with a different IP on the unit and still no results.

Thanks for all the help!! It is really appreciated. 

[MIG 680 LOG.log](https://github.com/bitfocus/companion-module-requests/files/4883569/MIG.680.LOG.log

**Comment by eledtech1234** [comment]
i could get it to work on w4000 and newer dn9421 machine.

just copy the hex value from wireshark and add % before all digits (take care that in udp protocol there is „no ending“ added.

**Comment by e-benj** [comment]
Found all the Hex commands. Just not sure how to send them out of Companion

Take Fade
ED CB 28 48 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A

Take Cut
ED CB 28 48 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 29

Load Preset 

1
ED CB 28 48 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2A

2
ED CB 28 48 01 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2B

3
ED CB 28 48 01 01 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2C

4
ED CB 28 48 01 01 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2D

5
ED CB 28 48 01 01 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2E

6
ED CB 28 48 01 01 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2F

7
ED CB 28 48 01 01 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 30

8
ED CB 28 48 01 01 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 31

9
ED CB 28 48 01 01 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 32

10
ED CB 28 48 01 01 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 33

11
ED CB 28 48 01 01 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 34

12
ED CB 28 48 01 01 0B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 35

13
ED CB 28 48 01 01 0C 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 36

14
ED CB 28 48 01 01 0D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 37

15
ED CB 28 48 01 01 0E 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 38

16
ED CB 28 48 01 01 0F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 39

17
ED CB 28 48 01 01 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3A

18
ED CB 28 48 01 01 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3B

19
ED CB 28 48 01 01 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3C

20
ED CB 28 48 01 01 13 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3D

**Comment by e-benj** [comment]
Formatted for companion generic UDP module. Use None for command end character 

Take Fade
%ED%CB%28%48%00%01%01%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2A

Take Cut
%ED%CB%28%48%00%01%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%29

Load Preset 

1
%ED%CB%28%48%01%01%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2A

2
%ED%CB%28%48%01%01%01%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2B

3
%ED%CB%28%48%01%01%02%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2C

4
%ED%CB%28%48%01%01%03%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2D

5
%ED%CB%28%48%01%01%04%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2E

6
%ED%CB%28%48%01%01%05%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%2F

7
%ED%CB%28%48%01%01%06%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%30

8
%ED%CB%28%48%01%01%07%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%31

9
%ED%CB%28%48%01%01%08%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%32

10
%ED%CB%28%48%01%01%09%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%33

11
%ED%CB%28%48%01%01%0A%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%34

12
%ED%CB%28%48%01%01%0B%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%35

13
%ED%CB%28%48%01%01%0C%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%36

14
%ED%CB%28%48%01%01%0D%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%37

15
%ED%CB%28%48%01%01%0E%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%38

16
%ED%CB%28%48%01%01%0F%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%39

17
%ED%CB%28%48%01%01%10%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%3A

18
%ED%CB%28%48%01%01%11%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%3B

19
%ED%CB%28%48%01%01%12%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%3C

20
%ED%CB%28%48%01%01%13%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%3D
