### ISSUE TITLE
Companion Module for BSS BLU Processors

### ISSUE THREAD

**Issue by JFonte7834** [bitfocus/companion-module-requests#244]
I'm looking to see if anyone has created or is interested in creating profile for the BSS BLU processors.  All I am currently looking for is for Gain up and gain down control.

**Comment by MeestorX** [comment]
Do you have a link to the protocol documentation?
Are you willing to do the testing and feedback that's required to verify and help debug a new module with your BLU Processor? (You'll probably want to test with an un-installed processor)

**Comment by JFonte7834** [comment]
> Do you have a link to the protocol documentation?
> Are you willing to do the testing and feedback that's required to verify and help debug a new module with your BLU Processor? (You'll probably want to test with an un-installed processor)

I am more than willing to do the testing on a processor I have here for testing.  Here is what I have found about connecting third party controllers.


[Soundweb-London-Third-Party-Control.pdf](https://github.com/bitfocus/companion-module-requests/files/4853264/Soundweb-London-Third-Party-Control.pdf)

**Comment by MeestorX** [comment]
Correct me if I'm wrong, but it looks like the commands can be different depending on your layout. That is to say, each command string is specific to your layout.
If that's the case, then there's no point in making a custom module as the command string would need to be entered for each device and control.
If I am correct, then the best solution would be the generic TCP/UDP module. And it would only work for your specific layout on your specific device.

**Comment by JFonte7834** [comment]
Sounds like your right here.  Sorry I hadn't dug into it a little more.  I'll have to figure out the custom commands to have it control each one individually.  Thank you for helping out.

**Comment by tm1000** [comment]
See: https://github.com/bitfocus/companion-module-bss-soundweb
