### ISSUE TITLE
Minrray PTZ Cameras 10/20/30x NDI

### ISSUE THREAD

**Issue by socieboy** [bitfocus/companion-module-requests#245]
I found a very powerful camera for lower price that i think will be a good addition in the modules.
This camera works with visca, so i don't know if the current module for ptzOptics will work for this camera also?

https://minriglory.com/products-item/ndi-hd-camera-uv510a-series/

**Comment by josephdadams** [comment]
Have you tried it with any of the VISCA modules?

**Comment by socieboy** [comment]
I just tried and it worked with the ptzOptics Visca.
