### ISSUE TITLE
[Module Request] Singular.live cloud-/browser-based CG for live production

### ISSUE THREAD

**Issue by shaunus** [bitfocus/companion-module-requests#246]
Looking to control the software service singular.live (that's their URL), which provides cloud-/browser-based CG for live production, with NDI output supported. It's an extremely powerful tool that many may find attractive if there were Companion support.

What would I like to make it do from Companion?
Selecting data sources, e.g. pulling social comments, pulling scoreboards
Loading configurations for various scenarios
Refresh compositions (there are two parts to Singular -- the Composer app and a Controller app)
Changing transition types/durations
Create/load automated playlists
Essentially the goal/benefit here is being able to control the output of Singular from a hardware surface instead of clicking buttons inside a web browser.

Here's their developer documentation:
https://developer.singular.live/app-sdk/app-sdk-introduction/

Balte de Wit on Companion Facebook Group reports they are readily available to help people with integrations.

**Comment by josephdadams** [comment]
Is that separate from this? https://github.com/bitfocus/companion-module-singularlive-studio

**Comment by shaunus** [comment]
Hi Joseph

That does look like it might be the same thing. Although this doesn't come
up in the modules list for me:

[image: Support_-_Bitfocus_AS.png]

I also searched "singular" on Github, maybe I searched in the wrong place?
Please could you help me identify how I missed this in my search? I tried
my best to check it wasn't already supported! 😆

Thanks
Shaun

**Comment by shaunus** [comment]
<img width="1670" alt="Support_-_Bitfocus_AS" src="https://user-images.githubusercontent.com/7552001/86411129-02a64980-bc71-11ea-9e37-997357bd0257.png">

**Comment by josephdadams** [comment]
That list is out of date. Sorry! Go download the latest Companion 2.0 beta and let me know how that goes!

**Comment by shaunus** [comment]
Oh! Good to know, I thought it was a live list that auto updated hehe :D

**Comment by josephdadams** [comment]
We gotta get our docs updated! Need this rona to stop first!

**Comment by shaunus** [comment]
🤣🤣🤣🍻

**Comment by haakonnessjoen** [comment]
Actually. The list on the website is supposed to auto update, so thats a bug. I will check it out.

**Comment by shaunus** [comment]
Legend! Thanks, Håkon.
