### ISSUE TITLE
Shutdown on Lan

### ISSUE THREAD

**Issue by dvreezen** [bitfocus/companion-module-requests#247]
is it possible to add a shutdown on lan module to the Wakeup on lan module?

thnx!

**Comment by josephdadams** [comment]
What would be the purpose of this?

**Comment by dvreezen** [comment]
I'am triggering a bunch of NUC's to turn on and i would like to trigger them to turn off .

**Comment by josephdadams** [comment]
Is “shutdown on lan” a thing? WOL works by sending special network packets to a machine to boot it up. But I’m not aware of a reverse that is universal. @haakonnessjoen you want to chime in here?

**Comment by josephdadams** [comment]
@dvreezen I'm going to close this as a universal shutdown on LAN is not a feature I am aware of. Depending on your NUC OS though, you can probably send a remote command to shut it down.

**Comment by MarekPro1** [comment]
How it is going I would like it too, to shutdown some nuc's.
