### ISSUE TITLE
TCW181b - 8Ch Relay Module

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-module-requests#248]
Not sure if this request has already been made, I can't seem to find a list of previous module requests.

Would it be possible to have a module to control a TCW181b 8 channel relay. The documentation for relay is here:

[tcw181b-cm-ethernet-digital-io-module-user-manual-r4.7.pdf](https://github.com/bitfocus/companion-module-requests/files/4902623/tcw181b-cm-ethernet-digital-io-module-user-manual-r4.7.pdf)

Thanks for your consideration!

**Comment by McHauge** [comment]
@jonhug82 If you look at the module created for request be #101 how does that look? Might do the same purpose with that relay. Haven't look at the documentation from both yet.

**Comment by josephdadams** [comment]
@McHauge I glanced and it seems different from the Sainsmart, although the boards look very similar. I think the TCW has some kind of XML based protocol.

**Comment by McHauge** [comment]
@Jonhug82 hi again, what actions are you looking for in this, just a simple action for on/off/toggle or do you need the pulse function?

**Comment by Jonhug82** [comment]
@McHauge - Hi I am looking for the on off and toggle function. It would be amazing if I could also get feedback from the relay to know if it’s on or off. Thank you

**Comment by McHauge** [comment]
@Jonhug82 Hi, I'm getting pretty close to having a complete module for you, expecting to be done tomorrow (Friday), would you have a chance to test it with a real unit, any time soon?

also just for as a note, it will include all HTTP actions in the API, Variables and feedback.

-McHauge

**Comment by McHauge** [comment]
@Jonhug82 Hi did you do any testing on this yet?

**Comment by Jonhug82** [comment]
Hi @McHauge Thank you so much for creating the module! Sorry with all of our additional Christmas services I ran out of time to test the module. I'm planning to test this week and will let you know how it works. 
Jonathan

**Comment by McHauge** [comment]
no worries, merry Christmas!

**Comment by Jonhug82** [comment]
Merry Christmas to you too.

I had a quick play with the module this afternoon, the feedback and variables seem to work great, however when I try and change a relay state the button press crashes companion.

**Comment by McHauge** [comment]
hmm, great with the feedback and variables, but do you have a picture of the java error,  instance setup and the button setup.

**Comment by Jonhug82** [comment]
Please see image of button and instance setup, I don't get a java error that I can see. I have noticed that the module is connected to the relay it crashed instantly and if not it crashes a short while later

![Relay Button](https://user-images.githubusercontent.com/67643240/103276151-b0df4180-49bd-11eb-84a4-22bcc3349889.png)
![Instance Setup](https://user-images.githubusercontent.com/67643240/103276533-bbe6a180-49be-11eb-860c-a13550639842.png)

**Comment by haakonnessjoen** [comment]
He means a javascript error, not java error. But what do you mean by "crashes" then, if you do not receive an error?

**Comment by McHauge** [comment]
Yes of course, ups ment a javascript error not a java error 😂

But if you don't get a "crash" what are you referring to then?

**Comment by McHauge** [comment]
Also could you try it both with and without a feedback on the button

**Comment by Jonhug82** [comment]
I'm running companion on a Raspberry Pi, when I press a button with the control on it the stream deck stops functioning and I can't get to the web page until I restart companion.

Where can I find the java script error ?

**Comment by McHauge** [comment]
Could you test it on a windows or mac, that way the javascript error will fill the screen

**Comment by Jonhug82** [comment]
Sure, can test on a windows machine.

**Comment by Jonhug82** [comment]
Stupid Question I know, but how do I load the development modules into a windows environment ?

**Comment by McHauge** [comment]
you don't, you just install the test vision on my link

**Comment by McHauge** [comment]
or any other beta build with it included, you can only add modules to a Dev environment, not to a instalation

**Comment by Jonhug82** [comment]
Sorry still not sure how to download or run your dev version

**Comment by McHauge** [comment]
Sorry my bad, forgot to add the link, dohhh. Did not realise this until now, since you added it to you Raspberry Pi (those are basicly a dev envirement) normaly I make a post with a where and how description first. but I simply forgot.

Here is the link, what you do is, go grap the .zip file for the module you wan't to test, and run the Companion.exe. This will install a test version of companion on the pc. If you wan't to just test it and not do a perminent install, the go into the folder: win-unpacked and run the Companion.exe inside it.

[OneDrive](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)

**Comment by Jonhug82** [comment]
I have downloaded and run the file form your link, the feedback and variable work well but the control functionality does not work. There is a demo unit at 212.25.45.120 port 60084 username: admin password: admin if you would like to have a look at a running unit. Demo unit can be controlled here http://212.25.45.120:60084/login.htm

**Comment by McHauge** [comment]
@Jonhug82  Hi, thx for the "demo unit" it should be working now if you go ahead and download the new zip file. and you can report back

**Comment by Jonhug82** [comment]
Hi @McHauge I have tested the module with a local unit this morning and all works really well thank you for your time in writing this module. The digital input with the ability to trigger buttons is a fantastic addition too can already see many usages for this !

**Comment by McHauge** [comment]
Lovely, that's great to hear, I'll get it qued up for inclusion into the companion core. Expect it to be in the beta builds within a week or two :)

I'll close this request, for now, feel free to open it up again if needs be.
