### ISSUE TITLE
Module request : L-acoustics amp support over snmp

### ISSUE THREAD

**Issue by Pierremck** [bitfocus/companion-module-requests#276]
Hi
Could you add a module in ordre to control a LA4X amp by L-acoustics ? This amp support snmp control but L-acoustics doesn't give more info about that.

**What is it supposed to be done :**
Functions available from third-party control systems using L-COM protocol or SNMP.
**Status information and monitoring (read only)** 
• amplified type
• current operating mode: standby, active
• full reporting of errors
• current input mode and status, fallback status
• current preset name, family, output names
• name of next available preset
• signal level / limit / clip
• front panel keys locked/unlocked
**Commands (write)**
• standby / wake-up
• input mode selection
• preset load
• mute/unmute, output gain control
• lock/unlock front panel keys
• output gain_

This list is from this document : https://www.l-acoustics.com/wp-content/uploads/2017/12/voice_alarm_system_integration_tb_en-1.pdf

I personnaly only want to command the mute/unmute.
I think I can send a http command with companion to node-red and node-red will send snmp command to the amp. If i can do this only with companion it would be great !

If you need more info don't mind asking. I can't give you the OID for the snmp protocole that L-acoustics use because I didn't find it online. I have ask L-acoustics about snmp but no response for now.

**Comment by Pierremck** [comment]
Hi
I have news from l-acoustics ! They send me some UDP commands to mute/unmute etc.
I give it to you, it might help someone :


Destination port UDP : 161 (SNMP)

Datagram :
POWER
SET Power Mode = ONLINE
30 2E 02 01 00 04 06 70 75 62 6C 69 63 A3 21 02 04 00 00 00 00 02 01 00 02 01 00 30 13 30 11 06 0C 2B 06 01 04 01 82 AD 06 01 04 01 00 02 01 01

SET Power Mode = STANDBY
30 2E 02 01 00 04 06 70 75 62 6C 69 63 A3 21 02 04 00 00 00 00 02 01 00 02 01 00 30 13 30 11 06 0C 2B 06 01 04 01 82 AD 06 01 04 01 00 02 01 02

GET Power Mode
30 2D 02 01 00 04 06 70 75 62 6C 69 63 A0 20 02 04 00 00 00 00 02 01 00 02 01 00 30 12 30 10 06 0C 2B 06 01 04 01 82 AD 06 01 04 01 00 05 00

Response if Power Mode == ONLINE
30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02 04 00 00 00 00 02 01 00 02 01 00 30 13 30 11 06 0C 2B 06 01 04 01 82 AD 06 01 04 01 00 02 01 01
Response if Power Mode == STANDBY
30 2E 02 01 00 04 06 70 75 62 6C 69 63 A2 21 02 04 00 00 00 00 02 01 00 02 01 00 30 13 30 11 06 0C 2B 06 01 04 01 82 AD 06 01 04 01 00 02 01 02
MUTE
SET output X = MUTED
30 30 02 01 00 04 06 70 75 62 6C 69 63 A3 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 0X 02 01 01
 
SET output X = UNMUTED
30 30 02 01 00 04 06 70 75 62 6C 69 63 A3 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 0X 02 01 02
 
Exemple:

SET output 2 = UNMUTED
30 30 02 01 00 04 06 70 75 62 6C 69 63 A3 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 02 02 01 02

GET output X mute state
30 2F 02 01 00 04 06 70 75 62 6C 69 63 A0 22 02 04 00 00 00 00 02 01 00 02 01 00 30 14 30 12 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 0X 05 00
 
Response if output == MUTED
30 30 02 01 00 04 06 70 75 62 6C 69 63 A2 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 0X 02 01 01
Response if output == UNMUTED 
30 30 02 01 00 04 06 70 75 62 6C 69 63 A2 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 0X 02 01 02



I tried to send a command with Generic UDP module but didn't managed to get it done. 
I tried that in the command section: %hh 30 30 02 01 00 04 06 70 75 62 6C 69 63 A3 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 01 02 01 01
I don't really know what end message to use (\r, \n, \r\n, \n\r or none)

Do you think you can create a specific module or i have to try more with UDP generic module ?

**Comment by istnv** [comment]
> I tried to send a command with Generic UDP module but didn't managed to get it done.
> I tried that in the command section: _%hh 30 30 02 01 00 04 06 70 75 62 6C 69 63 A3 23 02 04 00 00 00 00 02 01 00 02 01 00 30 15 30 13 06 0E 2B 06 01 04 01 82 AD 06 01 06 01 01 04 01 02 01 01_
> I don't really know what end message to use _(\r, \n, \r\n, \n\r or none)_

To try these commands...
In the generic UDP module, use `none` for the end message.
For the command `%hh` is the example of how to send hex:
Add `%` to every hex pair in your command like this:  `%30%30%02%01%00`...

**Comment by Pierremck** [comment]
Thanks for your reply
With a `%` before each number it get me a "Malformed packet SNMP" with wireshark. Why ?

**Comment by istnv** [comment]
I can only help with the UDP and Hex, I am not familiar with SNMP. Check for your characters are correct in the command.

**Comment by Pierremck** [comment]
After doing some tests with Companion with a L-acoustics engineer, I noticed that the generic Tcp-Udp module alters the command as follows:

 Original order

 30 2E 02 01 00 04 06 70 75 62 6C 69 63 A3 21 02 04 00 00 00 00 02 01 00 02 01 00 30 13 30 11 06 0C 2B 06 01 04 01 82 AD 06 01 04 01 00 02 01 01
 Resulting command
 30 2E 02 01 00 04 06 70 75 62 6C 69 63 C2 A3 21 02 04 00 00 00 00 02 01 00 02 01 00 30 13 30 11 06 0C 2B 06 01 04 01 C2 82 C2 AD 06 01 04 01 00 02 01  01

 We see that a byte of value 0xC2 is added in front of each byte whose value is strictly greater than 0x7F (i.e. 127) (in this case the values ​​0xA3, 0x82 and 0xAD).
 As a result, the SNMP packet is indeed malformed.
 I have no idea why this is happening.  However, the source code of the generic Tcp-Udp module does not seem to do anything other than apply the unescape () JavaScript function on the command (https://github.com/bitfocus/companion-module-generic-tcp-udp/  blob / master / index.js).

**Comment by istnv** [comment]
That is an encoding problem. utf-8 'expands' characters over 0x7F to that 2 byte sequence.

**Comment by Pierremck** [comment]
So what can I do ? Can the generic udp module be updated with the posssiblity to change the encoding ?
Do you think a module can be created to control the l-acoustics amps with those commands ?

**Comment by istnv** [comment]
That is a strange problem. I looked at the module and I do not see where the UDP module is altering the encoding.
A custom module would be better.

**Comment by Pierremck** [comment]
What does it need to create a custom module ? Did the commands I send are enough?

**Comment by Pierremck** [comment]
Just for the info : 
I find a way to do what I what. Companion send a UDP command to Node-Red and then Node-Red send a snmp command and that working ! 
Sadly i can't do it only with Companion because it doens't have a SNMP module...

**Comment by dronenb** [comment]
I would like to reopen this thread. I've seen that there's a companion-module-generic-snmp module, but it doesn't seem to be in the latest builds. From decoding these UDP strings in this thread, it seems as though these LA4X amplifiers use SNMP v1 with a community string of public. The OID for the power mode is 1.3.6.1.4.1.130.173.6.1.4.1.0, the OID for the output mute is 1.3.6.1.4.1.130.173.6.1.6.1.1.4.x where x is the output number.

**Comment by jejehamers** [comment]
Hello,
I've been inverstigating a bit on this topic :

Tested the following commands using the generic Tcp module.
Target ip : amplifier ip
Target port : 161 (snmp port)
Connect with TCP/UDP : UDP

Tested successfully these commands :
Go standby :
%30%2E%02%01%00%04%06%70%75%62%6C%69%63%A3%21%02%04%00%00%00%00%02%01%00%02%01%00%30%13%30%11%06%0C%2B%06%01%04%01%82%AD%06%01%04%01%00%02%01%02

Wakeup :
%30%2E%02%01%00%04%06%70%75%62%6C%69%63%A3%21%02%04%00%00%00%00%02%01%00%02%01%00%30%13%30%11%06%0C%2B%06%01%04%01%82%AD%06%01%04%01%00%02%01%01

Mute one : 
%30%30%02%01%00%04%06%70%75%62%6C%69%63%A3%23%02%04%00%00%00%00%02%01%00%02%01%00%30%15%30%13%06%0E%2B%06%01%04%01%82%AD%06%01%06%01%01%04%01%02%01%01

Unmute one : 
%30%30%02%01%00%04%06%70%75%62%6C%69%63%A3%23%02%04%00%00%00%00%02%01%00%02%01%00%30%15%30%13%06%0E%2B%06%01%04%01%82%AD%06%01%06%01%01%04%01%02%01%02

All of these using command end character : None

I still have to check if there is an answer to the get commands.

Would it be possible to get a module going with these infos ?

Thanks ;)

**Comment by danclarkau** [comment]
Pretty keen for an L-Acoustics module also..

**Comment by phillipivan** [comment]
L'Acoustics amp module via http (not snmp) is being developed. SNMP would only be required for devices on old firmware. For these old devices consider using the `generic-snmp` module if you know the necessary OIDs.
