### ISSUE TITLE
farrago sound triggering support mac

### ISSUE THREAD

**Issue by rexluna** [bitfocus/companion-module-requests#278]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
@rexluna I am closing your request.
* no documentation provided
* no use cases or desired actions listed

Please be more diligent in the future when making requests. You may re open this when you’ve provided the necessary information.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-requests/blob/master/README.md

**Comment by rexluna** [comment]
I am un clear as to what documentation you need. 

Farrago is a sound triggering app
https://rogueamoeba.com/farrago/

i would like to press a button on a stream deck and have it trigger that sound.

**Comment by josephdadams** [comment]
Farrago will need a network protocol or access mechanism for Companion to control it. Ask Rogue Amoeba for this if they have it. Otherwise you might have some options like MIDI or hornet control, which wouldn’t be custom modules.
