### ISSUE TITLE
Shure Microflex Wireless + P300-IMX Presets

### ISSUE THREAD

**Issue by CrimPro** [bitfocus/companion-module-requests#286]
**Describe the feature**
• Companion Preset control for Shure Microflex Wireless Access Point Control ([MXWAPT2](https://www.shure.com/en-US/products/wireless-systems/microflex_wireless/mxwapt2)/4/8)
• Companion Preset control for Shure P300-IMX conference processor ([P300-IMX](https://www.shure.com/en-US/products/mixers/p300))

**Is this platform dependent (windows, mac, ..)?**
Currently controlled from Flash-based browser app, P300-IMX control software also on Windows.
Most features can be controlled or monitored via command strings

**If documentation is required to implement, do you know where to find it?**
• [MXWAPT Command Strings](https://pubs.shure.com/command-strings/MXW/en-US)
• [P300-IMX Command Strings](https://pubs.shure.com/command-strings/P300/en-US.pdf?_ga=2.247590599.13239051.1601310310-306298782.1601065474)(https://pubs-api.shure.com/file/259491)

**Usecases**
• Recording/Archiving multiple conference rooms from a central control location.  Mic and processor changes are often required live, and using a browser-based software is cumbersome.  Being able to control gains, mutes, seeing battery status, seeing signal feedback would be incredibly useful.

**Comment by CrimPro** [comment]
> **Describe the feature**
> • Companion Preset control for Shure Microflex Wireless Access Point Control ([MXWAPT2](https://www.shure.com/en-US/products/wireless-systems/microflex_wireless/mxwapt2)/4/8)
> • Companion Preset control for Shure P300-IMX conference processor ([P300-IMX](https://www.shure.com/en-US/products/mixers/p300))
> 
> **Is this platform dependent (windows, mac, ..)?**
> Currently controlled from Flash-based browser app, P300-IMX control software also on Windows.
> Most features can be controlled or monitored via command strings
> 
> **If documentation is required to implement, do you know where to find it?**
> • [MXWAPT Command Strings](https://pubs.shure.com/command-strings/MXW/en-US)
> • [P300-IMX Command Strings](https://pubs.shure.com/command-strings/P300/en-US.pdf?_ga=2.247590599.13239051.1601310310-306298782.1601065474)(https://pubs-api.shure.com/file/259491)
> 
> **Usecases**
> • Recording/Archiving multiple conference rooms from a central control location. Mic and processor changes are often required live, and using a browser-based software is cumbersome. Being able to control gains, mutes, seeing battery status, seeing signal feedback would be incredibly useful.

**Comment by josephdadams** [comment]
@krocheck what is already supported here? The P300 is part of the shure-dsp, yeah?

**Comment by krocheck** [comment]
p300 would be part of shure-dsp, but there's no timeline for completing that module at this time.

Microflex is supported in shure-wireless, though the APT's aren't listed as models, only the 4 and 8 channel receivers.  Those may work to get you going, though MXW support has never been tested so it may be buggy.

**Comment by dnmeid** [comment]
Both devices are available at their modules
