### ISSUE TITLE
Faithlife Proclaim

### ISSUE THREAD

**Issue by RobbieBott** [bitfocus/companion-module-requests#295]
I would love to see a module that would allow the ability to control Faithlife's Proclaim. 

https://proclaim.faithlife.com

**Describe the feature:**
Basically a control for Proclaim like what the ProPresenter module does.

**Is this platform dependent (windows, mac, ..)?**
Runs on Windows and macOS

**If documentation is required to implement, do you know where to find it?**
No

**Usecases**
Would allow the control of Proclaim to navigate inside the presentation much like you can with the ProPresenter module.

**Comment by josephdadams** [comment]
Go take a look at #240 to see some possible methods for control. There’s a link there to a tutorial on how to do it. I’m closing this since there still isn’t a native protocol for Proclaim.
