### ISSUE TITLE
Module Request: Christie Roadster HD18K

### ISSUE THREAD

**Issue by JJAmmons** [bitfocus/companion-module-requests#3]
Some of the existing Christie control works with my Roadster HD18K projectors.  Would love to have Channel selection control though.  (This is what sets up the parameters of the input signal.  Different than Input selection.)

Also LAMP Changed command - Not sure how it would handle the numeric entry required.  It says it wants the S/N but for example - in my case - I just use a date since I use revamped housings.  Might could just automatically insert current date.

Also, saw that it was being worked on in some other threads but also look forward to instance feedback for Power On and Lamp Hours.

http://www.qed-productions.com/downloads/christie/serial-communications.pdf

**Usecases**
This would be particularly useful for basic power on/off, Input, Channel Select and Lamp Change since the Java used in the web interface is so old that I have to keep a couple of my computers running Firefox with old Java in order to access the 3 projectors I use.  I'm sure others have run into the same issue as the projectors remain in use in fixed installations and touring use.

**Comment by McHauge** [comment]
@PerRoine How much does the "Christie pj" module support, might be a reason to make a V2.0 of the module?

**Comment by McHauge** [comment]
@JJAmmons Think I got most of the commands updated and included, in the Christiepj module. +40 new commands but none with feedback yet, also still need to add presets.

If you could run a test with the current setup that would be awesome, you can find a compiled test build at this link: [https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by McHauge** [comment]
Updated the module, now with the 40+ commands, feedback for some options, and presets. There is a build available for testing at the link above. It should also be included the core and available in new V2.0 builds

**Comment by JJAmmons** [comment]
Andreas,

Thanks for your work on adding commands to this module!  Unfortunately, subsequent to my original request for more commands, we have replaced these Christie projectors with ones from another manufacturer so I no longer have the ability to participate in the testing process for these updates.  I do apologize.  The replacement of the projectors happened quickly and unexpectedly.

**Comment by McHauge** [comment]
think we can close this after as for now it is included in v2.0 and even though there is no testing we can take it from there.
