### ISSUE TITLE
Bitfocus Companion

### ISSUE THREAD

**Issue by jeffreylsoffer** [bitfocus/companion-module-requests#304]
Hello,

I would love to be able to control a companion instance on another computer from my companion instance.
Right now, I simply do this by using the Generic TCP module and use the commands mentioned in the "Settings" panel on the GUI interface. I plan on port-forwarding 51234 using a VPN on the remote computer. 

But since I get a huge 'IMPORTANT MESSAGE' when i add a Generic TCP/UDP module, I'd thought i'd submit this request. I'd also love to get feedback passed along, which it currently doesn't as this is a 1-way street right now. 

I don't think I need to include the protocol information since its right in the GUI, but let me know if you need anything else!

**Comment by jeffreylsoffer** [comment]
@josephdadams should I move this to the main repo? Sorry not sure what to do since this request is kind of meta

**Comment by josephdadams** [comment]
“Satellite” capability has been requested, and we have discussed it. There’s a few different methodologies in use right now where people do it with the current releases. One person even forked Companion and made a remote option. So it’s definitely on the list. If I can find any of the issues that mention it specifically, I can tag them here and we can decide whether or not to keep this open.

But yeah it’s definitely meta.

**Comment by jeffreylsoffer** [comment]
I messed around a bit more with using the generic http module. I almost forgot that was an option (seems like it's not listed under the remote control instructions in settings but it IS listed as a "hint" under each button. I'm thinking port forwarding the main GUI interface port is a better move here. So, I think I have a solution to what I'm doing, but definitely wasn't super easy to work through, so a dedicated module could be nice that basically lists this out cleaner.

**Comment by jpooley-hearst** [comment]
I second this request... currently using Generic HTTP and it works great!

**Comment by dnmeid** [comment]
This request is covered with Companion Cloud, please direct any further requests to the devs of cloud.
