### ISSUE TITLE
DiGiCo S Series

### ISSUE THREAD

**Issue by digicodan** [bitfocus/companion-module-requests#308]
Your current DiGiCo OSC module appears to be specific to SD Series. The S Series consoles have a different command set. Would love to see this implemented. Happy to assist with providing the commands

**Comment by josephdadams** [comment]
@JeffreyDavidsz should the DiGiCo S Series compatibility be added to the existing module, or do you want a new module?

**Comment by digicodan** [comment]
Probably best split into a new module.. the existing one would need renaming to SD / Quantum

**Comment by JeffreyDavidsz** [comment]
We can change naming of the module and support more desk in one module. The command structure should be more or less the same though. If you can share a typical action/command I can take a look

**Comment by digicodan** [comment]
Ah that would work. There are 3 snapshot specific commands for S Series to implement, as below

/digico/snapshots/fire    and user can send integer value for the snapshot number
/digico/snapshots/fire/next
/digico/snapshots/fire/previous

Thx

**Comment by JeffreyDavidsz** [comment]
To check, other commands work? What I did now when you select the S-series than the commands change only for those options. (the action dropdown populates with different actions). Or will only these 3 actions work?

**Comment by digicodan** [comment]
more commands are coming to S Series, but at this point in time, we have only released these 3 snapshot related commands to users.

**Comment by JeffreyDavidsz** [comment]
Ok so remove the other actions from the list when selecting S-series?

**Comment by digicodan** [comment]
yes i think that's best. When we release more commands for S Series we can revisit this if it looks like there is a demand. thanks

**Comment by JeffreyDavidsz** [comment]
It's in a newer build as we speak
