### ISSUE TITLE
Avipas AV-1082w

### ISSUE THREAD

**Issue by oran6191** [bitfocus/companion-module-requests#313]
My church has an Avipas AV-1082w, and companion doesn't seem to support it. It would be great if this could become a possibility, since we are a small church and can't afford to get a new camera.

**Comment by josephdadams** [comment]
I noticed you didn’t provide any documentation for your device. So I googled it. It supports the VISCA over IP methods. Please try ALL of the various VISCA modules for other device vendors and report back on whether or not any of them work. Start with Sony Visca.

**Comment by oran6191** [comment]
I'm pretty new to this, we have it connected over USB. Will VISCA work over USB or does it need to be connected over Ethernet?

**Comment by josephdadams** [comment]
Ethernet

**Comment by josephdadams** [comment]
Did you try one of the other VISCA modules?

**Comment by josephdadams** [comment]
#1045

**Comment by mwb9aa** [comment]
As an update from someone else who uses an Avipas camera, the Sony VISCA module works. The thing I can't seem to change without using the generic http module is the framerate (e.g. 60 fps to 30 fps).

**Comment by witeshadow** [comment]
Sony VISCA module works but does not support as many presets as AVIPAS supports.
