### ISSUE TITLE
Livemind Recorder

### ISSUE THREAD

**Issue by dbiser99** [bitfocus/companion-module-requests#315]
I was just going to do this manually, at least for testing purposes, and saw the notice about getting new modules added...Livemind has recently added TCP (and HTTP, but it sounded like that was still in progress to some extent) remote control of their recorder program. They sent me the following link to the TCP-API documentation: https://livemind.tv/docs/recorder/tcp-api/

Not sure how much makes sense (most all of it would be nice) but at the very least start & stop records and start & stop listening to audio please.

Thanks

**Comment by McHauge** [comment]
hmm, I get a timeout if I try and visit the link: "504 Gateway Time-out", might just be on my end

**Comment by dbiser99** [comment]
The link to the API? I just tried it and it's working fine for me. I suppose I can try to cut and paste it if you still have trouble. (They don't have a downloadable version that I've found.)

**Comment by McHauge** [comment]
hmm, it works now, lol -.-

**Comment by ChgoChad** [comment]
I recently incorporated Livemind Recorder into my workflow and have started development of a module for Companion.   The TCP XML API from Livemind is pretty simple (there are only a few commands) so it should not take long to implement this module and get it approved and added to the repository.

**Comment by jibberjabberish** [comment]
I too am looking forward to an integration with livemind recorder.

**Comment by ChgoChad** [comment]
There is a module for Livemind Recorder.  It has not been merged yet by the core dev team.  I can generate a custom build that includes the module.  Please send me your email address and I will send the custom build to you.

**Comment by ChgoChad** [comment]
This module has been created and merged into the core build. This module request can be closed.
