### ISSUE TITLE
AVIShop "HDBaseT HDMI Matrix 8x8 4K"

### ISSUE THREAD

**Issue by knelsonkc** [bitfocus/companion-module-requests#326]
**Describe the feature**
This new feature will control the AVIShop "HDBaseT Matrix 8x8 4K" by changing one or more of the eight inputs and direct it to one or more of the eight outputs. 

AVIShop is the brand label to my machine but the internals are used by Purelink and at least one other. 

**Is this platform dependent (windows, mac, ..)?**
Not that I'm aware. 

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

To implement:
I've used Generic HTML "GET" to make this work so far. 
http://localhost/cgi-bin/submit?cmd=hex(*hexcode*)

But, there may be a better way. I've included a javascript file but the hex code is all I've been able to make work so far. 

[Matrix Hex Codes  - Sheet1.pdf](https://github.com/bitfocus/companion/files/5691445/Matrix.Hex.Codes.-.Sheet1.pdf)
[processor (javascript).pdf](https://github.com/bitfocus/companion/files/5691446/processor.javascript.pdf)

**Usecases**
The stream deck can change inputs on multiple hdmi outputs with the push of a button. Currently, the online interface requires one click per change. The Stream Deck could control multiple changes when needed. 
I'm using the matrix in a church setting with three sanctuary computers. I'm hoping to be able to show two different inputs on the front screens when needed. For instance, the left screen could show a video while the right screen would show lyrics. Or, the rear screen can show a confidence monitor only when needed during a service.

**Comment by McHauge** [comment]
@knelsonkc Hi, a basic module with the command listed and presets for them should be simple enough, I'll give it a look when I get home. From what i can see in the list, feedback would not be an option.

**Comment by McHauge** [comment]
yes, I did guess the IP was wrong xD, but if you have the  Hex codes, and maybe the responses for it too, that would be nice, that way I can at least see what I can do with it.

**Comment by knelsonkc** [comment]
[Matrix Hex Submit and Query Codes.pdf](https://github.com/bitfocus/companion-module-requests/files/5697654/Matrix.Hex.Submit.and.Query.Codes.pdf)


[Matrix WebUI.zip](https://github.com/bitfocus/companion-module-requests/files/5697670/Matrix.WebUI.zip)


I've added all the Web UI files that I have access to. Perhaps there's something there that will be helpful. I've also updated the Hex codes to show the query response as per the console. It appears that it repeats with a hex response per the output status. 

I appreciate already the attention given to this. It's nothing urgent but it's great to see that something could be done towards this. I'm sorry I'm not of better help to solve this on my own. Thank you for sharing your knowledge and expertise.

**Comment by McHauge** [comment]
just for clearfication, since normaly hex is send as hex, with a 0x infront for it to be interbiet as hex, is it correctly asumed, that this is not the case here, and that it's just send in ASCII form but with the resemblance of HEX values in text, so like this: 
http://Target-IP/cgi-bin/submit?cmd=hex(a5,5b,06,01,f0,00,00,00,00,00,00,00,09)

**Comment by knelsonkc** [comment]
That's correct. In the Generic HTTP module I set the base url as "http://192.168.1.16/cgi-bin/submit?cmd=hex" and the URI as "(a5,5b,02,03,02,00,01,00,00,00,00,00,f8)" with the parentheses included and it works.

**Comment by McHauge** [comment]
@knelsonkc  Hey, just completed a test version of this module with actions, but no presets yet.

You can get a test build of companion v2.02 (for windows) with the module from the link below, it would be awesome if you could test if the module and all the actions work as expected. Then we can add it as completed and include it in the main build.

Just download the file: 2020-12-16-Companion-2.2.0-AVIShop.zip
Download link: [OneDrive](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)

**Comment by McHauge** [comment]
Updated the zip file it now includes presets.

**Comment by knelsonkc** [comment]
@McHauge This is incredible! I'm still testing and I'll give my updates below. But, I think I owe you a beer or whatever you like to drink in Denmark for making this happen so quickly! Let me know how to make that happen. 

Issues so far:
Companion crashed when first testing. It would happen when assigning Input 2 to Output B and testing the action. It crashed 5-6 times in a row and then I tried other inputs/outputs. After trying other In/Outputs I couldn't replicate the problem again even on 2>B.

I tested by assigning the same input to every output. The most concurrent input to output changed the hardware seems to be able to handle consistently is six. This will be helpful in knowing when creating presets. There are use cases where assigning the same Input to ALL outputs will be wanted. The changes will need to be staggered to make sure the hardware can register the command. 

I didn't see any presets preloaded. But again, presets to send an INPUT to ALL outputs would be helpful. 

EDID works until any of the 4k options. I double checked and I can make it happen within the webui so it does work. But, Companion couldn't make the change. 

Beep works. 
System on and off works. 
Reboot works. 

Restore should be renamed "Factory Reset" to match wording on the WebUI

Auto Set Format - I didn't see anything happen when I tested this action. 
---
Still to be added could be the ARC triggers for each input. 
---
Still to test are the EDID Copy actions.

**Comment by McHauge** [comment]
Quick question, did you do the testing on a clean setup, lot has changed since the release and the beta version s

**Comment by knelsonkc** [comment]
I didn't do it on a clean setup. I'll try it again with a clean install and see if it happens. Again, I couldn't get it to replicate the issue after trying other inputs/outputs. I'll test again though.

**Comment by McHauge** [comment]
The preset thing might be that i didn't let it sync for enough time to update on onedrive 😅

**Comment by knelsonkc** [comment]
I installed the updated version you uploaded. 

-Presets are nice. Great work! I've attached a screen shot though for the text. The text shows "X" as the input but doesn't show the input number. Also, when my screen 1920x1080 (125% in windows) and opened in Google Chrome at 100% the text is cut off. I didn't show that in the screenshot since that may just be my pc. 

![Screenshot 2020-12-16 130927](https://user-images.githubusercontent.com/24501818/102395527-e12be680-3fa0-11eb-8985-9c281162d06f.png)

-Preset EDID do work. But, programming it as an action within the button does not. Any of the 4k actions fail to trigger anything.

I'm not sure how many details you want in this testing phase. I hope I'm being helpful.

**Comment by McHauge** [comment]
did the new build, the one with presets, affect any of the other things you mentioned before.

Other than that the next step would be:
*Add ARC + presets for it. (had no idea what it was for, therefore I didn't implement it before)
*Double check the 4K actions 
*Rename restore to factory default

**Comment by knelsonkc** [comment]
Nothing was affected. Everything still appeared to work as planned. 

I don't use the ARC setting but it's part of the webui and someone might want it. 

And everything else seems good.

**Comment by McHauge** [comment]
@knelsonkc I have updated the link to include a version with the changes/additions mentioned above, please take a look and comeback if anything is missing/not working, then depending on what the response is, I'll make a note of what commands might be a bit iffy in the help file, for other people to see and read if they find something else. I don't plan on adding feedback currently, since I can't test it locally without knowing the full list/API. In an amount that I can emulate.

The new test build can be found in: "2020-12-17-Companion-2.2.0-AVIShop.zip"

You also requested some way of donating a beer, I will never ask for money but feel free if you want to give some anyway. the simplest way would proberply be via [Paypal](paypal.me/McHauge)

Other options would be to make a donation to Companion itself: [Donate To Companion](https://opencollective.com/companion)

**Comment by McHauge** [comment]
I have marked this as "Done" and it's now included in the Companion Betas, so I'll close this. If something comes up feel free to open it up again or create a new issue on the module itself.

**Comment by knelsonkc** [comment]
I'm sorry it took so long to get back to you. The basic functionality is there. Here's what is still not working and the steps I've taken:

Commands for switching to 4k continue to be buggy. The presets for switching to 4k EDID settings works every time AND works when if I change the input to another within the preset. But, if I add it via the dropdown menu, it won't trigger an EDID change if it is a 4K EDID change. 

Also, EDID to ALL only changes the last input (In8)

Also, *Auto Set Format doesn't seem to have any affect. 


That's the only issue that I can find right now. Thanks for your work.

**Comment by McHauge** [comment]
@knelsonkc hi, I just uploaded a new version on the old Onedrive link above, please give it a try, if 4k does not work with it, the i'll have to have you get the raw codes, as i curently is using the same code for generating them as them, so it must be some funny formating thing

-McHauge

**Comment by knelsonkc** [comment]
4k works perfect. EDID to ALL is the only setting that doesn't work yet.

**Comment by knelsonkc** [comment]
I just download the latest build. This is the issue I'm receiving:

14. 09:01:42 instance(iyhRnUg_e): Instance failed to launch: rgb is not defined
14. 09:01:42 instance(iyhRnUg_e): instance add avishop-hdbaset-matrix HDBaseT 8x8 4K

Anything I'm missing?

**Comment by rgischig** [comment]
Hi Guys, 

I'm about to buy a PureLink PT-MA-HD88UHD, I was wondering if we talk about the same box here, and if it's possible to use companion with the AVIShop integration to control the matrix. From the conversation in the first post, it should be the same matrix, but maybe someone knows.
https://eshop.avidex.gr/media/manual/PT-MA-HD88UHD.PDF

Many thanks 
roman
