### ISSUE TITLE
[Module Request] Run a Python Script

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion-module-requests#330]
Hi. It would be nice to have a module to run a python script on the click of a button.
I know companion is mostly aimed at the streamers and AV Engineers, but the power of this software is amazing and it can be useful to many other people.
I think that, adding the ability to run a python script at the click of a button would be awesome.
The argument of the module could be the location of the python bin, this way, it woudnt require bitfocus to ship it's own bin.

 
Additionaly, running sh scripts (linux/mac) and .bat/,ps1 scripts (windows) would make it even more awesome.

**Comment by thedist** [comment]
Companion already has a `Run shell path` action, so you can just use that to run any local script or file you like.

**Comment by yurividal** [comment]
> Companion already has a `Run shell path` action, so you can just use that to run any local script or file you like.

Is there an example of how this would be done on windows? What about on Linux? Maybe we can improve the documentation?

**Comment by Simber1** [comment]
set the path option to `pythonw "path/to/.py"`
