### ISSUE TITLE
Mixing Station

### ISSUE THREAD

**Issue by SNRSE** [bitfocus/companion-module-requests#333]
The mixing station has an OSC Api. which then could be used to control a lot of soundboards : 

https://dev-core.org/ms-docs/integrations/apis/

**Comment by davidgiga1993** [comment]
Can probably be merged into #764

**Comment by SNRSE** [comment]
Same as https://github.com/bitfocus/companion-module-requests/issues/764 ( and the dev of Mixingstation is there so closing this)
