### ISSUE TITLE
WLED : Aircookie

### ISSUE THREAD

**Issue by christiansass** [bitfocus/companion-module-requests#335]
I would love for there to be a simple way to integrate or trigger presets from Bitfocus Companion via my Elgato Streamdeck.. Basically, there's an onAir sign developed by "make that inc" out of Portland, that I would like to trigger when going live
The developer insists there's a way to make this work... it's just not obvious or simple.. I also have a request to integrate this over at the WLED forums I thought id open a request here to see if I could get pointers from any of you to help get this working

https://makethatinc.com/collections/signs
https://bitfocus.io/

Aircoookie/WLED#1573

**Comment by josephdadams** [comment]
It sounds like the WLED creator suggested you use the Generic HTTP module.

**Comment by christiansass** [comment]
ok, ill look into it...

**Comment by christiansass** [comment]
interestingly your own software suggests that if I have to use http to suggest a proper module... 

> PLEASE READ THIS! Generic modules is only for use with custom applications. If you use this module to control a device or software on the market that more than you are using, PLEASE let us know about this software, so we can make a proper module for it. If we already support this and you use this to trigger a feature our module doesnt support, please let us know. We want companion to be as easy as possible to use for anyone.

Use the 'Base URL' field below to define a starting URL for the instance's commands: e.g. 'http://server.url/path/'. This field will be ignored if a command uses a full URL.

![image](https://user-images.githubusercontent.com/35471675/103206371-4ea11680-48c1-11eb-8cec-557c679a854f.png)

**Comment by christiansass** [comment]
![image](https://user-images.githubusercontent.com/35471675/103207341-a93b7200-48c3-11eb-94dc-1d4c6a4e8929.png)

**Comment by christiansass** [comment]
![image](https://user-images.githubusercontent.com/35471675/103208553-88285080-48c6-11eb-8241-fc35daeba460.png)


Does this look even close?

**Comment by josephdadams** [comment]
I don’t know their API, so I don’t know if it’s close or not.

**Comment by cdrehner** [comment]
Yesss, big thumbs up for a WLED integration!  It's currently the No1 open source LED control solution imho. There are tons of LED devices running WLED, just no hardware control interface yet. The companion integration would fill this gap perfectly and add huge value!

I would be in for extensive testing with either Streamdeck or Loupedeck.

**Comment by cdrehner** [comment]
> ![image](https://user-images.githubusercontent.com/35471675/103208553-88285080-48c6-11eb-8241-fc35daeba460.png)
> 
> Does this look even close?

@christiansass Did you make any progress so far that you could share?

**Comment by flow1986** [comment]
Thumbs up from me too!
WLED Integration would be nice!

**Comment by BenJamesAndo** [comment]
There's now a WLED plugin for the Stream Deck [https://apps.elgato.com/plugins/com.kobaltz.wled](https://apps.elgato.com/plugins/com.kobaltz.wled)
It's a start. But I agree, a Companion module would be excellent. For now I'm using the generic HTTP module and using HTTP GET requests such as `http://192.168.1.7/win&A=50&R=0&G=255&B=0` in the URL. In that example it sets brightness to 50 and colour to Green.

**Comment by BenJamesAndo** [comment]
I was excited to see that a developer has made a Companion WLED integration. [wled-websocket companion](https://github.com/bitfocus/companion-module-wled-websocket)
It's available in the latest stable release.
