### ISSUE TITLE
Generic TCP for BSS Soundweb

### ISSUE THREAD

**Issue by larskmann** [bitfocus/companion-module-requests#34]
**Describe the feature**
I know you dont like generic modules, but being able to control BSS soundweb devices needs the ability for free tcp strings. Thats because the programming of a BSS is always unique and wont be able to be modulized.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Not needed.

**Usecases**
BSS Soundweb

**Comment by sendingstrings** [comment]
This would be helpful for us theater production folks. Both for the BSS gear and for the quickly modifiable TCP string option for bootstrapping solutions quickly.

**Comment by josephdadams** [comment]
A generic TCP UDP module will be available with the next Companion release which should solve this.

**Comment by tm1000** [comment]
For future Googlers there's an official module for Soundweb with companion now: https://github.com/bitfocus/companion-module-bss-soundweb
