### ISSUE TITLE
Wirecast Module

### ISSUE THREAD

**Issue by cipi1965** [bitfocus/companion-module-requests#346]
Hi, i'm developing a module that interface with an application installed on the same machine of Wirecast to provide network control. I would like to add to companion (i will also open source the network application of course). I can't seems to join Slack group because of it requiring a @bitfocus.io email to register.

**Comment by McHauge** [comment]
you shouldn't need a @bitfocus.io mail, but you will need to register your mail to the slack group => @bitfocus.io

**Comment by McHauge** [comment]
should work, if you just type your norma mail in the text field: 
![image](https://user-images.githubusercontent.com/31018035/103767358-bfae9f80-5020-11eb-927d-9e1534894fc3.png)

**Comment by cipi1965** [comment]
The link in wiki seems to be wrong, i joined using one found in previous issue on this repository, thank you! Wrote a message on #module-development

**Comment by cipi1965** [comment]
@McHauge any feedback on my module?

**Comment by cipi1965** [comment]
I would like to point to the new module https://github.com/bitfocus/companion-module-telestream-wirecast
I can close this issue
