### ISSUE TITLE
how to teach StreamDeck app where to find companion Raspi (not connected via USB on the same Mac)

### ISSUE THREAD

**Issue by dickmann** [bitfocus/companion-module-requests#351]
Hi, 

I love my Stream Deck and already use quite some buttons supporting me in my daily business. I installed Companion on a Rasberry Pi, working great. If I go into the StreamDeck (native) app and try to include a "Companion button" via the companion plugin, Streamdeck shows error "connecting to locally running companion...". Of course he is searching on my laptop and there is no Companion software up and running. 

Question: Is there a method to teach StreamDeck that the companion software is not running locally but at another IP in the same network?

I just posted the same question in the Bitfocus Slack group, but I guess I got better chances here 👍 

Thanks for your support!
P.S.: I hope this is not the standard nooby question, but I really spend some time for searching an answer without success...

Kind regards, Michael

**Comment by tgrushka** [comment]
From what I understand (I am just another user, but also a developer who develops my own customizations for Companion), Companion interfaces directly via USB. There is currently no way that I know of to run the server on one system and access the Stream Deck on another device.

BUT...

In such case, you can run the Companion agent/server directly on the Rasberry Pi your Stream Deck is attached to. Then, you can access the web interface of Companion from your main computer. You should be able to do this, as Companion talks to most device instances over IP...

**Comment by dickmann** [comment]
Hi, thanks for your post, yes, this should work.

I am looking for a way to connect from Companion on Raspi to my Macbook connected via USB with StreamDesk. Would this be possible?

**Comment by McHauge** [comment]
@dickmann not natively, but you can do some simple activation via a second companion that triggers the first (pi), but you will lose simplicity, feedbacks and variables. the only way natively to have full control over a Companion instance is via the Web interface/web buttons or via a stream deck connected directly to the host machine that runs companion.

**Comment by dickmann** [comment]
Hi Andreas, thanks for your clear guidance! Kind regards, Michael

Andreas Thomsen <notifications@github.com> schrieb am Di., 12. Jan. 2021,
09:26:
