### ISSUE TITLE
Yamaha Rivage Series Consoles

### ISSUE THREAD

**Issue by ICE9MOONEY** [bitfocus/companion-module-requests#352]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain.

No.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.  An existing module for SCP with the CL and QL series boards exists, but larger Rivage Series boards support more mixes and matrices. Necessary for lots of mix-minuses.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.
An existing module for SCP with the CL and QL series boards exists, but larger Rivage Series boards support more mixes and matrices. Necessary for lots of mix-minuses.

**Comment by josephdadams** [comment]
@ICE9MOONEY I've transferred this to the module requests repository as you posted in the wrong place.

Your request is missing protocol documentation.

**Comment by josephdadams** [comment]
@MeestorX not sure if you wanted to take a look at this or not

**Comment by MeestorX** [comment]
Planning on it, once Yamaha implements a control protocol. :-)

**Comment by MeestorX** [comment]
If someone has a Rivage and would like to test some things with me in preparation for an SCP module for that console, please contact me at andy@checkcheckonetwo.com.

**Comment by MeestorX** [comment]
I have preliminary support for the Rivage in my SCP module available on my website. Anyone with a Rivage that would like to work with me to test it, please contact me there. 
https://discourse.remotely-possible.ca

**Comment by MeestorX** [comment]
@ICE9MOONEY Please fix the typo in the title. My OCD can't take it. (Plus it stops people from seeing this thread if they're searching for "Yamaha")
;-)

**Comment by dpjarrett** [comment]
Is this still in the works?

**Comment by MeestorX** [comment]
It’s been out for a year.

**Comment by dpjarrett** [comment]
What about software for the mtx or mrx?

From: Andrew Broughton ***@***.***>
Reply-To: bitfocus/companion-module-requests ***@***.***>
Date: Thursday, April 21, 2022 at 3:32 PM
To: bitfocus/companion-module-requests ***@***.***>
Cc: Dan Jarrett ***@***.***>, Comment ***@***.***>
Subject: Re: [bitfocus/companion-module-requests] Yamaha Rivage Series Consoles (#352)


It’s been out for a year.
