### ISSUE TITLE
Support for BirdDog EYES PTZ cameras

### ISSUE THREAD

**Issue by wjdean76** [bitfocus/companion-module-requests#353]
Looking to find support for BirdDog eyes cameras. They support VISCA so I don't think it would be much different of a configuration than the PTZ or Sony cameras.

**Comment by josephdadams** [comment]
There's a Birddog Visca module.

https://github.com/bitfocus/companion-module-birddog-visca

Make sure you're using the latest beta version of Companion 2.2.0.
