### ISSUE TITLE
For-A MFR Routers

### ISSUE THREAD

**Issue by Fader-Monkey** [bitfocus/companion-module-requests#354]
Control and read data from the For-A MFR Series video routers.

Ideal functions would be:
Route crosspoint x->y
Recall salvos(internal function of router to recall multiple crosspoint)
use names of sources and destinations as variables for routing
Feedback of what is currently routed to Y destination
copy from current state of crosspoint to salvo (this could be two steps of copy crosspoints and store to x Salvo)

**Is this platform dependent (windows, mac, ..)?**
No, general TCP 

**If documentation is required to implement, do you know where to find it?**
Here is the documentation I received from For-A’s team on how to integrate with companion.

MFR router supports to be controlled via Serial / LAN command.
Communication protocol is TCP/IP, which is based on HARRIS.
For detail, please refer to the "8. Serial / LAN Command Control" on the attached manual as a reference. You can find the commands.
If you can find the protocol for companion, you may be able to send a command from it.

Ex.
 If you want to change crosspoint DST:1, SRC:2.

Command :
------------------------------------
@ B:C
@ P:0/0,1
@ B:E
------------------------------------
1st command : you need to clear the preset record.
2nd command : Preset a crosspoint (depends on the amount of crosspoint, amount of command will be changed)
last command : recall the crosspoints simultaneously.

I am also attaching the PDF documentation. LAN control starts on page 75

**Usecases**
Used to control video routers onsite and integrate with systems already using companion. After the HVS 100/2000 module was built For-A reached out to see if we could add the MFR routers as well. Sounds like they have a few customers asking for companion support. I also have a MFR 5000 and many companion Dev instances to test with.

[MFR3000-E-E6R4_SCS.pdf](https://github.com/bitfocus/companion-module-requests/files/5809748/MFR3000-E-E6R4_SCS.pdf)

**Comment by josephdadams** [comment]
@michaelallen how similar is this to the hvs protocol?

**Comment by Fader-Monkey** [comment]
@josephdadams as far as I know the MFR does not have the same web socket connection as the HVS. For-A also sent over a link to this project which connects to a different SDI router but uses the same harris protocol. 

hopefully I am conveying this well. I definitely do not know enough about these protocols to be a reliable source. Hoping someone can leverage the work already done.   

From For-A:
Our MFR routers use the same XY control protocol as the Leitch, Harris, Imagine router.
https://www.deepreflect.net/2021/01/11/video-router-xy-web-panel/
 
We haven’t tested his application yet. So no guarantees.
