### ISSUE TITLE
How to test a selfmade module?

### ISSUE THREAD

**Issue by JITZEH** [bitfocus/companion-module-requests#356]
Hi all,
I try to make a module for the Allen & Heath SQseries, but how can I test of this actual works?

Kind Regards,
Jitze van der Hoek

**Comment by McHauge** [comment]
Just add it to the module folder an compile or run in dev / headless mode. 

First of clone companion to your local pc and try to compile, don't try the module thing before you can do that.

Then take a look at how modules are build and get a look at the file structure, then it will make more sense. The thing is you can't add modules after the fact, they will have to be included before you compile

**Comment by McHauge** [comment]
Also please come and join slack, it's where all the communication is

**Comment by JITZEH** [comment]
> Also please come and join slack, it's where all the communication is

How to get there?

**Comment by McHauge** [comment]
There is a link on this page (I'm on 📱 Right Now so) https://bitfocus.io/companion

**Comment by McHauge** [comment]
Also based on that question a guess you haven't red the documentation yet 😅

Here is the wiki for crating modules: https://github.com/bitfocus/companion/wiki/Module-Development

**Comment by JITZEH** [comment]
Thanks Sir! I joint the slack. (It was too little too find it)

**Comment by JITZEH** [comment]
Can you set the Github issue on Closed?

**Comment by McHauge** [comment]
No problem

**Comment by saamerm** [comment]
Thanks for this question, helped get me to slack and the docs.
The docs are here now https://github.com/bitfocus/companion-module-base/wiki

Also, the slack location has moved to the Help section if any one cares, but when I try to join the community it gives me this error and asks me to use bitfocus email address unless I get an invite! 

<img width="624" height="796" alt="Image" src="https://github.com/user-attachments/assets/4c0068b7-f92e-40a1-a3d6-b6c599a0deb0" />
