### ISSUE TITLE
Allen and Heath SQ7 Module

### ISSUE THREAD

**Issue by thespica93** [bitfocus/companion-module-requests#369]
Hello,

I am requesting a module for the Allen and Heath SQ Digital Mixers, specifically the SQ 7.  Attached please find the Allen and Heath Midi Protocol Document. Please let me know if there is anything else you need. 
[SQ-MIDI-Protocol-Issue3.pdf](https://github.com/bitfocus/companion-module-requests/files/5863040/SQ-MIDI-Protocol-Issue3.pdf)

Thank you
-Nick

**Comment by josephdadams** [comment]
#56 duplicate. I recognize they are different models but the protocol is the same

**Comment by thespica93** [comment]
I didn't realize someone had created a request already. That request has
been closed. So what does that mean now?
Thank you
-Nick

**Comment by josephdadams** [comment]
#56 is still open
