### ISSUE TITLE
Generic SNMP Module

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion-module-requests#370]
### The name of the device, hardware, or software you would like to control.
Any SNMP capable device

### What you would like to be able to make it do from Companion.
I have a number of cameras and encoders that are powered over ethernet (PoE) enabled.  I would like to be able to:

- power on/off/cycle these devices from my stream deck (using the `powerEthernetMIB`)
- determine the power consumption of these devices (using the `powerEthernetMIB`)
- determine the admin/operation status of switch ports (using the ` ifMIB`)

These are only my immediate use cases, but the possibilities are endless. This generic module could serve as a basis for more specific devices.

### Direct links or attachments to the ethernet control protocol or API. 

- [net-snmp](https://www.npmjs.com/package/net-snmp) - NPM module implements versions 1, 2c and 3 of the Simple Network Management Protocol (SNMP)
- [RFC 1157](https://tools.ietf.org/html/rfc1157) - A Simple Network Management Protocol (SNMP)
- [RFC 1213](https://tools.ietf.org/html/rfc1213) - Management Information Base for Network Management of TCP/IP-based internets: MIB-II
- [RFC 2570](https://tools.ietf.org/html/rfc2570) - Introduction to Version 3 of the Internet-standard Network Management Framework
- [RFC 3413](https://tools.ietf.org/html/rfc3413) - Simple Network Management Protocol (SNMP) Applications
- [RFC 3416](https://tools.ietf.org/html/rfc3416) - Version 2 of the Protocol Operations for the Simple Network Management Protocol (SNMP)
- [RFC 3418](https://tools.ietf.org/html/rfc3418) - Management Information Base (MIB) for the Simple Network Management Protocol (SNMP)
- [RFC 3584](https://tools.ietf.org/html/rfc3584) - Coexistence between Version 1, Version 2, and Version 3 of the Internet-standard Network Management Framework
- [RFC 3621](https://tools.ietf.org/html/rfc3621) - Power Ethernet MIB
- [RFC 2863](https://tools.ietf.org/html/rfc2863) - The Interfaces Group MIB

---

I've already started working on this module for personal use. I'll gladly share it if there's community interest.

**Comment by Nreed18** [comment]
Yes Please Share it!

**Comment by estilles** [comment]
> Yes Please Share it!

https://github.com/bitfocus/companion-module-generic-snmp

**Comment by JonathanPowe** [comment]
Thank you for creating this module. 
It doesn't seem to be visible in the modules list in Companion. I've checked the latest beta builds and searched for "SNMP", but can't find it.
Do I need to change a setting in Companion to be able to use this module?
Or is it still awaiting approval before being added to the main builds?
![image](https://user-images.githubusercontent.com/101350871/163969983-a71954a5-1702-4df3-b3ed-db251c9ea5f3.png)

**Comment by mrcheap1984** [comment]
You need to put the folder in the node_modules folder.
Unfortunately I get a timeout when using it in docker, not sure if the docker image has the required libraries.
![snmperror](https://user-images.githubusercontent.com/2299043/169477198-a39efef1-ade3-48b7-ba53-f2eca824abe8.png)

**Comment by ShuheiUda** [comment]
@estilles Thank you for providing this module.
Is there any update for this module?

**Comment by phillipivan** [comment]
@ShuheiUda this is in 3.4 now.
