### ISSUE TITLE
Chroma-Q Vista

### ISSUE THREAD

**Issue by dherlein** [bitfocus/companion-module-requests#373]
Would it be possible to support Chroma-Q Vista (formerly Jands Vista)?
It would be nice to be able to fire cues or cuelists from companion.

Thanks!

**Comment by themediaguy1297** [comment]
You can only control vista by using the midi-relay module. Vista doesn't have a protocol that you can talk directly to it. Here is a video for using midi-relay with vista. ￼ https://youtu.be/w184FhkFGtM

**Comment by dherlein** [comment]
Thanks!
