### ISSUE TITLE
Philips Hue

### ISSUE THREAD

**Issue by PhotoJoseph** [bitfocus/companion-module-requests#374]
Would be great to control hue lights, individually and/or by running existing presets from the app

**Comment by aaronpk** [comment]
Here's the docs on the Philips Hue API, unfortunately it requires logging in to view them:

https://developers.meethue.com/

The Hue bridge has a local API that requires an initial "pairing" step. You'd add the module in Companion, then go tap the button on the bridge, then the module would get a token it can use in future requests.

**Comment by josephdadams** [comment]
What's wrong with this module? https://github.com/bitfocus/companion-module-phillips-hue

**Comment by aaronpk** [comment]
It's empty?

**Comment by josephdadams** [comment]
@mattehalen does your hue module work?

**Comment by aaronpk** [comment]
My bad, it looked like an empty repo with just a readme on my phone! Looks like a good start. No releases yet and it's not listed in the website yet though. https://bitfocus.io/support

**Comment by mattehalen** [comment]
I've got the model to work at home.
Haven't had anyone else test it yet.


You do need to run it in development environment because it's not in any release yet or at least not when I checked. I haven't looked into the beta versions if it's there.

**Comment by PhotoJoseph** [comment]
I'm the OP; I'm not a developer so probably best for me to stay out of dev environments but when ready for n00b testing, I'd be happy to check it out!

**Comment by josephdadams** [comment]
@mattehalen looks like the module is not included in the beta releases. @JeffreyDavidsz let's target this to go into core for others to test

**Comment by JeffreyDavidsz** [comment]
Included now
