### ISSUE TITLE
Datavideo NVS-40

### ISSUE THREAD

**Issue by pyhasanon** [bitfocus/companion-module-requests#378]
Request Companion Module for Datavideo NVS-40.  Looking for controls to start/stop streaming on individual channels, as well as start/stop recording for individual channels.  Documentation is vague, but is normally controlled via controls presented by logging into the IP in a web browser.  

https://resource.datavideo.com/Instruction_Manuals/NVS-40_E5_A5_EN.pdf

Thank you.

**Comment by josephdadams** [comment]
Thanks for including the instruction manual. It doesn't seem to list ethernet control protocols, so please try to find that.

**Comment by pyhasanon** [comment]
Yeah, I've been searching for a while, and their customer service isn't very responsive, unfortunately...  Will keep searching...  Thanks!

**Comment by pyhasanon** [comment]
Do you have any suggestions otherwise?  Like, what's a good way to manually look for these protocols?  I'm having trouble trying to understand something like Wireshark, but that's probably my best bet at the moment...

**Comment by josephdadams** [comment]
If it's not available from the vendor's website and they are not responsive, then the only other option is to reverse-engineer the protocol, which takes a massive amount of time to document. I would say your best option is to continue to reach out to customer service, and if you have others interested in such a module, to ask them to do the same. Invite the company to check out what Companion is/does, to see how having the protocol would help their own users to use their product without any effort from them other than to provide the protocol.

**Comment by BB21B** [comment]
@pyhasanon I've reached out to a contact I managed to get at Datavideo last year to see if they can provide the documentation

**Comment by pyhasanon** [comment]
You are amazing, thank you for that!

**Comment by pyhasanon** [comment]
So, while digging for more information, I stumbled upon a link on the Datavideo NVS-34 product page (https://www.datavideo.com/us/product/NVS-34) and found a link for "HTTP Command Sample" all the way on the bottom (https://resource.datavideo.com/otherFiles/'HTTP%20Command%20Sample%202.0%20NVS.zip)... is there a way I can utilize this information for the NVS-40 (which seemingly isn't too different from the NVS-34)...?

Again, any help would be greatly appreciated!

**Comment by josephdadams** [comment]
#1143  consolidating everything under this one
