### ISSUE TITLE
Custom module: Display external file text in button and triggering

### ISSUE THREAD

**Issue by tomatojc78** [bitfocus/companion-module-requests#381]
Good evening everyone.
I did not find a simple module in the existing ones.

I control led strip installed in exhibition boxes of a museum and I need to control the temperature in these boxes.

Currently, I am using QLC + for light control on raspberry and I have installed temperature sensors on the raspberry (up to 6 sensors per raspberry). I know how to retrieve the temperature value in a text file on the raspberry but I want to be able to display this temperature in the button which corresponds to the strip led on the streamdeck.

The temperatures are recorded in a file whose name is typed as raspberrynumbers_boxnumber.txt

example
1_1.txt
1_2.txt
2_1.txt
etc.

It is easy to retrieve these python text files on the machine which hosts the companion.

I am therefore looking for a module capable of displaying a title and reading and displaying the content of a text file (max 8 characters) with a refresh period (adjustable from 30s to 10mm?)

And since it is not forbidden to dream, I wonder if it is not also possible to be able in the module to enter a value (max value ?) capable of triggering an action on another button or on the current button.

For example, if max value> = 25 -> launch the strip led stop button or change the background to red to visually signal a problem

Thank you for your attention, I hope this does not already exist and that my request will be well received.

**Comment by josephdadams** [comment]
This would be a very customized module. I would suggest placing a bounty value on it for someone to take on creating this.

**Comment by tomatojc78** [comment]
"I would suggest placing a bounty value on it"

sorry i am new here. How to do this ?

:)

**Comment by josephdadams** [comment]
@JeffreyDavidsz do we have a preferred bounty tool/site?

**Comment by josephdadams** [comment]
@tomatojc78 Basically you just need to state what you would be willing to pay to have someone code this for you, and then a programmer may agree to that fee and write it

**Comment by JeffreyDavidsz** [comment]
bountysource.com

**Comment by josephdadams** [comment]
Generic file reader module now exists
