### ISSUE TITLE
RGBlink mini or Livepro L1

### ISSUE THREAD

**Issue by Arnaurvm** [bitfocus/companion-module-requests#384]
It's a simple 4 chanel hdmi video mixer.
Will be nice to switch chanel over Companion
It have an Ethernet app to control it, but i didn't find the API
This is the product web page: https://rgblink.com/product-detail?id=1081#!/tab/56140311-2

**Comment by Arnaurvm** [comment]
This is the same product, but from another brand:
http://www.feelworld.cn/ShowInfo.aspx?id=667&py=FEELWORLD-LIVEPRO-L1-Multi-format-Video-Mixer-4-x-HDMI-inputs-multi-camera-production-real-time-live-streaming
Maybe it helps

**Comment by semenovnick** [comment]
Hello. I asked for API from manufacturer, and he send me the API instructions.
Now I'm digging other functions, that are not mentioned in this document.
[API(EN).pdf](https://github.com/bitfocus/companion-module-requests/files/7527179/API.EN.pdf)

**Comment by thabaret** [comment]
I had the same need for TAO1 Pro, looks like API is built in the same way.
Although it's not implemented nicely as a module, I managed to trigger the channel switch by using companion generic TCP/UDP module
https://github.com/bitfocus/companion-module-generic-tcp-udp
 you set the IP of your device, port to 1000 and UDP in the module configuration then on the buttons configurations you send one of the command in the API

- Switch to signal source 1 send : 
<T0000750200000077>
 - Switch to signal source 2 send 
<T0000750200010078>
-  Switch to signal source 3 send : 
<T0000750200020079>
- Switch to signal source 4 send: 
<T000075020003007A>


hope this helps

**Comment by mrkabass** [comment]
> I had the same need for TAO1 Pro, looks like API is built in the same way. Although it's not implemented nicely as a module, I managed to trigger the channel switch by using companion generic TCP/UDP module https://github.com/bitfocus/companion-module-generic-tcp-udp you set the IP of your device, port to 1000 and UDP in the module configuration then on the buttons configurations you send one of the command in the API
> 
> * Switch to signal source 1 send :
> 
> - Switch to signal source 2 send - Switch to signal source 3 send : - Switch to signal source 4 send:
> hope this helps

It Does not work for me :/

**Comment by mrkabass** [comment]
> Hello. I asked for API from manufacturer, and he send me the API instructions.
> Now I'm digging other functions, that are not mentioned in this document.
> [API(EN).pdf](https://github.com/bitfocus/companion-module-requests/files/7527179/API.EN.pdf)

any news?

**Comment by mrkabass** [comment]
**Feelworld Livepro L1** Switching cameras commands using **companion generic TCP/UDP module**.
Set the IP of your device, port to 1000 and UDP in the module configuration
 then on the buttons configurations you send one of the command(just what's after the colon) bellow:

 Switching camera 01 - add command bellow: 
<T0000750200000077> 

Switching camera 02 - add command bellow:
<T0000750200010078> 

Switching camera 03 - add command bellow:
<T0000750200020079>

Switching camera 04 -add  command bellow:
<T000075020003007A>

**Comment by marcingum** [comment]
Together with a friend, we have created a module for RGBlink mini - https://github.com/bitfocus/companion-module-rgblink-mini.
Currently it's available in Beta Build.

**Comment by Sidonai-1** [comment]
> Together with a friend, we have created a module for RGBlink mini - https://github.com/bitfocus/companion-module-rgblink-mini. Currently it's available in Beta Build.

Hi, do you know if this would (on paper) support the D Series Lineup?

https://www.rgblink.com/productsinfo.aspx?id=52

Thanks!

**Comment by marcingum** [comment]
> > Together with a friend, we have created a module for RGBlink mini - https://github.com/bitfocus/companion-module-rgblink-mini. Currently it's available in Beta Build.
> 
> Hi, do you know if this would (on paper) support the D Series Lineup?
> 
> https://www.rgblink.com/productsinfo.aspx?id=52
> 
> Thanks!

I don't have an API description for D-series devices. Without that I can only guess. If you want, ask for an API description from RGBlink support (via email) and attach it here.

I'm guessing that D-series has a different API than mini. It's more likely to work with an existing module for VSP 628-pro, but I'm just basing it on a comment from https://github.com/bitfocus/companion-module-requests/issues/9 , and that X3/X7/X8 devices have similar APIs on paper.
