### ISSUE TITLE
Companion no longer working JS error

### ISSUE THREAD

**Issue by jeffmpelletier** [bitfocus/companion-module-requests#385]
after moving and copying a few buttons around. Companion started popping up an error
<img width="423" alt="Screen Shot 2021-02-02 at 4 27 09 PM" src="https://user-images.githubusercontent.com/51770046/106678937-f1138000-6578-11eb-8d91-c8fdb0e6ae5e.png">
<img width="1126" alt="Screen Shot 2021-02-02 at 5 04 26 PM" src="https://user-images.githubusercontent.com/51770046/106678951-f4a70700-6578-11eb-9df2-8df805ef2bf8.png">
My instances are no longer connecting. Any thoughts before I reinstall and have to completely rebuild my setup?

**Comment by JeffreyDavidsz** [comment]
Restore a backup, your db is probably messed up

**Comment by jeffmpelletier** [comment]
Probably so & shame on me for not having a backup, but rebuilding it all will help grow my chops. I did end up uninstalling and reinstalling but looks like that I have to manually delete the db. Where/how might I do this?

**Comment by JeffreyDavidsz** [comment]
That will be dependent of os. Search for it on Facebook it's there somewhere

**Comment by jeffmpelletier** [comment]
I'm not on the Facebook... But I think I found it; a folder not in the 'Package Contents' folder.
