### ISSUE TITLE
Module request: GEFEN DVI Matrix

### ISSUE THREAD

**Issue by rolandfoucher** [bitfocus/companion-module-requests#39]
**Describe the feature**
16x16 GEF-DVI-16416-PB
8x8 GEF-DVIKVM-848DL-PB

DVI matrix gefen (UDP and Telnet for the 16x16 // Telnet for the 8x8)

**Is this platform dependent (windows, mac, ..)?**
This platform is web based

**If documentation is required to implement, do you know where to find it?**
Yes 
https://www.comm-tec.de/de/bilder-und-dateien/artikel/gef-dvi-16416-pb.pdf
https://www.eavs-groupe.fr/downloads/dl/file/id/4981/product/48924/

**Usecases**
Make a simple way to recall preset or switch input and output with these Matrix

Thank you!

**Comment by josephdadams** [comment]
@mfoulks3200 did you ever take a look at this?

**Comment by josephdadams** [comment]
This module has been created and will be included in the next release.
