### ISSUE TITLE
Brompton Tessera LED Processor protocol module

### ISSUE THREAD

**Issue by HPMDW** [bitfocus/companion-module-requests#393]
Hi there, 

It would be really great if you could implement a Brompton Tessera LED Processor module. We have a new API which should make this very easy. There are a few features that it would be really useful to implement. We have a load of Stream Decks in the office and are Companion aficionados and users, and I have one at home so we can test any module developed with our hardware.  

For a first pass I think the features worth implementing would be:
Active Preset Number (also interrogate the processor for preset names to go with the numbers)
Output Brightness
Group Brightness
Blackout Enabled/ Disabled
Freeze Enabled/Disabled

Test Pattern Enabled/Disabled
Test Pattern Format
Test Pattern Type

Input Port Number 
Input Port Type

Any queries, please don't hesitate to ask. 
I have attached a copy of our API .pdf.  

All the best,
Hugh Davies-Webb
Product Consultant 
Brompton Technology

[TesseraIPControlAPI3_1_0_Beta4.pdf](https://github.com/bitfocus/companion-module-requests/files/5951346/TesseraIPControlAPI3_1_0_Beta4.pdf)

**Comment by josephdadams** [comment]
requested in #78

**Comment by gvitale1** [comment]
I know this is closed but i want to second this
