### ISSUE TITLE
Dante Controller

### ISSUE THREAD

**Issue by Stempoid** [bitfocus/companion-module-requests#395]
Is it possible to add support for Dante route, mute, switching?

https://www.audinate.com/products/software/dante-controller

**Comment by istnv** [comment]
Mute in Dante Controller is a status based on loss of clock, not a command.
Mute is handled at the receiving end (usually a mixer/console).
For other Dante operations (routing audio signals), Audinate wants $10K to start using their SDK.
Then $5K per year after that.

**Comment by josephdadams** [comment]
I've marked this with these labels because of what @istnv said. There is no publicly available API that would allow us to include this type of control into a free open source product.

**Comment by mkusmic** [comment]
There are people out there working on reverse engineering the Dante Control protocol.

https://gearspace.com/board/music-computers/1221989-dante-routing-without-dante-controller-possible.html

**Comment by dronenb** [comment]
This would, in theory, be feasible to implement into Companion: https://github.com/ryanmccartney/dante-control

**Comment by josephdadams** [comment]
I started working on this recently. I created a dante module, but since it is not paid work, I have not have not had time to finish it.

**Comment by Joelsuperstar** [comment]
> I started working on this recently. I created a dante module, but since it is not paid work, I have not have not had time to finish it.

any update on this?

**Comment by kjetilpp** [comment]
> No
> 
> https://github.com/bitfocus/companion-module-audinate-dantecontroller

So nothing ready for use? :)

**Comment by josephdadams** [comment]
Nope

**Comment by josephdadams** [comment]
there is a dante module now provided you use dante domain manager
