### ISSUE TITLE
Marshall Electronics CV355-10x

### ISSUE THREAD

**Issue by Prinzpaulaner** [bitfocus/companion-module-requests#405]
Hey there is it possible to controll my "Marshall Electronics CV355-10x" with companion? Now i controll it with "CamControl_R04" direct from marshall but this app is not that good. So i would like to ask if you can implement those cameras (its a wide product range) or if you can tell me some apps which use midi input for controll.
Thanks!

**Comment by psvail** [comment]
I'm using the sony visca module to control the CV630 over enet. Check it out.

**Comment by Prinzpaulaner** [comment]
Do you mean Ethernet? My cam only use SDI, HDMI and this scuft green conector that i dont know the name of.

**Comment by arichterras** [comment]
The marshall CV350 only can be controlled with RS485. It´s necessary to use an USB Serial to RS485 adapter or a TCP/IP RS485 converter, for example USR-TCP232-304. With a USR converter it´s possible to use the Generic TCP and UDP Request module, but you have to send raw hex codes in the %hh format. Below you can find  the Marshall VISCA command document.
[CV350_Protocol_pelco_visca.pdf](https://github.com/bitfocus/companion-module-requests/files/6100555/CV350_Protocol_pelco_visca.pdf)

**Comment by Prinzpaulaner** [comment]
How can i send those Hex data from my streamdeck?

**Comment by arichterras** [comment]
You can use the "Generic TCP and UDP Requests" companion instance, if you´re using a TCP RS485 converter hardware. 
For example you can send %81%01%04%07%02%FF if you want to zoom in with your camera with ID 1.
I wrote a module for the marshall RS485 cameras based on the PTZ Optics module. I have to check some things, maybe i can make a pull request next week. @josephdadams can you please create a repository for the Marshall RS485 Cameras.

**Comment by Prinzpaulaner** [comment]
I use that adapter (https://www.huss-licht-ton.de/product_info.php/Marshall-MS-CV-USB-RS485-Adapter-USB-auf-RS485422/info/39360.html) I dont know what i have to type in in the target ip thing?

**Comment by arichterras** [comment]
That´s only a USB Serial RS485 converter and no TCP RS485 converter. 
You could use the "generic-tcp-serial" companion instance to create a TCP server which transfers the received data to the USB RS485 converter. It´s important to have the newest version of the "generic-tcp-serial" which is available on github, otherwise there will be an issue with the string encoding, the camera control won´t work. 

virtual connection:
"Generic TCP and UDP Requests" enter IP adress from your Companion and port from "generic-tcp-serial"  --> "generic-tcp-serial" --> USB RS485 Hardware --> Marshall CV355 Camera

**Comment by josephdadams** [comment]
I control our Marshall CV503 cameras over UDP to RS485 just using the Sony VISCA module in Companion and it works great. Here's a little walkthrough of how we did it: https://techministry.blog/2021/03/11/using-a-stream-deck-and-a-raspberry-pi-to-create-a-remote-control-panel-to-adjust-marshall-cameras-over-ip-with-rs-485-control/

**Comment by arichterras** [comment]
I tested the sony visca module before I started to program the marshall module. For my applikation some commands are missing and other commands like pan and tilt are not necassary. The commands I´ve missed are variable zoom speed, zoom direct(zoom to a position, like a preset), osd menu contro land multiple camera control with one instance.

**Comment by Jamfever** [comment]
> I'm using the sony visca module to control the CV630 over enet. Check it out.

Hi, I'm having trouble getting companion to find & control my Marshall CV630 IP. If you could give me any tips it would be much appreciated :)

**Comment by Prinzpaulaner** [comment]
Do you use Ethernet or RS-422 for control?

**Comment by Jamfever** [comment]
Ethernet

**Comment by Prinzpaulaner** [comment]
Well i use an raspberry pi (like here https://techministry.blog/2021/03/11/using-a-stream-deck-and-a-raspberry-pi-to-create-a-remote-control-panel-to-adjust-marshall-cameras-over-ip-with-rs-485-control/) to controll my cams

**Comment by mark-epstein** [comment]
> I'm using the sony visca module to control the CV630 over enet. Check it out.

@psvail I know you wrote this ages ago but can you provide more details? I am able to communicate with the camera via web and 232, just not VISCA over Ethernet.

Using the Sony module is EXACTLY what I wanted but I can't get my CV630 to react to the module at all, and Marshall's documentation doesn't seem to mention it either.

**Comment by mark-epstein** [comment]
> > I'm using the sony visca module to control the CV630 over enet. Check it out.
> 
> @psvail I know you wrote this ages ago but can you provide more details? I am able to communicate with the camera via web and 232, just not VISCA over Ethernet.
> 
> Using the Sony module is EXACTLY what I wanted but I can't get my CV630 to react to the module at all, and Marshall's documentation doesn't seem to mention it either.

Never mind, I'm an idiot. I have a CV730, not a CV630

**Comment by mark-epstein** [comment]
> As long as it's poe+ and ndi-hx, I would suspect that the controls are the same. I'm betting it should work...
I would have thought so as well. Can you confirm what UDP port you are using with the Sony module? E.g. the standard 52381 or something else?
