### ISSUE TITLE
biamp Tesira Forté Protocol

### ISSUE THREAD

**Issue by JoRaeBim** [bitfocus/companion-module-requests#406]
Hi,
I would like to have a module to control a Tesira Forte via TCP/IP Telnet.
https://www.biamp.com/products/tesira-fixed-audio-dsp

Since the Tesira is a freely and variably configurable audio hardware, it should be possible to enter many different commands manually. Since everyone can give his own names to his blocks in the Tesira configuration, this must be considered in the Companion driver.

Example:

I created two level blocks in the Tesira and want to control them via companion. (Increment by 1)

LevelName1 increment level 1 1
LevelName2 increment level 1 1

Everything is the same but the name.

Protocol:
https://support.biamp.com/Tesira/Control/Tesira_Text_Protocol

Ports:
https://support.biamp.com/Tesira/Control/Tesira_network_ports_and_protocols

I would write a Module by myself, but i cant get a telnet connection with the device.

**Comment by NovussDei** [comment]
If anyone would be willing to work on this I would be happy to throw in some compensation to see it happen.

**Comment by timt-111** [comment]
Also very interested in this module being developed -- I'll also note that there's talk of this in your slack channel by [@Adrian Davis (Sydney, Australia)](https://bitfocusio.slack.com/team/UC5KR8CSV)

and looks like he has a really good start on a module -->  https://github.com/themusicnerd/bitfocus_companion_biamp_tesira

I'll certainly sign up to be a tester for this -- plenty of hardware available
