### ISSUE TITLE
Module request: Octava PRO DSX Video Over IP

### ISSUE THREAD

**Issue by jsuofga** [bitfocus/companion-module-requests#41]
**Describe the feature**
Please kindly add the Octava PRO DSX Video Over IP to the Equipment List for Companion

**Is this platform dependent (windows, mac, ..)?**

**If documentation is required to implement, do you know where to find it?**
Here is the API commands 
https://octavainc.com/wp-content/uploads/installation-guide/prodsx/PRO-DSX_Matrix_API_111218.pdf

**Usecases**
The Octava is a Video Over IP Encoder/Decoder Solution used in many Audio Video Applications ( Church, Education and etc). Some users would like to have a very simple and programmable buttons to do the switching.  
THe Switching commands are sent to the Receiver unit ( RX)
Each RX has an IP address

The PRO DSX- TX and RX has various features that can be enabled and modified by
directing accessing the TX or RX using HTTP request.
Example:
http://[device ip]/cgi-bin/query.cgi?cmd=[command]

Example 1:
Switching PRO DSX –RX unit 01 ( ip = 172.31.3.1) to
PRO DSX-TX unit 01 (ip = 172.31.3.2.1) unit 1
http://172.31.3.1/cgi-bin/query.cgi?cmd=rxswitch:001
Example 2:
Switching PRO DSX –RX unit 01 ( ip = 172.31.3.1) to
PRO DSX-TX unit 03 (ip = 172.31.3.2.1) unit 1
http://172.31.3.1/cgi-bin/query.cgi?cmd=rxswitch:003

**Comment by McHauge** [comment]
@jsuofga Hey just completed a test version of this module with most/nearly all available commands included and presets for all actions.

You can get a test build of companion v2.0 with the module from the link below, it would be awesome if you could test if the module and all the actions work as expected. Then we can add it as completed and include it in the main build.

Download link:
[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

-Andreas

**Comment by McHauge** [comment]
Gonna close this, it's included in the core, and if errors come up we can open it again
