### ISSUE TITLE
[Feature Request] Add support for Lightkey

### ISSUE THREAD

**Issue by jdeheer** [bitfocus/companion-module-requests#411]
**Describe the feature**
Similar to some of the other lighting control applications that can be controlled, it would be nice to be able to control Lightkey (www.lightkeyapp.com)

**Usecases**
Lightkey is a MacOS only (sadly!) lighting control software.  Being able to control scenes and shows from BitFocus would be hugely beneficial in refining our workflow.

**Comment by josephdadams** [comment]
See #219. Lightkey has no ethernet API as far as we know. However there are some control options via MIDI.

if there’s an api to share that would allow direct control from Companion, share it here.
