### ISSUE TITLE
Analog Way Pulse 4K

### ISSUE THREAD

**Issue by RafaelMittelberger** [bitfocus/companion-module-requests#417]
Hi, 

we are currently working with the Stream Deck XL and the Analog Way Pulse 4K. We tried to programm the commands with Generic TCP/UDP but it didn't work out. 
Would be nice to have a module for the Companion. 
The programmer's guide can be found here: 

https://www.analogway.com/files/uploads/produit/download/midra4k_rest_api_programmers_guide_v1_00_03.pdf

We would be happy about any ideas!

**Comment by JeffreyDavidsz** [comment]
In the title I see REST so that's not TCP... Try the Generic HTTP module, let us know which command you would like to use. I don't have access at the moment, but in my view midra is already in Companion. Are you using the latest version?

**Comment by dewiweb** [comment]
A new version of api is here:

https://www.analogway.com/files/uploads/produit/download/midra4k_rest_api_programmers_guide_v1_2_7.pdf

**Comment by mediahaus** [comment]
I use the generic http module with my Pulse 4k. Goes quite well. In the configuration the IP (http://xxx.xxx.xxx.xxx) then the button http:post URL and body. leave header blank!!! content-type: application/json. URL e.g.: /api/tpp/v1/.... Body e.g.: {"sourceType":"background-set", .... but without any spaces

**Comment by dnmeid** [comment]
Control of Pulse 4K as well as all other devices of the Midra 4K series and Alta 4k Series and LivePremier is now possible with the unified Analog Way AWJ module. Available since Companion 2.4.0
