### ISSUE TITLE
Tascam DA-6400

### ISSUE THREAD

**Issue by ClickTrackAudio** [bitfocus/companion-module-requests#418]
Hello...
Would like to request support for the Tascam DA-6400.
Specifically functions such as Play, Stop, Record, Set Marker, jump to marker, (based on timecode).
User manual and protocol documents are attached.
Many thanks!
[DA-6400dp-OwnersManual-VersionA.pdf](https://github.com/bitfocus/companion-module-requests/files/6075902/DA-6400dp-OwnersManual-VersionA.pdf)
[DA-6400-OwnersManual-Addendum-V220.pdf](https://github.com/bitfocus/companion-module-requests/files/6075906/DA-6400-OwnersManual-Addendum-V220.pdf)
[telnet_protocol_da6400dp_v100_en.pdf](https://github.com/bitfocus/companion-module-requests/files/6075907/telnet_protocol_da6400dp_v100_en.pdf)

**Comment by ClickTrackAudio** [comment]
Forgot to mention...we own two of these units so are able to be beta testers of both single- and multiple-unit command use cases.

**Comment by tlblankenship** [comment]
`var tcp = require('../../tcp');
var instance_skel = require('../../instance_skel');
var debug;
var log;

function instance(system, id, config) {
	var self = this;

	// super-constructor
	instance_skel.apply(this, arguments);

	self.actions(); // export actions

	return self;
}

instance.prototype.updateConfig = function(config) {
	var self = this;

	self.config = config;
	self.init_tcp();
};

instance.prototype.init = function() {
	var self = this;

	debug = self.debug;
	log = self.log;

	self.status(self.STATE_UNKNOWN);
	self.init_presets();

	self.init_tcp();
};

instance.prototype.init_tcp = function() {
	var self = this;

	if (self.socket !== undefined) {
		self.socket.destroy();
		delete self.socket;
	}

	if (self.config.host) {
		self.socket = new tcp(self.config.host, 23);

		self.socket.on('status_change', function (status, message) {
			self.status(status, message);
		});

		self.socket.on('connect', function () {
			self.socket.send("\r\n" + self.config.password + "\r\n");
		});

		self.socket.on('error', function (err) {
			debug("Network error", err);
			self.log('error',"Network error: " + err.message);
		});
	}
};

// Return config fields for web config
instance.prototype.config_fields = function () {
	var self = this;
	return [
		{
			type: 'textinput',
			id: 'host',
			label: 'Device IP',
			width: 12,
			regex: self.REGEX_IP
		},
		{
			type: 'textinput',
			id: 'password',
			label: 'Password',
			width: 6,
			default: 'DA-6400'
		},
		{
			type: 'text',
			id: 'info',
			width: 6,
			label: 'Information',
			value: 'You only need to change the password here if you have changed it from the default password of the device. If you are using an SS-R250N, the default password is DA-6400.'
		}
	]
};

// When module gets deleted
instance.prototype.destroy = function() {
	var self = this;

	if (self.socket !== undefined) {
		self.socket.destroy();
	}

	debug("destroy", self.id);;
};

instance.prototype.init_presets = function () {
	var self = this;
	var presets = [];

		presets.push({
			category: 'Transport Control',
			label: 'Play',
			bank: {
				style: 'text',
				text: 'PLAY',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'play'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Record Ready',
			bank: {
				style: 'text',
				text: 'RECORD READY',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'recordready'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Record',
			bank: {
				style: 'text',
				text: 'RECORD',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'record'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Mark Track',
			bank: {
				style: 'text',
				text: 'MARK\\nTRACK',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'mark'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Stop',
			bank: {
				style: 'text',
				text: 'STOP',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'stop'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Pause',
			bank: {
				style: 'text',
				text: 'PAUSE',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'pause'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Previous Mark',
			bank: {
				style: 'text',
				text: 'PREV\\nMARK',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'prev'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Next Mark',
			bank: {
				style: 'text',
				text: 'NEXT\\nMARK',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'next'
				}
			]
		});

		presets.push({
			category: 'Transport Control',
			label: 'Jump to track',
			bank: {
				style: 'text',
				text: 'JUMP\\nTO\\nTRACK',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'jump',
					options: {
						track: '1'
					}
				}
			]
		});

		presets.push({
			category: 'Power Control',
			label: 'Power On',
			bank: {
				style: 'text',
				text: 'POWER\\nON',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'powerOn'
				}
			]
		});

		presets.push({
			category: 'Power Control',
			label: 'Power Off',
			bank: {
				style: 'text',
				text: 'POWER\\nOFF',
				size: '14',
				color: '16777215',
				bgcolor: 0
			},
			actions: [
				{
					action: 'powerOff'
				}
			]
		});

	self.setPresetDefinitions(presets);
}

instance.prototype.actions = function(system) {
	var self = this;
	self.setActions({
		'play':        { label: 'Play' },
		'recordready': { label: 'Record ready' },
		'record':      { label: 'Record' },
		'mark':        { label: 'Mark track (while recording)' },
		'stop':        { label: 'Stop' },
		'pause':       { label: 'Pause' },
		'prev':        { label: 'Previous track' },
		'next':        { label: 'Next track' },
		'jump': {
			label: 'Jump to track',
			options: [
				{
					label: 'Track number',
					id: 'track',
					type: 'textinput',
					regex: self.REGEX_NUMBER,
					default: 1
				}
			]
		},
		'powerOn':     { label: 'Power on' },
		'powerOff':    { label: 'Power off' }
	});
}

instance.prototype.action = function(action) {
	var self = this;
	var cmd = '0';
	var opt = action.options;

	switch (action.action) {

		case 'play':
			cmd += '12';
			break;

		case 'recordready':
			cmd += '1301';
			break;

		case 'record':
			cmd += '1300';
			break;

		case 'mark':
			cmd += '1302';
			break;

		case 'stop':
			cmd += '10';
			break;

		case 'pause':
			cmd += '1401';
			break;

		case 'prev':
			cmd += '1A01';
			break;

		case 'next':
			cmd += '1A00';
			break;

		case 'jump':
			cmd += '23';

			var track = ('0000' + opt.track).substr(-4);
			cmd += track.substr(2);
			cmd += track.substr(0, 2);
			break;

		case 'powerOn':
			cmd += '7500';
			break;

		case 'powerOff':
			cmd += '7511';
			break;
	}

	if (cmd !== undefined) {

		debug('sending tcp', cmd, "to", self.config.host);

		if (self.socket !== undefined && self.socket.connected) {
			self.socket.send(cmd + "\r\n");
		} else {
			debug('Socket not connected :(');
		}

	}

	debug('action():', action);


};

instance_skel.extendedBy(instance);
exports = module.exports = instance;
`

**Comment by tlblankenship** [comment]
Here is a mockup of the DA-6400, using the Tascam CD-Master as a frame. 

I changed the default password to accommodate and changed the Previous/Next Track to Previous/Next Mark per my needs. Let me know if this helps. Is there anyway I can test this file locally using Companion?

[Original Post](https://github.com/bitfocus/companion-module-requests/issues/1147)
``
[tascamDA6400_index.txt](https://github.com/bitfocus/companion-module-requests/files/11432514/tascamDA6400_index.txt)

**Comment by phillipivan** [comment]
I have a module in dev if either of you would like to test let me know.

**Comment by ClickTrackAudio** [comment]
Huge thanks.  Really appreciate.  I'm swamped at the moment but I'll put this on the must-do list and should be able to do some testing with it in about 2 weeks.  
Huge thank you again!

Cheers
W

**Comment by phillipivan** [comment]
No worries.

Repo is [here](https://github.com/phillipivan/companion-module-tascam-da-6400) for the time being.

Are there specific actions or feedbacks your after? I've already covered my use case and some.

**Comment by phillipivan** [comment]
You can find the repo [here](https://github.com/bitfocus/companion-module-tascam-da-6400/) now

**Comment by phillipivan** [comment]
@ClickTrackAudio did you get a chance to test this? If so, how is it going for you?

**Comment by ClickTrackAudio** [comment]
Hey….thanks for following up

Unfortunately no…I got swamped during silly season (aka Christmas) and the gear was out on production.  
Its still on my to do list…I hope to get at it this month as it is quieter.

Cheers & Thanks!
W.

**Comment by Julusian** [comment]
Closed by https://github.com/bitfocus/companion-module-tascam-da-6400/
