### ISSUE TITLE
Requesting support for Tesla-Smart HDMI 8x8 Matrix

### ISSUE THREAD

**Issue by WachterChristoph** [bitfocus/companion-module-requests#422]
I have A Tesla-Smart 8x8 HDMI Matrix from AliExpress

I saw the KVM switch already has support, unfortunately the Matrix not.

If you could add it at some point this would be great.

**Comment by josephdadams** [comment]
Please provide the protocol documentation.

**Comment by WachterChristoph** [comment]
@josephdadams 

I received this from the manufacturer so far.

Works like a charm, but would need some reverse engineering to get the commands. I asked them to receive a "full" documentation with the commands. As soon as I have it, I will proved it.

Thanks for your fast reaction.

[8X8_HDMI_Matrix_Control_panel-V2.1.0.zip](https://github.com/bitfocus/companion-module-requests/files/6100721/8X8_HDMI_Matrix_Control_panel-V2.1.0.zip)

**Comment by WachterChristoph** [comment]
#376 is the same.

Looks like @jtrmc has the better documentation than me. 

Sorry for the double tracking
