### ISSUE TITLE
Blackmagic Design Web Presnter HD

### ISSUE THREAD

**Issue by 2to1mediallc** [bitfocus/companion-module-requests#438]
Just requesting that the stream functions be added to the list of supported devices for the Blackmagic Design Web Presenter HD.

**Comment by daniep01** [comment]
This module now exists in the latest beta.

**Comment by 2to1mediallc** [comment]
Please excuse my ignorance as I am very new to all of this but how do I
install the latest beta to test out the new module?

**Comment by daniep01** [comment]
You will need to create a free account at [bitfocus.io](https://bitfocus.io/) (unless you already have one) and then goto [https://bitfocus.io/companion/download/builds/](https://bitfocus.io/companion/download/builds/)

From the list of builds look for this section:

![image](https://user-images.githubusercontent.com/17852298/117469489-b5a89900-af4d-11eb-932c-709304137de5.jpeg)

**Comment by 2to1mediallc** [comment]
Awesome! Thank you so much!On May 7, 2021 11:03 AM, Peter ***@***.***> wrote:
You will need to create a free account at bitfocus.io (unless you already have one) and then goto https://bitfocus.io/companion/download/builds/
From the list of builds look for this section:
