### ISSUE TITLE
Discord.gg module

### ISSUE THREAD

**Issue by fccnorwalktech** [bitfocus/companion-module-requests#439]
I had an idea to create a module for Discord chat and voice channels.  Simple functionality such as mutes or macros to send via chat woudl be great.

Documentation for API is in the link below:
https://discord.com/developers/docs/intro

Functionalty ideas:

Voice - 
Mute
Unmute
Defen
Join specific voice channel

Text -
Send text macro

**Comment by Austinddan** [comment]
I would use this allot, we use discord for live chat between groups of the production team

**Comment by BrianGilbert** [comment]
+1

**Comment by cpbeaslin** [comment]
sometime similar to https://github.com/fredemmott/StreamDeck-Discord

**Comment by cpbeaslin** [comment]
something similar to https://github.com/fredemmott/StreamDeck-Discord

**Comment by thedist** [comment]
Just to add an update, I have been developing a Discord module but I'm waiting on the Discord team to open the RPC API again as right now it's limited to the apps that have previously been granted access and they're not currently accepting new apps into the testing.

**Comment by chabad360** [comment]
> Just to add an update, I have been developing a Discord module but I'm waiting on the Discord team to open the RPC API again as right now it's limited to the apps that have previously been granted access and they're not currently accepting new apps into the testing.

@thedist you can use the IPC API which is fully open (literally just tested it). See [discordjs/RPC](https://github.com/discordjs/RPC) for more.

**Comment by micbro123** [comment]
Is there a chance we could get a simple Discord Webhook Interface?

**Comment by thedist** [comment]
> Is there a chance we could get a simple Discord Webhook Interface?

I've already moved your previous topic on that subject to the discord modules repo as a feature request, https://github.com/bitfocus/companion-module-discord-api/issues/36

I'll work on it as and when I have the time to.

I'm also closing this module request, as Companion does include my Discord module now.

**Comment by micbro123** [comment]
Thank you!
