### ISSUE TITLE
Shure Systems Products

### ISSUE THREAD

**Issue by huebibelly** [bitfocus/companion-module-requests#443]
Hi Guys,
I would love to have control over a few Shure systems products, e.g. P300-IMX Audio DSP and the MXA Microphones (MXA910 Ceiling Array Mic, MXA710 Linear Array Mic, and MXA310 Table Array Mic)
Coulkd you be so kind and set up files for these devices???
I found some String Commands online that I attache here
Best 
Jochen

[MXA910_command-strings_en-US.pdf](https://github.com/bitfocus/companion-module-requests/files/6148005/MXA910_command-strings_en-US.pdf)

[MXA710_command-strings_en-US.pdf](https://github.com/bitfocus/companion-module-requests/files/6148007/MXA710_command-strings_en-US.pdf)

[P300_command-strings_en-US.pdf](https://github.com/bitfocus/companion-module-requests/files/6148043/P300_command-strings_en-US.pdf)

[MXCW_command-strings_en-US.pdf](https://github.com/bitfocus/companion-module-requests/files/6148121/MXCW_command-strings_en-US.pdf)

[MXA310_command-strings_en-US.pdf](https://github.com/bitfocus/companion-module-requests/files/6148129/MXA310_command-strings_en-US.pdf)

**Comment by josephdadams** [comment]
@huebibelly please break these out into separate module requests for each product. THANK YOU for including the protocol information!

@krocheck would any of these already be supported with the existing Shure modules?

**Comment by krocheck** [comment]
No, but only the MXCW would need to be split off to a separate request.  The rest should be able to be supported in a single module.
