### ISSUE TITLE
RGBLink Venus x3 

### ISSUE THREAD

**Issue by Nojbi2000** [bitfocus/companion-module-requests#444]
Hello,

It would be great to have native support for this presentation switcher, scaller, led processor.

Product desctiption:
X3, part of the RGBlink Universal Processor range, is a scalable, expandable videowall processor that is dynamically configurable across a wide range of modern display applications. Features high performance video scaling with one or more videos able to be displayed across a display surface of up to eight output displays..

Device link:
https://www.rgblink.com/product-detail?id=284

Here is API description:
https://www.dropbox.com/s/s3xxhwftu2zdsks/RGBlink%20VENUS%20X3p%20OpenAPI_20190710.pdf?dl=0

Functionality request:

Recalling presets, preview switching, program switching, loading banks.

This model X3 is part of line of Universal processors X2, X3, X7, X14 so it will find wide usage.
https://www.rgblink.com/universal-processors

I just did the settings and make it work by UDP module, but it would be great if someone can "cook" it into native support.

I can also provide access to this device for testing and will be active in testing.

Thank you
Jan

**Comment by dnmeid** [comment]
Module available, but not rewritten for v3. If it is not working, please open issue there.
