### ISSUE TITLE
Middle Control Software - Middle Things

### ISSUE THREAD

**Issue by thiblep** [bitfocus/companion-module-requests#446]
Would it be possible to make Companion compatible with the Middle Control Software ? https://www.middlethings.co/product-middle-control/

**Comment by josephdadams** [comment]
If there is an API for this software, you need to include a link. I did a brief search of their site and it does support hotkeys to run some functions, so for the functions that they list, you could use the VICREO Hotkey module in Companion and run the VICREO Listener program on your computer that has the Middle Control software installed, and trigger the hotkeys over the network this way.

Outside of that method, without an API, there is not much integration that can be done.
