### ISSUE TITLE
Axis Camera Vapix API

### ISSUE THREAD

**Issue by Fatzo757** [bitfocus/companion-module-requests#456]
Looking for a HTTP API for axis cameras. I am using a camera for streaming a large hall and looking to be able to remote control of camera PTZ controls, instead of web interface.

Thanks for the help.

[vapix_video_streaming_52937_en_1307.pdf](https://github.com/bitfocus/companion-module-requests/files/6192368/vapix_video_streaming_52937_en_1307.pdf)
[Vapix_ptz_52933_en_1307.pdf](https://github.com/bitfocus/companion-module-requests/files/6192405/Vapix_ptz_52933_en_1307.pdf)
[Axis Communications - VAPIX®.pdf](https://github.com/bitfocus/companion-module-requests/files/6200722/Axis.Communications.-.VAPIX.pdf)

**Comment by josephdadams** [comment]
Pretty simple HTTP API. I recommend anyone who looks to create this to use the Panasonic PTZ module as a boilerplate.

**Comment by fbosman** [comment]
I would like to start on this module, can you setup a reposory for me?

**Comment by WaltherWhite** [comment]
This would be great! 15 dutch theatres would be very happy for this to happen. Sadly I know next to nothing about javascript, but I'll be happy to test and provide feedback. 

Additional documentation about the VAPIX API can be found at https://www.axis.com/vapix-library/subjects/t10037719/section/t10036011/ . You'll need an account to access it.

**Comment by fbosman** [comment]
I'm testing the ptz functions yet. When the repo is available you can get access to this module.
Love to have it tested!

**Comment by Fatzo757** [comment]
I have two q6155-e ptz cameras for testing as well. One in production and one for testing. Thank you for your work.

**Comment by fbosman** [comment]
I made a test build: https://rkjohannesdedoper-my.sharepoint.com/:u:/g/personal/frans_jddoper_nl/ETx7WCiPx6xDrygTanYeyjABkoDrQzURI1IeHfq6jFRZZQ?e=uUgZPQ
Only PTZ and Zoom works at the moment, including the ptz and zoom presets.

**Comment by fbosman** [comment]
New testbuild: https://rkjohannesdedoper-my.sharepoint.com/:u:/g/personal/frans_jddoper_nl/ETx7WCiPx6xDrygTanYeyjABkoDrQzURI1IeHfq6jFRZZQ?e=jORPRK

**Comment by WaltherWhite** [comment]
Well, you certainly are fast. As soon as I'm back in the theatre I will give it a test. Probably sometime next week.
Thank you for your effort!

Ps. Would it be possible to make a MacOS build?

**Comment by fbosman** [comment]
As the module is now part of the companion beta builds I will remove this test build. You can also download a Mac build from the beta-builds.
