### ISSUE TITLE
Module request: Tvone Scaler Control

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion-module-requests#46]
**Describe the feature**
Remote control of the Tvone Corio2 scalers and switchers http://www.tvone.com/video-switchers

**Is this platform dependent (windows, mac, ..)?**
no, remote control via ip possible

**If documentation is required to implement, do you know where to find it?**
http://www.tvone.com/filestore/Manuals-CORIO-Products/tvONE%20C2-2x55%20Remote%20Control%20Specification%20V1.2.pdf

**Usecases**
Switching between cam mix and a PP pc

**Comment by daniep01** [comment]
I have a C2-2855 and would be happy to give this module a try if it is still required. I can't implement everything right away, is the priority setting freeze and loading presets?

**Comment by daniep01** [comment]
I have a basic version of this module working on my test system. It will need to go for approval and then release. Let me know if you have any function requests. I currently have

- Primary source
- Background source
- Freeze

**Comment by JeffreyDavidsz** [comment]
Merged into core

**Comment by sledzik1984** [comment]
C2-2855A is supported? Can't find it in 2.1.3

**Comment by daniep01** [comment]
It is included in the beta of 2.2.0

[https://bitfocus.io/companion/download/builds/](https://bitfocus.io/companion/download/builds/)
