### ISSUE TITLE
Magnimage V5

### ISSUE THREAD

**Issue by stevsimo** [bitfocus/companion-module-requests#464]
Somehow i can't get a connection to my Magnimage V5 via UDP. Would be great if the switcher could be supported.

**Comment by josephdadams** [comment]
@stevsimo please provide documentation on how the switcher can be controlled over the network

**Comment by Lessett** [comment]
> 不知何故，我无法通过 UDP 连接到我的 Magnimage V5。如果能支持切换器就好了。

MIG V series switches cannot support other external software and hardware control temporarily, only H series desktop switches can be used.
