### ISSUE TITLE
Blackmagic Design Web Presenter HD

### ISSUE THREAD

**Issue by audioman1983** [bitfocus/companion-module-requests#466]
**Describe the feature**
Basically only NEED start and stop stream function and the ability to use companion to schedule the trigger.

**Usecases**
Manually or Automatically start a live stream.

**Comment by josephdadams** [comment]
@audioman1983 please provide documentation or API

**Comment by jrviz** [comment]
The protocol is in https://documents.blackmagicdesign.com/UserManuals/BlackmagicWebPresenterHDManual.pdf?_v=1613635211000  It is a line oriented command structure over TCP so the TCP-UDP Generic module could make it work using a few actions and  a trigger. If you want feedbacks to show the stream on or off then that is a module.

**Comment by daniep01** [comment]
I'll try and write this module

**Comment by daniep01** [comment]
@audioman1983 

To test the new module please download and install this dev build of companion:
[https://we.tl/t-obo0lgfuWP](https://we.tl/t-obo0lgfuWP)

Please comment here if it works or has any issues.

**Comment by RobbieBott** [comment]
@danielp01 is there a way for me to download your module to expand on it? I would like to try and add "reboot". How much work am I looking at to add that option?

**Comment by daniep01** [comment]
The module is in github like all other companion modules. Anyone can make changes to the code and ask for them to be included. Alternatively I would be happy to add it for you.

https://github.com/bitfocus/companion-module-bmd-webpresenterhd

**Comment by daniep01** [comment]
@RobbieBott Actually I see someone else also requested reboot, so i will add that now.
