### ISSUE TITLE
Sony Broadcast / Post production monitors BVM-X300 / BVM-HX310

### ISSUE THREAD

**Issue by natjencks** [bitfocus/companion-module-requests#468]
These displays (X300 and HX310) are ubiquitous in Post Production as are their predecessors.  They have a painful menu system.  It would be incredibly valuable to be able to control via Streamdeck / companion.  The Sony control protocol documentation is attached.  Anyone interested?  For payment?
[Sony Professional Video Monitor Network Control Manual_EN_V100.pdf](https://github.com/bitfocus/companion-module-requests/files/6274240/Sony.Professional.Video.Monitor.Network.Control.Manual_EN_V100.pdf)

**Comment by daniep01** [comment]
Hi @natjencks 

If this is still a requirement then I may be able to help you.

**Comment by daniep01** [comment]
I have a test version of the module working on a PVM-A170. Currently it only controls mono on/off but could be expanded to cover the full spec if there's still interest.

**Comment by daniep01** [comment]
@josephdadams this can be assigned to me as I have working code

@natjencks are you still offering a bounty for me to finish this module and could you help test?

**Comment by josephdadams** [comment]
@daniep01 do you need me to create a bitfocus repo?

**Comment by daniep01** [comment]
@josephdadams @natjencks 
Happy to pick up this module again, please confirm your expectations in terms of functionality, timescales and payment.

**Comment by josephdadams** [comment]
@daniep01 I set up this repo for you: https://github.com/bitfocus/companion-module-sony-broadcastmonitor

**Comment by mattoshaughnessy** [comment]
Hi @daniep01 & @josephdadams

I will taking over this bounty from @natjencks.  Please reach to me directly, so we can get everything arranged.

**Comment by daniep01** [comment]
@josephdadams - this issue can be closed as completed.
