### ISSUE TITLE
Request: liminalet zoomOSC

### ISSUE THREAD

**Issue by jwworker201** [bitfocus/companion-module-requests#478]
An Instance for zoomOSC would be nice - It works like a charm via the Generic OSC Instance although I'd like to get OSC Feedback as well so that I can auto-populate Users in the meeting instead of manually writing it inside the buttons.

ZoomOSC:
https://www.liminalet.com/zoomosc

API/Control documentation:
https://filedn.com/lJhb55s9GTLpJecFnm56CRp/ZoomOSC/4.0/4.0.4/ZoomOSC%204.0.4%20Command%20Syntax.pdf

**Comment by krocheck** [comment]
Please see Companion v2.1.3, as this is supported in that version
