### ISSUE TITLE
Aida PTZ camera Control

### ISSUE THREAD

**Issue by thyREV** [bitfocus/companion-module-requests#486]
Could you make a companion module to control the Aida PTZ-NDI-X20 camera? 

Thanks a lot

**Comment by josephdadams** [comment]
Please provide documentation

**Comment by thyREV** [comment]
Here's the manual. Thanks

**Comment by thyREV** [comment]
Here is the manual

https://aidaimaging.com/wp-content/uploads/2020/11/AIDA-IPNDI-PTZ-manual-V2.1.pdf

**Comment by josephdadams** [comment]
It supports VISCA over IP. You should just use one of the existing VISCA modules in Companion. Start with the sony one.

**Comment by bakfiets2** [comment]
Yes. But the tally lights don't work...

**Comment by astrocasters** [comment]
Updated link to the manuals:  https://aidaimaging.com/download
[AIDA-IPNDI-PTZ-manual-V2.1(1).pdf](https://github.com/bitfocus/companion-module-requests/files/7646253/AIDA-IPNDI-PTZ-manual-V2.1.1.pdf)
/

**Comment by josephdadams** [comment]
duplicate of #281
