### ISSUE TITLE
RocoSoft PTZJoy

### ISSUE THREAD

**Issue by jdeheer** [bitfocus/companion-module-requests#487]
My church uses Rocosoft PTZJoy to control our PTZ cameras.  Would it be possible to add control of the HTTP commands from the URL listed below?

https://www.rocosoft.com/knowledge-base/controlling-cameras/ptzjoy-controller-http-request-commands-list/

Currently, I use the generic HTTP Requests module to accomplish this.  The 'Base URL' is set to "http://<IP>:<PORT>/PTZJoy=" and then each store recall button (1-16) has two GET commands "IntPresets" and "Preset3".  To store Preset 3, the button has a GET command of "SetIntPreset=3".  Both store and recall work, but an HTTP GET error is generated in the log file each time.  I don't know if that's because i'm not using any JSON data.  Either way, if a module for this software is possible, it would be MOST appreciated!

**Comment by daniep01** [comment]
Hi, 

This looks easy enough, I can write the module if you're happy to help with testing.

**Comment by JeffreyDavidsz** [comment]
@daniep01 if you make a complete one with Companion presets we will put an $150 in it for you. PM me on slack

**Comment by jdeheer** [comment]
I will happily test the module!! Thank you!Jeff
-------- Original message --------From: Peter ***@***.***> Date: 4/25/21  04:51  (GMT-05:00) To: bitfocus/companion-module-requests ***@***.***> Cc: Jeff DeHeer ***@***.***>, Author ***@***.***> Subject: Re: [bitfocus/companion-module-requests] RocoSoft PTZJoy (#487) 
Hi,
This looks easy enough, I can write the module if you're happy to help with testing.

**Comment by daniep01** [comment]
Do you have companion installed from source or do you need me to make a test build? Can you test on Windows?

**Comment by daniep01** [comment]
> but an HTTP GET error is generated in the log file each time

Could you paste the error text here please?

**Comment by jdeheer** [comment]
I have it installed on windows and I would need a test build.  I don't have it installed from source.

I am not at church right now, but will be in a couple of hours.  i can post the error then.

Jeff

**Comment by jdeheer** [comment]
Here are some screenshots of the button setup for recall and store, as well as the error message.  The camera responds to these commands, Companion just produces the attached error.
![2021-04-25 15 06 12](https://user-images.githubusercontent.com/8688147/116014302-a860e580-a602-11eb-803e-f976f5253b29.jpg)
![2021-04-25 20_12_07-Window](https://user-images.githubusercontent.com/8688147/116014312-af87f380-a602-11eb-9dd0-bac5588b953c.png)
![2021-04-25 20_12_20-Window](https://user-images.githubusercontent.com/8688147/116014317-b4e53e00-a602-11eb-82fc-2958d350fa5e.png)

**Comment by jdeheer** [comment]
here is the picture of the connection setup:
![2021-04-25 20_14_16-Window](https://user-images.githubusercontent.com/8688147/116014351-e3631900-a602-11eb-8eb7-c48ef6f6e210.png)

**Comment by daniep01** [comment]
Thanks Jeff, I've been able to get a trial copy of the ptzjoy software which will be a great help with testing this.

**Comment by daniep01** [comment]
The first version is done, it's working well for me so I've asked for it to be added to the next beta release of companion. Should appear in a few days, I'll let you know when it's available.

**Comment by jdeheer** [comment]
Fantastic!  I will happily test it when available.  Many thanks!!Jeff
-------- Original message --------From: Peter ***@***.***> Date: 4/27/21  05:11  (GMT-05:00) To: bitfocus/companion-module-requests ***@***.***> Cc: Jeff DeHeer ***@***.***>, Author ***@***.***> Subject: Re: [bitfocus/companion-module-requests] RocoSoft PTZJoy (#487) 
The first version is done, it's working well for me so I've asked for it to be added to the next beta release of companion. Should appear in a few days, I'll let you know when it's available.

**Comment by daniep01** [comment]
Please download the latest beta build from 

[https://bitfocus.io/companion/download/builds/](https://bitfocus.io/companion/download/builds/)

This includes the ptzjoy module, let me know how testing goes and if you would like any changes.

**Comment by jdeheer** [comment]
downloaded and tested it this evening.  I tested saving a preset, recalling a preset, moving the camera, selecting different cameras, zooming, and selecting interal/external presets.  All worked flawlessly.  For my needs, I consider this complete.  Thank you so very much for doing this!  I got no errors in the log file and everything worked exactly as expected.

Many thanks!

Jeff

**Comment by daniep01** [comment]
Great to hear, thank you. If you find anything in future please open a new issue in the ptzjoy repository.

[https://github.com/bitfocus/companion-module-rocosoft-ptzjoy](https://github.com/bitfocus/companion-module-rocosoft-ptzjoy)

Peter
