### ISSUE TITLE
Samsung Sero Rotate and Input Switch via Companion

### ISSUE THREAD

**Issue by Daleyelama** [bitfocus/companion-module-requests#488]
I am looking for a solution to rotate and switch between two HDMI inputs on the Samsung Sero via bit focus companion. So I would appreciate your help very much. I am clear, that there must be something like a infrared module, which replaces the remote control.. is there anything on the market? Thank you

**Comment by josephdadams** [comment]
@Daleyelama Companion has support for the GlobalCache iTach IR devices: https://www.globalcache.com/products/itach/ip2irspecs/
