### ISSUE TITLE
Module Request: MimoLive

### ISSUE THREAD

**Issue by HaroldvanDieren** [bitfocus/companion-module-requests#49]
Describe the feature
Mimolive - video engine midule

Is this platform dependent (windows, mac, ..)?
Module

If documentation is required to implement, do you know where to find it?
https://docs.mimo.live/docs/endpoints

Usecases
Turn Layers on or Off

**Comment by flashbangmedia** [comment]
I don't suppose there is any rough timeline for this to happen?
I can set it up manually in the http requests but its a massive pain to do for each button particularly when the shows change a lot.

**Comment by josephdadams** [comment]
There are so many outstanding module requests, with most of the modules requested being ones that those of us who actively create for Companion would not ever use. That doesn’t mean it couldn’t happen eventually, but this is something done in spare time. If you wanted to consider paying someone to create it, that could help it get made faster.

**Comment by PhotoJoseph** [comment]
I'll +1 this… getting more info from mimo on the buttons in general would be great. Just getting the name of the layer instead of only a URL would be sweet. Accessing individual layers would be even better!

**Comment by oliverbreidenbach** [comment]
There is now a Stream Deck plugin for mimoLive (https://github.com/boinx/mimoLive-Stream-Deck-Plugin). It should be fairly easy to take this and turn it into a Companion module? Is there an example of how to do this?

**Comment by josephdadams** [comment]
@oliverbreidenbach https://github.com/bitfocus/companion/wiki/Module-Development

**Comment by sphlabs** [comment]
There is now a working mimoLive module. It is available as part of the latest beta build of v.2.2.

Any issues can be filed here: https://github.com/bitfocus/companion-module-boinx-mimolive/issues
