### ISSUE TITLE
Kiloview encoders and decoders support

### ISSUE THREAD

**Issue by rpetrov1** [bitfocus/companion-module-requests#491]

**Comment by rpetrov1** [comment]
I have Kiloview API's

**Comment by josephdadams** [comment]
Then you should share them :)

**Comment by gerbrando** [comment]
The HTTP API for the Kiloview E1 encoder is available from the web admin of the device. 
I have downloaded a copy that can be accessed here:  http://kiloview-api.engagetv.com
(Hardware Ver.: 1.6.20, Firmware Ver.: 2.5.0, Software Ver.: 4.6.2405)

It seems that the API can do everything that you can also do with the web admin gui. 
For the decoder devices, there must be additional commands not listed in the documentation linked here.

**Comment by tigert10** [comment]
Is any work being done on this module? I'd love to see this implemented...eagerly waiting.

**Comment by tigert10** [comment]
> Then you should share them :)

It seems as though gerbrando has posted the API documentation for this device. Is this info sufficient? Link here:

http://kiloview-api.engagetv.com/

**Comment by josephdadams** [comment]
It's sufficient for me to remove the `missing documentation` label. As far as I know, no one is actively working on this.

If you need it urgently, I am available for hire.

**Comment by tigert10** [comment]
Right on. Thanks. I don't need it urgently. I will tinker with it myself and hopefully someone else smarter than I can ti keep with it too. Looking forward to this implementation.

**Comment by letsjustfixit** [comment]
Hey!
I've started working on a module to start/stop recording on kiloview E1. At the moment the modules name is:
kiloview-recording-control so please create a companion module: companion-module-kiloview-recording-control
Thank you

**Comment by josephdadams** [comment]
With the kiloview e1 being an encoder, I'd rather we call the repo `companion-module-kiloview-encoder`, even though it will only have start/stop recording for now. Your thoughts?

**Comment by tigert10** [comment]
I think that's great! You're the best thanks!

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-kiloview-encoder

@letsjustfixit you have write access to this repo. Let me know when you're ready for a code review.

**Comment by letsjustfixit** [comment]
well my tought pattern was to introduce this functionality and hopefully maybe extend to other kiloview products with the same (very similar) api as well(I would need to dig around a bit to compare device apis but thats a task after this initial one works as it should :-) ), but this current naming convention works just as well:

Thanks for the fast response! I've just started off working on this its going to take a while to have some initial push worthy code :-).

**Comment by josephdadams** [comment]
Well, if you do something that works with a decoder, we can always make a kiloview-decoder module also.

**Comment by gda-nh** [comment]
API for Kiloview S2. The existing module for Kiloview doesn't work for the S2 although some of the same commands seem to work in a browser - the syntax for the URL's have changed.

[S2-HTTP-API-en-220414.pdf](https://github.com/bitfocus/companion-module-requests/files/11885206/S2-HTTP-API-en-220414.pdf)

**Comment by dnmeid** [comment]
As the module is available, please direct any requests for additional functionality or support there.
