### ISSUE TITLE
http feedback

### ISSUE THREAD

**Issue by Qwiko** [bitfocus/companion-module-requests#495]
Be able to get feedback from http requests to display.
With custom json nesting so you can get .status.power displayed as color depending on value

**Comment by josephdadams** [comment]
I don't see an avenue of doing this with the generic HTTP module; you would need a custom module. If the device you're controlling is an industry standard device, then make a module request. If you're controlling a custom server, just have your server send the necessary requests back to companion to change a button color, etc.
