### ISSUE TITLE
Module Request: NEC Display 

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion-module-requests#50]
**Describe the feature**
NEC Display Module

**Is this platform dependent (windows, mac, ..)?**
Module

**If documentation is required to implement, do you know where to find it?**
https://www.necdisplay.com/documents/UserManuals/P402-P462-P552_UserManual.pdf

**Usecases**
For installation to be able to turn off and on. 
Change Input setting if using as a BASIC switcher
[P402-P462-P552-UserManual-english.pdf](https://github.com/bitfocus/companion/files/2727602/P402-P462-P552-UserManual-english.pdf)

**Comment by bryce-seifert** [comment]
Any updates on this? Be happy to help test.
