### ISSUE TITLE
DENON AVR DN-500AD Support

### ISSUE THREAD

**Issue by mfoulks3200** [bitfocus/companion-module-requests#525]
This should be a super simple module to integrate, and I've already done all the leg work. This device is TCP on port 23. A list of commands can be found in the attached doc. All commands must be terminated with a `\r`
[FY21AVR_DENON_PROTOCOL_V02_04062020.xlsx](https://github.com/bitfocus/companion-module-requests/files/6618688/FY21AVR_DENON_PROTOCOL_V02_04062020.xlsx)

**Comment by istnv** [comment]
Have you looked into updating the existing Denon AV Receiver module ?

**Comment by mfoulks3200** [comment]
The naming needs to be updated on that module, it is not a universal protocol

**Comment by istnv** [comment]
Every command in the current AV Module is identical to the parameter list you uploaded.
New functions would add new commands.

**Comment by mfoulks3200** [comment]
You're right, I guess I was looking at the wrong repo. I'll leave this issue open to submit a pull request with the rest of the updated commands.

**Comment by istnv** [comment]
The BD (blu-ray player) and -R (recorder) each have a different protocol. Denon has been pretty consistent within product lines. All of the 'recorder' choices are the same module.

**Comment by mfoulks3200** [comment]
The 500AD is just a receiver I believe

**Comment by mfoulks3200** [comment]
Implemented in PR https://github.com/bitfocus/companion-module-denon-receiver/pull/3
