### ISSUE TITLE
GENERIC feedback 

### ISSUE THREAD

**Issue by tobielepine** [bitfocus/companion-module-requests#526]
I have a process that refreshes a dynamic number and puts it on the clipboard on a computer with Companion. Is there anyway to display those  4-11 characters on a button using feedback ?

It would be nice to have a way to pull data from a .txt .csv or windows clipboard and frequently update a button's text and color. 

usecase: Open profit and loss for day traders.  

I use robotask and vicreo listener with companion. Robotask can store variables and create, overwrite .txt and .csv files in the background, getting those values pulled out in real time would be nice.

**Comment by josephdadams** [comment]
You would need to create a specific module for Robotask, provided it has an API or way of communicating with Companion to send that data back for feedback and display.
