### ISSUE TITLE
Module Request: Combiwave control

### ISSUE THREAD

**Issue by ghost** [bitfocus/companion-module-requests#53]
**Describe the feature**
I use Combiwave to play audio for live events. I need to be able to trigger multiple machines running combiwave. As a basic feature Combiwave uses the keyboard as hotkeys to play the relevant audio track so I need to send keyboard commands over TCP to the windows machines.
In particular the return key is play, space bar is stop and up and down arrows select the audio. That is in addition to the full keyboard and numbers.
As a more advance feature it would be good to be able to control features such as simultaneous play, loop, play next, and be able to select audio outs
**Is this platform dependent (windows, mac, ..)?**
Windows
**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.
Many pro sound engineers use combiwave (those that dont like macs!) and run a main and backup laptop. This would enable the backup to be a true hot back up 
This would also be a massive improvement in the general cueing of audio as the stream deck can be closer to hand and the sound desk making life a lot better.
it would make it possible to control different machines running in different locations from 1 single place. eg, when running BGM in different locations, VOGs can be triggered.

Many thanks.

**Comment by josephdadams** [comment]
@ghost is a deleted account. This request can be accomplished with the VICREO hotkey module. Closing this request for both of those reasons.
