### ISSUE TITLE
Module Request: For-A Hanabi HVS-100/110 Switcher

### ISSUE THREAD

**Issue by mikesmithdudeman** [bitfocus/companion-module-requests#531]
These switchers have become extremely popular in the Live video world, because they are great as both a small production switcher and a multi-destination screen switcher.  They have a fantastic little web server in them as well, though I don't know if that would enable html commands or maybe webhooks or something like that.  

Currently, there is no documentation by For-A for any other IP-based control of these switcher; so I have asked them to please provide it, or release a firmware update enabling such control.  Would love to see what more technical people than myself are able to find out, and I will also re-post with any information I receive from For-A.

**Comment by daniep01** [comment]
This module has been written 👍🏻 
https://bitfocus.io/support/fora-hvs?1.2.2
