### ISSUE TITLE
MixEffect Module

### ISSUE THREAD

**Issue by adamtow** [bitfocus/companion-module-requests#532]
I'm the developer of [MixEffect](https://mixeffect.app), an app for iOS and iPadOS to control Blackmagic ATEM switchers. I have some unique features in MixEffect such as my animated SuperSource presets and Video Follows Audio feature. Would like to work with someone to create a module in Companion with pre-defined commands, menus, and fields. 

**Platforms**

iOS and iPadOS

**Documentation**

I have an OSC server running in the app, and my current instructions for Companion instruct the user to use the Generic OSC module to control the app.  Current list of supported commands is here: [https://mixeffect.app/docs/osc](https://mixeffect.app/docs/osc)

**Comment by josephdadams** [comment]
@adamtow I’d like to help. Not a heavy ATEM user but looking to mentor someone who works for me in Companion module dev and this would be a good one for that person.

**Comment by adamtow** [comment]
Sure. Let’s talk! Ping me on the Bitfocus Slack and we can get started. I think the initial implementation will be relatively straightforward. If we want to add feedback, it may get more complicated. Thanks!

**Comment by Kronk7** [comment]
I am starting on this now.

**Comment by estilles** [comment]
@Kronk7 ... I hope you don't mind, but I've decided to pick up the development of this module. I happen to be a MixEffect user.

If anyone is interested, you can track my progress [here](https://github.com/estilles/companion-module-tow-mixeffect).

Is there any chance I can get a repo created for module within the Bitfocus org? Thanks!

**Comment by josephdadams** [comment]
@estilles https://github.com/bitfocus/companion-module-tow-mixeffect

**Comment by estilles** [comment]
> @estilles https://github.com/bitfocus/companion-module-tow-mixeffect
Thanks @josephdadams.

**Comment by estilles** [comment]
I'm happy to report our initial release is ready.

**Comment by estilles** [comment]
The intial version of this module is now on the Companion core beta. Thanks to everyone for their help. 

We can probably close this issue now.
