### ISSUE TITLE
Boxcast (Livestreaming)

### ISSUE THREAD

**Issue by shaunar2006** [bitfocus/companion-module-requests#539]
I would love to be able to stop a live broadcast by pressing a companion button. Maybe a button that automatically stops any live broadcast within a specific channel? Not sure if this is possible with Boxcast API.

Would also be awesome if the press of a button could create and start a new broadcast with title, description, start & end times, etc. This is possible using Boxcast API. I just dont if it would be able to be implemented on companion.

Boxcast API: https://www.boxcast.com/product/developers

**Comment by josephdadams** [comment]
Duplicates #35 , read the last comment over there, sounds like not every plan is able to use the API.

**Comment by josephdadams** [comment]
This module is now in the betas.
