### ISSUE TITLE
New Raspberry Pi Installation

### ISSUE THREAD

**Issue by RoggieRog** [bitfocus/companion-module-requests#543]
Hello. I just got a Pi4 B 8GB and did a manual Companion installation while following the directions very carefully. At present, I have a few issues:

-I don't get the welcome message when I first boot up either via a connected monitor, or via a PuTTY SSH session. 
-I am unable to update via the "sudo companion-update" command. I get a command not found error. 
-Upon my initial opening up of Companion via a browser on another laptop, not only were there no connections available, but the list to the right was empty. I'd type something and nothing would show up. A few minutes later the list was populated. Is this an expected first time kind of thing, or will this be the case each and every time I use it?

This is what I have for now. 

Thanks in advance for your help.

**Comment by josephdadams** [comment]
This is not a module request, so it should not be posted here.
