### ISSUE TITLE
Support for Kiloview E1/E2 H.264 Encoder.

### ISSUE THREAD

**Issue by foomankk** [bitfocus/companion-module-requests#544]
**Describe the feature**
Support for Kiloview encoder  to trigger Record and Streaming using Decklink.

**Usecases**
The E1/E2 uses a web interface and does not have any physical buttons to trigger record and streaming. Support would enable the hardware buttons on the Deck Link for stop and start.
Wondering if anyone is working on it?
https://www.kiloview.com/en/encoder/h264-wired/

**Comment by josephdadams** [comment]
#491 duplicate
