### ISSUE TITLE
tvONE CORIOmaster

### ISSUE THREAD

**Issue by dombuerkler** [bitfocus/companion-module-requests#549]
[tvONE CORIOmaster Commands_current.pdf](https://github.com/bitfocus/companion-module-requests/files/6776245/tvONE.CORIOmaster.Commands_current.pdf)

It would be fantastic to have control of some major features; call presets, route inputs to outputs, take.

[WebsocketAPI_CORIOmaster_current.pdf](https://github.com/bitfocus/companion-module-requests/files/6776277/WebsocketAPI_CORIOmaster_current.pdf)

**Comment by josephdadams** [comment]
tvONE CORIO is supported in the latest builds.

**Comment by dombuerkler** [comment]
> tvONE CORIO is supported in the latest builds.

Hi Joseph
Thanks for your reply. Unfortunately I'm not able to find tvONE in Companion 2.1.3.
Neither by searching "Add by manufacturer" nor "Add by search...".
What am I missing?

Kind regards
Dominic

**Comment by daniep01** [comment]
Please try the 2.2 build on this page
https://bitfocus.io/companion/download/builds/

**Comment by dombuerkler** [comment]
Great, that's the answer I needed! :)
