### ISSUE TITLE
Allen & Heath AHM64

### ISSUE THREAD

**Issue by ignotus-sum** [bitfocus/companion-module-requests#556]
Need a module to control the AHM 64. This is a great installation audio processor and switcher, but needs an ipad to control it. Would be great to have the simplicity of a stream deck. Is there any developer out there who is familiar enough with the product to develop something either open source or as a paid project? Contact me... looking for a developer to create this, even az a paid gig!

https://www.allen-heath.com/ahm-64/
https://www.allen-heath.com/media/AHM-64-Technical-Datasheet-1.pdf
https://www.allen-heath.com/media/AHM-TCP-Protocol-V1.pdf

also some module that would allow control of tuya/grosund  dimming switches from the streamdeck

elgato stream deck(s) running on companion pi would provide simple systems were they could be integrated

**Comment by buck-rogers999** [comment]
https://www.allen-heath.com/media/AHM-TCP-Protocol-V1.4.pdf

**Comment by buck-rogers999** [comment]
https://www.allen-heath.com/thirdpartycontrol/

**Comment by Phil0** [comment]
Maybe have a look at [this Module](https://github.com/bitfocus/companion-module-allenheath-ahm)

**Comment by bryce-seifert** [comment]
This module has been available in Companion for a while, with basic functionality. I’m currently working on adding additional features. Please refer any other issues or requests to that [repo](https://github.com/bitfocus/companion-module-allenheath-ahm)
