### ISSUE TITLE
Brompton Tessera Control

### ISSUE THREAD

**Issue by dtrench** [bitfocus/companion-module-requests#561]
Remote control for Brompton LED processors. Control over blackout options, brightness and colour.

[TesseraIPControlAPI3_2_1.pdf](https://github.com/bitfocus/companion-module-requests/files/6855495/TesseraIPControlAPI3_2_1.pdf)

**Comment by josephdadams** [comment]
Time for you to upgrade to the latest beta build, because there's a Brompton Tessera module now!

https://github.com/bitfocus/companion-module-brompton-tessera

**Comment by dtrench** [comment]
Thanks!
- -

*Dan Trenchard*

+44 7814 349 707
***@***.***
