### ISSUE TITLE
Elgato Stream Deck MK2 doesn't recognized by companion...

### ISSUE THREAD

**Issue by paswag** [bitfocus/companion-module-requests#562]
Hi everybody,

poorfully my companion application does not recognize my brand new Stream Deck MK2... Maybe there is at this time no support for the new device?

I would be really happy when there is an update soon, because I mostly bought it to use with companion.

Thanks for your help and your genius application.

Pascal

**Comment by josephdadams** [comment]
@Julusian its supported in the latest betas correct?

**Comment by Julusian** [comment]
Yep, it works in the betas

**Comment by josephdadams** [comment]
@paswag sounds like you need to upgrade your version of companion.
