### ISSUE TITLE
WattBox IP

### ISSUE THREAD

**Issue by Austinddan** [bitfocus/companion-module-requests#573]
**The name of the device, hardware, or software you would like to control:**
WattBox IP series power devices.
**What you would like to be able to make it do from Companion:**
Turn individual outlets on off or run a power cycle. I would also like to receive status of an outlet (on/off) so it can be indicated in the companion button feedback. 
**Direct links or attachments to API:**
https://www.snapav.com/wcsstore/ExtendedSitesCatalogAssetStore/attachments/documents/PowerManagement/SupportDocuments/Wattbox%20API%20v2.0.pdf

This module seems easy to build, the devices respond to HTTP requests. As always, I'm happy to test and provide feedback.

**Comment by josephdadams** [comment]
This exists now. @jtf4 made it and it’s in Companion
