### ISSUE TITLE
New Module for BlueBolt BB-RS232

### ISSUE THREAD

**Issue by tyler351** [bitfocus/companion-module-requests#593]
Wondering if it's possible to create a module for controlling BlueBolt BB-RS232. This device allows remote power sequencing of Furman power sequencing equipment used in most A/V installations. The device communicates to a web portal to give control and communicates to its devices over an RS232 connection. A module that would allow a person to initiate a sequence event would be really cool!

Link to product: https://furmanpower.com/product/bluebolt-ethernet-to-d9-rs232-adaptor/

**Comment by tyler351** [comment]
After looking more at it, I think this is similar a request someone recently made (https://github.com/bitfocus/companion-module-requests/issues/689). It can also use udp messages sent in xml format. See here (http://resources.nortekcontrol.com/products/BB-RS232/pdf_BB-RS232_datasheet.pdf)

**Comment by tyler351** [comment]
Did some more testing with the generic udp module and have been able get the bluebolt device to accept commands when sent from companion!

**Comment by elliotmatson** [comment]
Our team would likely be able to put a financial reward behind this project if I don't find time in the next few weeks to figure out writing companion modules. This would likely best be implemented as a module for all the BlueBolt enabled products, as they all have very similar commands over UDP port 57010.

Also this now has documentation, so the "Missing Documentation" tag can be updated.

**Comment by josephdadams** [comment]
@elliotmatson if you’d like, I’m available for hire to write this. My email is on my github profile if you’d like to discuss.

**Comment by elliotmatson** [comment]
@josephdadams I'll let you know! I do want to take a stab at it, if not just so I can more heavily contribute to to other modules in the future.

**Comment by elliotmatson** [comment]
I have an initial version here: [companion-module-nortek-bluebolt](https://github.com/bitfocus/companion-module-nortek-bluebolt)

Currently, it only supports the M4000 Pro, as that's the only model I have access to, but our BB-RS232 is on the way and I should be able to work on that next week

**Comment by tyler351** [comment]
That's dope! I'd love to learn how to build modules myself. 
Thanks for putting in the time to put this together!

**Comment by elliotmatson** [comment]
@tyler351 Absolutely!

I have a build that **should** work with the BB-RS232 and all SmartLink-chained devices, if I send it to you could you test it for me?

**Comment by tyler351** [comment]
Definitely! I'd be happy to help.

**Comment by elliotmatson** [comment]
Great, it got pushed to the latest Companion beta release, so you can download it on the bitfocus website! Our BB-RS232 gets here today, so I'll also be able to start testing

**Comment by elliotmatson** [comment]
@josephdadams this one can be closed also, we got our BB-RS232 yesterday and the module works as expected!
