### ISSUE TITLE
QLC+ Integration

### ISSUE THREAD

**Issue by wmcelroy1** [bitfocus/companion-module-requests#612]
Integration of the DMX control software QLC+ would be very helpful
https://www.qlcplus.org/

This software is amazing and packed with features. It's a great alternative to high priced consoles and other DMX software.

**Comment by jpooley-hearst** [comment]
Control of QLC+ already works via OSC, but feedback is not possible. Is anyone able to add functionality to provide OSC feedback to Companion?

**Comment by josephdadams** [comment]
https://www.qlcplus.org/docs/html_en_EN/oscplugin.html

**Comment by robsidle** [comment]
+1 for a specific QLC+ module. OSC feedback would be wonderful. Got 1 way OSC commands into QLC, but it wasn't very clear how to.

**Comment by jendamozna** [comment]
here is a link to their websocket interface: https://www.qlcplus.org/Test_Web_API.html
