### ISSUE TITLE
Midas Pro Series

### ISSUE THREAD

**Issue by FSpille** [bitfocus/companion-module-requests#621]
Hi, 

I'd like to request a Module for OSC remote control of Midas Pro Series Audio desks ( Pro 1 / Pro 2) 
Module would be handy to:
Remote of Mute / Solo Status 
Remote of Fader / Send Levels 
Displaying Names of different channels in companion 

All the good stuff we're able to do with me M/X32 Module. 
Thanks

**Comment by josephdadams** [comment]
#371
