### ISSUE TITLE
Canon PTZ CR-N300 XC or Visca 

### ISSUE THREAD

**Issue by bcrptz** [bitfocus/companion-module-requests#622]
Hi all,

I can't find a fully working module to control Canon PTZ Cameras like the CR-N300.  This uses Canon's XC Protocol and also Visca.

I've tried using the Sony Visca protocol which works for some features but then things like zoom in/out do not work.

**Comment by Camera84** [comment]
I have the document

**Comment by jznofc** [comment]
[XC Protocol_Specifications.pdf](https://github.com/bitfocus/companion-module-requests/files/7592141/Canon_XC_Control_Protocol_Specifications.1.pdf)

Document attached

**Comment by josephdadams** [comment]
module exists https://github.com/bitfocus/companion-module-canon-ptz
