### ISSUE TITLE
ChamSys QuickQ

### ISSUE THREAD

**Issue by lxdesigner** [bitfocus/companion-module-requests#624]
file:///Users/lxdesigner/Documents/QuickQ%20v6%20Manual.html#section-ethernet-remote-control

**Comment by josephdadams** [comment]
I will update the title of this request because it sounds like you want a QuickQ module, and there's already a MagicQ UDP module.

**Comment by lxdesigner** [comment]
Thank you. That is correct.

**Comment by josephdadams** [comment]
#239
