### ISSUE TITLE
Paid Module Request Shure

### ISSUE THREAD

**Issue by Paddy100288** [bitfocus/companion-module-requests#626]
I am looking for someone to create a couple of Shure modules for Companion.

Devices are the MXN5 Speakers and MXA910 Microphone.

Who can help me?

Thanks, 
Paddy

**Comment by Paddy100288** [comment]
Hi Keith,

 

Just wondered if you got my reply on Friday? If so, do you have an update?

**Comment by josephdadams** [comment]
I am working on these per my offline discussion with @Paddy100288

**Comment by josephdadams** [comment]
Pending payment to release these modules to core.
