### ISSUE TITLE
Paid module request for Yamaha new product Adecia

### ISSUE THREAD

**Issue by Yamaha316** [bitfocus/companion-module-requests#633]
I work for Yamaha and we recently launched a new family of audio products named Adecia. I am looking to create a module for our  processor RM-CR. I only need a few simple commands like mute\unmute, volume +\-, limit beam. I have the full API and can get you other resources if you need. I am willing to help anyway that I can and provide testing. I will offer compensation for this and if successful will have additional products for this with compensation.

Please let me know if anyone can help.

**Comment by daniep01** [comment]
I have successfully completed a number of companion modules and would be happy to help.

**Comment by Yamaha316** [comment]
Hey Peter,

Thank you for the quick response on this. How much compensation would you
want for this? Also, is there anything you would need from me other then
the API command list? I am happy to jump on a call if it’s helpful.

**Comment by daniep01** [comment]
Hi @Yamaha316,
I would need to review the API and understand what is required before giving you a price. Can I contact you by email?

**Comment by Yamaha316** [comment]
That sounds good. Please email me at ***@***.***

Thank you and I look forward to speaking!

**Comment by daniep01** [comment]
Hi, unfortunately your email has been masked by github but you can send me a message through my website pjdaniel.org.uk and I will reply to you.

**Comment by daniep01** [comment]
@Yamaha316 Or you can email 

contact(at)pjdaniel(dot)org(dot)uk

**Comment by Yamaha316** [comment]
Thank you so much Peter! I will be in touch shortly on this.

**Comment by josephdadams** [comment]
Since development for this is happening offline, I’ll close this. @daniep01 tag me when you’re ready for official repos. @Yamaha316 if you have other needs feel free to tag me as well.
