### ISSUE TITLE
SHURE Wireless Workbench unlock button

### ISSUE THREAD

**Issue by pylaflamme** [bitfocus/companion-module-requests#635]
Hi guys!
I’m looking if someone can create a button to lock and unlock the power or the menu (or both) for Axient Digital transmitter (ADX1, ADX2 and ADX3).
I don’t know if it’s possible because they are more controlled by Shure Wireless Workbench, but if it’s not directly, can you made an instance to control Shure Wireless Workbench?
Thank you so much!!

**Comment by krocheck** [comment]
The published protocol for ADX does not include remote control of the locks, so the existing [Shure Wireless module](https://github.com/bitfocus/companion-module-shure-wireless/blob/master/HELP.md) can't support this feature.  I can't find an API spec for WWB, so I don't think this is possible.

**Comment by pylaflamme** [comment]
Thanks for your answer, but just to make sure that we understand each other, are you saying that ADXs cannot be controlled remotely?  Because in fact they are handled by the WWB software through the properties of each of the units.
![5B4A464E-5967-4875-8C89-2BFD5CBECA75](https://user-images.githubusercontent.com/49406978/141687169-1e6b91db-24d5-4706-ae0c-6addd62bc843.png)

**Comment by krocheck** [comment]
Hey, so I'm saying that the [remote control spec](https://pubs.shure.com/command-strings/AD4/en-US) does not include lock control ... only readout.  I re-checked it before responding.  We do already have ADX control for RF power and output, but that's all Shure has provided in the spec.
