### ISSUE TITLE
Module Request: Mediashout

### ISSUE THREAD

**Issue by monoxane** [bitfocus/companion-module-requests#64]
**Describe the feature**
Control for Mediashout without octopus

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
It's apparently powerpoint compatible, I'll just Wireshark the remote app anyway because documentation is lacking to say the least...

**Usecases**
Churches use Mediashout a lot and I want to make more modules /shrugface

**Comment by obcocav** [comment]
We are looking into mediashout now.  It appears in the trial that a remote app and remote web control is now available.  Can’t find the docs but any chance this could have another look?  Thanks
