### ISSUE TITLE
sidus link app

### ISSUE THREAD

**Issue by Morrisduijkers** [bitfocus/companion-module-requests#643]

**Comment by Morrisduijkers** [comment]
I am sorry i am not that technical but the sidius app is a controller for aputure lights it would be nice to be able to controle light intensitie and the color of the light

**Comment by babul** [comment]
I would also so love to be able to control/trigger Sidus Link through Companion.

https://www.sidus.link
Sidus Link is an app to control Aputure lights through their proprietary mesh technology. 

Sadly it does not appear to have a public API or any technical information on control/trigger outside of their proprietary app 😞

**Comment by josephdadams** [comment]
#623

**Comment by JerryI** [comment]
Now it is 2022. We still have no access to  it. :( Only the glitchy Music FX is available. It sucks

**Comment by caseybasichis** [comment]
Have there been updates on this?

**Comment by josephdadams** [comment]
No. No one has offered any documentation on how to control the product

**Comment by kissu** [comment]
Latest news here: https://github.com/bitfocus/companion-module-requests/issues/623#issuecomment-2174595425
