### ISSUE TITLE
Syntax error token

### ISSUE THREAD

**Issue by Lintel-2011** [bitfocus/companion-module-requests#659]
I have a problem with BitCompanion since today (see picture). I do not know what to do about it.

This has already been done:
- Restart (program & computer)
- Uninstall and install

I need very urgent help!

![Screenshot 2021-12-08 193129](https://user-images.githubusercontent.com/95773372/145265253-71c49653-0cb6-4a30-8a90-d3c806cd1eac.png)

(a javascript error occurred in the main process)

**Comment by josephdadams** [comment]
Corrupted database. Also this is not a module request.
