### ISSUE TITLE
Module Request: Hippotizer

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion-module-requests#66]
I would like to request a module for Green-Hippo Hippotizer.

Maybe this link can be helpful:
https://www.green-hippo.com/manual/hippotizer-v4/4.4.0/en/topic/tcp-listener

thx in advance

**Comment by AlexWHughes** [comment]
You can already do basic stuff via OSC if you are looking for a quick solution. As long as you send OSC strings Hippo will read and understand them.

**Comment by SalkinDK** [comment]
> You can already do basic stuff via OSC if you are looking for a quick solution. As long as you send OSC strings Hippo will read and understand them.

I know how to do different workarounds but it would still be nice with a official module

**Comment by josephdadams** [comment]
@nagthas @JeffreyDavidsz can we close this? There’s a hippotizer module now?

**Comment by JeffreyDavidsz** [comment]
If there is a module, please close this

**Comment by Nagthas** [comment]
Yes, there is a module now so you can close it.
