### ISSUE TITLE
tp-link KASA Smart Switch

### ISSUE THREAD

**Issue by jvande7471** [bitfocus/companion-module-requests#663]
I would love to have a module that operates the Kasa smart switch.  I imagine this will be extremely similar to the Kasa smart plug module that exists.

**Comment by josephdadams** [comment]
Have you tried the current Kasa plug module with the switch? I find the same commands turn our plugs and switches on and off just fine.

**Comment by jvande7471** [comment]
I texted that this morning.  The plug module works well for the smart switch and smart 3-way.  It will also turn the dimmer on and off.
