### ISSUE TITLE
Aximmetry Support

### ISSUE THREAD

**Issue by DuffyManCZ** [bitfocus/companion-module-requests#666]
Hey, we are using Aximmetry for our virtual studio set. We are now using companion to for controlling Aximmetry with OSC protocol, but that is not very comfortable. It would be really nice to have Aximmetry full support in Companion with feedbacks etc. Let me know, if I can help somehow to integrate Aximmetry into Companion! Thank you!

**Comment by petefox** [comment]
I'd like to see this too - virtual studio productions are becoming more and more popular, and this is one of the best solutions for it so far. [Here's some HTTP docs](https://my.aximmetry.com/post/16-how-can-i-control-my-aximmetry-scene-from).

**Comment by daniep01** [comment]
I might be available to work on this. The docs linked above describe sending commands but don't seem to provide a way to get feedback into Companion. Is the module still useful without this? Are there any potential sponsors for this module?

**Comment by petefox** [comment]
There's already a StreamDeck plugin, and I do see the HTTP API also has the ability to return data after each request (but I couldn't find anything about webhooks or websockets).

What does a sponsorship entail? We might be interested in that at [Telzio](https://github.com/Telzio).

**Comment by daniep01** [comment]
@petefox Thanks for posting that link, there's definitely enough information there to get basic control into Companion. I have a github sponsor page where you can contribute towards the creation and maintenance of modules. For a new module like this I would probably need to spend 1 day to get the basics working and then additional time for feedbacks and variables.

**Comment by petefox** [comment]
Nice - we've submitted a donation now :)

**Comment by daniep01** [comment]
@petefox Many thanks for you donation! I am installing Aximmetry and should have something to test by the end of the weekend. I'm a bit confused as to the difference between the DE and SE downloads but hopefully the module will work with either.

**Comment by petefox** [comment]
@daniep01 I agree - they are really bad at explaining the difference... 

SE = Single Engine
DE = Dual Engine

DE is the version that uses Unreal Engine for rendering, where SE only uses Aximmetry's own engine. In other words, you wanna use the DE version ;)

**Comment by daniep01** [comment]
I now have something very basic working for changing the values of pins. It took a lot longer than it should because Aximmetry don't follow the http standard properly! 😕

**Comment by daniep01** [comment]
Here is a test build of the new module which can be added to Companion3.

[pkg.tgz](https://github.com/bitfocus/companion-module-requests/files/12698167/pkg.tgz)

Let me know how it goes and what features you would like to see added next.

**Comment by petefox** [comment]
@daniep01  This is awesome, and super quick. Thanks!

It's been a busy week, so not gonna have time to play with it until Monday - but I'll let you know once I try it out. 

One thing that comes to mind that could be useful (possibly as a template/preset thing) is the ability to switch between cameras when you're using a tracked camera rendered with UE5. Like having a button for each camera similarly to a regular video switcher.

**Comment by josephdadams** [comment]
Transferring this to: https://github.com/bitfocus/companion-module-aximetry-composer
