### ISSUE TITLE
Panasonic Kairos Vision Mixer

### ISSUE THREAD

**Issue by sh-video** [bitfocus/companion-module-requests#669]
Hi,

Would it be possible to support the Panasonic Kairos vision mixer natively in Companion?
The Kairos is a software defined vision mixer for broadcast and proAV which runs on commodity IT hardware for switching format agnostic IP and baseband video signals. It has inbuilt video playback, live graphics capability and its flexibility would only be expanded further with support via Companion. Having the ability to recall sources and scenes, trigger and stop media players and activate transitions if nothing else would be brilliant. It uses a 'Client-Server' model by which a single Kairos frame can be control from multiple 'GUI' PCs and has a full RESTful API as well as a web interface. Having Companion support would allow multiple operators to have 'physical hardware' button control over different elements of the unit, without the need for multiple hardware mixer panels.

Would anyone be able to help out with this?

Please see attached API documentation. 

Thanks

Sam

[KAIROS_REST_API_Specification_E_V1.0.pdf](https://github.com/bitfocus/companion-module-requests/files/7729522/KAIROS_REST_API_Specification_E_V1.0.pdf)

**Comment by Lenguafina** [comment]
Hi,

I am working also with Kairos and would be supergreat to have Companion working with it. 

Do you have any updates? Pleaseeeee It would be awesome I love Bitfocus

**Comment by JeffreyDavidsz** [comment]
Hi, Panasonic reached out on us for development for Companion. I'll start on this soon

**Comment by JeffreyDavidsz** [comment]
The module is in. For now it takes some time to load all data before you can start (+/- 40sec), have fun
