### ISSUE TITLE
Evertz Quartz router

### ISSUE THREAD

**Issue by llamafilm** [bitfocus/companion-module-requests#672]
It would be great to control Evertz video routers from here.  The protocol is called Quartz, and it's based on simple TCP sockets.  
Features:
- Route source to destination, with an option to choose which "levels" are routed.  Typically it would just be video (because SDI audio is embedded), but it's also possible to mix and match, e.g. audio source 1 and video source 2 both going to destination 1.  The router replies with success or error message.
- Select destination button, similar to the AJA Kumo module.  Hopefully button text can be automatically filled with the destination name, which can be read from the router.
- Lock destination
- Interrogate destination to see what source is routed to it, and update button text accordingly.  Perhaps this could run once per second for all buttons which are currently visible, in case another user changes routes from a different controller.
- Fire salvo

Interface options should include an IP address and port number.

Protocol documentation is here: https://drive.google.com/file/d/1oP9YVvoCS1_jbFjmedmqwk8jfDlUsHLN/view?usp=sharing

**Comment by daniep01** [comment]
Depending on your system controller configuration you may be able to use the Companion SWP-08 module to talk to the Evertz router.

**Comment by llamafilm** [comment]
@daniep01 I haven't seen anything in Evertz config or documentation about SWP-08.  Do you have some experience with that?

**Comment by daniep01** [comment]
I know that Evertz have products to enable interfacing with other protocols. 

https://evertz.com/products/7700R-SC-BRC#Specifications

**Comment by llamafilm** [comment]
I wrote a basic module for this, without feedback.  https://github.com/bitfocus/companion-module-evertz-quartz
