### ISSUE TITLE
ROLAND P20HD video replayer

### ISSUE THREAD

**Issue by loolou** [bitfocus/companion-module-requests#676]
ROLAND just launched a new product which could be elgato-controled: instant video replay: ROLAND P20HD ! There is a lan connexion, and the reference manual shows all the protocol to LAN-control the device. It would be great to add this replayer to Bitfocus Companion software, and enable a streamdeck to control it with macros :)

**Comment by loolou** [comment]
here are the quickstart guide, and the reference manual. I think there is all you need in the reference manual to add this device to bitfocus companion :
[P-20HD_eng03_W.pdf](https://github.com/bitfocus/companion-module-requests/files/7840791/P-20HD_eng03_W.pdf)
[P-20HD_reference_v12_eng01_W.pdf](https://github.com/bitfocus/companion-module-requests/files/7840792/P-20HD_reference_v12_eng01_W.pdf)
)

**Comment by loolou** [comment]
Hi, does anyone knows how to include the Roland P20HD into companion ?

**Comment by josephdadams** [comment]
Closed because this module exists now
