### ISSUE TITLE
Novastar H Series Hardware

### ISSUE THREAD

**Issue by adingess** [bitfocus/companion-module-requests#677]
**Describe the feature**
A clear and concise description of what the feature does](https://www.novastar.tech/products/processors/h-series/

**Usecases**
The future of LED processing

**Comment by adingess** [comment]
Looks like it's already built. It just needs added:
https://github.com/rit3sh7/companion-module-Novastar-H-series 

Thanks

**Comment by josephdadams** [comment]
It’s added now! To the betas
