### ISSUE TITLE
WAV Convey Video (TL S20)

### ISSUE THREAD

**Issue by JacobL3** [bitfocus/companion-module-requests#681]
Howdy, new here.

Would y'all please add support for the Williams AV Convey Video ([TL S20](https://williamsav.com/product/convey-video/ "See Downloads")).

It should be pretty easy to develop. The network control is simply a Telnet interface on port 8023, but each command starts with the < esc > character (not escape command "\ "). I primarily want to quickly set the language to one of 5ish languages, start/stop session, start/stop archiving, and change the video input.

I am a developer at WAV and would like to test my equipment and quickly reconfigure it with Companion, but I'm having trouble finding time and understanding to develop my own module. We would also likely use Companion at trade shows when we demonstrate our product.

I'll also keep learning module development in the meantime while I await a response.

Thank you!
Jacob

**Comment by josephdadams** [comment]
@JacobL3 if it would help, I’m available for hire to make this if you need it sooner than you might have time to learn Companion module development. Feel free to reach out to me via email, it’s on my profile. You can also ask any module development questions on our slack channel! Happy to help either way.

**Comment by JacobL3** [comment]
Product was discontinued on 2024/01/01.
