### ISSUE TITLE
Lightwave RF or Samsung Smartthings

### ISSUE THREAD

**Issue by x13pow** [bitfocus/companion-module-requests#683]
would like to request lightwave rf or samsung smartthings. I would like to change over to bitfocus but I need get a solution for my lighting first. At the moment I use this pluging https://github.com/thibautsabot/streamdeck-plugin-smartthings but need to control matrix and some other bits so want to change over to bitfocus companion. 

Lightwave RF API https://support.lightwaverf.com/hc/en-us/articles/360020665652-Link-Plus-Smart-Series-API-

Smartthings API https://developer-preview.smartthings.com/api/public/

**Comment by josephdadams** [comment]
This sounds like a request for two separate things. Please re submit each one individually.
