### ISSUE TITLE
Roland V-160hd

### ISSUE THREAD

**Issue by BasTimmer** [bitfocus/companion-module-requests#685]
Hello

is there a possibility to control the new roland mixer thru companion the pc program to control this mixer is just released maybe thats a start ?

thanks

**Comment by josephdadams** [comment]
Yes, it is possible. I reached out to Roland awhile back about creating it and by the time they sent me the protocol, I was no longer in a position where I could create the module for free. So unless someone would like to discuss hiring me to create this, I shall leave this here for someone else to take on.

**Comment by hotellteknikeren** [comment]
> Yes, it is possible. I reached out to Roland awhile back about creating it and by the time they sent me the protocol, I was no longer in a position where I could create the module for free. So unless someone would like to discuss hiring me to create this, I shall leave this here for someone else to take on.

Hi😀
What will the cost be?
Im interested 

lars.erik.pedersen (at) hotmail.com

**Comment by josephdadams** [comment]
@daniep01, @hotellteknikeren has reached out to me via email and I am communicating with him and one other person to see if they want to split cost. If they decide not to move forward with me, I will ping you.

**Comment by Offairwithjez** [comment]
Can't wait to see this project come to fruition

**Comment by Djiaant** [comment]
Any updates on this?  A company I work with recently purchased this switcher and I would love to control it.

**Comment by josephdadams** [comment]
Has been in the builds for months. Go try it!

**Comment by Djiaant** [comment]
> 

Is it on v2.3 or v2.4?  I am on v2.3 and cannot locate the module.

**Comment by josephdadams** [comment]
Try 2.4
