### ISSUE TITLE
Panamax BlueBolt

### ISSUE THREAD

**Issue by gdlopez** [bitfocus/companion-module-requests#689]
Power Sequencer (may be similar to Furnam request as Panamax owns furnam). Enables user to turn off, on, cycle power strip in a specific order. 

See pages 7-11 in https://content.abt.com/documents/25897/User_M4315PRO.pdf 

Honestly the most useful command would be: 3.5 SWITCH OUTLET

**Comment by josephdadams** [comment]
Simple telnet protocol. Not too bad at all.

**Comment by elliotmatson** [comment]
@gdlopez I have an initial version here: [companion-module-nortek-bluebolt](https://github.com/bitfocus/companion-module-nortek-bluebolt)
Currently, it only supports the M4000 Pro, as that's the only model I have access to, but our BB-RS232 is on the way and I should be able to work on that next week. I can also start working on adding support for the telnet models.

**Comment by elliotmatson** [comment]
@gdlopez the latest version has beta support for the M4315 Pro. I don't have access to that model, so if you could try it out once it's pushed to beta that would be great!
