### ISSUE TITLE
Module Request: PTZOptics SuperJoy

### ISSUE THREAD

**Issue by mxxmxn** [bitfocus/companion-module-requests#701]
Features:
- Control the SuperJoy using the HTTP-CGI commands documented in the linked pdf
- Reading out the status and make it usable via variables

Documentation:
https://f.hubspotusercontent20.net/hubfs/418770/PTZOptics%20Documentation/Misc/SuperJoy%20HTTP-CGI%20Commands.pdf

**Comment by daniep01** [comment]
I have already built this module, you need to download a recent beta build of Companion

**Comment by MaxM3001** [comment]
When did you add it?
The most recent builds (since 2 days) don't work for me any more.
How is it named?

**Comment by daniep01** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/17852298/149999289-8a3dbd61-8b82-433a-b613-784cffa1294c.png">

**Comment by josephdadams** [comment]
Is that the same as the PTZ Optics Super Joy @daniep01? If so, maybe we could update package.json to include that so it shows up in the search.

**Comment by daniep01** [comment]
Hmm, looking at this again now I'm more awake we may need to re-open this one! @josephdadams

**Comment by MaxM3001** [comment]
I tested it with my SuperJoy and it didn't work. I was referring to the physical controller from PTZOptics called SuperJoy. I don't think this is the same.

**Comment by daniep01** [comment]
My module supports Rocosoft PTZ Joy software which then supports among many others:

PTZOptics: 12X-IP, 12X-USB, 20X-IP, 20X-USB, 12X-SDI-G2, 12X-USB-G2, 20X-SDI-G2, 20X-USB-G2, and all newer cameras.

However I can see the benefit of going direct to the SuperJoy.

**Comment by bryce-seifert** [comment]
Module is now developed for the Superjoy: https://github.com/bitfocus/companion-module-ptzoptics-superjoy
