### ISSUE TITLE
Sonoran Video Systems Coyote Playback Server

### ISSUE THREAD

**Issue by graet63** [bitfocus/companion-module-requests#71]
Coyote has a JSON-based API. Details attached.
[coyotejson.pdf](https://github.com/bitfocus/companion-module-requests/files/3527878/coyotejson.pdf)

**Comment by willosof** [comment]
https://www.sonoranvideosystems.com/

**Comment by McHauge** [comment]
Hey, just got done setting up what I would call a demo module, with all the main commands. And it would be very helpful if you could run a test on the buttons. And run these to requests: /getpresets and /gettimecode and post the results, for implementing a dropdown menu in selecting the ID.

You can acces the demo build for testing here: [https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by graet63** [comment]
Thanks Andreas.

 

I have downloaded the demo build but I am not sure what to do with it. Do I just run the exe file? I am on Mac so will have to get onto a PC to do it.

**Comment by McHauge** [comment]
Hey, yes you will need a pc for this build, (i don't own a mac, therefore I sadly can't compile for mac) but with the content of the folder you got two choises:

- You can run the "Companion-win64.exe" en the main folder, this wil install companion 2.0 on the divice.

- The other option is to open the folder "win-unpacked" and run "Companion.exe", this will launch a local version, and will not install the program but just run it.

Hope it helps.

**Comment by graet63** [comment]
Thanks, I will try it and let you know how it goes.

**Comment by graet63** [comment]
Here are the results from the /getpresets command. I have not had a chance to run the demo module yet, hopefully in the next few days.
[GetPresets.pdf](https://github.com/bitfocus/companion-module-requests/files/3539038/GetPresets.pdf)

**Comment by McHauge** [comment]
@graet63 Nice, I'll take a look at the file and try to implement it over the upcoming days. One thing I see, is that the preset id seems the be a number only when phrasing with "PK", which is what the module is set up to do now.

**Comment by josephdadams** [comment]
@graet63 were you able to test?

**Comment by graet63** [comment]
@josephdadams sorry for my late reply I have been busy on a string of shows. I have now tested the demo module. I am pleased to report that all the actions work as expected. Thanks to @McHauge 
A drop down box for selecting presets is not required, as all it needs is the preset number to be entered.
One thing is that the commands END, PAUSE & PLAY act on the current selected preset if the preset ID is set to zero. I find it useful to use these in this mode, so it would be better if the default value for preset ID was zero for these actions.
Sonoran have advised the following in firmware version 1.3:
_API bumped to 0.3, you must now specify "CoyoteAPIVersion" : "0.3"_

Also results of /GetTimeCode attached.
[GetTimeCode.pdf](https://github.com/bitfocus/companion-module-requests/files/3631042/GetTimeCode.pdf)

**Comment by McHauge** [comment]
@graet63 lovely, I will get that updated right away if there are other options you need in the module feel free to ask.

**Comment by graet63** [comment]
@McHauge Great. SeekTo commands would be useful especially in rehearsal or CueToCue situations to skip to the end of videos, eg SeekTo 30 seconds from end, SeekTo 10 seconds from end.

**Comment by McHauge** [comment]
@graet63 just updated my module with SeekTo and for API V0.3 an updated compiled zip file will be in the onedrive folder from before in a 20 min or so, then you can test the SeekTo function, and i'll get a rep created for it to be included in the 2.0 builds in the future

**Comment by McHauge** [comment]
The file is now updated

**Comment by josephdadams** [comment]
@graet63 @McHauge you guys ready to close this issue since we have module support now? In the meantime, I'll move it to the repository for this module.

**Comment by McHauge** [comment]
@josephdadams  fine by me, but moving it to the rep is also fine by me. then it's still simpler to keep the contact open.

**Comment by graet63** [comment]
@josephdadams yes thanks
