### ISSUE TITLE
Aver PTC310H PTZ Camera

### ISSUE THREAD

**Issue by Fairrington** [bitfocus/companion-module-requests#737]
Can someone please create a module for the PTZ Camera Aver PTC310H.

Document is attached.

Thank you

[PTC310_PTC310H_PTC310N_PTC310U_PTC330U_Control+Codes+Manual(Visca+command_RS232_IP)_20210330_v5.pdf](https://github.com/bitfocus/companion-module-requests/files/8153886/PTC310_PTC310H_PTC310N_PTC310U_PTC330U_Control%2BCodes%2BManual.Visca%2Bcommand_RS232_IP._20210330_v5.pdf)

**Comment by josephdadams** [comment]
Have you tried using any of the existing VISCA modules in Companion?

**Comment by vlada140** [comment]
Based on Visca codes I think existing modules will work ([PTZoptics codes](https://ptzoptics.com/wp-content/uploads/2020/11/PTZOptics-VISCA-over-IP-Rev-1_2-8-20.pdf), [Aver codes](https://presentation.aver.com/DownloadFile.aspx?n=5294%7CA4C91B77-6295-4034-818F-8D7E4D67680A&t=ServiceDownload)). Try and say results to us!

**Comment by lipensky** [comment]
I Have a couple of Running Installations with All kind of AVER cameras. It works with the standard Sony Visca Module (cam ID:1), BUT zoom speeds are terrible slow and the Pan/Till speed can not be adjusted...
I've always used the PTZOPTICS Module but after upgrading to the newest Software it just does not work properly anymore... i get dis and reconnects all the time it seems that the ptzoptic module checks for feedback...

**Comment by vlada140** [comment]
> I Have a couple of Running Installations with All kind of AVER cameras. It works with the standard Sony Visca Module (cam ID:1), BUT zoom speeds are terrible slow and the Pan/Till speed can not be adjusted... I've always used the PTZOPTICS Module but after upgrading to the newest Software it just does not work properly anymore... i get dis and reconnects all the time it seems that the ptzoptic module checks for feedback...

What about preset execution speed? and also for features like presenter mode, auto tracking and so on? There is option for costume variable, can it be used?

**Comment by Fairrington** [comment]
Hello, for me is the Sony Visca Module fine.

**Comment by josephdadams** [comment]
#789
