### ISSUE TITLE
Support for Kramer VS-41H HDMI switcher

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion-module-requests#74]
This request is coming via the ProPresenter forums. One of our users requested support for TCP, but it would be a long time coming, if ever. Since it's possible to trigger Companion indirectly with MIDI, I'd rather see the module here and then help him control Companion.

He provided a link to a Python script that works: https://github.com/UbiCastTeam/kramer-python-control/blob/master/kramer_switch.py

This switcher uses the Protocol 2000. https://k.kramerav.com/downloads/protocols/protocol_2000_rev0_51.pdf

**Comment by SteveTherrien** [comment]
See https://github.com/bitfocus/companion-module-kramer-vs41h/issues/1

**Comment by josephdadams** [comment]
We included this in the core build, so this will be closed. If anyone has an issue with using it, they can file a bug report.
