### ISSUE TITLE
Logic Pro Mute Buttons

### ISSUE THREAD

**Issue by morales127** [bitfocus/companion-module-requests#741]
We use Logic Pro to process livestream sound for our church.  We use ProPresenter on a different computer, ATEM, and X32 mixers.  I'm hoping there's a way to mute/unmute Logic Pro channels.

**Comment by josephdadams** [comment]
You might be able to do this with MIDI.

https://9to5mac.com/2015/06/14/logic-pros-how-to-map-midi-controller/

So you could use midi-relay running on the Logic Pro mac and the midi-relay module in Companion

**Comment by morales127** [comment]
Thank you, Joseph.  Forgive me for asking, I’m really new, is there documentation on how to setup midi-relay?

**Comment by josephdadams** [comment]
https://github.com/josephdadams/midi-relay

**Comment by morales127** [comment]
Thank you!
