### ISSUE TITLE
Huddlecam Simpltrack lite auto tracking enable

### ISSUE THREAD

**Issue by morales127** [bitfocus/companion-module-requests#742]
Hi.  We bought this camera for our church, I know that huddlecam hd is a sister company of PTZ optics . Is there a way to enable/ disable auto tracking and manual mode for this camera using companion?

**Comment by josephdadams** [comment]
Have you contacted Huddlecam to see if they have an API or protocol that would allow for external control of this? That will be needed if you want something like this implemented.

**Comment by morales127** [comment]
I found it.  Presets 80 and 81 turns the auto tracking on and off.  Thanks for the response
