### ISSUE TITLE
Google Sheets

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion-module-requests#744]
Module Request:
A module that would connect to google sheets and connect Data in Cells i.e. (Sheet,A23) to a variable. This would streamline many workflows. And could make some workflows more universal.
You would need to set the Google API credentials in the module setup. And a refresh timer setting. Are my initial thoughts

I hope this is self explanatory :-)

Steve

**Comment by stevespaw** [comment]
Here is a possible framework for this:
[https://github.com/RCVolus/obs-google-sheet-importer](url)
The ability to push variables back to the Sheet would also be tremendous for a "Dashboard"
Come on, I know you want it 💯 :-)

**Comment by thedist** [comment]
If people are okay with needing to create their own app in the Google dev console, and enter the credentials into the modules config, then this is something I could work create.

I already have an app that integrates with Google Sheets but never too widely advertised it as it uses a Google project I created and my own server to handle the OAuth process and with it being it beta it hasn't gone through Googles verification process, but this wont be an issue for a Companion module if people are using their own credentials anyway.

**Comment by stevespaw** [comment]
I knew that you would be the first to see the value in this :-). Storing my data in vMix XAML tiles is no way to go through life. Yeah I think that the vMix way of documenting the API/credentials setup would be fine for people that really want this, it will be expected....  Thanks, I look forward to this project!

**Comment by DachsbauTV** [comment]
@thedist you don't know how much I would appreciate a google sheets module. I'm happy to throw in 20€ for this to be made.
We are desperately looking for a way to have a google sheet for lower thirds which automatically fills our OBS lower third buttons in companion.

**Comment by thedist** [comment]
There's now a module started for Google Sheets https://github.com/bitfocus/companion-module-google-sheets and I've added a feature request to the issues page with the basic functionality I'm planning to start with.

I'm currently working on a Discord module which is my current focus but when I'm done with that and put it into beta I'll be able to work on this, so for the time being feel free to add any feature requests of what you want to see to that github repo.

**Comment by thedist** [comment]
v0.1.0 of the Google Sheets module is now ready, and should soon be in the beta builds.
