### ISSUE TITLE
Module request: AV Stumpfl Wings & Pixera

### ISSUE THREAD

**Issue by Carlofornasari** [bitfocus/companion-module-requests#75]
**Describe the feature**
Module to control media server "Pixera" and "Wings" by company AV Stumpfl
Pixera is the new software being released this month replacing the older Wings software

**Is this platform dependent (windows, mac, ..)?**
Pixera and wings runs on a cut down version of windows.

**If documentation is required to implement, do you know where to find it?**
I am struggling to get a working user manual at the moment. I did see in the software that there is UDP control support but help files on the server are missing. (thanks AV Stumpfl). I will ask them to send me documentation and I will forward it through when it comes.

**Usecases**
Pixera and Wings don't have a control surface at all, so using companion would be great to trigger cue points, pause, play etc.

**Comment by BenniMTools** [comment]
i will upload a module next week

**Comment by JeffreyDavidsz** [comment]
[pixera_api_documentation_5.pdf](https://github.com/bitfocus/companion-module-requests/files/3651059/pixera_api_documentation_5.pdf)
some API info

**Comment by josephdadams** [comment]
Closing because we have this now :)

**Comment by BenniMTools** [comment]
:-)
_________________________________

Benjamin Müller

Pyrmonter Str. 3
30459 Hannover

web: http://www.benni-m.de <http://www.benni-m.de/>
mobil: +49 172 - 875 25 63
mail: info@benni-m.de <mailto:info@benni-m.de>
