### ISSUE TITLE
BluStream HMXL44 HDMI Matrix Switcher

### ISSUE THREAD

**Issue by adeattheback** [bitfocus/companion-module-requests#772]
Uses TCP Telnet commands on port 23 - tested basic commands with generic tcp-udp module and seems to work fine. I'm guessing the rest of the BluStream range will probably work in just the same way. Full set of TCP commands is in the attached manual.

[HMXL44AB+V2+Manual_FINAL.pdf](https://github.com/bitfocus/companion-module-requests/files/8453102/HMXL44AB%2BV2%2BManual_FINAL.pdf)

**Comment by jrviz** [comment]
I have created several HDMI martix modules. This one is straightforward and would be quick to adapt from another. PM me using address in my profile to arrange testing and I would need to see the output from the telnet status command

**Comment by jrviz** [comment]
This can now be closed. Module tested and ready for beta

**Comment by adeattheback** [comment]
Thanks again, James!
