### ISSUE TITLE
Faithlife Proclaim

### ISSUE THREAD

**Issue by adeattheback** [bitfocus/companion-module-requests#773]
Church presentation software: closer to PowerPoint than Propresenter but has all the functionality that we need for simultaneously projecting in the sanctuary along with complementary streaming and confidence monitors. It has an interface that doesn't need extensive training and is cloud-based so can be prepared at home ahead of the service. Has midi in and out to allow remote control in both directions, and you can use "webpages" to send html strings to control Companion.

https://faithlife.com/products/proclaim

**Comment by adeattheback** [comment]
Also has it's own API https://support.faithlife.com/hc/en-us/articles/4972373093005-Proclaim-App-Command-API

**Comment by josephdadams** [comment]
#600
