### ISSUE TITLE
Send a 'Press Button' command to the Emulator

### ISSUE THREAD

**Issue by larryseyer** [bitfocus/companion-module-requests#778]
I would like to be able to trigger a Companion Emulator Button from a web page WITHOUT having to press a key once the emulator is loaded.

For instance, I would like to have a single HTML file send a single button press TO the emulator automatically when the html page is loaded into a browser.

This would allow me to create HTML web pages for EACH button and then call them via OBS or some other browser and AUTOMATICALLY trigger a companion button.

examples:

button_01.html
button_02.html

etc.

Having OBS automatically load those HTML files would then send a command to companion automatically upon loading each html file.  The power of this feature cannot be underestimated.

**Comment by dszoka** [comment]
You can already do this  ---

click on the button, at the bottom of the edit button page is the html line you need to enter to "Press" that button 

__"Hint: Control buttons with OSC or HTTP: /press/bank/1/14 to press this button remotely."_

so it would be  http:// ip address:8000/press/bank/1/14      the 1 is the page, the 14 equals the button number

**Comment by Julusian** [comment]
This is possible, see above
