### ISSUE TITLE
ADDERLink XDIP

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-module-requests#781]
This is a KVM over IP
Setting and getting channel status

I tried using the Generic http module,
but It is a HTTPS API so authentication is needed

They have a C# example on their github 
https://github.com/AdderAPI/XDIP

The API is described on page 38
https://www.adder.com/sites/default/files/2020-06/MAN-XDIP-ADDER.pdf

Maybe there is some cross compatibility with this #294

**Comment by daniep01** [comment]
The XDIP module has been added, download the latest beta release:
https://bitfocus.io/companion/download/builds/
