### ISSUE TITLE
Analogway Pulse 4k

### ISSUE THREAD

**Issue by sisoyjuan** [bitfocus/companion-module-requests#785]
Dear,

I see you can support different devices from analog way but I can't fing Pulse 4k, https://www.analogway.com/emea/products/midra-4k-presentation-switchers/pulse-4k/ 
can you confirm me if is currently supported? I'm going to use it with streamdeck panel.

Thanks in advance for your help

best regards

**Comment by dnmeid** [comment]
This is now supported as of Companion release 2.4.0. Look for module Analog Way AWJ device.
