### ISSUE TITLE
Support for Avid Pro Tools DAW, with support for Antares Auto Tune

### ISSUE THREAD

**Issue by acknapp2012** [bitfocus/companion-module-requests#788]
I'm looking for support in Companion for Avid Pro Tools digital audio workstation, with a specific need to also support the Antares Auto-Tune plugin. This is so I can easily change the key of a song in Auto-Tune with just a button press on the Streamdeck. I was unable to see that it is currently supported, although I did notice that Reaper DAW is supported.

**Comment by dmitrylive** [comment]
I would also like to see AVID Pro Tools

**Comment by Teressss** [comment]
I agree, support for Avid Pro Tools would be amazing!

**Comment by Xanderdanny** [comment]
I agree, too. Support for Avid Pro Tools would make our work faster and easier!

**Comment by josephdadams** [comment]
duplicate of #598
