### ISSUE TITLE
Lightware MX2 Request

### ISSUE THREAD

**Issue by Gitflon** [bitfocus/companion-module-requests#801]
missing the connection for lightware MX2 Matrix :(

**Comment by josephdadams** [comment]
@Gitflon please read this: https://github.com/bitfocus/companion-module-requests/blob/master/README.md

And add more information to your request.

**Comment by tsd80** [comment]
https://lightware.com/pub/media/lightware/filedownloader/file/User%20Manuals/MX2-8x8-HDMI20_Users_Manual_v2.0.pdf Chaper 8 in this doc

**Comment by magdatev** [comment]
Still  missing any information here?

**Comment by dnmeid** [comment]
Lightware matricies of the MX2 series can be controlled with either the LW2 or the LW3 protocols which are both supported by Companion. Since the the OP hasn't answered for nearly a year and there is no new information I'm closing this issue.

**Comment by liquidprod** [comment]
Im noticing LW2 connection 2.0.1 continually starts and restarts on version 4.2.4. I saw there have been some reported issues on this. Does anybody know if this is still in the pipeline or is this now a write off? :)
