### ISSUE TITLE
Samsung Tizen based Smart TVs

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-requests#805]
I'd love to be able to control my stage displays, particularly power state more than anything via companion.  I've tried to hook into them with HomeAssistant and control that way but have had no success.  I found the samsung api page on their website, but it's entirely in greek to me.  If this isn't helpful to anyone that has the programming ability, please let me know what I need to look for that is helpful and I will gladly do the leg work on the research front.

https://developer.samsung.com/smarttv/develop/api-references.html

Thanks!

**Comment by josephdadams** [comment]
@JeffreyDavidsz does this fall in line with the samsung module I've seen you working on?

**Comment by JeffreyDavidsz** [comment]
@josephdadams no the one I worked on is just sending hex commands to Samsung displays.
This seems a JavaScript implementation to control specific models.
It seems doable though

**Comment by jsnyder886** [comment]
I will gladly participate in testing when the time comes if that helps...
Thank you!

**Comment by peternewman** [comment]
This module will probably work:
https://www.npmjs.com/package/samsung-tv-control

See also #102 .

I don't know if they should be one module or two separate ones?

**Comment by josephdadams** [comment]
Maybe one module but a protocol selector (older/newer) and if older, behave one way, if newer, the other. The vizio module does this.

**Comment by peternewman** [comment]
In which case this module might be a better bet. It looks like it's got less features, but does at least seem to have the same API as the one for older models:
https://www.npmjs.com/package/samsung-tv-remote

It's actually this on GitHub (despite the links on npm)!
https://github.com/Badisi/samsung-tv-remote

**Comment by josephdadams** [comment]
@peternewman will you be writing this module? Do you need me to set up a repo for you?

**Comment by peternewman** [comment]
> @peternewman will you be writing this module? Do you need me to set up a repo for you?

I want to get https://github.com/bitfocus/companion/pull/2436 in first at least, and then probably another surface PR for an alternative foot pedal. I've only got an older TV so I could try writing that code after and attempt to use the linked package with the same API but would need someone else to test on newer TVs...

From what I could see though, with V3 I could get it all working in my own dev repo and then just migrate/PR that into the official one in due course?

**Comment by matt-flaig** [comment]
@peternewman I've been developing a module ([companion-module-samsung-smarttv](https://github.com/bitfocus/companion-module-samsung-smarttv)) over the past couple of weeks which is a wrapper around the npm package [samsung-tv-control](https://www.npmjs.com/package/samsung-tv-control).

Feel free to contribute to the repo if you started a similar development effort, or give it a test and pass on any feedback on how it works on your TVs. I've tested on these models of Samsung Smart TVs:

- UE43NU7400
- UN55NU7100
- UN50MU6070
