### ISSUE TITLE
Philips HUE lights

### ISSUE THREAD

**Issue by Joelsuperstar** [bitfocus/companion-module-requests#807]
Hello,

Can philips HUE lights be added?

The user can give the IP of a bridge,
Then its basically making a POST request to authenticate the user (with a press on the bridge)

After that its mostly sending web request to the bridge (and receiving information about lamps/bridges/rooms).

There is a lot of information online:
[https://developers.meethue.com/develop/get-started-2/ ](https://developers.meethue.com/develop/get-started-2/ )

I can try to help on it this summer (think its a nice summer project for me), but things like javascript is new for me :) Not sure how to help or look for more information to try something myself.

**Comment by josephdadams** [comment]
It already exists

https://github.com/bitfocus/companion-module-phillips-hue
