### ISSUE TITLE
ChamSys QuickQ UDP

### ISSUE THREAD

**Issue by lxdesigner** [bitfocus/companion-module-requests#820]
[QuickQ Manual_ Installation, Operation Manual and Warranty Certificate.pdf](https://github.com/bitfocus/companion-module-requests/files/8807491/QuickQ.Manual_.Installation.Operation.Manual.and.Warranty.Certificate.pdf)

**Comment by lxdesigner** [comment]
@josephdadams I do not see a UDP version of the companion module for QuickQ?

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-chamsys-magicq-udp
