### ISSUE TITLE
Companion / Companion Satellite  Module

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-module-requests#824]
Companion is fantastic. 
and is now so widespread that I often arrive on a venue and the local tech already has a Companion instance running.

Unfortunately it is often impractical/impossible to migrate my setup to their instance or vice versa. 
That may be because of a version mismatch, time constraints, or them just not wanting you to mess with there stuff.    

I am aware that I can remote control the other instance with OSC and so on
but a module would make it so I can't accidentally misspell the path😉
and hopefully also enable receiving the color and text of remote button.

I think all of the necessary connections already exists through the Satellite API 
https://github.com/bitfocus/companion/wiki/Satellite-API

**Comment by krocheck** [comment]
https://github.com/bitfocus/companion-satellite/releases

**Comment by alex-Arc** [comment]
I think you misunderstood something.
I have my own Companion instance running controlling my stuff
and want to control another Companion instance.

or am I missing something on the releases page?
