### ISSUE TITLE
Module Request: Generic TCP/UDP module

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion-module-requests#84]
A module for easily sending strings over tcp or udp.

It should have option for closing tcp connections for each action, or if it should keep it alive.

String input should have support for escape tags like \x00 etc, for mimicking binary protocols.

**Comment by McHauge** [comment]
If you set up a dev environment and compile it yourself, then I got this generic TCP and UDP module you can use, but it will probably not be included in the main build for a long time, as mentioned.
[https://github.com/McHauge/companion-module-generic-tcp-udp](url)

**Comment by MrMagicSlick** [comment]
Hi McHauge

Do you have a build that includes your module?
For us lesser experienced people which a compiling might be to much to swallow.

**Comment by McHauge** [comment]
Yes, I do, it's included in all my V2.0 test builds for Windows, compiled for other modules that I'm working on, or at some point did.

You can find them at this link, but remember there is no official support for it:
[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by MrMagicSlick** [comment]
Thanks, that's great

**Comment by Nojbi2000** [comment]
> Yes, I do, it's included in all my V2.0 test builds for Windows, compiled for other modules that I'm working on, or at some point did.
> 
> You can find them at this link, but remember there is no official support for it:
> [https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

Hello, I tryed to download the build but link does not show the file. Could you please share again? I would like to use it too! Thank you!

**Comment by McHauge** [comment]
@Nojbi2000 here you go: [download](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)

**Comment by Nojbi2000** [comment]
Great. Thank you!
Jan
 <skype:jan.neubauer?chat>

**Comment by McHauge** [comment]
Hi again, are we still on the "no generic TCP/UDP" module in Companion wagon? just added support for selecting termination characters on generic commands in my old module.
[Module Available Here](https://github.com/McHauge/companion-module-generic-tcp-udp
)

**Comment by JeffreyDavidsz** [comment]
We are, but at this moment it might be a good idea to include it for 2.0. I feel this could be a major plus for the 2.0 release. I'll discuss it with the guys

**Comment by JeffreyDavidsz** [comment]
Oh yeah, just a little message... it's in
