### ISSUE TITLE
Tesla Smart 8x8 Matrix

### ISSUE THREAD

**Issue by DGdB** [bitfocus/companion-module-requests#844]
I have a Tesla Smart 8x8 HDMI matrix which I have managed to control using TCP/telnet requests. I am using companion-module-generic-tcp-udp to achieve this.

It would be great if there was a proper module for it! These are extremely cheap and I can see being used as an inexpensive way to improve vision workflows.

It also reports what inputs are displaying on each output so this would allow for instance feedback.

This is how I controlled using telnet: "MT00SW0601NT" where 06 is input and 01 is output

See the documentation here: https://cdn.shopify.com/s/files/1/0271/3429/6200/files/8X8HDMImatrixcommunicationprotocol_nl7n.pdf

**Comment by jrviz** [comment]
This can be closed. Implemented as Tesmart (product name has changed from Tesla)
