### ISSUE TITLE
livepro l1 video mixer

### ISSUE THREAD

**Issue by mrkabass** [bitfocus/companion-module-requests#854]
Hi
It would be very useful to be able to control the "freeworl livepro l1"(video mixer) with streamdeck, it would be enough to enable the switching of cameras (which are 4 inputs) There is software capable of controlling this device via mouse, but it would be great to be able to switch cameras via streamdeck.
Livepro L1 software: "Feelworld Live XPOSE (MAC) V1.0.3.12"
Download link: http://www.feelworld.cn/Common/ShowDownloadUrl.aspx?urlid=1&id=667
Thanks!
Valter Carvalho

**Comment by josephdadams** [comment]
I think this is the same product as the rgblink mini #384 

There is a module here, coming to the betas soon: https://github.com/bitfocus/companion-module-rgblink-mini

**Comment by mrkabass** [comment]
> I think this is the same product as the rgblink mini #384
> 
> There is a module here, coming to the betas soon: https://github.com/bitfocus/companion-module-rgblink-mini

I don't know if I understand this correctly, but is there any way to download this and use it on my companion or do I need to wait for the beta version?
Thanks anyway
