### ISSUE TITLE
Marshall's CV-630 PTZ camera controlling from Bitfocus companion

### ISSUE THREAD

**Issue by Moosabitfocus** [bitfocus/companion-module-requests#857]
Hi, I am using 2 Vmix computers along with various PTZ cameras, from PTZoptics and Marshall's CV-630-NDI. I am controlling both Vmix machines and PTZoptics cameras with a StreamDeck XL device with the help of Bitfocus Companion. But I could not connect the Marshall's CV-630 with Companion to control the Exposure/IRIS and using the Camera web control login to change the Exposure/IRIS every time. Any help or guidance to connect  CV-630 with Companion will be appreciated.

Regards,

Danny.

**Comment by josephdadams** [comment]
#284
