### ISSUE TITLE
Epson Webremote integration 

### ISSUE THREAD

**Issue by roshjothe** [bitfocus/companion-module-requests#861]
My church uses an Epson projector, and we control it using epson web remote over a local network. If companion is able to integrate with epson web remote, that would be very useful! If you need any documentation, I'd love to help!

**Comment by istnv** [comment]
Most epson projectors support the PJLink protocol.
Companion has a PJLink module and a more specific Epson control module.

**Comment by roshjothe** [comment]
Thank you! I actually just implemented this for our projectors. I am having issue with our epson power on, while my sony's are working great. Opened a ticket for that, so we'll have to see what happens.

**Comment by BenJamesAndo** [comment]
@roshjothe make sure you have the latest beta build installed. You'll then find the Epson module as Epson Business Projectors. More info here: https://github.com/bitfocus/companion-module-epson-businesspj

**Comment by josephdadams** [comment]
@roshjothe did you upgrade and try the epson-businesspj module?
