### ISSUE TITLE
plamen2801

### ISSUE THREAD

**Issue by plamen2801** [bitfocus/companion-module-requests#864]
I use bitfocus companion with X-keys keypads XKE-40 to control ATEM 2 M/E Production Studio 4K. I have a problem with feedbaback x-keys backlight does not light up on even keys corresponding to Elgato Streamdeck are for example 1.21, 1.22, 1.23, 1.24..., but 1.1, 1.2, 1.3 feedbaback works.

**Comment by josephdadams** [comment]
this is not a module request
