### ISSUE TITLE
Roland V-600 UHD

### ISSUE THREAD

**Issue by magneriise** [bitfocus/companion-module-requests#87]
Hi. 

Want to control the V-600UHD from Roland.
Over Telnet TCP you get control from port 8023 to control switching/source/preset.

Documentation is avalible https://static.roland.com/assets/media/pdf/V-600UHD_reference_eng01_W.pdf

The use case is to control the V-600 simultanious with other live event gear. 
Or remote control it in a instalation inviroment. 

[V-600UHD_reference_eng01_W controll.pdf](https://github.com/bitfocus/companion/files/3550586/V-600UHD_reference_eng01_W.controll.pdf)

**Comment by magneriise** [comment]
Hi @josephdadams  
That's great. might be very noob, but I can't find it in the latest build. 
Where do I find it?

**Comment by josephdadams** [comment]
Use Companion 1.4 or 2.0!

**Comment by magneriise** [comment]
Ah. Found it. Was under Vision mixer and not Roland, by category :) Thanks!
