### ISSUE TITLE
Boxcast Streaming Service

### ISSUE THREAD

**Issue by ericbusby77** [bitfocus/companion-module-requests#877]
There has been some research on implementing Boxcast support in the past. Here is a link to the API documentation: https://boxcast.github.io/boxcast_api/ 

Mostly I am just interested in the ability to set starts_at and stops_at commands so it can start and stop the selected stream.

As stated before it is available to only those with a higher level plan, I believe it is $200 per month. I can supply testing creds if necessary.

**Comment by josephdadams** [comment]
#35

**Comment by josephdadams** [comment]
This module is now in the betas.
