### ISSUE TITLE
NoHassleAV 16x16 HDMI Matrix

### ISSUE THREAD

**Issue by jcborn93** [bitfocus/companion-module-requests#878]
Can support be added for this 16x16 Mixer from NoHassleAV?https://www.nohassleav.com/support/matrix_hdmi_16x16_4k/

**Comment by josephdadams** [comment]
probably a duplicate of #846

**Comment by SkylerJEhly** [comment]
Hi @jcborn93 I implemented this alongside [#846](https://github.com/bitfocus/companion-module-requests/issues/846). If you send me an email (found on my profile) I'll send you over an early alpha for you to test.
