### ISSUE TITLE
Logic & Protools

### ISSUE THREAD

**Issue by Tobiaswalkerlighting101** [bitfocus/companion-module-requests#882]
I am hoping to control some functions in both Logic and Protools such as:

Record Start/Stop
Play
Mute
Solo
Channel/Bus Selection
Open FX Inserts

any other function you think might be useful....Record Start/Stop is the most important as i am trying to tie a whole system together with 1 button

**Comment by ICEKREAMNL** [comment]
Follow

**Comment by josephdadams** [comment]
#341 duplicate

**Comment by josephdadams** [comment]
These programs don't have a remote API, they really only support MIDI for remote control
