### ISSUE TITLE
Vista by Chroma-Q

### ISSUE THREAD

**Issue by beaunortontrinity** [bitfocus/companion-module-requests#899]
Would love to see control for Vista by Chroma-Q. All of the basic functions like firing cues, releasing cues, etc.. Thank you!

**Comment by SkylerJEhly** [comment]
Repeat of [#373](https://github.com/bitfocus/companion-module-requests/issues/373)

**Comment by josephdadams** [comment]
@beaunortontrinity Chroma Q has chosen not to add a protocol for control beyond midi at this time. So refer to #373 for how to control.

**Comment by benkorpella** [comment]
As of version R5, Vista supports Open Stage Control. [R5 Release notes](https://github.com/user-attachments/files/25754079/Vista-by-Chroma-Q-Vista-3-R5.0-Release-Notes.pdf) See pages 40-48 for the command reference. It can also be seen in the application at Help > External Reference.

**Comment by josephdadams** [comment]
Nice! Maybe someone will make a proper module now
