### ISSUE TITLE
Wirecast Support

### ISSUE THREAD

**Issue by bumbalard** [bitfocus/companion-module-requests#90]
[rsrc.zip](https://github.com/bitfocus/companion-module-requests/files/3571090/rsrc.zip)

1. Please unzip the archive.
2. You will find two folders, scriptdocs and scriptingexamples
3. In scriptdocs, open intro_welcome.html

Wirecast License: Contact Bryce via info below if needed.
Wirecast Download: http://www.telestream.net/controls/wirecast/download-wirecast-resources.htm

Technical Contact:
Bryce Stejskal
Technical Product Manager
530-830-2141
bryces@telestream.net
brycestejskal@gmail.com

Once Wirecast is installed, the scripting docs/examples can also all be found within the help menu on Windows.
MacOS variants of Wirecast utilize AppleScript.

Existing scripting implementations exist for both platforms, tally-lights.com, 1beyond.com, etc.

**Comment by josephdadams** [comment]
Thanks for the free license code! Did you mean to post that?

**Comment by bumbalard** [comment]
@josephdadams Good catch. I had originally drafted as an email before discovering there was a git project for this. Copy paste... you know how it goes.

I edited the post, and removed the edit revision from history that contained the license code.

For whoever may chose to implement, please reach out to me directly at the contact information provided above. I have posted my personal email address as well, as our work addresses sometimes auto reject as spam.

**Comment by josephdadams** [comment]
Nope, not me.

**Comment by josephdadams** [comment]
@bumbalard Companion is still largely designed to control devices and software over the network. Has Telestream developed a network API yet or is this just examples for how to control via COM objects or AppleScript on the same computer? Of course there are ways of creating “listener” software that can receive the command from Companion and then relay the local OS script necessary but some kind of TCP/UDP control directly to the software would be preferred and ultimately would get more buy in. I switched to an alternative product for this reason.

**Comment by McHauge** [comment]
@josephdadams and @bumbalard, just a heads up the license code is still visible in the Slack group. whoever got the rights to delete the auto messages, proberply should.

and also it wasn't me who used it

**Comment by bumbalard** [comment]
It's ok @McHauge, I blacklisted that particular serial. If someone were to implement, they can reach out directly to me.

@josephdadams Unfortunately, these are local, same-machine scripting options. Existing integrations have done exactly what you mentioned, created listener software if they needed the controller or signaling device to be a different device/machine.

I do agree that a proper network API would be ideal. Unfortunately there have been so few requests from customers that would warrant that work, that it has not been prioritized highly enough to ever make the roadmap.

**Comment by haakonnessjoen** [comment]
@bumbalard if you look at it in another way. There might be a surge in purchases of wirecast, if you implement a network protocol that we quickly would support. You should really try to prioritize network api. :)

**Comment by bumbalard** [comment]
> @bumbalard if you look at it in another way. There might be a surge in purchases of wirecast, if you implement a network protocol that we quickly would support. You should really try to prioritize network api. :)

While I personally would LOVE to see a proper API for many reasons in Wirecast, it ultimately is not my call :(

**Comment by josephdadams** [comment]
Closing this until Wirecast decides to have a network API. Otherwise we're just generating hotkeys or applescripts, which isn't a true integration.
