### ISSUE TITLE
New Pharos Lighting Controller

### ISSUE THREAD

**Issue by Profi-Power** [bitfocus/companion-module-requests#900]
Can you make a driver for Pharos Lighting control  ?

**Comment by SkylerJEhly** [comment]
Can you please provide the API or ethernet protocol as requested in [README.md](https://github.com/bitfocus/companion-module-requests/blob/master/README.md). You can usually find these in user manuals

**Comment by josephdadams** [comment]
bitfocus/companion-module-pharos-designer#1
