### ISSUE TITLE
New device connections for Companion

### ISSUE THREAD

**Issue by Arch-Media-Group** [bitfocus/companion-module-requests#902]
Yesterday during setup for show, I wanted to add some cues for my switcher as well as the router.  The devices are the Ross Carbonite Black switcher and the matrix is the Blackmagic Smart Videohub 20 X 20.  Was hoping that someone would be willing to take care of adding those.

**Comment by josephdadams** [comment]
Use the Rosstalk module for the Carbonite and the Videohub module for your 20x20.
