### ISSUE TITLE
Allen & Heath QU16

### ISSUE THREAD

**Issue by DiViPro01** [bitfocus/companion-module-requests#91]
Hi,

would it be possible to write a module for the Allen & Heath audio mixer series?
A client of mine bought the QU16 model, and I would love to be able to control them via companion.

I know there is a tcp/ip protocol, but I cant seem to find the commandos

**Comment by DiViPro01** [comment]
Hi jeffrey,
The dlive module gives me an exception error when trying to mute a channel on the qu16

**Comment by JeffreyDavidsz** [comment]
Can you do a screenshot?

**Comment by DiViPro01** [comment]
I will trie to convince my audio collegue to let me do some more testing.
I did the testing during a stolen moment :-)

**Comment by DiViPro01** [comment]
<img width="903" alt="Schermafbeelding 2019-09-09 om 10 15 04" src="https://user-images.githubusercontent.com/43602201/64524120-2e30ff80-d2fe-11e9-9990-d21492a7ff5e.png">

**Comment by DiViPro01** [comment]
<img width="423" alt="Screenshot 2019-09-09 at 12 15 48" src="https://user-images.githubusercontent.com/43602201/64524160-40ab3900-d2fe-11e9-80a7-369844976019.png">

**Comment by JeffreyDavidsz** [comment]
That's an old version/bug, did you got the latest?

**Comment by DiViPro01** [comment]
I tried it out with the latest, no bug, but also no cigar.
Nothing happens.
On the other hand, I have no idea to what port to send the commands too.
Ip adresses and ranges are all okay, companion also sees the dlive module (instance is green/OK)

**Comment by EventReplay** [comment]
Just had to update firmware on a couple of these to get ducker and AMM.

Is this what your after Re: Protocol Documentation?
https://www.allen-heath.com/media/Qu_MIDI_Protocol_V1.9.pdf

**Comment by crisgaret** [comment]
Is there a module for the Qu series yet to test out?

**Comment by juanmtta** [comment]
Hi there, any news on this module? I'm available for testing! 
https://www.allen-heath.com/media/Qu_MIDI_Protocol_V1.9.pdf

**Comment by MeestorX** [comment]
Please try the iLive module. I think the mute functions should work already. Whoever tries it can let me know what DOESN'T work of the iLive command set on the QU series.

**Comment by Phil0** [comment]
Just for reference, there is a module for the QU series by now, so I think this probably could be closed 😄 https://github.com/bitfocus/companion-module-allenheath-qu

**Comment by dnmeid** [comment]
resolved in #761
