### ISSUE TITLE
Marshall CV730 (and others) CGI control

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion-module-requests#927]
Marshall released a new firmware for this camera which supports CGI commands that look like this (from a web browser):
`http://user:pass@192.168.86.66/command/presetposition.cgi?PresetCall=1`

The command list (attached) implies that these commands work for these models:
CV355
CV420
CV420e
CV630
CV730
I've only tested the browser control on the 730.

The commands issues via a web browser work great, but I'd like to operate this in Companion. It does seem a little complex because the camera requires Digest authentication.

[Marshall_CGI_Command 2.xls](https://github.com/bitfocus/companion-module-requests/files/9725800/Marshall_CGI_Command.2.xls)

**Comment by paule26** [comment]
I control my CV730 by the Birdorg PTZ Module, almost everything works, only Preset numbers are different (I think +1 shifted)

**Comment by mwhittenmerck** [comment]
Any chance you could share what settings you used to get it to work with the Birdorg PTZ Module? I tried connecting to it but got an error.

**Comment by mark-epstein** [comment]
> Any chance you could share what settings you used to get it to work with the Birdorg PTZ Module? I tried connecting to it but got an error.

I was also unable to get any success using the BirdDog module. Although I'm not on the latest version of Companion

**Comment by paule26** [comment]
You both are wright, with the new Version v2.4.1 I as well get an error.
With the older Version, I think 2.31 it worked perfect.
Now I have the Problem that I can't download 2.3.1 anywhere, not funny

Update:
After testing different PTZ-Modules, the Lumens works as well perfect with the Marshall

**Comment by JaaHann** [comment]
Hey, I could create a module for Marshall CGI commands to control supported cameras. I have some experience in automating those cameras via cgi commands. There is a clear advantage over all the viscaip modules, that can be used, to have more control over the camera and getting feedback from it (which is not possible via viscaip at all).

I'll keep you updated :)

**Comment by mwhittenmerck** [comment]
@JaaHann 
Thanks

**Comment by JaaHann** [comment]
Good news everybody. The new module for Marshall IP cameras is now part of the latest v3 beta. Don't forget to update your camera as well to the latest firmware...
