### ISSUE TITLE
Support for characterworks broadcast graphic system

### ISSUE THREAD

**Issue by T68** [bitfocus/companion-module-requests#93]
Hi!
It would be great if Companion could interface with the cg-system characterworks. 
You can read more about it on:
https://www.chrworks.com/

Our company run control rooms with atem mixers and characterworks. It would be neat to be able to use the stacked commands feature in companion to create buttons that runs both atem and chrworks.

Don´t hesitate to contact me if you have any questions about this.

Regards!
Torbjörn Lindström

**Comment by JeffreyDavidsz** [comment]
I'm quite sure characterworks is in there already, did you try downloading a newer version of Companion?

**Comment by T68** [comment]
Thanks! I have downloaded latest version but unfortunately cannot find characterworks in the list.

**Comment by JeffreyDavidsz** [comment]
From builds.bitfocus.io? It's AGF Multimedia Characterworks

**Comment by T68** [comment]
Aha! Do you have to install that separately. Sorry for my noob questions :-)

**Comment by T68** [comment]
Should it be in this listing?
![image](https://user-images.githubusercontent.com/2562120/64708475-f324fc80-d4b4-11e9-8ebf-d4c49a150a93.png)

**Comment by JeffreyDavidsz** [comment]
No just install a later Companion and use the search box

**Comment by josephdadams** [comment]
Closing because AGF Characterworks is in both 1.4 and 2.0.

**Comment by T68** [comment]
Thanks! Yes figured it out that I needed a newer version than the 1.3 thats promoted on the main webpage
