### ISSUE TITLE
Cable Matters 4x4 Audio/Video Matrix Switch

### ISSUE THREAD

**Issue by D45mpinney** [bitfocus/companion-module-requests#951]
Hello-
  We are using this inexpensive hdmi matrix (https://www.cablematters.com/pc-894-139-4x4-hdmi-matrix-switch-4k-60hz-ready.aspx) for a small conference room setup. I've been able to get the basic switching functions working using generic TCP send. It would be great if a module could be developed. It looks like there is potential for feedback as well. Thanks for the consideration.
-Mike

TCP Commands with no end character:
<html>
<body>
<google-sheets-html-origin>

Output/Input | Hex for Companion
-- | --
A1 | %a5%5b%02%03%01%00%01%00%00%00%00%00%F9
B1 | %a5%5b%02%03%01%00%02%00%00%00%00%00%F8
C1 | %a5%5b%02%03%01%00%03%00%00%00%00%00%F7
D1 | %a5%5b%02%03%01%00%04%00%00%00%00%00%F6
A2 | %a5%5b%02%03%02%00%01%00%00%00%00%00%F8
B2 | %a5%5b%02%03%02%00%02%00%00%00%00%00%F7
C2 | %a5%5b%02%03%02%00%03%00%00%00%00%00%F6
D2 | %a5%5b%02%03%02%00%04%00%00%00%00%00%F5
A3 | %a5%5b%02%03%03%00%01%00%00%00%00%00%F7
B3 | %a5%5b%02%03%03%00%02%00%00%00%00%00%F6
C3 | %a5%5b%02%03%03%00%03%00%00%00%00%00%F5
D3 | %a5%5b%02%03%03%00%04%00%00%00%00%00%F4
A4 | %a5%5b%02%03%04%00%01%00%00%00%00%00%F6
B4 | %a5%5b%02%03%04%00%02%00%00%00%00%00%F5
C4 | %a5%5b%02%03%04%00%03%00%00%00%00%00%F4
D4 | %a5%5b%02%03%04%00%04%00%00%00%00%00%F3

</body>
</html>

Manual with commands that (seem to) work:
[500440_HDMI-4x4-Matrix-Switch-RS-232-and-IR-command.pdf](https://github.com/bitfocus/companion-module-requests/files/9902813/500440_HDMI-4x4-Matrix-Switch-RS-232-and-IR-command.pdf)

**Comment by josephdadams** [comment]
@jtf4 made this and it's in the v3 betas now
