### ISSUE TITLE
Request new behavior for [Page] buttons

### ISSUE THREAD

**Issue by BBrazner** [bitfocus/companion-module-requests#952]
I have multiple surfaces each with a different Startup Page.  Pressing a [Page] button on any surface sends that surface to page 1.  Enhancement suggestion: Pressing [Page] button on a surface sends that surface to it's Startup Page.

**Comment by josephdadams** [comment]
Not a module request

**Comment by BBrazner** [comment]
Please direct me to the correct forum for making this enhancement request.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion/issues
