### ISSUE TITLE
Sharp PN-LE901

### ISSUE THREAD

**Issue by JeffNeubauer** [bitfocus/companion-module-requests#96]
**PLEASE USE THIS PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE**

https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

Provide TCP Control over Sharp Display

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

https://siica.sharpusa.com/Portals/0/downloads/Manuals/PN-LE%20_Quick_Start_Setup_Guide.pdf

*Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

Turn Power on/off
switch input

**Comment by McHauge** [comment]
Hi, got the basics for this module set up with most of the available commands included, but I'm a bit stuck on how to do the login sequence, they don't really specify that part to the same depth.

-Andreas

**Comment by McHauge** [comment]
@JeffNeubauer Hey just got done with the initial part of the module, and I think I got the login part, up and running. 

It would be awesome if you had time to test the module, there is a Windows build of companion 2.0 with the module, attached in the download link below.

[https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g](url)

**Comment by JeffNeubauer** [comment]
I'll try and test it this week.  Thanks so much!

**Comment by josephdadams** [comment]
@JeffNeubauer how did testing go?

**Comment by josephdadams** [comment]
@JeffNeubauer were you able to test this?

**Comment by McHauge** [comment]
have a feeling there won't be a test in the near future but it is ready for inclusion as it is, and I think for now it is up to date in v2.0

**Comment by josephdadams** [comment]
@McHauge I'll close this.

**Comment by Dwvsplat** [comment]
I am testing this module.....The power on/off function does not work. All the other functions do work. Let me know if there is an update & I will test again.

**Comment by McHauge** [comment]
> I am testing this module.....The power on/off function does not work. All the other functions do work. Let me know if there is an update & I will test again.

Thx, for testing, and commenting. when you say that the power on/off doesn't work, is that as it does absolutely nothing?

**Comment by Dwvsplat** [comment]
Correct.
The power and quick power do nothing (on or off).
But as I said, all the other functions work perfectly.
I know it is not the TV's, because I have crestron turning them on/off with
no problem.

**Comment by Dwvsplat** [comment]
You are correct, the commands are backwards.
OFF=ON

Also, did you know in version 2.1
the Allen & Heath Dlive module has no port (so the module does not work,
but it has the port field in 2.0 (and works)).
Just FYI

Thanks, for the help!

Dan
