### ISSUE TITLE
Error for Samsung Galaxy S22 phone

### ISSUE THREAD

**Issue by bphick** [bitfocus/companion-module-requests#960]
I do not see this posted anywhere.  My wife just got a new Samsung Galaxy S22 phone.  We put WLED on it and when we hit "DISCOVER LIGHTS..." for the lights, it errors out the App and closes it.  I have deleted the WLED app and tried again, with the same result.
She is running Android 13.  No further updates are available for her phone at this time.

**Comment by bphick** [comment]
If it matters... it is on a Verizon variant.

**Comment by josephdadams** [comment]
What does this have to do with Companion?
