### ISSUE TITLE
I would love to see a profile built for HuddleCamHD Simple Track Lite

### ISSUE THREAD

**Issue by Sydmatthes** [bitfocus/companion-module-requests#962]
https://huddlecamhd.com/support-utilities/

I would like to be able to trigger individual camera P, T Z
I would like to be able to trigger individual camera tracking feature
I would like to be able to trigger individual camera presets

**Comment by josephdadams** [comment]
this is a duplicate of #848

**Comment by Sydmatthes** [comment]
Apologize I added the requested material in this one.

Syd
