### ISSUE TITLE
JSON file reader

### ISSUE THREAD

**Issue by chrissabato** [bitfocus/companion-module-requests#964]
There should be a basic JSON file reader module that lets you define a local or remote JSON file that could be loaded into a variable. You could then use _Internal: Set custom variable from a stored JSONresult via a JSONpath expression_ to extract a piece of data from that json and use in other aspects of Companion.

**Comment by josephdadams** [comment]
It should probably also include a config setting to re-read the file periodically. And an action to do it on demand.

**Comment by chrissabato** [comment]
Yes. The action would be great and I can see being able to set a poll rate as being useful too.

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-generic-filereader

I added this to the betas

**Comment by josephdadams** [comment]
I figured for remote JSON files, you can retrieve those via the http module, so I only included local reads.
