### ISSUE TITLE
About adding Generic DMX function

### ISSUE THREAD

**Issue by ivanl1234** [bitfocus/companion-module-requests#969]
Can it support Generic DMX? I want to archive control or trigger some function in the Unreal engine and the Aximmetry, it only needs a trigger function by the DMX value change (e.g 255 to 254)
<img width="550" alt="1" src="https://user-images.githubusercontent.com/19159500/202346627-450f65b2-a5cb-4dc5-b369-795d56b3d435.PNG">
<img width="567" alt="2" src="https://user-images.githubusercontent.com/19159500/202346630-09f6cdec-a9c9-4d55-a054-711548db53f0.PNG">

**Comment by josephdadams** [comment]
DMX is a protocol but you need an interface to send it. And they’re all different. You can send sacn and artnet from companion though. So if you need it to be sent as traditional DMX on a wire, get a sacn or artnet node.
