### ISSUE TITLE
MT-VIKI 16 port HDMI Matrix Switch

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-requests#975]
I have purchased a MT-VIKI HDMI Matrix switch from amazon.  It's admittedly an off brand switcher but it does that job nicely for a 16x16 switch at a more reasonable price than the bigger names.  After much back and forth, I've been able to navigate the language barrier with their tech support in China, and I've been able to make the switch work with commands using the generic TCP module.

It just needs the IP address and port to connect.  It defaults to port 8080.  Commands to switch are sent in plain text, 1 per line in the format as follows:

[Command] [Source] [Destination] [Destination] [Destination] etc....

As an example, to connect input 5 to output 10, the command would be as follows, without quotes:

"SW 5 10"

Attached is their http command reference.

The devices comes in 4 port, 8 port, and 16 port flavors.  Here's the link for the one I specifically have and am VERY willing to help test...

https://smile.amazon.com/dp/B0B3DJX9W9/ref=emc_bcc_2_i?th=1

[MT-HD4X4 0808 1616 Protocol.xlsx](https://github.com/bitfocus/companion-module-requests/files/10088109/MT-HD4X4.0808.1616.Protocol.xlsx)

**Comment by guy-BW** [comment]
+1 for this. I have the 8x8 version and would like to be able to control it even from a basic level from Companion.

**Comment by emanspeaks** [comment]
+1 here as well

**Comment by Lexorius** [comment]
+1 , have a 8x8 version

**Comment by JeLuF** [comment]
Hi, I've developed a module for this, https://github.com/JeLuF/companion-module-mt-viki-matrix
How can I get this reviewed and included into the main distribution?

**Comment by JeLuF** [comment]
The module has been included into the 3.2 beta version.

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion-module-mt-viki-matrix

**Comment by mmabba5** [comment]
has anyone tried this version of it MT-HD4X4
