### ISSUE TITLE
Module Request: Go Button 3 (Figure 53)

### ISSUE THREAD

**Issue by stephen-gh** [bitfocus/companion-module-requests#98]
Have a module that will allow you to run the hits as well as the cues for Go Button 3 by Figure 53 which runs on an iPad / iPhone.

**Comment by EventReplay** [comment]
Have you tried this:
Create an OSC Generic instance,
change the label to 'GOButton',
enter the IP address,
enter port #53100.

**Comment by EventReplay** [comment]
@josephdadams 
Label I would have thought should be Software and the link I posted is a list of commands.
I had a test a while back and it worked fine with the commands I tried including hits.

**Comment by stephen-gh** [comment]
> Have you tried this:
> Create an OSC Generic instance,
> change the label to 'GOButton',
> enter the IP address,
> enter port #53100.
> http://figure53.com/docs/gobutton/v3/working-with-your-show/working-with-osc/

Hi @EventReplay, what do you put on the button that would fire Hits 1 then? As I don't quite understand from that documentation what actually needs to be entered in companion on a button, to make Go Button 3, run Hit 1 as an example.

Thanks ...

**Comment by EventReplay** [comment]
@stephen-gh 
Send Message
/hit/1/start

**Comment by stephen-gh** [comment]
> @stephen-gh
> Send Message
> /hit/1/start

@EventReplay Thank you, I will give that a try later today.

**Comment by stephen-gh** [comment]
> @stephen-gh
> Send Message
> /hit/1/start

@EventReplay Thanks for the information, and I now have Go Button 3 on the iPad working via the generic OSC setup.
