### ISSUE TITLE
Netgear M4250 AV-Line

### ISSUE THREAD

**Issue by SK-RaoSel** [bitfocus/companion-module-requests#989]
- [x] **I have researched the list of existing Companion modules and requests and have determined this has not yet been requested**

The name of the device, hardware, or software you would like to control: Netgear M4250 AV-Line, Switches

What you would like to be able to make it do from Companion: f.e. turn on and off POE

Direct links or attachments to the ethernet control protocol or API: https://www.netgear.de/support/product/msm4214x.aspx#download

**Comment by SK-RaoSel** [comment]
https://www.downloads.netgear.com/files/GDC/M4250/M4250_AV_UM_EN.pdf

**Comment by bryce-seifert** [comment]
I can work on this

**Comment by Lulu2409** [comment]
Hello everyone,
is it possible to add that you can set the PVID per port and display the current Vlan ID as feedback?
It would also be great if you could switch one Vlan per port untagged and tagged.
Many greetings and many thanks

**Comment by bryce-seifert** [comment]
@Lulu2409 Please open this as an issue on the Netgear AV repo
https://github.com/bitfocus/companion-module-netgear-avline/issues
